DECLARE	@Company		Varchar(5),
		@RunDate		Date = GETDATE(),
		@Query			Varchar(MAX)

DECLARE	@tblData Table
	([Customer Number]	Varchar(25),
	[Customer Name]		Varchar(75),
	Current_Outstanding	Numeric(12,2),
	Days31_60			Numeric(12,2),
	Days61_90			Numeric(12,2),
	Days91_180			Numeric(12,2),
	Days180More			Numeric(12,2),
	[Transaction Type]	Varchar(10),
	[Company Name]		Varchar(50))

DECLARE curCompanies CURSOR LOCAL KEYSET OPTIMISTIC FOR
SELECT	CompanyId
FROM	GPCustom.dbo.Companies
WHERE	Trucking = 1
		AND IsTest = 0

OPEN curCompanies 
FETCH FROM curCompanies INTO @Company

WHILE @@FETCH_STATUS = 0
BEGIN
	SET @Query = N'SELECT	RTRIM(DAT.CUSTNMBR) AS CUSTNMBR,
		CUS.CUSTNAME,
		SUM(CASE WHEN DATEDIFF(dd, DAT.DUEDATE, GETDATE()) <= 30 THEN DAT.CURTRXAM ELSE 0 END) AS [Current],
		SUM(CASE WHEN DATEDIFF(dd, DAT.DUEDATE, GETDATE()) BETWEEN 31 AND 60 THEN DAT.CURTRXAM ELSE 0 END) AS [Days31_60],
		SUM(CASE WHEN DATEDIFF(dd, DAT.DUEDATE, GETDATE()) BETWEEN 61 AND 90 THEN DAT.CURTRXAM ELSE 0 END) AS [Days61_90],
		SUM(CASE WHEN DATEDIFF(dd, DAT.DUEDATE, GETDATE()) BETWEEN 91 AND 180 THEN DAT.CURTRXAM ELSE 0 END) AS [Days91_180],
		SUM(CASE WHEN DATEDIFF(dd, DAT.DUEDATE, GETDATE()) > 180 THEN DAT.CURTRXAM ELSE 0 END) AS [Days180More],
		TRXTYPE,
		CPY.CompanyName
FROM	(
		SELECT	OPE.CUSTNMBR,
				OPE.DOCNUMBR,
				OPE.RMDTYPAL,
				OPE.DOCDATE,
				CASE WHEN OPE.RMDTYPAL < 6 THEN OPE.DOCDATE ELSE CASE WHEN OPE.DUEDATE < ''01/01/1980'' THEN CASE WHEN DAY.Days = 0 THEN GETDATE() ELSE DATEADD(dd, DAY.Days, OPE.DOCDATE) END ELSE OPE.DUEDATE END END AS DUEDATE,
				OPE.CURTRXAM * CASE WHEN OPE.RMDTYPAL > 6 THEN -1 ELSE 1 END AS CURTRXAM,
				BALANCE = OPE.CURTRXAM,
				CASE WHEN OPE.RMDTYPAL > 6 THEN ''Credit'' ELSE ''Debit'' END AS TRXTYPE
		FROM	' + @Company + '.dbo.RM20101 OPE
				INNER JOIN (
							SELECT	CUSTNMBR,
									ISNULL(PAYT.DUEDTDS, 0) AS Days
							FROM	' + @Company + '.dbo.RM00101 CUST
									LEFT JOIN ' + @Company + '.dbo.SY03300 PAYT ON CUST.PYMTRMID = PAYT.PYMTRMID
							) DAY ON OPE.CUSTNMBR = DAY.CUSTNMBR
		WHERE	OPE.VOIDSTTS = 0 
				AND OPE.CURTRXAM <> 0
		) DAT
		INNER JOIN ' + @Company + '.dbo.RM00101 CUS ON DAT.CUSTNMBR = CUS.CUSTNMBR
		INNER JOIN GPCustom.dbo.Companies CPY ON CPY.CompanyId = ''' + @Company + '''
WHERE	ISNULL(BALANCE,0) <> 0
GROUP BY
		DAT.CUSTNMBR,
		CUS.CUSTNAME,
		DAT.TRXTYPE,
		CPY.CompanyName
ORDER BY
		DAT.CUSTNMBR'
		
	INSERT INTO @tblData
	EXECUTE(@Query)

	FETCH FROM curCompanies INTO @Company
END

CLOSE curCompanies
DEALLOCATE curCompanies

SELECT	*
FROM	@tblData