SELECT	A.VENDORID Vendor_ID,
		B.VENDNAME Vendor_Name,
		B.VNDCHKNM Vendor_Check_Name,
		B.VNDCLSID Class_ID,
		CASE B.VENDSTTS
			WHEN 1 THEN 'Active'
			WHEN 2 THEN 'Inactive'
			WHEN 3 THEN 'Temporary'
		END Vendor_Status,
		CASE A.TEN99TYPE
			WHEN 1 THEN 'Not a 1099 Vendor'
			WHEN 2 THEN 'Dividend'
			WHEN 3 THEN 'Interest'
			WHEN 4 THEN 'Miscellaneous'
		END [Type],
		CASE --Set 1099 Box Number Values
			WHEN A.TEN99TYPE = 1 THEN 'Not a 1099 Vendor' 
			WHEN A.TEN99BOXNUMBER = 0 THEN 'Not a 1099 Vendor'
			--1099 Type DividEND Box Numbers
			WHEN A.TEN99TYPE = 2 AND A.TEN99BOXNUMBER = 1 THEN '1a Ordinary Dividends'
			WHEN A.TEN99TYPE = 2 AND A.TEN99BOXNUMBER = 2 THEN '1b Qualified Dividends'
			WHEN A.TEN99TYPE = 2 AND A.TEN99BOXNUMBER = 3 THEN '2a Capital Gain Dist.'
			WHEN A.TEN99TYPE = 2 AND A.TEN99BOXNUMBER = 4 THEN '2b Unrecap. 1250 Gain'
			WHEN A.TEN99TYPE = 2 AND A.TEN99BOXNUMBER = 5 THEN '2c Section 1202 Gain'
			WHEN A.TEN99TYPE = 2 AND A.TEN99BOXNUMBER = 6 THEN '2d 28% Rate Gain'
			WHEN A.TEN99TYPE = 2 AND A.TEN99BOXNUMBER = 7 THEN '3 Nontaxable Dist.'
			WHEN A.TEN99TYPE = 2 AND A.TEN99BOXNUMBER = 8 THEN '4 Federal Tax Withheld'
			WHEN A.TEN99TYPE = 2 AND A.TEN99BOXNUMBER = 9 THEN '5 Investment Expense'
			WHEN A.TEN99TYPE = 2 AND A.TEN99BOXNUMBER = 10 THEN '6 Foreign Tax Paid'
			WHEN A.TEN99TYPE = 2 AND A.TEN99BOXNUMBER = 11 THEN '8 Cash'
			WHEN A.TEN99TYPE = 2 AND A.TEN99BOXNUMBER = 12 THEN '9 Noncash'
			WHEN A.TEN99TYPE = 2 AND A.TEN99BOXNUMBER = 13 THEN '10 Exempt Interest Dividend'
			WHEN A.TEN99TYPE = 2 AND A.TEN99BOXNUMBER = 14 THEN '11 Specified Private Activity'
			WHEN A.TEN99TYPE = 2 AND A.TEN99BOXNUMBER = 15 THEN '14 State Tax Withheld'
			--1099 Type Interest Box Numbers
			WHEN A.TEN99TYPE = 3 AND A.TEN99BOXNUMBER = 1 THEN '1 Interest'
			WHEN A.TEN99TYPE = 3 AND A.TEN99BOXNUMBER = 2 THEN '2 Early Withdrawal'
			WHEN A.TEN99TYPE = 3 AND A.TEN99BOXNUMBER = 3 THEN '3 U.S. Savings Bond Int.'
			WHEN A.TEN99TYPE = 3 AND A.TEN99BOXNUMBER = 4 THEN '4 Federal Tax Withheld'
			WHEN A.TEN99TYPE = 3 AND A.TEN99BOXNUMBER = 5 THEN '5 Investment Expense'
			WHEN A.TEN99TYPE = 3 AND A.TEN99BOXNUMBER = 6 THEN '6 Foreign Tax Paid'
			WHEN A.TEN99TYPE = 3 AND A.TEN99BOXNUMBER = 7 THEN '8 Tax-Exempt Interest'
			WHEN A.TEN99TYPE = 3 AND A.TEN99BOXNUMBER = 8 THEN '9 Private Activity Bond Int.'
			WHEN A.TEN99TYPE = 3 AND A.TEN99BOXNUMBER = 9 THEN '10 Market Discount'
			WHEN A.TEN99TYPE = 3 AND A.TEN99BOXNUMBER = 10 THEN '11 Bond Premium'
			WHEN A.TEN99TYPE = 3 AND A.TEN99BOXNUMBER = 11 THEN '12 Bond premium on Treasury obligations'
			WHEN A.TEN99TYPE = 3 AND A.TEN99BOXNUMBER = 12 THEN '13 Bond premium on Tax-exempt bond' 
			WHEN A.TEN99TYPE = 3 AND A.TEN99BOXNUMBER = 13 THEN '17 State Tax Withheld'
			--1099 Type Miscellaneous Box Numbers
			WHEN A.TEN99TYPE = 4 AND A.TEN99BOXNUMBER = 1 THEN '1 - Rents'
			WHEN A.TEN99TYPE = 4 AND A.TEN99BOXNUMBER = 2 THEN '2 - Royalties'
			WHEN A.TEN99TYPE = 4 AND A.TEN99BOXNUMBER = 3 THEN '3 - Other Income'
			WHEN A.TEN99TYPE = 4 AND A.TEN99BOXNUMBER = 4 THEN '4 - Federal Tax Withheld'
			WHEN A.TEN99TYPE = 4 AND A.TEN99BOXNUMBER = 5 THEN '5 - Fishing Boat Proceeds'
			WHEN A.TEN99TYPE = 4 AND A.TEN99BOXNUMBER = 6 THEN '6 - Medical Payments'
			WHEN A.TEN99TYPE = 4 AND A.TEN99BOXNUMBER = 7 THEN '7 - Nonemployee Compensation'
			WHEN A.TEN99TYPE = 4 AND A.TEN99BOXNUMBER = 8 THEN '8 - Substitue Payments'
			WHEN A.TEN99TYPE = 4 AND A.TEN99BOXNUMBER = 9 THEN '10 – Crop Insurance'
			WHEN A.TEN99TYPE = 4 AND A.TEN99BOXNUMBER = 10 THEN '13 – Golden Parachute'
			WHEN A.TEN99TYPE = 4 AND A.TEN99BOXNUMBER = 11 THEN '14 – Attorney Proceeds'
			WHEN A.TEN99TYPE = 4 AND A.TEN99BOXNUMBER = 12 THEN '15a – Section 409A Deferrals'
			WHEN A.TEN99TYPE = 4 AND A.TEN99BOXNUMBER = 13 THEN '15b – Section 409A Income'
			WHEN A.TEN99TYPE = 4 AND A.TEN99BOXNUMBER = 14 THEN '16 - State Tax Withheld'
			WHEN A.TEN99TYPE = 4 AND A.TEN99BOXNUMBER = 15 THEN '18 - State Income'
		END [1099_Box_Number], 
		B.TXRGNNUM Tax_Registration_Number,
		B.PYMTRMID Payment_Terms_ID,
		A.YEAR1 [Year],
		SUM(A.TEN99AMNT) Amount_Paid_1099,
		B.ADDRESS1 Address_1,
		B.ADDRESS2 Address_2,
		B.ADDRESS3 Address_3,
		B.CITY City,
		B.[STATE] [State],
		B.ZIPCODE Zip_Code,
		B.COUNTRY Country,
		B.TXIDNMBR Tax_ID
FROM	PM00204 A
		INNER JOIN PM00200 B ON A.VENDORID = B.VENDORID
WHERE	A.YEAR1 = 2018
		AND A.VENDORID = '61815'
GROUP BY 
		A.VENDORID, 
		B.VENDNAME, 
		B.VNDCLSID,
		B.VENDSTTS, 
		A.TEN99TYPE, 
		B.PYMTRMID, 
		A.YEAR1, 
		B.ADDRESS1, 
		B.ADDRESS2,
		B.ADDRESS3, 
		B.CITY, 
		B.[STATE], 
		B.ZIPCODE, 
		B.COUNTRY, 
		B.TXIDNMBR, 
		B.VNDCHKNM, 
		B.TXRGNNUM, 
		A.TEN99BOXNUMBER
