SELECT	PMH.VENDORID,
		PMH.VCHRNMBR,
		PMH.DOCNUMBR,
		PMH.DOCAMNT,
		PMH.TEN99AMNT,
		CAST(PMH.DOCDATE AS Date) AS DOCDATE,
		CAST(PMH.POSTEDDT AS Date) AS POSTEDDT,
		CAST(APL.PAYDATE AS Date) AS PAYDATE,
		PMH.DOCTYPE,
		CASE WHEN PMH.DOCTYPE = 4 THEN 'Debit Memo' WHEN PMH.DOCTYPE = 5 THEN 'Credit Memo' WHEN PMH.DOCTYPE = 6 THEN 'Payment' ELSE 'Invoice' END AS DOC_TYPE,
		PMH.TEN99TYPE
FROM	PM30200 PMH
		INNER JOIN PM00200 VND ON PMH.VENDORID = VND.VENDORID AND VND.VNDCLSID = 'DRV'
		LEFT JOIN (
					SELECT	VENDORID,
							APTODCNM,
							MAX(DOCDATE) AS PAYDATE
					FROM	PM30300
					WHERE	DOCDATE BETWEEN '12/01/2017' AND '12/31/2018'
							AND VENDORID = '51703'
					GROUP BY VENDORID, APTODCNM
					) APL ON PMH.VENDORID = APL.VENDORID AND PMH.DOCNUMBR = APL.APTODCNM
WHERE	ISNULL(APL.PAYDATE, PMH.DOCDATE) BETWEEN '01/01/2018' AND '12/31/2018'
		AND PMH.VENDORID = '51703'
		AND PMH.TEN99TYPE > 0
		OR (PMH.TEN99TYPE > 0 AND PMH.TEN99AMNT = 0 AND PMH.DOCTYPE < 5)
ORDER BY PMH.VENDORID, DOCTYPE, TEN99TYPE

/*
UPDATE	PM30200
SET		TEN99AMNT = 0
WHERE	POSTEDDT BETWEEN '01/01/2017' AND '12/31/2017'
		AND TEN99AMNT <> 0
		AND DOCTYPE > 4
*/