SELECT	H.BACHNUMB,
		H.VCHRNMBR,
		H.DOCTYPE,
		H.VENDORID,
		H.DOCNUMBR,
		H.DOCAMNT,
		H.DOCDATE,
		H.TRXDSCRN,
		D.DSTSQNUM,
		G.ACTNUMST,
		D.DEBITAMT,
		D.CRDTAMNT,
		D.DISTTYPE,
		D.DistRef
FROM	PM20000 H
		INNER JOIN PM10100 D ON H.VCHRNMBR = D.VCHRNMBR AND H.VENDORID = D.VENDORID
		INNER JOIN GL00105 G ON D.DSTINDX = G.ACTINDX
WHERE	H.BACHNUMB = 'FPT_20210424_FU'
ORDER BY H.VENDORID, H.VCHRNMBR, D.DSTSQNUM

SELECT	H.BACHNUMB,
		H.VCHRNMBR,
		H.DOCTYPE,
		H.VENDORID,
		H.DOCNUMBR,
		H.DOCAMNT,
		H.DOCDATE,
		H.TRXDSCRN,
		D.DSTSQNUM,
		G.ACTNUMST,
		D.DEBITAMT,
		D.CRDTAMNT,
		D.DISTTYPE,
		D.DistRef
FROM	PM30200 H
		INNER JOIN PM30600 D ON H.VCHRNMBR = D.VCHRNMBR AND H.VENDORID = D.VENDORID
		INNER JOIN GL00105 G ON D.DSTINDX = G.ACTINDX
WHERE	H.BACHNUMB = 'FPT_20210424_FU'
ORDER BY H.VENDORID, H.VCHRNMBR, D.DSTSQNUM