DECLARE	@RunDate	Date = '02/25/2020'

DECLARE @curData	Table
	(Customer		Varchar(15) NOT NULL,
	CustomerName	Varchar(65) NOT NULL,
	DocNumber		Varchar(21) NOT NULL,
	AppliedDoc		Varchar(21) NULL,
	AppliedDate		Date NULL,
	DocDate			Date NULL,
	DueDate			Date NULL,
	DocAmount		Numeric(20, 2) NULL,
	[Current]		Numeric(20, 2) NULL,
	Days31_60		Numeric(20, 2) NULL,
	Days61_90		Numeric(20, 2) NULL,
	Days91_180		Numeric(20, 2) NULL,
	Days180More		Numeric(20, 2) NULL,
	Balance			Numeric(20, 2) NULL,
	CompanyName		Varchar(75) NULL,
	IsSummary		Bit NULL)

INSERT INTO @curData
SELECT	RTRIM(DATA.CUSTNMBR) AS Customer,
		RTRIM(DATA.CUSTNAME) AS CustomerName,
		RTRIM(DATA.DOCNUMBR) AS DocNumber,
		'' AS AppliedDoc,
		Null AS AppliedDate,
		CAST(DATA.DOCDATE AS Date) AS DocDate,
		CAST(DATA.DUEDATE AS Date) AS DueDate,
		DATA.ORTRXAMT AS DocAmount,
		DATA.[Current],
		DATA.[Days31_60],
		DATA.[Days61_90],
		DATA.[Days91_180],
		DATA.[Days180More],
		DATA.[Current] + DATA.[Days31_60] + DATA.[Days61_90] + DATA.[Days91_180] + DATA.[Days180More] AS Balance,
		CPY.CompanyName,
		0 AS IsSummary
FROM	(
		SELECT	RM2.CUSTNMBR,
				CUS.CUSTNAME,
				RM2.DOCNUMBR,
				RM2.DOCDATE,
				RM2.DUEDATE,
				RM2.ORTRXAMT,
				SUM(CASE WHEN DATEDIFF(dd, RM2.DOCDATE, '2020-02-25') <= 30 THEN RM2.ORTRXAMT ELSE 0 END) AS [Current],
				SUM(CASE WHEN DATEDIFF(dd, RM2.DOCDATE, '2020-02-25') BETWEEN 31 AND 60 THEN RM2.ORTRXAMT ELSE 0 END) AS [Days31_60],
				SUM(CASE WHEN DATEDIFF(dd, RM2.DOCDATE, '2020-02-25') BETWEEN 61 AND 90 THEN RM2.ORTRXAMT ELSE 0 END) AS [Days61_90],
				SUM(CASE WHEN DATEDIFF(dd, RM2.DOCDATE, '2020-02-25') BETWEEN 91 AND 180 THEN RM2.ORTRXAMT ELSE 0 END) AS [Days91_180],
				SUM(CASE WHEN DATEDIFF(dd, RM2.DOCDATE, '2020-02-25') > 180 THEN RM2.ORTRXAMT ELSE 0 END) AS [Days180More]
		FROM	(
					SELECT	CUSTNMBR,
							DOCNUMBR,
							DOCDATE,
							DUEDATE,
							ORTRXAMT,
							ORTRXAMT - ISNULL(BALANCE,0) AS CURTRXAM,
							RMDTYPAL
					FROM	(
							--SELECT	HIS.CUSTNMBR,
							--		HIS.DOCNUMBR,
							--		HIS.RMDTYPAL,
							--		HIS.DOCDATE,
							--		CASE WHEN HIS.RMDTYPAL < 6 THEN HIS.DOCDATE ELSE CASE WHEN HIS.DUEDATE < '01/01/1980' THEN CASE WHEN DAY.Days = 0 THEN '2020-02-25' ELSE DATEADD(dd, DAY.Days, HIS.DOCDATE) END ELSE HIS.DUEDATE END END AS DUEDATE,
							--		HIS.ORTRXAMT * CASE WHEN HIS.RMDTYPAL > 6 THEN -1 ELSE 1 END AS ORTRXAMT,
							--		HIS.CURTRXAM * CASE WHEN HIS.RMDTYPAL > 6 THEN -1 ELSE 1 END AS CURTRXAM,
							--		BALANCE = CASE WHEN HIS.RMDTYPAL > 6 THEN -1 ELSE 1 END * (SELECT SUM(HAP.APPTOAMT) FROM OIS.dbo.RM30201 HAP WHERE HAP.CUSTNMBR = HIS.CUSTNMBR AND (HAP.APTODCNM = HIS.DOCNUMBR OR HAP.APFRDCNM = HIS.DOCNUMBR) AND HAP.GLPOSTDT <= '2020-02-25')
							--FROM	OIS.dbo.RM30101 HIS
							--		INNER JOIN (
							--					SELECT	CUSTNMBR,
							--							ISNULL(PAYT.DUEDTDS, 0) AS Days
							--					FROM	OIS.dbo.RM00101 CUST
							--							LEFT JOIN OIS.dbo.SY03300 PAYT ON CUST.PYMTRMID = PAYT.PYMTRMID 
							--						WHERE	CUST.CUSTNMBR = '21833' ) DAY ON HIS.CUSTNMBR = DAY.CUSTNMBR
							--WHERE	HIS.VOIDSTTS = 0
							--		AND HIS.RMDTYPAL < 7
							--		AND HIS.DOCDATE <= '2020-02-25'AND HIS.CUSTNMBR = '21833' 
							--UNION
							SELECT	OPE.CUSTNMBR,
									OPE.DOCNUMBR,
									OPE.RMDTYPAL,
									OPE.DOCDATE,
									CASE WHEN OPE.RMDTYPAL < 6 THEN OPE.DOCDATE ELSE CASE WHEN OPE.DUEDATE < '01/01/1980' THEN CASE WHEN DAY.Days = 0 THEN '2020-02-25' ELSE DATEADD(dd, DAY.Days, OPE.DOCDATE) END ELSE OPE.DUEDATE END END AS DUEDATE,
									OPE.ORTRXAMT * CASE WHEN OPE.RMDTYPAL > 6 THEN -1 ELSE 1 END AS ORTRXAMT,
									OPE.CURTRXAM * CASE WHEN OPE.RMDTYPAL > 6 THEN -1 ELSE 1 END AS CURTRXAM,
									BALANCE = CASE WHEN OPE.RMDTYPAL > 6 THEN -1 ELSE 1 END * (SELECT SUM(APPTOAMT) FROM (SELECT HAP.APPTOAMT FROM OIS.dbo.RM30201 HAP WHERE HAP.CUSTNMBR = OPE.CUSTNMBR AND (HAP.APTODCNM = OPE.DOCNUMBR OR HAP.APFRDCNM = OPE.DOCNUMBR) AND HAP.GLPOSTDT <= '2020-02-25' UNION SELECT OAP.APPTOAMT FROM OIS.dbo.RM20201 OAP WHERE OAP.CUSTNMBR = OPE.CUSTNMBR AND (OAP.APTODCNM = OPE.DOCNUMBR OR OAP.APFRDCNM = OPE.DOCNUMBR) AND OAP.GLPOSTDT <= '2020-02-25') TMP)
							FROM	OIS.dbo.RM20101 OPE
									INNER JOIN (
												SELECT	CUSTNMBR,
														ISNULL(PAYT.DUEDTDS, 0) AS Days
												FROM	OIS.dbo.RM00101 CUST
														LEFT JOIN OIS.dbo.SY03300 PAYT ON CUST.PYMTRMID = PAYT.PYMTRMID 
													WHERE	CUST.CUSTNMBR = '21833' ) DAY ON OPE.CUSTNMBR = DAY.CUSTNMBR
							WHERE	OPE.VOIDSTTS = 0
									AND OPE.RMDTYPAL < 7
									AND OPE.DOCDATE <= '2020-02-25'AND OPE.CUSTNMBR = '21833' ) DATA
					--WHERE	ORTRXAMT - ISNULL(BALANCE,0) <> 0
				) RM2
				INNER JOIN OIS.dbo.RM00101 CUS ON RM2.CUSTNMBR = CUS.CUSTNMBR
		GROUP BY
				RM2.CUSTNMBR,
				CUS.CUSTNAME,
				RM2.DOCNUMBR,
				RM2.DOCDATE,
				RM2.DUEDATE,
				RM2.ORTRXAMT,
				RM2.RMDTYPAL
		) DATA
		LEFT JOIN GPCustom.dbo.Companies CPY ON CPY.CompanyId = 'OIS'
ORDER BY
		DATA.CUSTNAME,
		DATA.DOCDATE,
		DATA.DOCNUMBR

INSERT INTO @curData
SELECT	DATA.Customer,
		DATA.CustomerName,
		DATA.DocNumber,
		RMA.APFRDCNM,
		RMA.DATE1 AS AppliedDate,
		DATA.DocDate,
		DATA.DueDate,
		RMA.APPTOAMT * -1 AS DocAmount,
		IIF(DATA.[Current] <> 0, RMA.APPTOAMT * -1, 0),
		IIF(DATA.Days31_60 <> 0, RMA.APPTOAMT * -1, 0),
		IIF(DATA.Days61_90 <> 0, RMA.APPTOAMT * -1, 0),
		IIF(DATA.Days91_180 <> 0, RMA.APPTOAMT * -1, 0),
		IIF(DATA.Days180More <> 0, RMA.APPTOAMT * -1, 0),
		RMA.APPTOAMT * -1 AS Balance,
		DATA.CompanyName,
		DATA.IsSummary
FROM	@curData DATA
		INNER JOIN OIS.dbo.RM20201 RMA ON DATA.Customer = RMA.CUSTNMBR AND DATA.DocNumber = RMA.APTODCNM AND RMA.Date1 <= @RunDate
--UNION
--SELECT	DATA.Customer,
--		DATA.CustomerName,
--		DATA.DocNumber,
--		RMA.APFRDCNM,
--		RMA.DATE1 AS AppliedDate,
--		DATA.DocDate,
--		DATA.DueDate,
--		RMA.APPTOAMT * -1 AS DocAmount,
--		IIF(DATA.[Current] <> 0, RMA.APPTOAMT * -1, 0),
--		IIF(DATA.Days31_60 <> 0, RMA.APPTOAMT * -1, 0),
--		IIF(DATA.Days61_90 <> 0, RMA.APPTOAMT * -1, 0),
--		IIF(DATA.Days91_180 <> 0, RMA.APPTOAMT * -1, 0),
--		IIF(DATA.Days180More <> 0, RMA.APPTOAMT * -1, 0),
--		RMA.APPTOAMT * -1 AS Balance,
--		DATA.CompanyName,
--		DATA.IsSummary
--FROM	@curData DATA
--		INNER JOIN OIS.dbo.RM30201 RMA ON DATA.Customer = RMA.CUSTNMBR AND DATA.DocNumber = RMA.APTODCNM AND RMA.Date1 <= @RunDate

SELECT	*
FROM	@curData
ORDER BY
		Customer,
		DocDate,
		DocNumber,
		AppliedDoc