SELECT	*
FROM	(
		SELECT	RTRIM(RM2.CUSTNMBR) AS CustomerId,
				RTRIM(RM1.CUSTNAME) AS CustomerName,
				SUM(CAST(RM2.CURTRXAM * IIF(RM2.RMDTYPAL < 5, 1, -1) AS Numeric(12,2))) AS Total_Balance,
				SUM(CAST(RM2.CURTRXAM * IIF(RM2.RMDTYPAL < 5 AND RM2.DUEDATE < GETDATE(), 1, 0) AS Numeric(12,2))) AS Due_Balance,
				CASE RM1.CRLMTTYP WHEN 0 THEN 'No credit' WHEN 1 THEN 'Unlimited' ELSE 'Amount' END AS CreditType,
				CAST(RM1.CRLMTAMT AS Numeric(12,2)) AS CreditLimit
		FROM	RM20101 RM2
				INNER JOIN RM00101 RM1 ON RM2.CUSTNMBR = RM1.CUSTNMBR
		WHERE	RM2.CURTRXAM > 0
				--AND RM2.CUSTNMBR = '1565'
		GROUP BY RM2.CUSTNMBR, RM1.CRLMTAMT, RM1.CRLMTTYP, RM1.CUSTNAME
		HAVING SUM(RM2.CURTRXAM * IIF(RM2.RMDTYPAL < 5, 1, -1)) > 0
		) DATA
WHERE	Total_Balance > CreditLimit
ORDER BY 2

-- select * from RM00101 where CUSTNMBR = '1565'