SELECT	'AIS' AS Company,
		CUSTNMBR AS CustomerNumber,
		DOCNUMBR AS DocumentNumber,
		ORTRXAMT AS DocumentAmount,
		CURTRXAM AS DocumentBalance
FROM	RM20101
WHERE	RMDTYPAL > 6
		AND CURTRXAM <= ORTRXAMT
		AND CURTRXAM > 0
UNION
SELECT	'DNJ' AS Company,
		CUSTNMBR AS CustomerNumber,
		DOCNUMBR AS DocumentNumber,
		ORTRXAMT AS DocumentAmount,
		CURTRXAM AS DocumentBalance
FROM	DNJ.dbo.RM20101
WHERE	RMDTYPAL > 6
		AND CURTRXAM <= ORTRXAMT
		AND CURTRXAM > 0
UNION
SELECT	'GIS' AS Company,
		CUSTNMBR AS CustomerNumber,
		DOCNUMBR AS DocumentNumber,
		ORTRXAMT AS DocumentAmount,
		CURTRXAM AS DocumentBalance
FROM	GIS.dbo.RM20101
WHERE	RMDTYPAL > 6
		AND CURTRXAM <= ORTRXAMT
		AND CURTRXAM > 0
UNION
SELECT	'IGS' AS Company,
		CUSTNMBR AS CustomerNumber,
		DOCNUMBR AS DocumentNumber,
		ORTRXAMT AS DocumentAmount,
		CURTRXAM AS DocumentBalance
FROM	GLSO.dbo.RM20101
WHERE	RMDTYPAL > 6
		AND CURTRXAM <= ORTRXAMT
		AND CURTRXAM > 0
UNION
SELECT	'IMCG' AS Company,
		CUSTNMBR AS CustomerNumber,
		DOCNUMBR AS DocumentNumber,
		ORTRXAMT AS DocumentAmount,
		CURTRXAM AS DocumentBalance
FROM	IMC.dbo.RM20101
WHERE	RMDTYPAL > 6
		AND CURTRXAM <= ORTRXAMT
		AND CURTRXAM > 0
UNION
SELECT	'NDS' AS Company,
		CUSTNMBR AS CustomerNumber,
		DOCNUMBR AS DocumentNumber,
		ORTRXAMT AS DocumentAmount,
		CURTRXAM AS DocumentBalance
FROM	NDS.dbo.RM20101
WHERE	RMDTYPAL > 6
		AND CURTRXAM <= ORTRXAMT
		AND CURTRXAM > 0
ORDER BY
		1,
		CUSTNMBR,
		DOCNUMBR
