-- SELECT * FROM RM20101 WHERE BACHNUMB IN ('PD_OPENITEMS','DEP_OPENITEMS','IMC_OPENITEMS') AND RmdTypal = 1
-- UPDATE RM20101 SET GLPOSTDT = DOCDATE WHERE BACHNUMB IN ('PD_OPENITEMS','DEP_OPENITEMS','IMC_OPENITEMS')
-- UPDATE imc.dbo.RM20101 SET PYMTRMID = 'Net 30 days' WHERE BACHNUMB IN ('PD_OPENITEMS','DEP_OPENITEMS','IMC_OPENITEMS')

-- SELECT * FROM RM10101 WHERE TrxSorce IN (SELECT TrxSorce FROM RM20101 WHERE BACHNUMB IN ('PD_OPENITEMS','DEP_OPENITEMS','IMC_OPENITEMS'))
/*
UPDATE	RM10101
SET		PostEddt = RM20101.PostDate
FROM	(SELECT TrxSorce, PostDate FROM RM20101 WHERE BACHNUMB IN ('PD_OPENITEMS','DEP_OPENITEMS','IMC_OPENITEMS')) RM20101
WHERE	RM10101.TrxSorce = RM20101.TrxSorce
*/
select * from RM20101 

SELECT * FROM IMC.dbo.RM20101 WHERE BACHNUMB IN ('IMC_OPENITEMS') AND RmdTypal = 1 AND CustNmbr = '463B'
UPDATE RM20101 SET GLPOSTDT = DOCDATE, POSTDATE = DOCDATE WHERE BACHNUMB IN ('IMC_OPENITEMS') AND RmdTypal = 1 AND CustNmbr = '463B'