DECLARE @tblAccounts	Table (
		Company			Varchar(5),
		Intercompany	Varchar(5),
		Account			Varchar(15), 
		Description		Varchar(50))

-- ="INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('"&A2&"','"&B2&"','"&C2&"','"&D2&"')"

UPDATE IntercompanyReport_Accounts SET Inactive = 1

INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','DNJ','0-07-1100','Rec from DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','DNJ','0-07-2100','Pay to DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','GIS','0-20-1100','Rec from GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','GIS','0-20-1199','Rec from GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','GIS','0-20-2100','Pay to GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','GLSO','0-90-1100','Rec from IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','GLSO','0-90-1199','ICB Receivable - IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','GLSO','0-90-2100','Pay to IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','HMIS','0-45-1100','Rec from HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','HMIS','0-45-1199','ICB Receivable - HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','HMIS','0-45-2100','Pay to HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','IILS','0-10-1100','Rec from IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','IILS','0-10-2100','Pay to IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','IMC','0-40-1100','Rec from IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','IMC','0-40-1199','ICB Receivable - IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','IMC','0-40-2100','Pay to IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','IMC','0-40-2199','Pay to IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','IMCC','0-80-1100','Rec from IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','IMCC','0-80-1101','Rec from IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','IMCC','0-80-2100','Pay to IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','IMCMR','0-57-1100','Rec from IMCGMR')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','OIS','0-15-1100','Rec from OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','OIS','0-15-2100','Pay to OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','OIS','0-15-2199','ICB Payable - OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','PDS','0-33-1100','Rec from PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','PDS','0-33-2100','Pay to PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','RCCL','0-70-1100','Rec from RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','RCCL','0-70-2100','Pay to RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('AIS','RCCL','5-70-2100','Pay to RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('DNJ','AIS','0-40-2100','Pay to AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('DNJ','AIS','0-40-1100','Rec from AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('DNJ','GIS','0-20-1100','Rec from GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('DNJ','GIS','0-20-2100','Pay to GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('DNJ','GIS','0-20-2199','Pay to GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('DNJ','GLSO','0-90-1100','Rec from IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('DNJ','GLSO','0-90-1199','Rec from IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('DNJ','GLSO','0-90-2100','Pay to IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('DNJ','HMIS','0-45-1100','Rec from HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('DNJ','HMIS','0-45-2100','Pay to HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('DNJ','IILS','0-10-1100','Rec from IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('DNJ','IILS','0-10-2100','Pay to IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('DNJ','IMC','0-07-1100','Rec from IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('DNJ','IMC','0-07-1199','Rec from IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('DNJ','IMC','0-07-2100','Pay to IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('DNJ','IMC','0-07-2199','Pay to IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('DNJ','IMCC','0-80-1100','Rec from IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('DNJ','IMCC','0-80-1101','Rec from IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('DNJ','IMCC','0-80-2100','Pay to IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('DNJ','OIS','0-15-1100','Rec from OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('DNJ','OIS','0-15-1199','Rec from OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('DNJ','OIS','0-15-2100','Pay to OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('DNJ','OIS','0-15-2199','Pay to OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('DNJ','PDS','0-33-1100','Rec from PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('DNJ','PDS','0-33-2100','Pay to PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('DNJ','RCCL','0-70-1100','Rec from RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('DNJ','RCCL','0-70-2100','Pay to RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','AIS','0-40-2100','Pay to AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','AIS','0-40-2199','Pay to AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','AIS','0-40-1100','Rec from AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','DNJ','0-07-2100','Pay to DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','DNJ','0-07-1100','Rec from DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','DNJ','0-07-1199','Rec from DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','GLSO','0-90-1100','Rec from IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','GLSO','0-90-1199','Rec from IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','GLSO','0-90-2100','Pay to IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','GLSO','0-90-2199','Pay to IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','HMIS','0-45-1100','Rec from HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','HMIS','0-45-2100','Pay to HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','IILS','0-10-1100','Rec from IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','IILS','0-10-2100','Pay to IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','IMC','0-20-1100','Rec from IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','IMC','0-20-1199','Rec from IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','IMC','0-20-2100','Pay to IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','IMC','0-20-2199','Pay to IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','IMCC','0-80-1100','Rec from IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','IMCC','0-80-1101','Rec from IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','IMCC','0-80-2100','Pay to IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','IMCMR','0-57-2100','Pay to IMCGMR')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','OIS','0-15-1100','Rec from OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','OIS','0-15-2100','Pay to OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','PDS','0-33-1100','Rec from PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','PDS','0-33-2100','Pay to PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','RCCL','0-70-1100','Rec from RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','RCCL','5-70-1100','Rec from RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','RCCL','0-70-2100','Pay to RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GIS','RCCL','5-70-2100','Pay to RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('HMIS','AIS','0-40-2100','Pay to AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('HMIS','AIS','0-40-2199','Pay to AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('HMIS','AIS','0-40-1100','Rec from AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('HMIS','DNJ','0-07-2100','Pay to DNj')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('HMIS','DNJ','0-07-1100','Rec from DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('HMIS','GIS','0-20-2100','Pay to GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('HMIS','GIS','0-20-1100','Rec from GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('HMIS','GLSO','0-90-2100','Pay to IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('HMIS','GLSO','0-90-1100','Rec from IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('HMIS','GLSO','0-90-1199','ICB Rec from IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('HMIS','IILS','0-10-2100','Pay to IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('HMIS','IILS','0-10-1100','Rec from IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('HMIS','IMC','0-45-2100','Pay to IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('HMIS','IMC','0-45-1100','Rec from IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('HMIS','IMCC','0-80-2100','Pay to IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('HMIS','IMCC','0-80-1100','Rec from IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('HMIS','IMCC','0-80-1101','Rec from IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('HMIS','OIS','0-15-2100','Pay to OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('HMIS','OIS','0-15-1100','Rec from OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('HMIS','OIS','0-15-1199','ICB Rec from OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('HMIS','PDS','0-33-1100','Rec from PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('HMIS','PDS','0-33-2100','Pay to PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('HMIS','RCCL','0-70-2100','Pay to RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IGS','AIS','0-40-2100','Pay to AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IGS','AIS','0-40-2199','Pay to AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IGS','DNJ','0-07-2100','Pay to DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IGS','DNJ','0-07-2199','Pay to DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IGS','GIS','0-20-2100','Pay to GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IGS','GIS','0-20-2199','Pay to GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IGS','HMIS','0-45-2100','Pay to HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IGS','HMIS','0-45-2199','ICB Payable - HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IGS','IILS','0-10-2100','Pay to IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IGS','IMC','0-90-2100','Pay to IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IGS','IMC','0-90-2199','Pay to IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IGS','IMCC','0-80-2100','Pay to IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IGS','IMCMR','0-57-2100','Pay to IMCGMR')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IGS','OIS','0-15-2100','Pay to OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IGS','OIS','0-15-2199','Pay to OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IGS','PDS','0-33-2199','Pay to PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IGS','PDS','0-33-2100','Pay to PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IGS','RCCL','0-70-2100','Pay to RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IILS','AIS','0-40-2100','Pay to AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IILS','AIS','0-40-1100','Rec from AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IILS','DNJ','0-07-2100','Pay to DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IILS','DNJ','0-07-1100','Rec from DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IILS','GIS','0-20-2100','Pay to GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IILS','GIS','0-20-1100','Rec from GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IILS','GLSO','0-90-2100','Pay to IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IILS','GLSO','0-90-1100','Rec from IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IILS','HMIS','0-45-1100','Rec from HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IILS','HMIS','0-45-2100','Pay to HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IILS','IMC','0-10-2100','Pay to IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IILS','IMC','0-10-1100','Rec from IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IILS','IMCC','0-80-2100','Pay to IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IILS','IMCC','0-80-1100','Rec from IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IILS','IMCC','0-80-1101','Rec from IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IILS','IMCMR','0-57-1100','Rec from IMCGMR')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IILS','MCCP','0-75-1100','Rec from MCCP')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IILS','OIS','0-15-1100','Rec from OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IILS','OIS','0-15-2100','Pay to OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IILS','PDS','0-33-1100','Rec from PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IILS','PDS','0-33-2100','Pay to PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IILS','PDS','0-33-2100','Pay to PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IILS','PDS','0-33-2101','Pay to PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IILS','RCCL','0-70-1100','Rec from RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IILS','RCCL','5-70-1100','Rec from RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IILS','RCCL','0-70-2100','Pay to RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','AIS','0-40-2100','Pay to AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','AIS','0-40-2199','ICB Payable - AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','AIS','0-40-1100','Rec from AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','AIS','0-40-1199','Rec from AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','DNJ','0-07-2100','Pay to DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','DNJ','0-07-2199','Pay to DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','DNJ','0-07-1100','Rec from DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','DNJ','0-07-1199','Rec from DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','GIS','0-20-2100','Pay to GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','GIS','0-20-2199','Pay to GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','GIS','0-20-1100','Rec from GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','GIS','0-20-1199','Rec from GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','GLSO','0-90-2100','Pay to IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','GLSO','0-90-2199','Pay to IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','GLSO','0-90-1100','Rec from IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','GLSO','0-90-1199','Rec from IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','HMIS','0-45-1100','Rec from HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','HMIS','0-45-2100','Pay to HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','IILS','0-10-1100','Rec from IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','IILS','0-10-2100','Pay to IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','IMCC','0-80-2100','Pay to IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','IMCC','0-80-1100','Rec from IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','IMCC','0-80-1101','Rec from IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','IMCMR','0-57-2100','Pay to IMCGMR')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','MCCP','0-75-2100','Pay to MCCP')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','OIS','0-15-1100','Rec from OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','OIS','0-15-2100','Pay to OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','PDS','0-33-1100','Rec from PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','PDS','0-33-1199','Rec from PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','PDS','0-33-2100','Pay to PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','RCCL','0-70-1100','Rec from RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','RCCL','5-70-1100','Rec from RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','RCCL','0-70-2100','Pay to RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','RCCL','5-70-2100','Pay to RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','IMCMR','0-57-1100','Rec from IMCGMR')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMC','OIS','0-15-1199','Rec from OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCMR','AIS','0-40-2100','Pay to AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCMR','GIS','0-20-1100','Rec from GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCMR','GLSO','0-90-1100','Rec from IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCMR','IILS','0-10-2100','Pay to IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCMR','IMC','0-57-2100','Pay to IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCMR','IMC','0-57-1100','Rec from IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCMR','IMCC','0-80-1100','Rec from IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCMR','IMCC','0-80-1101','Rec from IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCMR','OIS','0-15-1100','Rec from OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCMR','RCCL','0-70-2100','Pay to RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCMR','RCCL','0-70-1100','Rec from RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','AIS','0-40-2100','Pay to AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','AIS','0-40-2101','Pay from AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','AIS','0-40-1100','Rec from AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','DNJ','0-07-2100','Pay to DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','DNJ','0-07-2101','Pay from DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','DNJ','0-07-1100','Rec from DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','GIS','0-20-2100','Pay to GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','GIS','0-20-2101','Pay from GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','GIS','0-20-1100','Rec from GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','GLSO','0-90-2100','Pay to IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','GLSO','0-90-2101','Pay to IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','GLSO','0-90-1100','Rec from IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','HMIS','0-45-1100','Rec form HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','HMIS','0-45-2100','Pay to HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','HMIS','0-45-2101','Pay to HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','IILS','0-10-1100','Rec from IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','IILS','0-10-2100','Pay to IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','IILS','0-10-2101','Pay to IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','IMC','0-80-1100','Rec from IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','IMC','0-80-2100','Pay to IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','IMC','0-80-2101','Pay to IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','IMCMR','0-57-2100','Pay to IMCGMR')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','IMCMR','0-57-2101','Pay to IMCGMR')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','MCCP','0-75-1100','Rec from MCCP')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','MCCP','0-75-2100','Pay to MCCP')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','OIS','0-15-1100','Rec from OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','OIS','0-15-2100','Pay to OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','OIS','0-15-2101','Pay to OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','PDS','0-33-1100','Rec from PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','RCCL','0-70-1100','Rec from RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','RCCL','0-70-2100','Pay to RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('IMCC','RCCL','0-70-2101','Pay to RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GLSO','AIS','0-40-1100','Rec from AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GLSO','DNJ','0-07-1100','Rec from DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GLSO','GIS','0-20-1100','Rec from GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GLSO','GIS','0-20-1199','Rec from GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GLSO','HMIS','0-45-1100','REC from HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GLSO','IILS','0-10-1100','Rec from IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GLSO','IMC','0-90-1100','Rec from IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GLSO','IMC','0-90-1199','Rec from IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GLSO','IMCC','0-80-1100','Rec from IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GLSO','IMCC','0-80-1101','Rec from IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GLSO','OIS','0-15-1100','Rec from OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GLSO','OIS','0-15-1199','Rec from OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GLSO','PDS','0-33-1100','Rec from PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('GLSO','PDS','0-33-1199','Rec from PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('MCCP','IILS','0-10-2100','Pay to IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('MCCP','IMC','0-75-1100 ','Rec from IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('MCCP','IMCC','0-80-2100','Pay to IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('MCCP','IMCC','0-80-1100','Rec from IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('MCCP','RCCL','0-70-2100','Pay to RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','AIS','0-40-2100','Pay to AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','AIS','0-40-1100','Rec from AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','AIS','0-40-1199','ICB Rec-AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','DNJ','0-07-2100','Pay to DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','DNJ','0-07-2199','Pay to DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','DNJ','0-07-1100','Rec from DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','DNJ','0-07-1199','Rec from DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','GIS','0-20-2100','Pay to GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','GIS','0-20-1100','Rec from GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','GLSO','0-90-2100','Pay to IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','GLSO','0-90-2199','Pay to IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','GLSO','0-90-1100','Rec from IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','GLSO','0-90-1199','Rec from IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','HMIS','0-45-1100','Rec from HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','HMIS','0-45-2100','Pay to HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','HMIS','0-45-2199','ICB Payable - HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','IILS','0-10-2100','Pay to IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','IILS','0-10-1100','Rec from IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','IMC','0-15-2100','Pay to IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','IMC','0-15-2199','Pay to IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','IMC','0-15-1100','Rec from IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','IMCC','0-80-2100','Pay to IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','IMCC','0-80-1100','Rec from IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','IMCC','0-80-1101','Rec from IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','IMCMR','0-57-2100','Pay to IMCGMR')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','PDS','0-33-1100','Rec from PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','PDS','0-33-2199','Pay to PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','RCCL','0-70-2100','Pay to RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('OIS','RCCL','0-70-1100','Rec from RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('PDS','AIS','0-40-2100','Pay to AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('PDS','AIS','0-40-1100','Rec from AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('PDS','DNJ','0-07-2100','Pay to DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('PDS','DNJ','0-07-1100','Rec from DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('PDS','GIS','0-20-2100','Pay to GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('PDS','GIS','0-20-1100','Rec from GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('PDS','GLSO','0-90-2100','Pay to IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('PDS','GLSO','0-90-2199','Pay to IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('PDS','GLSO','0-90-1199','Rec from IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('PDS','GLSO','0-90-1100','Rec from IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('PDS','HMIS','0-45-2100','Pay to HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('PDS','HMIS','0-45-1100','Rec from HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('PDS','IILS','0-10-2100','Pay to IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('PDS','IILS','0-10-1100','Rec from IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('PDS','IMC','0-33-2100','Pay to IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('PDS','IMC','0-33-2199','Pay to IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('PDS','IMC','0-33-1100','Rec from IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('PDS','IMCC','0-80-2100','Pay to IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('PDS','IMCC','0-80-1100','Rec from IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('PDS','IMCC','0-80-1101','Rec from IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('PDS','OIS','0-15-2100','Pay to OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('PDS','OIS','0-15-1199','Rec from OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('PDS','RCCL','0-70-2100','Pay to RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('PDS','RCCL','0-70-1100','Rec from RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('RCCL','AIS','0-40-2100','Pay to AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('RCCL','AIS','0-40-1100','Rec from AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('RCCL','AIS','5-40-1100','Rec from AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('RCCL','DNJ','0-07-2100','Pay to DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('RCCL','DNJ','0-07-1100','Rec from DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('RCCL','GIS','0-20-2100','Pay to GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('RCCL','GIS','5-20-2100','Pay to GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('RCCL','GIS','0-20-1100','Rec from GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('RCCL','GIS','5-20-1100','Rec from GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('RCCL','GLSO','0-90-1100','Rec from IMCNA')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('RCCL','HMIS','0-45-1100','Rec from HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('RCCL','IILS','0-10-2100','Pay to IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('RCCL','IILS','5-10-2100','Pay to IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('RCCL','IILS','0-10-1100','Rec from IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('RCCL','IMC','0-70-2100','Pay to IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('RCCL','IMC','5-70-2100','Pay to IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('RCCL','IMC','0-70-1100','Rec from IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('RCCL','IMC','5-70-1100','Rec from IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('RCCL','IMCC','0-80-2100','Pay to IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('RCCL','IMCC','0-80-1100','Rec from IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('RCCL','IMCC','0-80-1101','Rec from IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('RCCL','IMCMR','0-57-1100','Rec from IMCGMR')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('RCCL','IMCMR','0-57-2100','Pay to IMCGMR')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('RCCL','MCCP','0-75-1100','Rec from MCCP')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('RCCL','OIS','0-15-1100','Rec from OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('RCCL','OIS','0-15-2100','Pay to OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('RCCL','PDS','0-33-1100','Rec from PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description) VALUES ('RCCL','PDS','0-33-2100','Pay to PDS')


INSERT INTO IntercompanyReport_Accounts (Company, Intercompany, Account, Description)
SELECT	DATA.*
FROM	@tblAccounts DATA
		LEFT JOIN IntercompanyReport_Accounts ACCT ON DATA.Company = ACCT.Company AND DATA.Intercompany = ACCT.Intercompany AND DATA.Account = ACCT.Account AND ACCT.Inactive = 0
WHERE	ACCT.Account IS NULL
		--AND DATA.Company in ('PTS','NDS','IMCCS')

SELECT	*
FROM	IntercompanyReport_Accounts
WHERE	Inactive = 0
ORDER BY Company, Intercompany, Account

/*
SELECT	*
FROM	IntercompanyReport_Accounts
WHERE	Company = 'IMCNA'

UPDATE	IntercompanyReport_Accounts
SET		COMPANY = 'IMC'
WHERE	Company = 'IMCG'

DELETE	IntercompanyReport_Accounts
WHERE	Intercompany IN ('GSA','PTS','NDS','IMCCS')
		OR company IN ('GSA','PTS','NDS','IMCCS')
*/