DECLARE	@Company	Varchar(5) = 'IMC',
		@UserId		Varchar(30) = 'CFLORES',
		@ReceiptNum	Varchar(30) = 'ACH8000010535'

DECLARE	@Query		Varchar(MAX)

SET @Query = N'SELECT ''' + @Company + ''' AS COMPANY, APP.CUSTNMBR, APP.CPRCSTNM, APP.APFRDCNM, OPN.ORTRXAMT AS DOCFROMAMNT, APP.APTODCNM, OP2.ORTRXAMT AS DOCTOAMNT, APP.ActualApplyToAmount, ''' + @UserId + ''' AS UserId
FROM	' + @Company + '.dbo.RM20201 APP
		LEFT JOIN ' + @Company + '.dbo.RM20101 OPN ON APP.APFRDCNM = OPN.DOCNUMBR AND (APP.CUSTNMBR = OPN.CUSTNMBR OR APP.CPRCSTNM = OPN.CUSTNMBR)
		LEFT JOIN ' + @Company + '.dbo.RM20101 OP2 ON APP.APTODCNM = OP2.DOCNUMBR AND (APP.CUSTNMBR = OP2.CUSTNMBR OR APP.CPRCSTNM = OP2.CUSTNMBR)
WHERE	APP.APFRDCNM = ''' + @ReceiptNum + ''''

EXECUTE(@Query)

select * from GPCashReceipts_Activity 