DECLARE @CUSTNMBR	Varchar(15) = '23653'

SELECT CUSTNMBR, BALNCTYP FROM RM00101 WHERE CUSTNMBR = @CUSTNMBR

SELECT	CUSTBLNC AS CustomerBalance
FROM	RM00103
WHERE	CUSTNMBR = @CUSTNMBR

UPDATE RM00101 SET BALNCTYP = 0 WHERE CUSTNMBR = @CUSTNMBR 