DECLARE	@DOCNUMBR	Varchar(30) = '071014LOCKBOX',
		@CUSTNMBR	Varchar(20) = '2756',
		@RMDTYPAL	Int

SET		@RMDTYPAL	= (SELECT RMDTYPAL FROM RM20101 WHERE DOCNUMBR = @DOCNUMBR) -- CUSTNMBR = @CUSTNMBR AND

SELECT	DOCNUMBR,
		DOCDATE,
		CUSTNMBR,
		ORTRXAMT,
		CURTRXAM,
		RMDTYPAL
FROM	RM20101
WHERE	DOCNUMBR = @DOCNUMBR

IF @RMDTYPAL > 6
BEGIN
	SELECT	APFRDCNM,
			APTODCNM,
			CUSTNMBR,
			APFRDCTY,
			APTODCTY,
			APPTOAMT
	FROM	RM20201
	WHERE	--CUSTNMBR = @CUSTNMBR 
			APFRDCNM = @DOCNUMBR

			--DELETE RM20201
			--WHERE	--CUSTNMBR = @CUSTNMBR 
			--APFRDCNM = @DOCNUMBR

	SELECT	APFRDCNM,
			CUSTNMBR,
			APFRDCTY,
			APTODCTY,
			APPTOAMT
	FROM	RM30201
	WHERE	--CUSTNMBR = @CUSTNMBR 
			APFRDCNM = @DOCNUMBR
END
ELSE
BEGIN
	--SELECT	APFRDCNM,
	--		CUSTNMBR,
	--		APFRDCTY,
	--		APTODCTY,
	--		APPTOAMT
	SELECT	*
	FROM	RM20201
	WHERE	--CUSTNMBR = @CUSTNMBR 
			APTODCNM = @DOCNUMBR

	SELECT	*
	FROM	RM30201
	WHERE	--CUSTNMBR = @CUSTNMBR 
			APTODCNM = @DOCNUMBR
END
