SELECT	PMH.BACHNUMB,
		PMH.VCHRNMBR,
		PMH.VENDORID,
		PMH.DOCNUMBR,
		PMH.DOCAMNT,
		GL5.ACTNUMST,
		PMD.DISTTYPE,
		CAST(PMD.CRDTAMNT AS Numeric(10,2)) AS CRDTAMNT,
		CAST(PMD.DEBITAMT AS Numeric(10,2)) AS DEBITAMT,
		PMD.PSTGSTUS
FROM	PM10000 PMH
		LEFT JOIN PM10100 PMD ON PMH.VCHRNMBR = PMD.VCHRNMBR AND PMH.VENDORID = PMD.VENDORID
		LEFT JOIN GL00105 GL5 ON PMD.DSTINDX = GL5.ACTINDX
WHERE	PMH.BACHNUMB = 'PPD20200528'
ORDER BY PMH.VCHRNMBR,
		PMD.CRDTAMNT

SELECT	PMH.BACHNUMB,
		PMH.VCHRNMBR,
		PMH.VENDORID,
		PMH.DOCNUMBR,
		PMH.DOCAMNT,
		GL5.ACTNUMST,
		PMD.CRDTAMNT,
		PMD.DEBITAMT,
		PMD.PSTGSTUS
FROM	PM20000 PMH
		LEFT JOIN PM10100 PMD ON PMH.VCHRNMBR = PMD.VCHRNMBR AND PMH.VENDORID = PMD.VENDORID
		LEFT JOIN GL00105 GL5 ON PMD.DSTINDX = GL5.ACTINDX
WHERE	PMH.BACHNUMB = 'PPD20200528'
ORDER BY PMH.VCHRNMBR,
		PMD.CRDTAMNT