INSERT INTO PDS.dbo.RM00106 (CUSTNMBR, Email_Type, Email_Recipient)
SELECT	R6.CUSTNMBR,
		R6.Email_Type,
		R6.Email_Recipient
FROM	RM00106 R6
		INNER JOIN RM00101 R1 ON R6.CUSTNMBR = R1.CUSTNMBR
WHERE	R6.CUSTNMBR IN (SELECT CUSTNMBR FROM PDS.dbo.RM00101)
		AND RTRIM(R6.CUSTNMBR) + '_'+ RTRIM(R6.Email_Recipient) NOT IN (SELECT RTRIM(CUSTNMBR) + '_'+ RTRIM(Email_Recipient) FROM PDS.dbo.RM00106)

SELECT	R6.CUSTNMBR,
		upper(R1.CUSTNAME) AS CustomerName,
		LOWER(R6.Email_Recipient) AS EmailAddress
FROM	RM00106 R6
		INNER JOIN RM00101 R1 ON R6.CUSTNMBR = R1.CUSTNMBR
WHERE	R6.DEX_ROW_ID > 101
ORDER BY 2