BEGIN TRANSACTION

INSERT INTO [dbo].[PM00200]
           ([VENDORID]
           ,[VENDNAME]
           ,[VNDCHKNM]
           ,[VENDSHNM]
           ,[VADDCDPR]
           ,[VADCDPAD]
           ,[VADCDSFR]
           ,[VADCDTRO]
           ,[VNDCLSID]
           ,[VNDCNTCT]
           ,[ADDRESS1]
           ,[ADDRESS2]
           ,[ADDRESS3]
           ,[CITY]
           ,[STATE]
           ,[ZIPCODE]
           ,[COUNTRY]
           ,[PHNUMBR1]
           ,[PHNUMBR2]
           ,[PHONE3]
           ,[FAXNUMBR]
           ,[UPSZONE]
           ,[SHIPMTHD]
           ,[TAXSCHID]
           ,[ACNMVNDR]
           ,[TXIDNMBR]
           ,[VENDSTTS]
           ,[CURNCYID]
           ,[TXRGNNUM]
           ,[PARVENID]
           ,[TRDDISCT]
           ,[TEN99TYPE]
           ,[TEN99BOXNUMBER]
           ,[MINORDER]
           ,[PYMTRMID]
           ,[MINPYTYP]
           ,[MINPYPCT]
           ,[MINPYDLR]
           ,[MXIAFVND]
           ,[MAXINDLR]
           ,[COMMENT1]
           ,[COMMENT2]
           ,[USERDEF1]
           ,[USERDEF2]
           ,[CRLMTDLR]
           ,[PYMNTPRI]
           ,[KPCALHST]
           ,[KGLDSTHS]
           ,[KPERHIST]
           ,[KPTRXHST]
           ,[HOLD]
           ,[PTCSHACF]
           ,[CREDTLMT]
           ,[WRITEOFF]
           ,[MXWOFAMT]
           ,[SBPPSDED]
           ,[PPSTAXRT]
           ,[DXVARNUM]
           ,[CRTCOMDT]
           ,[CRTEXPDT]
           ,[RTOBUTKN]
           ,[XPDTOBLG]
           ,[PRSPAYEE]
           ,[PMAPINDX]
           ,[PMCSHIDX]
           ,[PMDAVIDX]
           ,[PMDTKIDX]
           ,[PMFINIDX]
           ,[PMMSCHIX]
           ,[PMFRTIDX]
           ,[PMTAXIDX]
           ,[PMWRTIDX]
           ,[PMPRCHIX]
           ,[PMRTNGIX]
           ,[PMTDSCIX]
           ,[ACPURIDX]
           ,[PURPVIDX]
           ,[NOTEINDX]
           ,[CHEKBKID]
           ,[MODIFDT]
           ,[CREATDDT]
           ,[RATETPID]
           ,[Revalue_Vendor]
           ,[Post_Results_To]
           ,[FREEONBOARD]
           ,[GOVCRPID]
           ,[GOVINDID]
           ,[DISGRPER]
           ,[DUEGRPER]
           ,[DOCFMTID]
           ,[TaxInvRecvd]
           ,[USERLANG]
           ,[WithholdingType]
           ,[WithholdingFormType]
           ,[WithholdingEntityType]
           ,[TaxFileNumMode]
           ,[BRTHDATE]
           ,[LaborPmtType]
           ,[CCode]
           ,[DECLID]
           ,[CBVAT]
           ,[Workflow_Approval_Status]
           ,[Workflow_Priority]
           ,[VADCD1099]
           ,[DEX_ROW_TS])

SELECT	NewVendorId AS [VendorId]
		,[VENDNAME]
		,[VNDCHKNM]
		,[VENDSHNM]
		,[VADDCDPR]
		,[VADCDPAD]
		,[VADCDSFR]
		,[VADCDTRO]
		,[VNDCLSID]
		,[VNDCNTCT]
		,[ADDRESS1]
		,[ADDRESS2]
		,[ADDRESS3]
		,[CITY]
		,[STATE]
		,[ZIPCODE]
		,[COUNTRY]
		,[PHNUMBR1]
		,[PHNUMBR2]
		,[PHONE3]
		,[FAXNUMBR]
		,[UPSZONE]
		,[SHIPMTHD]
		,[TAXSCHID]
		,[ACNMVNDR]
		,[TXIDNMBR]
		,[VENDSTTS]
		,[CURNCYID]
		,[TXRGNNUM]
		,[PARVENID]
		,[TRDDISCT]
		,[TEN99TYPE]
		,[TEN99BOXNUMBER]
		,[MINORDER]
		,[PYMTRMID]
		,[MINPYTYP]
		,[MINPYPCT]
		,[MINPYDLR]
		,[MXIAFVND]
		,[MAXINDLR]
		,[COMMENT1]
		,[COMMENT2]
		,[USERDEF1]
		,[USERDEF2]
		,[CRLMTDLR]
		,[PYMNTPRI]
		,[KPCALHST]
		,[KGLDSTHS]
		,[KPERHIST]
		,[KPTRXHST]
		,[HOLD]
		,[PTCSHACF]
		,[CREDTLMT]
		,[WRITEOFF]
		,[MXWOFAMT]
		,[SBPPSDED]
		,[PPSTAXRT]
		,[DXVARNUM]
		,[CRTCOMDT]
		,[CRTEXPDT]
		,[RTOBUTKN]
		,[XPDTOBLG]
		,[PRSPAYEE]
		,[PMAPINDX]
		,[PMCSHIDX]
		,[PMDAVIDX]
		,[PMDTKIDX]
		,[PMFINIDX]
		,[PMMSCHIX]
		,[PMFRTIDX]
		,[PMTAXIDX]
		,[PMWRTIDX]
		,[PMPRCHIX]
		,[PMRTNGIX]
		,[PMTDSCIX]
		,[ACPURIDX]
		,[PURPVIDX]
		,[NOTEINDX]
		,[CHEKBKID]
		,[MODIFDT]
		,[CREATDDT]
		,[RATETPID]
		,[Revalue_Vendor]
		,[Post_Results_To]
		,[FREEONBOARD]
		,[GOVCRPID]
		,[GOVINDID]
		,[DISGRPER]
		,[DUEGRPER]
		,[DOCFMTID]
		,[TaxInvRecvd]
		,[USERLANG]
		,[WithholdingType]
		,[WithholdingFormType]
		,[WithholdingEntityType]
		,[TaxFileNumMode]
		,[BRTHDATE]
		,[LaborPmtType]
		,[CCode]
		,[DECLID]
		,[CBVAT]
		,[Workflow_Approval_Status]
		,[Workflow_Priority]
		,[VADCD1099]
		,[DEX_ROW_TS]
FROM	(
		SELECT	VND.*, TMP.NewVendorId
		FROM	AIS.dbo.PM00200 VND
				INNER JOIN GPCustom.dbo.FRS_MappedVendors TMP ON VND.VendorId = TMP.VendorId AND TMP.Company = 'AIS' AND TMP.Payment = 'Charge Account'
		UNION
		SELECT	VND.*, TMP.NewVendorId
		FROM	DNJ.dbo.PM00200 VND
				INNER JOIN GPCustom.dbo.FRS_MappedVendors TMP ON VND.VendorId = TMP.VendorId AND TMP.Company = 'DNJ' AND TMP.Payment = 'Charge Account'
		UNION
		SELECT	VND.*, TMP.NewVendorId
		FROM	IMC.dbo.PM00200 VND
				INNER JOIN GPCustom.dbo.FRS_MappedVendors TMP ON VND.VendorId = TMP.VendorId AND TMP.Company = 'IMC' AND TMP.Payment = 'Charge Account'
		) DATA

INSERT INTO PM00300
		([VENDORID]
		,[ADRSCODE]
		,[VNDCNTCT]
		,[ADDRESS1]
		,[ADDRESS2]
		,[ADDRESS3]
		,[CITY]
		,[STATE]
		,[ZIPCODE]
		,[COUNTRY]
		,[UPSZONE]
		,[PHNUMBR1]
		,[PHNUMBR2]
		,[PHONE3]
		,[FAXNUMBR]
		,[SHIPMTHD]
		,[TAXSCHID]
		,[EmailPOs]
		,[POEmailRecipient]
		,[EmailPOFormat]
		,[FaxPOs]
		,[POFaxNumber]
		,[FaxPOFormat]
		,[CCode]
		,[DECLID]
		,[DEX_ROW_TS])
SELECT	NewVendorId AS [VENDORID]
		,[ADRSCODE]
		,[VNDCNTCT]
		,[ADDRESS1]
		,[ADDRESS2]
		,[ADDRESS3]
		,[CITY]
		,[STATE]
		,[ZIPCODE]
		,[COUNTRY]
		,[UPSZONE]
		,[PHNUMBR1]
		,[PHNUMBR2]
		,[PHONE3]
		,[FAXNUMBR]
		,[SHIPMTHD]
		,[TAXSCHID]
		,[EmailPOs]
		,[POEmailRecipient]
		,[EmailPOFormat]
		,[FaxPOs]
		,[POFaxNumber]
		,[FaxPOFormat]
		,[CCode]
		,[DECLID]
		,[DEX_ROW_TS]
FROM	(
		SELECT	VND.*, TMP.NewVendorId
		FROM	AIS.dbo.PM00300 VND
				INNER JOIN GPCustom.dbo.FRS_MappedVendors TMP ON VND.VendorId = TMP.VendorId AND TMP.Company = 'AIS' AND TMP.Payment = 'Charge Account'
		UNION
		SELECT	VND.*, TMP.NewVendorId
		FROM	DNJ.dbo.PM00300 VND
				INNER JOIN GPCustom.dbo.FRS_MappedVendors TMP ON VND.VendorId = TMP.VendorId AND TMP.Company = 'DNJ' AND TMP.Payment = 'Charge Account'
		UNION
		SELECT	VND.*, TMP.NewVendorId
		FROM	IMC.dbo.PM00300 VND
				INNER JOIN GPCustom.dbo.FRS_MappedVendors TMP ON VND.VendorId = TMP.VendorId AND TMP.Company = 'IMC' AND TMP.Payment = 'Charge Account'
		) DATA

IF @@ERROR > 0
	ROLLBACK TRANSACTION
ELSE
	COMMIT TRANSACTION