INSERT INTO [GPCustom].[dbo].[EscrowTransactions]
           ([Source]
           ,[VoucherNumber]
           ,[ItemNumber]
           ,[CompanyId]
           ,[Fk_EscrowModuleId]
           ,[AccountNumber]
           ,[AccountType]
           ,[VendorId]
           ,[DriverId]
           ,[Division]
           ,[Amount]
           ,[ClaimNumber]
           ,[DriverClass]
           ,[AccidentType]
           ,[Status]
           ,[DMSubmitted]
           ,[DeductionPlan]
           ,[Comments]
           ,[ProNumber]
           ,[TransactionDate]
           ,[PostingDate]
           ,[EnteredBy]
           ,[EnteredOn]
           ,[ChangedBy]
           ,[ChangedOn]
           ,[Void]
           ,[InvoiceNumber]
           ,[OtherStatus]
           ,[DeletedBy]
           ,[DeletedOn]
           ,[BatchId])
           
SELECT	[Source]
		,[VoucherNumber]
		,[ItemNumber]
		,'DNJ' AS [CompanyId]
		,[Fk_EscrowModuleId]
		,[AccountNumber]
		,[AccountType]
		,[VendorId]
		,[DriverId]
		,[Division]
		,[Amount]
		,[ClaimNumber]
		,[DriverClass]
		,[AccidentType]
		,[Status]
		,[DMSubmitted]
		,[DeductionPlan]
		,[Comments]
		,[ProNumber]
		,[TransactionDate]
		,[PostingDate]
		,[EnteredBy]
		,[EnteredOn]
		,[ChangedBy]
		,[ChangedOn]
		,[Void]
		,[InvoiceNumber]
		,[OtherStatus]
		,[DeletedBy]
		,[DeletedOn]
		,[BatchId]
FROM	View_EscrowTransactions
WHERE	VendorId IN (
					SELECT	VendorId
					FROM	VendorMaster
					WHERE	Company = 'IMC'
							AND Division = '26'
					)
		AND AccountNumber = '0-02-2790'