USE IMCGH

IF @@ERROR = 0
BEGIN
	TRUNCATE TABLE GL00100
	TRUNCATE TABLE GL00102
	TRUNCATE TABLE GL00103
	TRUNCATE TABLE GL00104
	TRUNCATE TABLE GL00105
	TRUNCATE TABLE GL40200
	TRUNCATE TABLE DTA00100
	TRUNCATE TABLE DTA00200
	TRUNCATE TABLE DTA00300
	TRUNCATE TABLE DTA00301
	TRUNCATE TABLE SY00300

	INSERT INTO dbo.DTA00100
			(GROUPID
			,DSCRIPTN
			,NOTEINDX)
	SELECT	GROUPID,
			DSCRIPTN,
			NOTEINDX
	FROM	IMC.dbo.DTA00100

	INSERT INTO [dbo].[DTA00200]
			([GROUPID]
			,[CODEID]
			,[CODEDESC])
	SELECT	GROUPID,
			CODEID,
			CODEDESC
	FROM	IMC.dbo.DTA00200

	INSERT INTO [dbo].[DTA00300]
			([ACTINDX]
			,[GROUPID]
			,[DTA_Quantities]
			,[ACCTSTAT]
			,[DECPLQTY])
	SELECT	ACTINDX,
			GROUPID,
			DTA_Quantities,
			ACCTSTAT,
			DECPLQTY
	FROM	IMC.dbo.DTA00300

	INSERT INTO [dbo].[DTA00301]
			([ACTINDX]
			,[GROUPID]
			,[CODEID]
			,[POSTDESC]
			,[PERCENTAMOUNT])
	SELECT	ACTINDX,
			GROUPID,
			CODEID,
			POSTDESC,
			PERCENTAMOUNT
	FROM	IMC.dbo.DTA00301

	INSERT INTO [dbo].[GL00100]
			([ACTINDX]
			,[ACTNUMBR_1]
			,[ACTNUMBR_2]
			,[ACTNUMBR_3]
			,[ACTALIAS]
			,[MNACSGMT]
			,[ACCTTYPE]
			,[ACTDESCR]
			,[PSTNGTYP]
			,[ACCATNUM]
			,[ACTIVE]
			,[TPCLBLNC]
			,[DECPLACS]
			,[FXDORVAR]
			,[BALFRCLC]
			,[DSPLKUPS]
			,[CNVRMTHD]
			,[HSTRCLRT]
			,[NOTEINDX]
			,[CREATDDT]
			,[MODIFDT]
			,[USERDEF1]
			,[USERDEF2]
			,[PostSlsIn]
			,[PostIvIn]
			,[PostPurchIn]
			,[PostPRIn]
			,[ADJINFL]
			,[INFLAREV]
			,[INFLAEQU]
			,[ACCTENTR]
			,[USRDEFS1]
			,[USRDEFS2]
			,[Clear_Balance]
			,[DEX_ROW_TS])
	SELECT	ACTINDX,
			ACTNUMBR_1,
			ACTNUMBR_2,
			ACTNUMBR_3,
			ACTALIAS,
			MNACSGMT,
			ACCTTYPE,
			ACTDESCR,
			PSTNGTYP,
			ACCATNUM,
			ACTIVE,
			TPCLBLNC,
			DECPLACS,
			FXDORVAR,
			BALFRCLC,
			DSPLKUPS,
			CNVRMTHD,
			HSTRCLRT,
			NOTEINDX,
			CREATDDT,
			MODIFDT,
			USERDEF1,
			USERDEF2,
			PostSlsIn,
			PostIvIn,
			PostPurchIn,
			PostPRIn,
			ADJINFL,
			INFLAREV,
			INFLAEQU,
			ACCTENTR,
			USRDEFS1,
			USRDEFS2,
			Clear_Balance,
			DEX_ROW_TS
	FROM	IMC.dbo.GL00100

	INSERT INTO [dbo].[GL00102]
			([ACCATNUM]
			,[ACCATDSC]
			,[DEX_ROW_TS])
	SELECT	ACCATNUM,
			ACCATDSC,
			DEX_ROW_TS
	FROM	IMC.dbo.GL00102

	INSERT INTO [dbo].[GL00103]
			([ACTINDX]
			,[PRCNTAGE]
			,[DSTINDX])
	SELECT	ACTINDX,
			PRCNTAGE,
			DSTINDX
	FROM	IMC.dbo.GL00103

	INSERT INTO [dbo].[GL00104]
			([ACTINDX]
			,[SEPRATR1]
			,[DSTINDX]
			,[SEPRATR2]
			,[BDNINDX])
	SELECT	ACTINDX,
			SEPRATR1,
			DSTINDX,
			SEPRATR2,
			BDNINDX
	FROM	IMC.dbo.GL00104

	INSERT INTO [dbo].[GL00105]
			([ACTINDX]
			,[ACTNUMBR_1]
			,[ACTNUMBR_2]
			,[ACTNUMBR_3]
			,[ACTNUMST])
	SELECT	ACTINDX,
			ACTNUMBR_1,
			ACTNUMBR_2,
			ACTNUMBR_3,
			ACTNUMST
	FROM	IMC.dbo.GL00105

	INSERT INTO [dbo].[GL40200]
			([SGMTNUMB]
			,[SGMNTID]
			,[DSCRIPTN]
			,[SEGCOUNT]
			,[NOTEINDX]
			,[DEX_ROW_TS])
	SELECT	SGMTNUMB,
			SGMNTID,
			DSCRIPTN,
			SEGCOUNT,
			NOTEINDX,
			DEX_ROW_TS
	FROM	IMC.dbo.GL40200

	INSERT INTO [dbo].[SY00300]
			([SGMTNUMB]
			,[SGMTNAME]
			,[LOFSGMNT]
			,[MXLENSEG]
			,[USDFSGKY]
			,[MNSEGIND]
			,[SegmentWidth]
			,[DEX_ROW_TS])
	SELECT	SGMTNUMB,
			SGMTNAME,
			LOFSGMNT,
			MXLENSEG,
			USDFSGKY,
			MNSEGIND,
			SegmentWidth,
			DEX_ROW_TS
	FROM	IMC.dbo.SY00300
END