INSERT INTO Integrations.dbo.FSI_ReceivedHeader
		([Company]
		,[BatchId]
		,[WeekEndDate]
		,[ReceivedOn]
		,[TotalTransactions]
		,[TotalSales]
		,[TotalVendorAccrual]
		,[TotalTruckAccrual]
		,[Status]
		,[Agent]
		,[Imaged]
		,[Verified])
SELECT	[Company]
		,[BatchId]
		,[WeekEndDate]
		,[ReceivedOn]
		,[TotalTransactions]
		,[TotalSales]
		,[TotalVendorAccrual]
		,[TotalTruckAccrual]
		,[Status]
		,[Agent]
		,[Imaged]
		,[Verified]
FROM	Integrations_restore.dbo.FSI_ReceivedHeader

INSERT INTO Integrations.dbo.FSI_ReceivedDetails
			([BatchId]
			,[DetailId]
			,[VoucherNumber]
			,[InvoiceNumber]
			,[CustomerNumber]
			,[ApplyTo]
			,[BillToRef]
			,[InvoiceDate]
			,[DeliveryDate]
			,[DueDate]
			,[AccessorialTotal]
			,[VendorPayTotal]
			,[FuelSurcharge]
			,[FuelRebateTotal]
			,[InvoiceTotal]
			,[DocumentType]
			,[ShipperName]
			,[ShipperCity]
			,[ConsigneeName]
			,[ConsigneeCity]
			,[BrokeredSale]
			,[TruckAccrualTotal]
			,[CompanyTruckAccrual]
			,[CompanyTruckDivision]
			,[CompanyTruckFuelRebate]
			,[CompanyDriverPay]
			,[InvoiceType]
			,[Division]
			,[RatingTable]
			,[Verification]
			,[Processed]
			,[Intercompany]
			,[RecordStatus]
			,[Imaged]
			,[Printed]
			,[Emailed]
			,[BrokerageOrderId]
			,[Equipment]
			,[TipProcessed]
			,[ICB]
			,[CheckDigit]
			,[PrePayType]
			,[WorkOrder])
	SELECT	FDR.BatchId
			,FDR.DetailId
			,FDR.VoucherNumber
			,FDR.InvoiceNumber
			,FDR.CustomerNumber
			,FDR.ApplyTo
			,FDR.BillToRef
			,FDR.InvoiceDate
			,FDR.DeliveryDate
			,FDR.DueDate
			,FDR.AccessorialTotal
			,FDR.VendorPayTotal
			,FDR.FuelSurcharge
			,FDR.FuelRebateTotal
			,FDR.InvoiceTotal
			,FDR.DocumentType
			,FDR.ShipperName
			,FDR.ShipperCity
			,FDR.ConsigneeName
			,FDR.ConsigneeCity
			,FDR.BrokeredSale
			,FDR.TruckAccrualTotal
			,FDR.CompanyTruckAccrual
			,FDR.CompanyTruckDivision
			,FDR.CompanyTruckFuelRebate
			,FDR.CompanyDriverPay
			,FDR.InvoiceType
			,FDR.Division
			,FDR.RatingTable
			,FDR.Verification
			,FDR.Processed
			,FDR.Intercompany
			,FDR.RecordStatus
			,FDR.Imaged
			,FDR.Printed
			,FDR.Emailed
			,FDR.BrokerageOrderId
			,FDR.Equipment
			,FDR.TipProcessed
			,FDR.ICB
			,FDR.CheckDigit
			,FDR.PrePayType
			,FDR.WorkOrder
	FROM	Integrations_Restore.dbo.FSI_ReceivedDetails FDR

	INSERT INTO Integrations.dbo.FSI_ReceivedSubDetails 
			([BatchId]
			,[DetailId]
			,[RecordType]
			,[RecordCode]
			,[Reference]
			,[ChargeAmount1]
			,[ChargeAmount2]
			,[ReferenceCode]
			,[Verification]
			,[Processed]
			,[VndIntercompany]
			,[VendorDocument]
			,[VendorReference]
			,[PrePay]
			,[AccCode]
			,[ICB]
			,[CheckDigit]
			,[PrePayType]
			,[FileRowNumber]
			,[PerDiemType]
			,[DemurrageAdminFee]
			,[ExternalId]
			,[SWSRecordId])
	SELECT	FSI.BatchId
			,FSI.DetailId
			,FSI.RecordType
			,FSI.RecordCode
			,FSI.Reference
			,FSI.ChargeAmount1
			,FSI.ChargeAmount2
			,FSI.ReferenceCode
			,FSI.Verification
			,FSI.Processed
			,FSI.VndIntercompany
			,FSI.VendorDocument
			,FSI.VendorReference
			,FSI.PrePay
			,FSI.AccCode
			,FSI.ICB
			,FSI.CheckDigit
			,FSI.PrePayType
			,FSI.FileRowNumber
			,FSI.PerDiemType
			,FSI.DemurrageAdminFee
			,FSI.ExternalId
			,FSI.SWSRecordId
	FROM	Integrations_Restore.dbo.FSI_ReceivedSubDetails FSI