DECLARE	@ACTINDX	Int,
		@ACTNUMBR_1	Char(3), 
		@ACTNUMBR_2	Char(3), 
		@ACTNUMBR_3	Char(5), 
		@ACTALIAS	Char(21), 
		@MNACSGMT	Char(67), 
		@ACCTTYPE	Smallint, 
		@ACTDESCR	Char(51), 
		@PSTNGTYP	Smallint, 
		@ACCATNUM	Smallint, 
		@ACTIVE		Tinyint, 
		@TPCLBLNC	Smallint,
		@DECPLACS	Smallint, 
		@FXDORVAR	Smallint,
		@BALFRCLC	Smallint, 
		@CNVRMTHD	Smallint

DECLARE curAccounts CURSOR LOCAL KEYSET OPTIMISTIC FOR
SELECT 	ACTNUMBR_1, 
		ACTNUMBR_2, 
		ACTNUMBR_3, 
		ACTALIAS, 
		MNACSGMT, 
		ACCTTYPE, 
		ACTDESCR, 
		PSTNGTYP, 
		ACCATNUM, 
		ACTIVE, 
		TPCLBLNC, 
		DECPLACS, 
		FXDORVAR, 
		BALFRCLC, 
		CNVRMTHD 
FROM	PRISQL01P.RCCL.DBO.GL00100 
WHERE	RTRIM(ActNumbr_1)+RTRIM(ActNumbr_2)+RTRIM(ActNumbr_3) NOT IN (SELECT RTRIM(ActNumbr_1)+RTRIM(ActNumbr_2)+RTRIM(ActNumbr_3) FROM RCCL.dbo.GL00100)

OPEN curAccounts 
FETCH FROM curAccounts INTO @ACTNUMBR_1, @ACTNUMBR_2, @ACTNUMBR_3, @ACTALIAS, @MNACSGMT, @ACCTTYPE, @ACTDESCR, 
			@PSTNGTYP, @ACCATNUM, @ACTIVE, @TPCLBLNC, @DECPLACS, @FXDORVAR, @BALFRCLC, @CNVRMTHD
BEGIN TRANSACTION

WHILE @@FETCH_STATUS = 0 
BEGIN
	SET	@ACTINDX = (SELECT MAX(ACTINDX) + 1 FROM GL00100)

	INSERT INTO GL00100 (
		ACTINDX,
		ACTNUMBR_1, 
		ACTNUMBR_2, 
		ACTNUMBR_3, 
		ACTALIAS, 
		MNACSGMT, 
		ACCTTYPE, 
		ACTDESCR, 
		PSTNGTYP, 
		ACCATNUM, 
		ACTIVE, 
		TPCLBLNC, 
		DECPLACS, 
		FXDORVAR, 
	       	BALFRCLC, 
		CNVRMTHD)
	VALUES (@ACTINDX,
		@ACTNUMBR_1, 
		@ACTNUMBR_2, 
		@ACTNUMBR_3, 
		@ACTALIAS, 
		@MNACSGMT, 
		@ACCTTYPE, 
		@ACTDESCR, 
		@PSTNGTYP, 
		@ACCATNUM, 
		@ACTIVE, 
		@TPCLBLNC, 
		@DECPLACS, 
		@FXDORVAR, 
	       	@BALFRCLC, 
		@CNVRMTHD)

	FETCH FROM curAccounts INTO @ACTNUMBR_1, @ACTNUMBR_2, @ACTNUMBR_3, @ACTALIAS, @MNACSGMT, @ACCTTYPE, @ACTDESCR, 
				@PSTNGTYP, @ACCATNUM, @ACTIVE, @TPCLBLNC, @DECPLACS, @FXDORVAR, @BALFRCLC, @CNVRMTHD
END

IF @@ERROR = 0
	COMMIT TRANSACTION
ELSE
	ROLLBACK TRANSACTION

CLOSE curAccounts
DEALLOCATE curAccounts

--SELECT * FROM gpcustom.dbo.MSR_ReceviedTransactions WHERE Account NOT IN (SELECT RTRIM(ActNumbr_1)+'-'+RTRIM(ActNumbr_2)+'-'+RTRIM(ActNumbr_3) FROM FRTES.DBO.GL00100)
--SELECT RTRIM(ActNumbr_1)+'-'+RTRIM(ActNumbr_2)+'-'+RTRIM(ActNumbr_3) FROM GL00100 order by 1
--select * FROM GL00105 order by actnumst

INSERT INTO GL00105
SELECT	 ACTINDX, ActNumbr_1, ActNumbr_2,ActNumbr_3, RTRIM(ActNumbr_1)+'-'+RTRIM(ActNumbr_2)+'-'+RTRIM(ActNumbr_3)
FROM 	GL00100 WHERE RTRIM(ActNumbr_1)+'-'+RTRIM(ActNumbr_2)+'-'+RTRIM(ActNumbr_3) NOT IN (SELECT ACTNUMST FROM GL00105)

INSERT INTO RM00101 (CUSTNMBR, CUSTNAME, CUSTCLAS, CPRCSTNM, CNTCPRSN, STMTNAME, SHRTNAME, ADRSCODE, UPSZONE, SHIPMTHD, TAXSCHID, ADDRESS1, ADDRESS2, 
                      ADDRESS3, COUNTRY, CITY, STATE, ZIP, PHONE1, PHONE2, PHONE3, FAX, PRBTADCD, PRSTADCD, STADDRCD, SLPRSNID, CHEKBKID, PYMTRMID, CRLMTTYP, 
                      CRLMTAMT, CRLMTPER, CRLMTPAM, CURNCYID, RATETPID, CUSTDISC, PRCLEVEL, MINPYTYP, MINPYDLR, MINPYPCT, FNCHATYP, FNCHPCNT, FINCHDLR, 
                      MXWOFTYP, MXWROFAM, COMMENT1, COMMENT2, USERDEF1, USERDEF2, TAXEXMT1, TAXEXMT2, TXRGNNUM, BALNCTYP, STMTCYCL, BANKNAME, 
                      BNKBRNCH, SALSTERR, DEFCACTY, RMCSHACC, RMSLSACC, RMARACC, RMIVACC, RMCOSACC, RMTAKACC, RMAVACC, RMFCGACC, RMWRACC, RMSORACC, 
                      FRSTINDT, INACTIVE, HOLD, CRCARDID, CRCRDNUM, CCRDXPDT, KPDSTHST, KPCALHST, KPERHIST, KPTRXHST, NOTEINDX, CREATDDT, MODIFDT, 
                      Revalue_Customer, Post_Results_To, FINCHID, GOVCRPID, GOVINDID, DISGRPER, DUEGRPER, DOCFMTID, Send_Email_Statements, USERLANG, 
                      GPSFOINTEGRATIONID, INTEGRATIONSOURCE, INTEGRATIONID, ORDERFULFILLDEFAULT, CUSTPRIORITY, CCode, DECLID, RMOvrpymtWrtoffAcctIdx, 
                      SHIPCOMPLETE, CBVAT)
SELECT CUSTNMBR, CUSTNAME, CUSTCLAS, CPRCSTNM, CNTCPRSN, STMTNAME, SHRTNAME, ADRSCODE, UPSZONE, SHIPMTHD, TAXSCHID, ADDRESS1, ADDRESS2, 
                      ADDRESS3, COUNTRY, CITY, STATE, ZIP, PHONE1, PHONE2, PHONE3, FAX, PRBTADCD, PRSTADCD, STADDRCD, SLPRSNID, CHEKBKID, PYMTRMID, CRLMTTYP, 
                      CRLMTAMT, CRLMTPER, CRLMTPAM, CURNCYID, RATETPID, CUSTDISC, PRCLEVEL, MINPYTYP, MINPYDLR, MINPYPCT, FNCHATYP, FNCHPCNT, FINCHDLR, 
                      MXWOFTYP, MXWROFAM, COMMENT1, COMMENT2, USERDEF1, USERDEF2, TAXEXMT1, TAXEXMT2, TXRGNNUM, BALNCTYP, STMTCYCL, BANKNAME, 
                      BNKBRNCH, SALSTERR, DEFCACTY, RMCSHACC, RMSLSACC, RMARACC, RMIVACC, RMCOSACC, RMTAKACC, RMAVACC, RMFCGACC, RMWRACC, RMSORACC, 
                      FRSTINDT, INACTIVE, HOLD, CRCARDID, CRCRDNUM, CCRDXPDT, KPDSTHST, KPCALHST, KPERHIST, KPTRXHST, NOTEINDX, CREATDDT, MODIFDT, 
                      Revalue_Customer, Post_Results_To, FINCHID, GOVCRPID, GOVINDID, DISGRPER, DUEGRPER, DOCFMTID, Send_Email_Statements, USERLANG, 
                      GPSFOINTEGRATIONID, INTEGRATIONSOURCE, INTEGRATIONID, ORDERFULFILLDEFAULT, CUSTPRIORITY, CCode, DECLID, RMOvrpymtWrtoffAcctIdx, 
                      SHIPCOMPLETE, CBVAT FROM RCMR.DBO.RM00101 WHERE CUSTNMBR NOT IN (SELECT CUSTNMBR FROM RTEST.DBO.RM00101)
SELECT * FROM RM00101

/*
insert into rm00102 (CUSTNMBR, ADRSCODE, SLPRSNID, UPSZONE, SHIPMTHD, TAXSCHID, CNTCPRSN, ADDRESS1, ADDRESS2, ADDRESS3, COUNTRY, CITY, STATE, ZIP, PHONE1, 
                      PHONE2, PHONE3, FAX, MODIFDT, CREATDDT, GPSFOINTEGRATIONID, INTEGRATIONSOURCE, INTEGRATIONID, CCode, DECLID, LOCNCODE, SALSTERR, 
                      USERDEF1, USERDEF2)
select CUSTNMBR, ADRSCODE, SLPRSNID, UPSZONE, SHIPMTHD, TAXSCHID, CNTCPRSN, ADDRESS1, ADDRESS2, ADDRESS3, COUNTRY, CITY, STATE, ZIP, PHONE1, 
                      PHONE2, PHONE3, FAX, MODIFDT, CREATDDT, GPSFOINTEGRATIONID, INTEGRATIONSOURCE, INTEGRATIONID, CCode, DECLID, LOCNCODE, SALSTERR, 
                      USERDEF1, USERDEF2 from rcmr.dbo.RM00102 WHERE CUSTNMBR NOT IN (SELECT CUSTNMBR FROM RTEST.DBO.RM00102)
*/