USE GLSO

SELECT	SUM(Counter)
FROM	(
		SELECT	COUNT(*) AS Counter
		FROM	PM20000
		WHERE	DOCTYPE = 1
				AND VOIDED = 0
				AND YEAR(POSTEDDT) = 2017
		UNION
		SELECT	COUNT(*) AS Counter
		FROM	PM30200
		WHERE	DOCTYPE = 1
				AND VOIDED = 0
				AND YEAR(POSTEDDT) = 2017
		) DATA