USE rccl

SELECT	count(VendorId)
FROM	(
		SELECT	DISTINCT VendorId
		FROM	PM20000
		WHERE	DOCTYPE = 1
				AND VOIDED = 0
				AND YEAR(POSTEDDT) = 2017
		UNION
		SELECT	DISTINCT VendorId
		FROM	PM30200
		WHERE	DOCTYPE = 1
				AND VOIDED = 0
				AND YEAR(POSTEDDT) = 2017
		) DATA