USE [master]
GO

/****** Object:
		Database dta40
Script Date: 8/28/2014 3:52:58 PM ******/
CREATE DATABASE [dta40]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dta40', FILENAME = N'D:\MSSQL\DATA\dta40.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'dta40_log', FILENAME = N'L:\MSSQL\LOGS\dta40_log.ldf' , SIZE = 4224KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [dta40] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dta40].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dta40] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dta40] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dta40] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dta40] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dta40] SET ARITHABORT OFF 
GO

ALTER DATABASE [dta40] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dta40] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [dta40] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dta40] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dta40] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dta40] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dta40] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dta40] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dta40] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dta40] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dta40] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dta40] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dta40] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dta40] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dta40] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dta40] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dta40] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dta40] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dta40] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [dta40] SET  MULTI_USER 
GO

ALTER DATABASE [dta40] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dta40] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dta40] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dta40] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [dta40] SET  READ_WRITE 
GO

USE [dta40]
GO

IF NOT EXISTS(SELECT Name FROM SYS.SysUsers WHERE Name = 'loadmaster')
BEGIN
	CREATE USER loadmaster FOR LOGIN loadmaster WITH DEFAULT_SCHEMA = dbo

	EXECUTE sp_addrolemember @rolename = 'db_owner', @membername = 'loadmaster' ;
	EXECUTE sp_addrolemember @rolename = 'db_accessadmin', @membername = 'loadmaster' ;

	EXECUTE master..sp_addsrvrolemember @loginame = N'loadmaster', @rolename = N'sysadmin'
END
GO