
CREATE TABLE [dbo].[GP_PM00200_Logs](
	[COMPANY] [char](5) NOT NULL,
	[VENDORID] [char](15) NOT NULL,
	[VENDNAME] [char](65) NOT NULL,
	[VNDCHKNM] [char](65) NOT NULL,
	[VENDSHNM] [char](15) NOT NULL,
	[VADDCDPR] [char](15) NOT NULL,
	[VADCDPAD] [char](15) NOT NULL,
	[VADCDSFR] [char](15) NOT NULL,
	[VADCDTRO] [char](15) NOT NULL,
	[VNDCLSID] [char](11) NOT NULL,
	[VNDCNTCT] [char](61) NOT NULL,
	[ADDRESS1] [char](61) NOT NULL,
	[ADDRESS2] [char](61) NOT NULL,
	[ADDRESS3] [char](61) NOT NULL,
	[CITY] [char](35) NOT NULL,
	[STATE] [char](29) NOT NULL,
	[ZIPCODE] [char](11) NOT NULL,
	[COUNTRY] [char](61) NOT NULL,
	[PHNUMBR1] [char](21) NOT NULL,
	[PHNUMBR2] [char](21) NOT NULL,
	[PHONE3] [char](21) NOT NULL,
	[FAXNUMBR] [char](21) NOT NULL,
	[UPSZONE] [char](3) NOT NULL,
	[SHIPMTHD] [char](15) NOT NULL,
	[TAXSCHID] [char](15) NOT NULL,
	[ACNMVNDR] [char](21) NOT NULL,
	[TXIDNMBR] [char](11) NOT NULL,
	[VENDSTTS] [smallint] NOT NULL,
	[CURNCYID] [char](15) NOT NULL,
	[TXRGNNUM] [char](25) NOT NULL,
	[PARVENID] [char](15) NOT NULL,
	[TRDDISCT] [smallint] NOT NULL,
	[TEN99TYPE] [smallint] NOT NULL,
	[TEN99BOXNUMBER] [smallint] NOT NULL,
	[MINORDER] [numeric](19, 5) NOT NULL,
	[PYMTRMID] [char](21) NOT NULL,
	[MINPYTYP] [smallint] NOT NULL,
	[MINPYPCT] [smallint] NOT NULL,
	[MINPYDLR] [numeric](19, 5) NOT NULL,
	[MXIAFVND] [smallint] NOT NULL,
	[MAXINDLR] [numeric](19, 5) NOT NULL,
	[COMMENT1] [char](31) NOT NULL,
	[COMMENT2] [char](31) NOT NULL,
	[USERDEF1] [char](21) NOT NULL,
	[USERDEF2] [char](21) NOT NULL,
	[CRLMTDLR] [numeric](19, 5) NOT NULL,
	[PYMNTPRI] [char](3) NOT NULL,
	[KPCALHST] [tinyint] NOT NULL,
	[KGLDSTHS] [tinyint] NOT NULL,
	[KPERHIST] [tinyint] NOT NULL,
	[KPTRXHST] [tinyint] NOT NULL,
	[HOLD] [tinyint] NOT NULL,
	[PTCSHACF] [smallint] NOT NULL,
	[CREDTLMT] [smallint] NOT NULL,
	[WRITEOFF] [smallint] NOT NULL,
	[MXWOFAMT] [numeric](19, 5) NOT NULL,
	[SBPPSDED] [tinyint] NOT NULL,
	[PPSTAXRT] [smallint] NOT NULL,
	[DXVARNUM] [char](25) NOT NULL,
	[CRTCOMDT] [datetime] NOT NULL,
	[CRTEXPDT] [datetime] NOT NULL,
	[RTOBUTKN] [tinyint] NOT NULL,
	[XPDTOBLG] [tinyint] NOT NULL,
	[PRSPAYEE] [tinyint] NOT NULL,
	[PMAPINDX] [int] NOT NULL,
	[PMCSHIDX] [int] NOT NULL,
	[PMDAVIDX] [int] NOT NULL,
	[PMDTKIDX] [int] NOT NULL,
	[PMFINIDX] [int] NOT NULL,
	[PMMSCHIX] [int] NOT NULL,
	[PMFRTIDX] [int] NOT NULL,
	[PMTAXIDX] [int] NOT NULL,
	[PMWRTIDX] [int] NOT NULL,
	[PMPRCHIX] [int] NOT NULL,
	[PMRTNGIX] [int] NOT NULL,
	[PMTDSCIX] [int] NOT NULL,
	[ACPURIDX] [int] NOT NULL,
	[PURPVIDX] [int] NOT NULL,
	[NOTEINDX] [numeric](19, 5) NOT NULL,
	[CHEKBKID] [char](15) NOT NULL,
	[MODIFDT] [datetime] NOT NULL,
	[CREATDDT] [datetime] NOT NULL,
	[RATETPID] [char](15) NOT NULL,
	[Revalue_Vendor] [tinyint] NOT NULL,
	[Post_Results_To] [smallint] NOT NULL,
	[FREEONBOARD] [smallint] NOT NULL,
	[GOVCRPID] [char](31) NOT NULL,
	[GOVINDID] [char](31) NOT NULL,
	[DISGRPER] [smallint] NOT NULL,
	[DUEGRPER] [smallint] NOT NULL,
	[DOCFMTID] [char](15) NOT NULL,
	[TaxInvRecvd] [tinyint] NOT NULL,
	[USERLANG] [smallint] NOT NULL,
	[WithholdingType] [smallint] NOT NULL,
	[WithholdingFormType] [smallint] NOT NULL,
	[WithholdingEntityType] [smallint] NOT NULL,
	[TaxFileNumMode] [smallint] NOT NULL,
	[BRTHDATE] [datetime] NOT NULL,
	[LaborPmtType] [smallint] NOT NULL,
	[CCode] [char](7) NOT NULL,
	[DECLID] [char](15) NOT NULL,
	[CBVAT] [tinyint] NOT NULL,
	[Workflow_Approval_Status] [smallint] NOT NULL,
	[Workflow_Priority] [smallint] NOT NULL,
	[Workflow_Status] [smallint] NOT NULL,
	[VADCD1099] [char](15) NOT NULL,
	[ONEPAYPERVENDINV] [smallint] NOT NULL,
	[VENDDBA] [char](65) NOT NULL,
	[DEX_ROW_TS] [datetime] NOT NULL,
	[DEX_ROW_ID] [int],
	[CHANGEDON] datetime,
	[CHANGEDBY] varchar(50))