SELECT	GL.JRNENTRY,
		GL.REFRENCE,
		GL.TRXDATE,
		GL.ORMSTRID AS VENDORIR,
		GL.ORMSTRNM AS VENDORNAME,
		GL.CRDTAMNT + GL.DEBITAMT AS AMOUNT,
		GL.OPENYEAR,
		GL.PERIODID AS AP_PERIOD,
		'AP OPEN' AS SourceTable
FROM	GL20000 GL
		INNER JOIN PM20000 PM ON GL.ORTRXSRC = PM.TRXSORCE AND GL.ORMSTRID = PM.VENDORID AND GL.ORDOCNUM = PM.DOCNUMBR
WHERE	GL.ACTINDX = 179
UNION
SELECT	GL.JRNENTRY,
		GL.REFRENCE,
		GL.TRXDATE,
		GL.ORMSTRID AS VENDORIR,
		GL.ORMSTRNM AS VENDORNAME,
		GL.CRDTAMNT + GL.DEBITAMT AS AMOUNT,
		GL.OPENYEAR,
		GL.PERIODID AS AP_PERIOD,
		'AP HISTORIC' AS SourceTable
FROM	GL20000 GL
		INNER JOIN PM30200 PM ON GL.ORTRXSRC = PM.TRXSORCE AND GL.ORMSTRID = PM.VENDORID AND GL.ORDOCNUM = PM.DOCNUMBR
WHERE	GL.ACTINDX = 179

