DECLARE	@DOCNUMBR	Varchar(25) = 'D31-135618',
		@DOCAMOUNT	Numeric(10,2),
		@DEXROWID	Int

SELECT	@DOCAMOUNT	= ORTRXAMT,
		@DEXROWID	= DEX_ROW_ID
FROM	RM30101
WHERE	DOCNUMBR = @DOCNUMBR

DELETE	RM30201
WHERE	APTODCNM = @DOCNUMBR
		AND APPTOAMT = @DOCAMOUNT

DELETE	RM30101
WHERE	DEX_ROW_ID = @DEXROWID
