SELECT	*
FROM	View_ExpenseRecovery
--DELETE ExpenseRecovery
WHERE	Company = 'IMC'
		--AND Expense IS NULL
		--AND Recovery IS NULL
		AND	VoucherNo NOT IN (SELECT CAST(JRNENTRY AS VARCHAR) FROM IMC..GL20000)
		AND	VoucherNo NOT IN (SELECT VCHRNMBR FROM IMC..PM20000)
		AND	VoucherNo NOT IN (SELECT VCHRNMBR FROM IMC..PM30600)
		AND Closed = 0
ORDER BY Description, DocNumber

-- SELECT * FROM IMC..GL20000 WHERE JRNENTRY = 872996
-- SELECT * FROM IMC..PM20000