DECLARE	@BatchId Varchar(25) = 'FSIAR2208151625'

DELETE	GL20000
WHERE	ORGNTSRC IN (SELECT TRXSORCE FROM RM20101 WHERE BACHNUMB = @BatchId AND RIGHT(RTRIM(DOCNUMBR),1) = 'Z')

DELETE	RM10101
WHERE	TRXSORCE IN (SELECT TRXSORCE FROM RM20101 WHERE BACHNUMB = @BatchId AND RIGHT(RTRIM(DOCNUMBR),1) = 'Z')

DELETE	RM20201
WHERE	APFRDCNM IN (SELECT DOCNUMBR FROM RM20101 WHERE BACHNUMB = @BatchId AND RIGHT(RTRIM(DOCNUMBR),1) = 'Z')

DELETE	RM00401
WHERE	DOCNUMBR IN (SELECT DOCNUMBR FROM RM20101 WHERE BACHNUMB = @BatchId AND RIGHT(RTRIM(DOCNUMBR),1) = 'Z')

DELETE	RM20101 
WHERE	BACHNUMB = @BatchId
		AND RIGHT(RTRIM(DOCNUMBR),1) = 'Z'
