SELECT	*
FROM	gl40200

DELETE	gl40200
WHERE	DEX_ROW_ID IN (

SELECT	DEX_ROW_ID
FROM	(
SELECT LEN(SGMNTID) as SegLength
	 ,SGMTNUMB
	 , SGMNTID
	 ,DEX_ROW_ID
    FROM gl40200
    GROUP BY SGMTNUMB, SGMNTID, DEX_ROW_ID
    HAVING (SGMTNUMB = 1 AND LEN(sgmntid) <> 1)
    OR (SGMTNUMB = 2 AND LEN(sgmntid) <> 2)
    OR (SGMTNUMB = 3 AND LEN(SGMNTID) <> 4)
    ) DATA)


--SELECT * INTO GPCUSTOM.dbo.IMCMR_GL40200 FROM gl40200