SELECT * FROM DeaParts WHERE DESCRIPT like '%fuel%'

SELECT	PART_NO,
		DESCRIPT,
		BIN,
		CDEX_DAMAG,
		CDEX_MATER,
		CDEX_REPAI,
		CDEX_COMPO,
		CDEX_LOCAT
FROM	DeaParts 
WHERE	row_status = 'N'
ORDER BY BIN, PART_NO