INSERT INTO NDS.dbo.RM00102
           (CUSTNMBR
           ,ADRSCODE
           ,SLPRSNID
           ,UPSZONE
           ,SHIPMTHD
           ,TAXSCHID
           ,CNTCPRSN
           ,ADDRESS1
           ,ADDRESS2
           ,ADDRESS3
           ,COUNTRY
           ,CITY
           ,STATE
           ,ZIP
           ,PHONE1
           ,PHONE2
           ,PHONE3
           ,FAX
           ,MODIFDT
           ,CREATDDT
           ,GPSFOINTEGRATIONID
           ,INTEGRATIONSOURCE
           ,INTEGRATIONID
           ,CCode
           ,DECLID
           ,LOCNCODE
           ,SALSTERR
           ,USERDEF1
           ,USERDEF2)
SELECT	DISTINCT IM.NewCustNo
		,RM.ADRSCODE
		,RM.SLPRSNID
		,RM.UPSZONE
		,RM.SHIPMTHD
		,RM.TAXSCHID
		,RM.CNTCPRSN
		,RM.ADDRESS1
		,RM.ADDRESS2
		,RM.ADDRESS3
		,RM.COUNTRY
		,RM.CITY
		,RM.STATE
		,RM.ZIP
		,RM.PHONE1
		,RM.PHONE2
		,RM.PHONE3
		,RM.FAX
		,RM.MODIFDT
		,RM.CREATDDT
		,RM.GPSFOINTEGRATIONID
		,RM.INTEGRATIONSOURCE
		,RM.INTEGRATIONID
		,RM.CCode
		,RM.DECLID
		,RM.LOCNCODE
		,RM.SALSTERR
		,RM.USERDEF1
		,RM.USERDEF2
FROM	NDS.dbo.RM00102 RM
		INNER JOIN NDS_Agent_22_Customers IM ON IM.CustNo = RM.CUSTNMBR
WHERE	IM.NewCustNo NOT IN (SELECT CustNmbr FROM NDS.dbo.RM00102)

/*
INSERT INTO NDS.dbo.RM00101
           (CUSTNMBR
           ,CUSTNAME
           ,CUSTCLAS
           ,CPRCSTNM
           ,CNTCPRSN
           ,STMTNAME
           ,SHRTNAME
           ,ADRSCODE
           ,UPSZONE
           ,SHIPMTHD
           ,TAXSCHID
           ,ADDRESS1
           ,ADDRESS2
           ,ADDRESS3
           ,COUNTRY
           ,CITY
           ,STATE
           ,ZIP
           ,PHONE1
           ,PHONE2
           ,PHONE3
           ,FAX
           ,PRBTADCD
           ,PRSTADCD
           ,STADDRCD
           ,SLPRSNID
           ,CHEKBKID
           ,PYMTRMID
           ,CRLMTTYP
           ,CRLMTAMT
           ,CRLMTPER
           ,CRLMTPAM
           ,CURNCYID
           ,RATETPID
           ,CUSTDISC
           ,PRCLEVEL
           ,MINPYTYP
           ,MINPYDLR
           ,MINPYPCT
           ,FNCHATYP
           ,FNCHPCNT
           ,FINCHDLR
           ,MXWOFTYP
           ,MXWROFAM
           ,COMMENT1
           ,COMMENT2
           ,USERDEF1
           ,USERDEF2
           ,TAXEXMT1
           ,TAXEXMT2
           ,TXRGNNUM
           ,BALNCTYP
           ,STMTCYCL
           ,BANKNAME
           ,BNKBRNCH
           ,SALSTERR
           ,DEFCACTY
           ,RMCSHACC
           ,RMARACC
           ,RMSLSACC
           ,RMIVACC
           ,RMCOSACC
           ,RMTAKACC
           ,RMAVACC
           ,RMFCGACC
           ,RMWRACC
           ,RMSORACC
           ,FRSTINDT
           ,INACTIVE
           ,HOLD
           ,CRCARDID
           ,CRCRDNUM
           ,CCRDXPDT
           ,KPDSTHST
           ,KPCALHST
           ,KPERHIST
           ,KPTRXHST
           ,NOTEINDX
           ,CREATDDT
           ,MODIFDT
           ,Revalue_Customer
           ,Post_Results_To
           ,FINCHID
           ,GOVCRPID
           ,GOVINDID
           ,DISGRPER
           ,DUEGRPER
           ,DOCFMTID
           ,Send_Email_Statements
           ,USERLANG
           ,GPSFOINTEGRATIONID
           ,INTEGRATIONSOURCE
           ,INTEGRATIONID
           ,ORDERFULFILLDEFAULT
           ,CUSTPRIORITY
           ,CCode
           ,DECLID
           ,RMOvrpymtWrtoffAcctIdx
           ,SHIPCOMPLETE
           ,CBVAT
           ,INCLUDEINDP)
SELECT	DISTINCT AGT.NewCustNo AS CustNmbr
		,CUS.CUSTNAME
		,CUS.CUSTCLAS
		,CUS.CPRCSTNM
		,CUS.CNTCPRSN
		,CUS.STMTNAME
		,CUS.SHRTNAME
		,CUS.ADRSCODE
		,CUS.UPSZONE
		,CUS.SHIPMTHD
		,CUS.TAXSCHID
		,CUS.ADDRESS1
		,CUS.ADDRESS2
		,CUS.ADDRESS3
		,CUS.COUNTRY
		,CUS.CITY
		,CUS.STATE
		,CUS.ZIP
		,CUS.PHONE1
		,CUS.PHONE2
		,CUS.PHONE3
		,CUS.FAX
		,CUS.PRBTADCD
		,CUS.PRSTADCD
		,CUS.STADDRCD
		,CUS.SLPRSNID
		,CUS.CHEKBKID
		,CUS.PYMTRMID
		,CUS.CRLMTTYP
		,CUS.CRLMTAMT
		,CUS.CRLMTPER
		,CUS.CRLMTPAM
		,CUS.CURNCYID
		,CUS.RATETPID
		,CUS.CUSTDISC
		,CUS.PRCLEVEL
		,CUS.MINPYTYP
		,CUS.MINPYDLR
		,CUS.MINPYPCT
		,CUS.FNCHATYP
		,CUS.FNCHPCNT
		,CUS.FINCHDLR
		,CUS.MXWOFTYP
		,CUS.MXWROFAM
		,CUS.COMMENT1
		,CUS.COMMENT2
		,CUS.USERDEF1
		,CUS.USERDEF2
		,CUS.TAXEXMT1
		,CUS.TAXEXMT2
		,CUS.TXRGNNUM
		,CUS.BALNCTYP
		,CUS.STMTCYCL
		,CUS.BANKNAME
		,CUS.BNKBRNCH
		,22 AS SALSTERR
		,CUS.DEFCACTY
		,CUS.RMCSHACC
		,CUS.RMARACC
		,CUS.RMSLSACC
		,CUS.RMIVACC
		,CUS.RMCOSACC
		,CUS.RMTAKACC
		,CUS.RMAVACC
		,CUS.RMFCGACC
		,CUS.RMWRACC
		,CUS.RMSORACC
		,CUS.FRSTINDT
		,0 AS INACTIVE
		,CUS.HOLD
		,CUS.CRCARDID
		,CUS.CRCRDNUM
		,CUS.CCRDXPDT
		,CUS.KPDSTHST
		,CUS.KPCALHST
		,CUS.KPERHIST
		,CUS.KPTRXHST
		,CUS.NOTEINDX
		,CUS.CREATDDT
		,CUS.MODIFDT
		,CUS.Revalue_Customer
		,CUS.Post_Results_To
		,CUS.FINCHID
		,CUS.GOVCRPID
		,CUS.GOVINDID
		,CUS.DISGRPER
		,CUS.DUEGRPER
		,CUS.DOCFMTID
		,CUS.Send_Email_Statements
		,CUS.USERLANG
		,CUS.GPSFOINTEGRATIONID
		,CUS.INTEGRATIONSOURCE
		,CUS.INTEGRATIONID
		,CUS.ORDERFULFILLDEFAULT
		,CUS.CUSTPRIORITY
		,CUS.CCode
		,CUS.DECLID
		,CUS.RMOvrpymtWrtoffAcctIdx
		,CUS.SHIPCOMPLETE
		,CUS.CBVAT
		,CUS.INCLUDEINDP
FROM	NDS_Agent_22_Customers AGT
		INNER JOIN NDS.dbo.RM00101 CUS ON AGT.CustNo = CUS.CustNmbr
WHERE	AGT.NewCustNo NOT IN (SELECT CustNmbr FROM NDS.dbo.RM00101)

SELECT	* 
FROM	NDS.dbo.RM00101
WHERE	CustNmbr IN (SELECT NewCustNo FROM NDS_Agent_22_Customers) WHERE Inactivate = 'Y')

UPDATE	NDS.dbo.RM00101
SET		Inactive = 1
WHERE	CustNmbr IN (SELECT CustNo FROM NDS_Agent_22_Customers WHERE Inactivate = 'Y')
*/