SELECT	DISTINCT USERID, USERNAME, SecurityTaskName--, CompanyName
FROM	(
		SELECT	S.USERID UserID, 
				U.USERNAME,
				S.CMPANYID CompanyID,
				C.CMPNYNAM CompanyName, S.SecurityRoleID,
				coalesce(T.SECURITYTASKID,'') SecurityTaskID,
				coalesce(TM.SECURITYTASKNAME,'') SecurityTaskName,
				coalesce(TM.SECURITYTASKDESC,'') SecurityTaskDescription
		FROM	SY10500 S   -- security assignment user role
				INNER JOIN SY01400 U ON S.USERID = U.USERID
				LEFT OUTER JOIN SY01500 C ON S.CMPANYID = C.CMPANYID
				LEFT OUTER JOIN SY10600 T ON S.SECURITYROLEID = T.SECURITYROLEID 
				LEFT OUTER JOIN SY09000 TM ON T.SECURITYTASKID = TM.SECURITYTASKID 
		WHERE	SecurityTaskName  = 'Maintain customers and addresses'
				AND C.CMPNYNAM NOT LIKE '%TEST%'
				AND C.CMPNYNAM NOT LIKE '%ARCHIVE%'
				AND C.CMPNYNAM NOT LIKE '%HISTORI%'
				AND C.CMPNYNAM NOT LIKE '%HOLDI%'
				AND C.CMPNYNAM NOT LIKE '%CONSOLI%'
		) DATA
ORDER BY USERID, USERNAME--, CompanyName