SELECT	* 
FROM	(
		SELECT	R1.CUSTNMBR,
				R1.DOCNUMBR AS [Pro],
				CAST(R1.DOCDATE AS Date) AS DOCDATE,
				CAST(R1.ORTRXAMT AS Numeric(10,2)) AS ORTRXAMT,
				CAST(R1.CURTRXAM AS Numeric(10,2)) AS CURTRXAM,
				R1.RMDTYPAL,
				ApplyDate = (SELECT CAST(MAX(GLPOSTDT) AS Date) FROM [GLSO].[dbo].[RM20201] R2 WHERE R1.CUSTNMBR = R2.CUSTNMBR AND R1.DOCNUMBR = R2.APTODCNM AND R2.APFRDCTY <> 7),
				EB.ProNumber
		FROM	[GLSO].[dbo].[RM20101] R1 
				INNER JOIN [GPCustom].[dbo].[CustomerMaster] CM ON R1.CUSTNMBR = CM.CUSTNMBR AND CM.CompanyId = 'GLSO'
				LEFT JOIN PRISQL09P.Tributary.dbo.lu_ActiveShortPay EB ON CM.CompanyId = EB.Company AND R1.DOCNUMBR = EB.ProNumber
		WHERE	VOIDSTTS = 0
				AND RMDTYPAL < 7 
				AND CM.ExcludeFromShortPay = 0 
				AND R1.CURTRXAM > 0
				AND R1.CURTRXAM < R1.ORTRXAMT
		) DATA
ORDER BY PRO
