--SELECT * FROM UPR40300
--SELECT * FROM UPR00102

SELECT	HDR.EMPLOYID,
		RTRIM(HDR.LASTNAME) + ', ' + RTRIM(HDR.FRSTNAME) + IIF(HDR.MIDLNAME = '', '', ' ' + RTRIM(HDR.MIDLNAME)) AS Name,
		CAST(HDR.STRTDATE AS Date) AS STARTDATE,
		CAST(HDR.DEMPINAC AS Date) AS TERMDATE,
		ISNULL(RTRIM(DET.ADDRESS1) + IIF(DET.ADDRESS2 <> '', ' ' + RTRIM(DET.ADDRESS2), ''), ''),
		ISNULL(DET.CITY, ''),
		ISNULL(DET.STATE, ''),
		ISNULL(DET.ZIPCODE, ''),
		GPCustom.dbo.FormatPhoneNumber(DET.PHONE1) AS PhoneNumber
FROM	UPR00100 HDR
		LEFT JOIN UPR00102 DET ON HDR.EMPLOYID = DET.EMPLOYID AND DET.ADRSCODE = 'PRIMARY'
WHERE	HDR.DEMPINAC BETWEEN '01/01/2004' AND '12/31/2016'
ORDER BY 2


--HDR.STRTDATE BETWEEN '01/01/2005' AND '12/31/2015'