DECLARE	@Query		Varchar(1000),
		@Company	Varchar(5)

DECLARE curCompanies CURSOR LOCAL KEYSET OPTIMISTIC FOR
SELECT	CompanyID 
FROM	DYNAMICS.dbo.View_Companies 
ORDER BY CompanyID

OPEN curCompanies 
FETCH FROM curCompanies INTO @Company

WHILE @@FETCH_STATUS = 0 
BEGIN
	SET @Query = 'ALTER DATABASE ' + RTRIM(@Company) + '  
				SET CHANGE_TRACKING = ON;' 
	
	BEGIN TRY  
		EXECUTE(@Query)
	END TRY  
	BEGIN CATCH  
		 PRINT ERROR_MESSAGE()  
	END CATCH  

	SET @Query = 'ALTER TABLE ' + RTRIM(@Company) + '.dbo.GL10001
ENABLE CHANGE_TRACKING  
WITH (TRACK_COLUMNS_UPDATED = ON) ' 
	
	BEGIN TRY  
		EXECUTE(@Query)
	END TRY  
	BEGIN CATCH  
		 PRINT ERROR_MESSAGE()  
	END CATCH  

	SET @Query = 'ALTER TABLE ' + RTRIM(@Company) + '.dbo.GL20000
ENABLE CHANGE_TRACKING  
WITH (TRACK_COLUMNS_UPDATED = ON) '
	
	BEGIN TRY  
		EXECUTE(@Query)
	END TRY  
	BEGIN CATCH  
		 PRINT ERROR_MESSAGE()  
	END CATCH 

	SET @Query = 'ALTER TABLE ' + RTRIM(@Company) + '.dbo.GL30000
ENABLE CHANGE_TRACKING  
WITH (TRACK_COLUMNS_UPDATED = ON) '
	
	BEGIN TRY  
		EXECUTE(@Query)
	END TRY  
	BEGIN CATCH  
		 PRINT ERROR_MESSAGE()  
	END CATCH 

	SET @Query = 'ALTER TABLE ' + RTRIM(@Company) + '.dbo.MC40600
ENABLE CHANGE_TRACKING  
WITH (TRACK_COLUMNS_UPDATED = ON) '
	
	BEGIN TRY  
		EXECUTE(@Query)
	END TRY  
	BEGIN CATCH  
		 PRINT ERROR_MESSAGE()  
	END CATCH 

	FETCH FROM curCompanies INTO @Company
END

CLOSE curCompanies
DEALLOCATE curCompanies

/*
ALTER TABLE DYNAMICS.dbo.SY01500
ENABLE CHANGE_TRACKING  
WITH (TRACK_COLUMNS_UPDATED = ON)  
GO

ALTER TABLE DYNAMICS.dbo.SY01501
ENABLE CHANGE_TRACKING  
WITH (TRACK_COLUMNS_UPDATED = ON)  
GO

ALTER TABLE MHGH.dbo.GL30000
ENABLE CHANGE_TRACKING  
WITH (TRACK_COLUMNS_UPDATED = ON) 
GO

ALTER TABLE MHGH.dbo.MC40600
ENABLE CHANGE_TRACKING  
WITH (TRACK_COLUMNS_UPDATED = ON)  
--GO
*/