EXECUTE SP_LoadCensusData 'CFLORES', 0, '1/4/2007','3/26/2007', 'ALL', 'ALL', 'BLANK', 'BLANK', 'BLANK', 'BLANK', '314', 'NONE'

SELECT RowNumber, IMC_CENSUSREP.EMPLOYID, DEPRTMNT, DEPTDESC, LASTNAME, FNAMEMI, SOCSCNUM, CASE CONVERT(NVARCHAR,HIREDATE,101) WHEN '01/01/1900' THEN '' ELSE CONVERT(NVARCHAR,HIREDATE,101) END HIREDATE ,CASE GENDER WHEN 1 THEN 'Male' WHEN 2 THEN 'Female'  WHEN 3 THEN 'N/A' END GENDER, GROSSPAY, CITY, STATE, CASE CONVERT(NVARCHAR,LASTDAYWORKED_I,101) WHEN '01/01/1900' THEN '' ELSE CONVERT(NVARCHAR,LASTDAYWORKED_I,101) END LASTDAYWORKED_I, CASE CONVERT(NVARCHAR,BIRTHDATE,101) WHEN '01/01/1900' THEN '' ELSE CONVERT(NVARCHAR,BIRTHDATE,101) END BIRTHDATE, CASE MARITALSTATUS WHEN 1 THEN 'Married' WHEN 2 THEN 'Single'  WHEN 3 THEN 'N/A' END MARITALSTATUS, CASE INACTIVE WHEN 1 THEN 'INACTIVE'  WHEN 0 THEN 'ACTIVE' END INACTIVE, CASE EMPLYTYPE WHEN 1 THEN 'Full Time Regular'  WHEN 2 THEN 'Full Time Temp'  WHEN 3 THEN 'Part Time Regular'  WHEN 4 THEN 'Part Time Temp'  WHEN 5 THEN 'Intern' END EMPLYTYPE, WC_CODE, WC_RATE, WC_COST, JOBDESC, PAYRATE, FLSA, BENCODE, BENRATE, MONTHLY_BENEFIT, DEDNCODE, DEDNRATE, MONTHLY_DEDN, CASE CONVERT(NVARCHAR,BEN_ACTIVATION_DATE,101) WHEN '01/01/1900' THEN '' ELSE CONVERT(NVARCHAR,BEN_ACTIVATION_DATE,101) END BEN_ACTIVATION_DATE, CASE CONVERT(NVARCHAR,BEN_TERM_DATE,101) WHEN '01/01/1900' THEN '' ELSE CONVERT(NVARCHAR,BEN_TERM_DATE,101) END BEN_TERM_DATE, CASE CONVERT(NVARCHAR,DEDN_ACTIVATION_DATE,101) WHEN '01/01/1900' THEN '' ELSE CONVERT(NVARCHAR,DEDN_ACTIVATION_DATE,101) END DEDN_ACTIVATION_DATE, CASE CONVERT(NVARCHAR,DEDN_TERM_DATE,101) WHEN '01/01/1900' THEN '' ELSE CONVERT(NVARCHAR,DEDN_TERM_DATE,101) END DEDN_TERM_DATE, REPID, USERID, PayrolCD, UprTrxAm, 'RCMR' AS DBName FROM IMC_CENSUSREP WHERE USERID = 'CFLORES' ORDER BY DEPRTMNT, LASTNAME, FNAMEMI

SELECT * FROM IMC_CENSUSREP WHERE EMPLOYID = 11

SELECT 	DISTINCT PAYTYPE, PAYRCORD, 
			PAYRTAMT 
		FROM 	UPR00400 
		WHERE 	EMPLOYID = 11 AND 
			PAYTYPE IN (1, 2, 3) AND
			PAYRTAMT > 0