SELECT	RTRIM(ACTNUMBR_1) + '-' + RTRIM(ACTNUMBR_2) + '-' + RTRIM(ACTNUMBR_3) AS GLAccount,
		ISNULL(ACCATDSC, '[NOT DEFINED]') AS Category,
		ActDescr AS Description,
		UsrDefs1 AS UserDefineCategory
FROM	GL00100
		LEFT JOIN GL00102 ON GL00100.ACCATNUM = GL00102.ACCATNUM
ORDER BY 1

--select * from GL00102
--SELECT * FROM GL00100
-- SELECT * FROM DYNAMICS.DBO.VIEW_ALLCOMPANIES