SELECT	DB_NAME() AS CompanyId,
		CUSTNMBR,
		CASE WHEN INACTIVE = 1 THEN 'YES' ELSE 'NO' END AS INACTIVE,
		CUSTNAME,
		CUSTCLAS AS CUSTOMER_CLASS,
		CNTCPRSN AS CONTACT,
		ADDRESS1,
		ADDRESS2,
		CITY,
		STATE,
		ZIP,
		PHONE1
FROM	RM00101
ORDER BY CUSTNMBR