SELECT	JRNENTRY,
		REFRENCE,
		CAST(TRXDATE AS Date) AS TRXDATE,
		ORGNTSRC,
		DEBITAMT,
		CRDTAMNT,
		ROW_NUMBER() OVER(PARTITION BY REFRENCE ORDER BY JRNENTRY)
FROM	GL20000
WHERE	REFRENCE IN (
					SELECT	REFRENCE
					FROM	(
							SELECT	REFRENCE,
									COUNT(REFRENCE) AS Counter
							FROM	GL20000
							WHERE	ACTINDX = 613
									AND REFRENCE LIKE 'ICB%'
							GROUP BY REFRENCE
							HAVING COUNT(REFRENCE) > 2
							) DATA
					)
		AND ACTINDX = 613
ORDER BY REFRENCE, JRNENTRY