DECLARE @Invoice	Varchar(30) = '100074568'

SELECT	APH.VENDORID,
		APH.DOCNUMBR,
		APH.DOCDATE,
		APH.TRXDSCRN,
		APH.DOCAMNT,
		GL5.ACTNUMST
FROM	GLSO.dbo.PM20000 APH
		INNER JOIN GLSO.dbo.PM10100 APD ON APH.VCHRNMBR = APD.VCHRNMBR AND APH.VENDORID = APD.VENDORID
		INNER JOIN GLSO.dbo.GL00105 GL5 ON APD.DSTINDX = GL5.ACTINDX
WHERE	APH.DOCNUMBR LIKE ('%' + @Invoice + '%')
UNION
SELECT	APH.VENDORID,
		APH.DOCNUMBR,
		APH.DOCDATE,
		APH.TRXDSCRN,
		APH.DOCAMNT,
		GL5.ACTNUMST
FROM	GLSO.dbo.PM30200 APH
		INNER JOIN GLSO.dbo.PM30600 APD ON APH.VCHRNMBR = APD.VCHRNMBR AND APH.VENDORID = APD.VENDORID
		INNER JOIN GLSO.dbo.GL00105 GL5 ON APD.DSTINDX = GL5.ACTINDX
WHERE	APH.DOCNUMBR LIKE ('%' + @Invoice + '%')