/*
EXECUTE USP_AGRCustomerBalances
*/
ALTER PROCEDURE USP_AGRCustomerBalances
AS
SELECT	CUS.CUSTNMBR
		,CUS.CUSTNAME
		,CUS.CRLMTAMT AS CreditLimit
		,opn.RMDTYPAL
		,OPN.DOCNUMBR
		,OPN.DOCDATE
		,OPN.DUEDATE
		,CASE WHEN RMDTYPAL IN (1) THEN 1 ELSE -1 END * OPN.CURTRXAM AS CURTRXAM
FROM	RM00101 CUS
		INNER JOIN RM20101 OPN ON CUS.CUSTNMBR = OPN.CUSTNMBR and OPN.CURTRXAM <> 0
WHERE	CUS.CustClas = 'AGR'
		--AND CUS.CUSTNMBR IN ('10422','10619','10756','11797','22046','22047')
UNION
SELECT	CUS.CUSTNMBR
		,CUS.CUSTNAME
		,CUS.CRLMTAMT AS CreditLimit
		,opn.RMDTYPAL
		,OPN.DOCNUMBR
		,OPN.DOCDATE
		,OPN.DUEDATE
		,CASE WHEN RMDTYPAL IN (1) THEN 1 ELSE -1 END * OPN.CURTRXAM AS CURTRXAM
FROM	RM00101 CUS
		INNER JOIN RM30101 OPN ON CUS.CUSTNMBR = OPN.CUSTNMBR and OPN.CURTRXAM <> 0
WHERE	CUS.CustClas = 'AGR'
		--AND CUS.CUSTNMBR IN ('10422','10619','10756','11797','22046','22047')
ORDER BY
		CUS.CUSTNMBR
		,OPN.DOCDATE
/*
SELECT	*
FROM	RM20101

SELECT	*
FROM	RM00101
WHERE	CustClas = 'AGR'
*/