DECLARE	@tblCustomers	Table (CUSTNMBR Varchar(12))
DECLARE @CUSTNMBR		Varchar(12),
		@RowId			Int

INSERT INTO @tblCustomers
SELECT	DISTINCT CUSTNMBR
FROM	(
		SELECT	CUSTNMBR,
				COUNT(*) AS COUNTER
		FROM	RM00103
		GROUP BY CUSTNMBR
		HAVING COUNT(*) > 1
		) DATA

DECLARE curSummary CURSOR LOCAL KEYSET OPTIMISTIC FOR
SELECT	CUSTNMBR,
		MIN(DEX_ROW_ID) AS DEX_ROW_ID
FROM	RM00103
WHERE	CUSTNMBR IN (SELECT CUSTNMBR FROM @tblCustomers)
GROUP BY CUSTNMBR

OPEN curSummary 
FETCH FROM curSummary INTO @CUSTNMBR, @RowId

WHILE @@FETCH_STATUS = 0 
BEGIN
	PRINT @CUSTNMBR

	DELETE	RM00103
	WHERE	CUSTNMBR = @CUSTNMBR
			AND DEX_ROW_ID > @RowId

	FETCH FROM curSummary INTO @CUSTNMBR, @RowId
END

CLOSE curSummary
DEALLOCATE curSummary