DECLARE @DOCNUMBR	Varchar(30) = 'C98-100046',
		@APPTOAMT	Numeric(12,0),
		@BALANCE	Numeric(12,0),
		@ORIGAMNT	Numeric(12,0)

SELECT	@BALANCE	= CURTRXAM,
		@ORIGAMNT	= ORTRXAMT
FROM	RM20101
WHERE	DOCNUMBR = @DOCNUMBR

SELECT	@APPTOAMT = SUM(APPTOAMT)
FROM	(
		SELECT	CUSTNMBR, APTODCNM, APPTOAMT
		FROM	RM20201
		WHERE	APFRDCNM = @DOCNUMBR
		UNION
		SELECT	CUSTNMBR, APTODCNM, APPTOAMT
		FROM	RM30201
		WHERE	APFRDCNM = @DOCNUMBR
		) DATA

IF @ORIGAMNT - @BALANCE <> @APPTOAMT AND ISNULL(@ORIGAMNT,0) > 0
BEGIN
	PRINT 'YES'

	UPDATE	RM20101
	SET		ORTRXAMT = @ORIGAMNT - @APPTOAMT
	WHERE	DOCNUMBR = @DOCNUMBR
END
ELSE
	PRINT 'NO'

/*
update	RM20101
set		curtrxam = ortrxamt - 38678.69000
WHERE	DOCNUMBR = 'C98-100046'
*/