SELECT	*
FROM	GL10001
WHERE	CRDTAMNT = DEBITAMT
		OR ORCRDAMT = ORDBTAMT

SELECT	*
FROM	GL20000
WHERE	CRDTAMNT = DEBITAMT
		OR ORCRDAMT = ORDBTAMT

SELECT	*
FROM	GL30000
WHERE	CRDTAMNT = DEBITAMT
		OR ORCRDAMT = ORDBTAMT

SELECT	*
FROM	GL30000
WHERE	(CRDTAMNT = DEBITAMT
		OR ORCRDAMT = ORDBTAMT)
		AND ORCRDAMT + ORDBTAMT = 0

SELECT	*
FROM	GL30000
WHERE	CRDTAMNT = DEBITAMT
		AND ORCRDAMT = ORDBTAMT

UPDATE	GL20000
SET		ORCRDAMT = CRDTAMNT,
		ORDBTAMT = DEBITAMT
WHERE	CRDTAMNT = DEBITAMT
		OR ORCRDAMT = ORDBTAMT

UPDATE	GL30000
SET		ORCRDAMT = 0,
		CRDTAMNT = 0
WHERE	CRDTAMNT = DEBITAMT
		AND ORCRDAMT = ORDBTAMT

UPDATE	GL30000
SET		ORCRDAMT = CRDTAMNT,
		ORDBTAMT = DEBITAMT
WHERE	(CRDTAMNT = DEBITAMT
		OR ORCRDAMT = ORDBTAMT)
		AND ORCRDAMT + ORDBTAMT = 0

-- DELETE GL20000 WHERE JRNENTRY = 321228
-- DELETE GL30000 WHERE CRDTAMNT + DEBITAMT = 0