/*
SELECT	RM.*
FROM	RM10101 RM
		INNER JOIN GL00100 GL ON RM.DSTINDX = GL.ACTINDX
WHERE	RM.DOCNUMBR IN (
					SELECT	DOCNUMBR
					FROM	RM10301 --RM10101
					WHERE	BACHNUMB = 'AR_RCMR_111004')
		AND GL.ACTNUMBR_3 = '4013'

2110 = Tax
4013 = Materials
4016 = Labor
*/
DECLARE	@Account Char(4)

SET @Account = '4013'

UPDATE	RM10101
SET		RM10101.CRDTAMNT = RECS.CRDTAMNT + RECS.Difference
FROM	(
		SELECT	RM.DEX_ROW_ID,
				RM.CRDTAMNT,
				RECS.Difference
		FROM	RM10101 RM
				INNER JOIN GL00100 GL ON RM.DSTINDX = GL.ACTINDX
				INNER JOIN (
							SELECT	DOCNUMBR,
									DEBITAMT - CRDTAMNT AS Difference
							FROM	(
									SELECT	DOCNUMBR,
											SUM(DEBITAMT) AS DEBITAMT,
											SUM(CRDTAMNT) AS CRDTAMNT
									FROM	RM10101
									WHERE	DOCNUMBR IN (
														SELECT	DOCNUMBR
														FROM	RM10301
														WHERE	BACHNUMB = 'AR_FI_120319')
									GROUP BY DOCNUMBR
									HAVING SUM(DEBITAMT) <> SUM(CRDTAMNT)) DATA
							) RECS ON RM.DOCNUMBR = RECS.DOCNUMBR
		WHERE	GL.ACTNUMBR_3 = @Account
		) RECS
WHERE	RM10101.DEX_ROW_ID = RECS.DEX_ROW_ID