DECLARE	@BachNumber	Varchar(25),
		@VCHRNMBR	Varchar(25),
		@TRXSORCE	Varchar(20),
		@DOCNUMBR	Varchar(30),
		@DSTINDX	Int,
		@DSTSQNUM	Int,
		@DistRef	Varchar(30),
		@CRDTAMNT	Numeric(10,2),
		@DEBITAMT	Numeric(10,2),
		@ACTNUMST	Varchar(20),
		@DEX_ROW_ID	Int

SET		@BachNumber = 'DEX110701170001'

SELECT	PMH.VCHRNMBR
		,PMH.TRXSORCE
		,PMH.DOCNUMBR
		,PMD.DSTINDX
		,PMD.DSTSQNUM
		,PMD.DistRef
		,PMD.CRDTAMNT
		,PMD.DEBITAMT
		,PMD.DEX_ROW_ID
FROM	PM20000 PMH
		INNER JOIN PM10100 PMD ON PMH.VCHRNMBR = PMD.VCHRNMBR
WHERE	PMH.BACHNUMB = @BachNumber

DECLARE DataRecords CURSOR LOCAL KEYSET OPTIMISTIC FOR
SELECT	PMH.VCHRNMBR
		,PMH.TRXSORCE
		,PMH.DOCNUMBR
		,PMD.DSTINDX
		,PMD.DSTSQNUM
		,PMD.DistRef
		,PMD.CRDTAMNT
		,PMD.DEBITAMT
		,PMD.DEX_ROW_ID
FROM	PM20000 PMH
		INNER JOIN PM10100 PMD ON PMH.VCHRNMBR = PMD.VCHRNMBR
WHERE	PMH.BACHNUMB = @BachNumber

OPEN DataRecords 
FETCH FROM DataRecords INTO @VCHRNMBR, @TRXSORCE, @DOCNUMBR, @DSTINDX, @DSTSQNUM, @DistRef, @CRDTAMNT, @DEBITAMT, @DEX_ROW_ID

WHILE @@FETCH_STATUS = 0 
BEGIN
	SET		@DistRef = NULL
	
	SELECT	@ACTNUMST = RTRIM(ACTNUMST)
	FROM	GL00105
	WHERE	ACTINDX = @DSTINDX
	
	SELECT	@DistRef = DISTREF
	FROM	ILSINT01.Integrations.dbo.Integrations_AP
	WHERE	BatchId = @BachNumber
			AND VCHNUMWK = @VCHRNMBR
			AND ACTNUMST = @ACTNUMST
			AND CRDTAMNT = @CRDTAMNT
			AND DEBITAMT = @DEBITAMT
	
	IF @DistRef IS NOT Null
	BEGIN
		UPDATE	PM10100
		SET		DistRef = @DistRef
		WHERE	DEX_ROW_ID = @DEX_ROW_ID
		
		UPDATE	GL20000
		SET		REFRENCE = @DistRef,
				DSCRIPTN = @DistRef
		WHERE	ORTRXSRC = @TRXSORCE
				AND ORCTRNUM = @VCHRNMBR
				AND OrigSeqNum = @DSTSQNUM
				AND ACTINDX = @DSTINDX
	END
	
	FETCH FROM DataRecords INTO @VCHRNMBR, @TRXSORCE, @DOCNUMBR, @DSTINDX, @DSTSQNUM, @DistRef, @CRDTAMNT, @DEBITAMT, @DEX_ROW_ID
END

CLOSE DataRecords
DEALLOCATE DataRecords

/*
SELECT * FROM GL20000 WHERE JRNENTRY = 214836
*/