INSERT INTO IV00101 (ITEMNMBR, ITEMDESC, ITMCLSCD, DECPLQTY)
SELECT	Part_No,
		Descript,
		Bin, 
		0
FROM	GPCustom.dbo.FI_Tires
WHERE	Part_No NOT IN (SELECT ITEMNMBR FROM IV00101)

/*
SELECT	*
FROM	IV00101
WHERE	ITMCLSCD = 'TIRES'

SELECT	*
FROM	IV00103

SELECT	*
FROM	GPCustom.dbo.FI_Tires

INSERT INTO IV00103 (ITEMNMBR, VENDORID, VNDITNUM)
SELECT	RTRIM(Part_No),
		RTRIM(VendorId),
		RTRIM(VendorCode)
FROM	GPCustom.dbo.FI_Tires
WHERE	Part_No IN (SELECT ITEMNMBR FROM IV00101)
		AND Part_No NOT IN (SELECT ITEMNMBR FROM IV00103)

UPDATE	IV00101
SET		DECPLQTY = 1,
		DECPLCUR = 2,
		ITMGEDSC = 'TIRES',
		ITMTRKOP = 1,
		ITEMTYPE = 1,
		TAXOPTNS = 3,
		UOMSCHDL = 'TIRE',
		USCATVLS_1 = 'TIRES',
		PRCLEVEL = 'RETAIL',
		PRICEGROUP = 'TIRES',
		VCTNMTHD = 1,
		MSTRCDTY = 1,
		ABCCODE = 1,
		Revalue_Inventory = 1,
		Purchase_Tax_Options = 1,
		ITMPLNNNGTYP = 1
WHERE	ITMCLSCD = 'TIRES'
		AND DECPLQTY = 0
*/