-- FIND CUSTOMER MASTER SUMMARY DUPLICATED RECORDS

SET NOCOUNT ON

DECLARE	@Company	Varchar(5),
		@Query		Varchar(2000)

DECLARE @tblRows	Table (Company Varchar(5), CustomerId Varchar(15), Counter Int, LastDate Date)

DECLARE curGPCompanies CURSOR LOCAL KEYSET OPTIMISTIC FOR
SELECT	RTRIM(InterId)
FROM	DYNAMICS.dbo.View_AllCompanies
ORDER BY 1

OPEN curGPCompanies 
FETCH FROM curGPCompanies INTO @Company

WHILE @@FETCH_STATUS = 0 
BEGIN
	PRINT @Company

	SET @Query = N'SELECT ''' + @Company + ''' AS Company, RTRIM(CUSTNMBR) AS CUSTNMBR, COUNT(*) AS COUNTER, MAX(LSTTRXDT) AS LSTTRXDT
FROM	' + @Company + '.dbo.RM00103
GROUP BY CUSTNMBR
HAVING	COUNT(*) > 1
ORDER BY CUSTNMBR'
		
	INSERT INTO @tblRows
	EXECUTE(@Query)

	FETCH FROM curGPCompanies INTO @Company
END

CLOSE curGPCompanies
DEALLOCATE curGPCompanies

SELECT	*
FROM	@tblRows

/*

*/
--SELECT	*
--FROM	GIS..RM00103
--WHERE	CUSTNMBR IN ('12789','15711','4173','4701','552H','7000S')
--ORDER BY CUSTNMBR, LSTTRXDT DESC

/*
DELETE	GIS.dbo.RM00103
FROM	(
		SELECT	RTRIM(CUSTNMBR) AS CUSTNMBR, COUNT(*) AS COUNTER, MAX(LSTTRXDT) AS LSTTRXDT
		FROM	GIS.dbo.RM00103
		GROUP BY CUSTNMBR
		HAVING	COUNT(*) > 1
		) DATA
WHERE	RM00103.CUSTNMBR = DATA.CUSTNMBR
		AND RM00103.LSTTRXDT < DATA.LSTTRXDT
*/