DECLARE	@JRNENTRY	Int,
		@SEQNUMBR	Int,
		@DEBITAMT	Numeric(12,3),
		@CRDTAMNT	Numeric(12,3),
		@ORDBTAMT	Numeric(12,3),
		@ORCRDAMT	Numeric(12,3),
		@Amount		Numeric(12,3)

DECLARE @tblRecords Table (
		JRNENTRY	Int,
		SEQNUMBR	Int,
		DEBITAMT	Numeric(12,3),
		CRDTAMNT	Numeric(12,3),
		ORDBTAMT	Numeric(12,3),
		ORCRDAMT	Numeric(12,3))

INSERT INTO @tblRecords
SELECT	JRNENTRY,
		SEQNUMBR,
		DEBITAMT,
		CRDTAMNT,
		ORDBTAMT,
		ORCRDAMT
FROM	GL30000
WHERE	CRDTAMNT > 0
		AND DEBITAMT > 0

DECLARE Transaction_Companies CURSOR LOCAL KEYSET OPTIMISTIC FOR
SELECT	*
FROM	@tblRecords

OPEN Transaction_Companies 
FETCH FROM Transaction_Companies INTO @JRNENTRY, @SEQNUMBR, @DEBITAMT, @CRDTAMNT, @ORDBTAMT, @ORCRDAMT

WHILE @@FETCH_STATUS = 0 
BEGIN
	SET @Amount = @CRDTAMNT - @DEBITAMT

	IF @Amount > 0
		UPDATE	GL30000
		SET		DEBITAMT = 0,
				CRDTAMNT = @Amount,
				ORDBTAMT = 0,
				ORCRDAMT = @Amount
		WHERE	JRNENTRY = @JRNENTRY
				AND SEQNUMBR = @SEQNUMBR
	ELSE
		UPDATE	GL30000
		SET		DEBITAMT = ABS(@Amount),
				CRDTAMNT = 0,
				ORDBTAMT = ABS(@Amount),
				ORCRDAMT = 0
		WHERE	JRNENTRY = @JRNENTRY
				AND SEQNUMBR = @SEQNUMBR	

	FETCH FROM Transaction_Companies INTO @JRNENTRY, @SEQNUMBR, @DEBITAMT, @CRDTAMNT, @ORDBTAMT, @ORCRDAMT
END

CLOSE Transaction_Companies
DEALLOCATE Transaction_Companies

/*
SELECT	*
FROM	GL30000
WHERE	JRNENTRY = 9606
--WHERE	CRDTAMNT > 0
--		AND DEBITAMT > 0

UPDATE	GL20000
SET		DEBITAMT = 0,
		CRDTAMNT = 53.02,
		ORDBTAMT = 0,
		ORCRDAMT = 53.02
WHERE	JRNENTRY = 191
		AND ACTINDX = 15

UPDATE	GL20000
SET		DEBITAMT = 0,
		CRDTAMNT = 53.02,
		ORDBTAMT = 0,
		ORCRDAMT = 53.02
WHERE	JRNENTRY = 191
		AND ACTINDX = 16

UPDATE	GL20000
SET		DEBITAMT = 0,
		CRDTAMNT = 54.82,
		ORDBTAMT = 0,
		ORCRDAMT = 54.82
WHERE	JRNENTRY = 191
		AND ACTINDX = 18

UPDATE	GL20000
SET		DEBITAMT = 53.02,
		CRDTAMNT = 0,
		ORDBTAMT = 53.02,
		ORCRDAMT = 0
WHERE	JRNENTRY = 191
		AND ACTINDX = 52

UPDATE	GL20000
SET		DEBITAMT = 693,
		CRDTAMNT = 0,
		ORDBTAMT = 693,
		ORCRDAMT = 0
WHERE	JRNENTRY = 191
		AND ACTINDX = 80

UPDATE	GL20000
SET		DEBITAMT = 0,
		CRDTAMNT = 585.16,
		ORDBTAMT = 0,
		ORCRDAMT = 585.16
WHERE	JRNENTRY = 191
		AND ACTINDX = 88
*/