--SELECT	*
--FROM	PM00200
--WHERE	VENDORID >= '969'
--		AND LEFT(VENDORID, 1) <> 'A'
SET NOCOUNT OFF

SELECT	PMD.VENDORID,
		PMD.VENDNAME,
		PMD.VNDCHKNM AS VENDOR_CURRENT,
		PMA.VNDCHKNM AS VENDOR_AIS
INTO	#tmpVendors
FROM	IMC.dbo.PM00200 PMD
		LEFT JOIN AIS.dbo.PM00200 PMA ON PMD.VENDORID = PMA.VENDORID
WHERE	LEFT(PMD.VENDORID, 1) <> 'D'
		AND PMD.VENDNAME <> PMD.VNDCHKNM
		AND PMD.VNDCHKNM = PMA.VNDCHKNM
		AND PMD.VENDORID NOT IN ('PDEGLV','PDANLC','PDCSVU')

UPDATE	IMC.dbo.PM00200
SET		VNDCHKNM = VENDNAME
WHERE	LEFT(VENDORID, 1) <> 'D'
		AND VENDNAME <> VNDCHKNM
		AND VENDORID IN (SELECT VENDORID FROM #tmpVendors)

DROP TABLE #tmpVendors