/*
EXECUTE USP_FixGLReferences
*/
ALTER PROCEDURE USP_FixGLReferences
AS
DECLARE	@Year	Int,
		@Period	Int

SELECT	@Year	= MAX(YEAR1),
		@Period	= MIN(PERIODID)
FROM	View_FiscalPeriods
WHERE	CLOSED = 0
		AND YEAR1 = YEAR(GETDATE() - 10)

PRINT	@Period
PRINT	@Year
		
UPDATE	GL20000
SET		REFRENCE = DSCRIPTN
WHERE	REFRENCE <> DSCRIPTN
		AND DSCRIPTN <> ''
		AND VOIDED = 0 
		AND OPENYEAR = @Year
		--AND MONTH(ORPSTDDT) >= @Period

/*
SELECT	DISTINCT PM.DistRef,
		GL.REFRENCE,
		PM.TRXSORCE,
		PM.DSTSQNUM,
		PM.DSTINDX,
		PH.VCHRNMBR
INTO	##tmpOpenRecords
FROM	GL20000 GL
		INNER JOIN PM30600 PM ON GL.ORGNTSRC = PM.TRXSORCE AND GL.OrigSeqNum = PM.DSTSQNUM AND GL.ACTINDX = PM.DSTINDX
		INNER JOIN PM30200 PH ON PM.TRXSORCE = PH.TRXSORCE AND PM.VCHRNMBR = PH.VCHRNMBR AND GL.ORDOCNUM = PH.DOCNUMBR
WHERE	LEFT(GL.ORGNTSRC, 2) = 'PM'
		AND GL.OPENYEAR = @Year
		AND GL.PERIODID = @Period
		AND GL.REFRENCE <> PM.DistRef
		AND PM.DistRef <> ''
		AND GL.ORPSTDDT > GETDATE() - 30

INSERT INTO ##tmpOpenRecords
SELECT	DISTINCT PM.DistRef,
		GL.REFRENCE,
		PM.TRXSORCE,
		PM.DSTSQNUM,
		PM.DSTINDX,
		PH.VCHRNMBR
FROM	GL20000 GL
		INNER JOIN PM20000 PH ON GL.ORGNTSRC = PH.TRXSORCE AND GL.ORDOCNUM = PH.DOCNUMBR AND GL.ORCTRNUM = PH.VCHRNMBR
		INNER JOIN PM10100 PM ON PH.TRXSORCE = PM.TRXSORCE AND PH.VCHRNMBR = PM.VCHRNMBR AND GL.OrigSeqNum = PM.DSTSQNUM AND GL.ACTINDX = PM.DSTINDX
WHERE	GL.OPENYEAR = @Year
		AND GL.PERIODID = @Period
		AND LEFT(GL.ORGNTSRC, 2) = 'PM'
		AND GL.REFRENCE <> PM.DistRef
		AND PM.DistRef <> ''
		AND GL.ORPSTDDT > GETDATE() - 30

INSERT INTO ##tmpOpenRecords
SELECT	CASE WHEN RD.DistRef = '' THEN RTRIM(LEFT(CU.CUSTNAME, 15)) + ' ' + RTRIM(RH.DOCNUMBR) ELSE RD.DistRef END AS DistRef,
		GL.REFRENCE,
		RH.TRXSORCE,
		RD.SEQNUMBR,
		RD.DSTINDX,
		RD.DOCNUMBR
FROM	GL20000 GL
		INNER JOIN RM20101 RH ON GL.ORGNTSRC = RH.TRXSORCE AND GL.ORCTRNUM = RH.DOCNUMBR
		INNER JOIN RM10101 RD ON RH.DOCNUMBR = RD.DOCNUMBR AND RH.TRXSORCE = RD.TRXSORCE AND RH.CUSTNMBR = RD.CUSTNMBR AND GL.OrigSeqNum = RD.SEQNUMBR AND GL.ACTINDX = RD.DSTINDX
		INNER JOIN RM00101 CU ON RH.CUSTNMBR = CU.CUSTNMBR
WHERE	LEFT(GL.ORGNTSRC, 2) = 'SL'
		AND GL.OPENYEAR = @Year
		AND GL.PERIODID = @Period
		AND GL.REFRENCE <> CASE WHEN RD.DistRef = '' THEN RTRIM(LEFT(CU.CUSTNAME, 15)) + ' ' + RTRIM(RH.DOCNUMBR) ELSE RD.DistRef END
		AND GL.ORPSTDDT > GETDATE() - 30

INSERT INTO ##tmpOpenRecords
SELECT	CASE WHEN RD.DistRef = '' THEN RTRIM(LEFT(CU.CUSTNAME, 15)) + ' ' + RTRIM(RH.DOCNUMBR) ELSE RD.DistRef END AS DistRef,
		GL.REFRENCE,
		RH.TRXSORCE,
		RD.SEQNUMBR,
		RD.DSTINDX,
		RD.DOCNUMBR
FROM	GL20000 GL
		INNER JOIN RM30101 RH ON GL.ORGNTSRC = RH.TRXSORCE AND GL.ORCTRNUM = RH.DOCNUMBR
		INNER JOIN RM30301 RD ON RH.DOCNUMBR = RD.DOCNUMBR AND RH.TRXSORCE = RD.TRXSORCE AND RH.CUSTNMBR = RD.CUSTNMBR AND GL.OrigSeqNum = RD.SEQNUMBR AND GL.ACTINDX = RD.DSTINDX
		INNER JOIN RM00101 CU ON RH.CUSTNMBR = CU.CUSTNMBR
WHERE	LEFT(GL.ORGNTSRC, 2) = 'SL'
		AND GL.OPENYEAR = @Year
		AND GL.PERIODID = @Period
		AND GL.REFRENCE <> CASE WHEN RD.DistRef = '' THEN RTRIM(LEFT(CU.CUSTNAME, 15)) + ' ' + RTRIM(RH.DOCNUMBR) ELSE RD.DistRef END
		AND GL.ORPSTDDT > GETDATE() - 30

UPDATE	GL20000
SET		GL20000.REFRENCE = DATA.DistRef,
		GL20000.DSCRIPTN = DATA.DistRef
FROM	(
		SELECT	*
		FROM	##tmpOpenRecords
		) DATA
WHERE	GL20000.ORGNTSRC = DATA.TRXSORCE 
		AND GL20000.OrigSeqNum = DATA.DSTSQNUM 
		AND GL20000.ACTINDX = DATA.DSTINDX
		AND GL20000.ORCTRNUM = DATA.VCHRNMBR
		AND GL20000.REFRENCE <> DATA.DistRef
		AND DATA.DistRef <> ''

UPDATE	GL20000
SET		REFRENCE = DSCRIPTN
WHERE	OPENYEAR = @Year
		AND PERIODID = @Period
		AND SOURCDOC = 'GJ'
		AND REFRENCE <> DSCRIPTN
		AND DSCRIPTN <> ''

DROP TABLE ##tmpOpenRecords
GO
*/
--UPDATE	GL30000
--SET		GL30000.REFRENCE = DATA.DistRef,
--		GL30000.DSCRIPTN = DATA.DistRef
--FROM	(
--		SELECT	DISTINCT PM.DistRef,
--				GL.REFRENCE,
--				PM.TRXSORCE,
--				PM.DSTSQNUM,
--				PM.DSTINDX,
--				PH.DOCNUMBR
--		FROM	GL30000 GL
--				INNER JOIN PM30600 PM ON GL.ORGNTSRC = PM.TRXSORCE AND GL.OrigSeqNum = PM.DSTSQNUM AND GL.ACTINDX = PM.DSTINDX
--				INNER JOIN PM30200 PH ON PM.TRXSORCE = PH.TRXSORCE AND PM.VCHRNMBR = PH.VCHRNMBR AND GL.ORDOCNUM = PH.DOCNUMBR
--		WHERE	LEFT(GL.SourcDoc, 2) = 'PM'
--				AND GL.HSTYEAR = YEAR(GETDATE())
--				AND GL.REFRENCE <> PM.DistRef
--		) DATA
--WHERE	GL30000.ORGNTSRC = DATA.TRXSORCE 
--		AND GL30000.OrigSeqNum = DATA.DSTSQNUM 
--		AND GL30000.ACTINDX = DATA.DSTINDX
--		AND GL30000.ORDOCNUM = DATA.DOCNUMBR
--		AND GL30000.REFRENCE = DATA.DistRef
