DECLARE	@NTVCHNUM	Varchar(30)

SELECT	@NTVCHNUM = GPCustom.dbo.PADL(MAX(VCHNUMWK) + 1, LEN(RTRIM(VCHNUMWK)), '0')
FROM	(
		SELECT	MAX(VCHNUMWK) AS VCHNUMWK
		FROM	PM10000
		WHERE	LEFT(VCHNUMWK, 4) = '0000'
		UNION
		SELECT	MAX(VCHRNMBR) AS VCHNUMWK
		FROM	PM20000
		WHERE	LEFT(VCHRNMBR, 4) = '0000'
		) RECS
GROUP BY VCHNUMWK

PRINT @NTVCHNUM

UPDATE	PM40100 
SET		NTVCHNUM = @NTVCHNUM 

SELECT	NTVCHNUM
FROM	PM40100

/*
SELECT	*
FROM	PM20000
*/