DECLARE	@DocNumber	Varchar(30) = 'ACH072215CMA',
		@DocStatus	Int

SET NOCOUNT OFF

SELECT	@DocStatus = DCSTATUS
FROM	RM00401
WHERE	DOCNUMBR = @DocNumber

IF @DocStatus = 2 AND EXISTS(SELECT DOCNUMBR FROM RM30101 WHERE DOCNUMBR = @DocNumber)
BEGIN
	PRINT 'Deleted from history'

	DELETE	RM30101
	WHERE	DOCNUMBR = @DocNumber
END

IF @DocStatus = 3 AND EXISTS(SELECT DOCNUMBR FROM RM20101 WHERE DOCNUMBR = @DocNumber)
BEGIN
	PRINT 'Deleted from open'

	DELETE	RM20101
	WHERE	DOCNUMBR = @DocNumber
END

-- REMOVE FROM OPEN
DELETE	RM20101
WHERE	DOCNUMBR IN (
					SELECT	RM2.DOCNUMBR 
					FROM	RM20101 RM2
							INNER JOIN RM00401 RM4 ON RM2.CUSTNMBR = RM4.CUSTNMBR AND RM2.DOCNUMBR = RM4.DOCNUMBR AND RM4.DCSTATUS = 3
					WHERE	RM2.DOCNUMBR IN (SELECT DOCNUMBR FROM RM30101)
					)

-- REMOVE FROM HISTORICAL
DELETE	RM30101
WHERE	DOCNUMBR IN (
					SELECT	RM3.DOCNUMBR 
					FROM	RM30101 RM3
							INNER JOIN RM00401 RM4 ON RM3.CUSTNMBR = RM4.CUSTNMBR AND RM3.DOCNUMBR = RM4.DOCNUMBR AND RM4.DCSTATUS = 2
					WHERE	RM3.DOCNUMBR IN (SELECT DOCNUMBR FROM RM20101)
					)