SELECT	Company, ParameterCode, VarC
FROM	PRISQL01P.GPCustom.dbo.Parameters
WHERE	ParameterCode IN (
		'FSIVENDORCREACCT',
		'FSIVENDORPREPAYDEBACCT',
		'PIERPASS_ACCT_DEBIT',
		'PIERPASS_ACCT_CREDIT',
		'FSIACCRUDDEBIT',
		'FSIACCRUDCREDIT',
		'DEMURRAGE_AP_CREDIT',
		'DEMURRAGE_AP_DEBIT',
		'DEMURRAGE_AR_CREDIT',
		'DEMURRAGE_AR_DEBIT',
		'FSIVENDORDEBACCT',
		'FSISALESCREACCT',
		'FSISALESDEBACCT',
		'FSISALESDEBACCT',
		'FSISALESCREACCT',
		'FSISUMMARYACCOUNT',
		'DEMURRAGE_ADMINFEEACT',
		'ICB_DEBIT_ACCT',
		'ICB_CREDIT_ACCT',
		'ICB_DEBACCT')
		AND Company = 'OIS'