USE GPCustom
GO

/*
EXECUTE USP_GL_DetailTrailBalance_New 'GLSO', '0-00-2105', '0-00-2105', '01/01/2022', '12/09/2022', 0
EXECUTE USP_GL_DetailTrailBalance_New 'AIS', '0-01-1011', '0-01-1011', '08/01/2021', '08/09/2022', 0
EXECUTE USP_GL_DetailTrailBalance_New 'AIS', '0-01-1011', '0-01-1011', '08/01/2021', '08/09/2022', 1
*/
CREATE PROCEDURE USP_GL_DetailTrailBalance_New
		@Company		Varchar(5),
		@AccountIni		Varchar(15),
		@AccountEnd		Varchar(15),
		@DateIni		Date,
		@DateEnd		Date,
		@Summary		Bit = 0
AS
SET NOCOUNT ON

DECLARE	@Query			Varchar(MAX)

DECLARE @tblGLData		Table (
		COMPANY			Varchar(10),
		OPENYEAR		Int,
		PERIODID		Int,
		JRNENTRY		Int,
		GPSOURCE		Char(2),
		GLACCOUNT		Varchar(25),
		TRXDATE			Date,
		ACCTDESCRIPTION	Varchar(100),
		REFERENCE		Varchar(100),
		PRONUMBER		Varchar(50),
		CREDIT			Numeric(10,2),
		DEBIT			Numeric(10,2),
		ORG_MSTR_NUMBER	Varchar(30),
		ORG_MSTR_NAME	Varchar(100),
		ORG_DOC_NUMBER	Varchar(50),
		BATCHID			Varchar(30),
		ORG_TRX			Varchar(30))

SET @Query = N'SELECT ''' + @Company + ''',
		G2.OPENYEAR,
		G2.PERIODID,
		G2.JRNENTRY,
		CASE WHEN LEFT(G2.SOURCDOC, 2) = ''PM'' THEN ''AP''
			 WHEN LEFT(G2.SOURCDOC, 2) IN (''AP'',''CR'',''SJ'') THEN ''AR''
		ELSE ''GL'' END AS GPSOURCE,
		RTRIM(G5.ACTNUMST) AS GLACCOUNT,
		CAST(G2.TRXDATE AS Date) AS TRXDATE,
		RTRIM(G1.ACTDESCR) AS ACCTDESCRIPTION,
		RTRIM(G2.REFRENCE) AS REFERENCE,
		GPCustom.dbo.FindProNumber(G2.REFRENCE) AS PRONUMBER,
		CAST(G2.CRDTAMNT AS Numeric(10,2)) AS CREDIT,
		CAST(G2.DEBITAMT AS Numeric(10,2)) As DEBIT,
		RTRIM(G2.ORMSTRID) AS ORG_MSTR_NUMBER,
		RTRIM(G2.ORMSTRNM) AS ORG_MSTR_NAME,
		RTRIM(G2.ORDOCNUM) AS ORG_DOC_NUMBER,
		RTRIM(G2.ORGNTSRC) AS BATCHID,
		RTRIM(G2.ORCTRNUM) AS ORG_TRX
FROM	' + @Company + '.dbo.GL20000 G2
		INNER JOIN ' + @Company + '.dbo.GL00100 G1 ON G2.ACTINDX = G1.ACTINDX
		INNER JOIN ' + @Company + '.dbo.GL00105 G5 ON G2.ACTINDX = G5.ACTINDX
WHERE	G5.ACTNUMST BETWEEN ''' + @AccountIni + ''' AND ''' + @AccountEnd + '''
		AND G2.TRXDATE BETWEEN ''' + CAST(@DateIni AS Varchar) + ''' AND ''' + CAST(@DateEnd AS Varchar) + '''
		AND G2.VOIDED = 0'

SET @Query = @Query + N'UNION 
SELECT ''' + @Company + ''',
		G2.HSTYEAR,
		G2.PERIODID,
		G2.JRNENTRY,
		CASE WHEN LEFT(G2.SOURCDOC, 2) = ''PM'' THEN ''AP''
			 WHEN LEFT(G2.SOURCDOC, 2) IN (''AP'',''CR'',''SJ'') THEN ''AR''
		ELSE ''GL'' END AS GPSOURCE,
		RTRIM(G5.ACTNUMST) AS GLACCOUNT,
		CAST(G2.TRXDATE AS Date) AS TRXDATE,
		RTRIM(G1.ACTDESCR) AS ACCTDESCRIPTION,
		RTRIM(G2.REFRENCE) AS REFERENCE,
		GPCustom.dbo.FindProNumber(G2.REFRENCE) AS PRONUMBER,
		CAST(G2.CRDTAMNT AS Numeric(10,2)) AS CREDIT,
		CAST(G2.DEBITAMT AS Numeric(10,2)) As DEBIT,
		RTRIM(G2.ORMSTRID) AS ORG_MSTR_NUMBER,
		RTRIM(G2.ORMSTRNM) AS ORG_MSTR_NAME,
		RTRIM(G2.ORDOCNUM) AS ORG_DOC_NUMBER,
		RTRIM(G2.ORGNTSRC) AS BATCHID,
		RTRIM(G2.ORCTRNUM) AS ORG_TRX
FROM	' + @Company + '.dbo.GL30000 G2
		INNER JOIN ' + @Company + '.dbo.GL00100 G1 ON G2.ACTINDX = G1.ACTINDX
		INNER JOIN ' + @Company + '.dbo.GL00105 G5 ON G2.ACTINDX = G5.ACTINDX
WHERE	G5.ACTNUMST BETWEEN ''' + @AccountIni + ''' AND ''' + @AccountEnd + '''
		AND G2.TRXDATE BETWEEN ''' + CAST(@DateIni AS Varchar) + ''' AND ''' + CAST(@DateEnd AS Varchar) + '''
		AND G2.VOIDED = 0'

INSERT INTO @tblGLData
EXECUTE(@Query)

IF @Summary = 0
BEGIN
	SELECT	DAT.COMPANY,
			DAT.OPENYEAR,
			DAT.PERIODID,
			DAT.JRNENTRY,
			DAT.GPSOURCE,
			DAT.GLACCOUNT,
			DAT.TRXDATE,
			DAT.ACCTDESCRIPTION,
			DAT.REFERENCE,
			DAT.PRONUMBER,
			DAT.CREDIT,
			DAT.DEBIT,
			DAT.ORG_MSTR_NUMBER,
			DAT.ORG_MSTR_NAME,
			DAT.ORG_DOC_NUMBER,
			DAT.BATCHID,
			DAT.ORG_TRX,
			COALESCE(VCH.TrailerNumber, SAL.TrailerNumber, GLT.Container, Null) AS Container,
			COALESCE(REPLACE(VCH.ChassisNumber, 'Select if Neede', ''), SAL.ChassisNumber, '') AS Chassis
	FROM	@tblGLData DAT
			LEFT JOIN Purchasing_Vouchers VCH ON DAT.ORG_TRX = VCH.VoucherNumber AND VCH.CompanyId = @Company AND DAT.GPSOURCE = 'AP'
			LEFT JOIN SalesInvoices SAL ON DAT.ORG_DOC_NUMBER = SAL.InvoiceNumber AND SAL.CompanyId = @Company AND DAT.GPSOURCE = 'AR'
			LEFT JOIN GP_FinancialTransactions GLT ON DAT.JRNENTRY = GLT.JournalNumber AND GLT.Company = @Company AND DAT.GPSOURCE = 'GL'
	ORDER BY DAT.OPENYEAR,
			DAT.GLACCOUNT,
			DAT.PERIODID,
			DAT.JRNENTRY
END
ELSE
BEGIN
	SELECT	DAT.COMPANY,
			DAT.OPENYEAR,
			DAT.GLACCOUNT,
			DAT.ACCTDESCRIPTION,
			SUM(DAT.CREDIT) AS CREDIT,
			SUM(DAT.DEBIT) AS DEBIT
	FROM	@tblGLData DAT
	GROUP BY DAT.COMPANY,
			DAT.OPENYEAR,
			DAT.GLACCOUNT,
			DAT.ACCTDESCRIPTION
	ORDER BY DAT.OPENYEAR,
			DAT.GLACCOUNT
END

-- SELECT TOP 1000 * FROM AIS..GL30000 WHERE TRXDATE > '08/01/2021'