SELECT	ORGNTSRC AS BATCHID, 
		CAST(MIN(TRXDATE) AS Date) AS MinDate,
		CAST(MAX(TRXDATE) AS Date) AS MaxDate,
		COUNT(*) AS COUNT
FROM	GL20000
WHERE	PERIODID = 12
		AND ORGNTSRC LIKE '9FSI202012%'
GROUP BY ORGNTSRC
ORDER BY ORGNTSRC