SELECT	g.YEAR1 [Year],
		a.ACTNUMST Account,
		g.ACTDESCR [Description],
		c.ACCATDSC Category,
		SUM(CASE g.PERIODID WHEN  0
			THEN g.PERDBLNC ELSE 0 END) Beginning_Balance,
		SUM(CASE g.PERIODID WHEN  1
			THEN g.DEBITAMT-g.CRDTAMNT ELSE 0 END) January,
		SUM(CASE g.PERIODID WHEN  2
			THEN g.DEBITAMT-g.CRDTAMNT ELSE 0 END) February,
		SUM(CASE g.PERIODID WHEN  3
			THEN g.DEBITAMT-g.CRDTAMNT ELSE 0 END) March,
		SUM(CASE g.PERIODID WHEN  4
			THEN g.DEBITAMT-g.CRDTAMNT ELSE 0 END) April,
		SUM(CASE g.PERIODID WHEN  5
			THEN g.DEBITAMT-g.CRDTAMNT ELSE 0 END) May,
		SUM(CASE g.PERIODID WHEN  6
			THEN g.DEBITAMT-g.CRDTAMNT ELSE 0 END) June,
		SUM(CASE g.PERIODID WHEN  7
			THEN g.DEBITAMT-g.CRDTAMNT ELSE 0 END) July,
		SUM(CASE g.PERIODID WHEN  8
			THEN g.DEBITAMT-g.CRDTAMNT ELSE 0 END) August,
		SUM(CASE g.PERIODID WHEN  9
			THEN g.DEBITAMT-g.CRDTAMNT ELSE 0 END) September,
		SUM(CASE g.PERIODID WHEN  10
			THEN g.DEBITAMT-g.CRDTAMNT ELSE 0 END) October,
		SUM(CASE g.PERIODID WHEN  11
			THEN g.DEBITAMT-g.CRDTAMNT ELSE 0 END) November,
		SUM(CASE g.PERIODID WHEN  12
			THEN g.DEBITAMT-g.CRDTAMNT ELSE 0 END) December,
		SUM(g.PERDBLNC) Ending_Balance
 FROM	GL11110 G
		INNER JOIN GL00102 c ON g.ACCATNUM = c.ACCATNUM
		INNER JOIN GL00105 a ON g.ACTINDX = a.ACTINDX
 WHERE	g.ACCTTYPE = 1
		AND g.YEAR1 = (SELECT MIN(YEAR1) FROM GL11110)
 GROUP BY g.YEAR1, g.ACTDESCR, a.ACTNUMST, c.ACCATDSC
 HAVING SUM(g.PERDBLNC) <> 0