SELECT	TSUM.YEAR1 [Year],
		RTRIM(TCAT.ACCATDSC) Category,
		RTRIM(TACC.ACTNUMST) Account,
		RTRIM(TSUM.ACTDESCR) [Description],
		SUM(CASE TSUM.PERIODID WHEN 0 THEN TSUM.PERDBLNC ELSE 0 END) Beginning_Balance,
		SUM(CASE WHEN TSUM.PERIODID <= 1 THEN TSUM.DEBITAMT-TSUM.CRDTAMNT ELSE 0 END) Jan_Balance,
		SUM(CASE WHEN TSUM.PERIODID <= 2 THEN TSUM.DEBITAMT-TSUM.CRDTAMNT ELSE 0 END) Feb_Balance,
		SUM(CASE WHEN TSUM.PERIODID <= 3 THEN TSUM.DEBITAMT-TSUM.CRDTAMNT ELSE 0 END) Mar_Balance,
		SUM(CASE WHEN TSUM.PERIODID <= 4 THEN TSUM.DEBITAMT-TSUM.CRDTAMNT ELSE 0 END) Apr_Balance,
		SUM(CASE WHEN TSUM.PERIODID <= 5 THEN TSUM.DEBITAMT-TSUM.CRDTAMNT ELSE 0 END) May_Balance,
		SUM(CASE WHEN TSUM.PERIODID <= 6 THEN TSUM.DEBITAMT-TSUM.CRDTAMNT ELSE 0 END) Jun_Balance,
		SUM(CASE WHEN TSUM.PERIODID <= 7 THEN TSUM.DEBITAMT-TSUM.CRDTAMNT ELSE 0 END) Jul_Balance,
		SUM(CASE WHEN TSUM.PERIODID <= 8 THEN TSUM.DEBITAMT-TSUM.CRDTAMNT ELSE 0 END) Aug_Balance,
		SUM(CASE WHEN TSUM.PERIODID <= 9 THEN TSUM.DEBITAMT-TSUM.CRDTAMNT ELSE 0 END) Sep_Balance,
		SUM(CASE WHEN TSUM.PERIODID <= 10 THEN TSUM.DEBITAMT-TSUM.CRDTAMNT ELSE 0 END) Oct_Balance,
		SUM(CASE WHEN TSUM.PERIODID <= 11 THEN TSUM.DEBITAMT-TSUM.CRDTAMNT ELSE 0 END) Nov_Balance,
		SUM(CASE WHEN TSUM.PERIODID <= 12 THEN TSUM.DEBITAMT-TSUM.CRDTAMNT ELSE 0 END) Dec_Balance
FROM	GL11110 TSUM
		INNER JOIN GL00102 TCAT ON TSUM.ACCATNUM = TCAT.ACCATNUM
		INNER JOIN GL00105 TACC ON TSUM.ACTINDX = TACC.ACTINDX
WHERE	TSUM.ACCTTYPE = 1
		AND TSUM.YEAR1 = (SELECT MIN(YEAR1) FROM GL11110)
		--AND TCAT.ACCATDSC IN ('Accounts Payable','Accounts Receivable')
		--AND TSUM.ACTINDX IN (SELECT ACTINDX FROM GL00105 WHERE ACTNUMST = '0-00-1050')
GROUP BY TSUM.YEAR1, TSUM.ACTDESCR, TACC.ACTNUMST, TCAT.ACCATDSC
ORDER BY TACC.ACTNUMST