SELECT	GL2.JRNENTRY,
		GPCustom.dbo.FindProNumber(GL2.REFRENCE) AS ProNumber,
		RTRIM(GL2.REFRENCE) AS REFRENCE,
		CAST(GL2.TRXDATE AS Date) AS TRXDATE,
		CAST(GL2.ORPSTDDT AS Date) AS POSTINGDATE,
		RTRIM(GL5.ACTNUMST) AS ACCOUNT,
		CAST(GL2.DEBITAMT AS Numeric(10,2)) AS DEBITAMT,
		cast(GL2.CRDTAMNT AS Numeric(10,2)) AS CRDTAMNT,
		CASE WHEN GL2.SOURCDOC = 'PMTRX' THEN 'AP' ELSE 'GL' END AS SOURCE,
		RTRIM(GL2.ORGNTSRC) AS BATCHID,
		GL2.PERIODID AS MONTH
		--GL2.ORMSTRID AS VENDORID,
		--GL2.ORDOCNUM AS DOCUMENTID
--INTO	#tmpData
FROM	GL20000 GL2
		INNER JOIN GL00105 GL5 ON GL2.ACTINDX = GL5.ACTINDX
WHERE	GL2.ORGNTSRC = '1205_FIX'
ORDER BY 2, 6

/*
SELECT	GL2.JRNENTRY,
		GPCustom.dbo.FindProNumber(GL2.REFRENCE) AS ProNumber,
		RTRIM(GL2.REFRENCE) AS REFRENCE,
		CAST(GL2.TRXDATE AS Date) AS TRXDATE,
		CAST(GL2.ORPSTDDT AS Date) AS POSTINGDATE,
		RTRIM(GL5.ACTNUMST) AS ACCOUNT,
		CAST(GL2.DEBITAMT AS Numeric(10,2)) AS DEBITAMT,
		cast(GL2.CRDTAMNT AS Numeric(10,2)) AS CRDTAMNT,
		CASE WHEN GL2.SOURCDOC = 'PMTRX' THEN 'AP' ELSE 'GL' END AS SOURCE,
		RTRIM(GL2.ORGNTSRC) AS BATCHID,
		GL2.PERIODID AS MONTH
		--GL2.ORMSTRID AS VENDORID,
		--GL2.ORDOCNUM AS DOCUMENTID
INTO	#tmpData
FROM	GL20000 GL2
		INNER JOIN GL00105 GL5 ON GL2.ACTINDX = GL5.ACTINDX
WHERE	GL2.SOURCDOC <> 'PMTRX'
		AND GL2.PERIODID = 12
		AND GL2.ORGNTSRC LIKE '9FSI%'
		AND (((GL5.ACTNUMST = '0-00-5010' AND GL2.DEBITAMT > 0)
		OR (GL5.ACTNUMST = '0-99-1866' AND GL2.CRDTAMNT > 0))
		OR ((GL5.ACTNUMST = '0-00-5010' AND GL2.DEBITAMT > 0)
		OR (GL5.ACTNUMST = '0-00-1866' AND GL2.CRDTAMNT > 0)))
		--AND GL2.REFRENCE LIKE '%96-133878%'
		--AND GL2.JRNENTRY IN (627262,627263,627264)
--ORDER BY 2, 1, 5

SELECT	DISTINCT ProNumber, RTRIM(JRNENTRY) + ','
FROM	(
SELECT	ProNumber,
		REFRENCE,
		ACCOUNT,
		COUNT(*) AS Counter,
		MAX(JRNENTRY) AS JRNENTRY
FROM	#tmpData
--WHERE	ProNumber = '95-178547'
GROUP BY ProNumber, REFRENCE, ACCOUNT
HAVING COUNT(*) > 1
		) DATA

SELECT	*
FROM	#tmpData
WHERE	ProNumber = '95-178547'
ORDER BY 3,2,6

DROP TABLE #tmpData
*/