SELECT	GL1.BACHNUMB,
		GL1.JRNENTRY,
		GL1.DSCRIPTN,
		RTRIM(GL5.ACTNUMST) AS ACTNUMST,
		GL1.DEBITAMT,
		GL1.CRDTAMNT
FROM	GL10001 GL1
		INNER JOIN GL00105 GL5 ON GL1.ACTINDX = GL5.ACTINDX
WHERE	GL1.DSCRIPTN LIKE '%DEP%'
ORDER BY GL1.JRNENTRY