DECLARE	@BatchId	Varchar(15) = LEFT('9FSI20230125_1451', 15),
		@Journal	Int = NULL,
		@GLAcct		Varchar(15) = NULL,
		@ProNumber	Varchar(15) = NULL,
		@ByAccount	Bit = 0

IF @ByAccount = 0
BEGIN
	-- BY GL TRANSACTION
	DECLARE @tblGLData	Table (
	BACHNUMB			Varchar(20),
	JOURNAL				Bigint,
	ProNumber			Varchar(30),
	REFERENCE			Varchar(50),
	[DATE]				Date,
	[MONTH]				Int,
	ACCOUNT				Varchar(20),
	ACCT_Description	Varchar(50),
	DEBIT				Numeric(10,2),
	CREDIT				Numeric(10,2),
	DatSource			Varchar(15),
	DocumentNumber		Varchar(50),
	User_Defined_Text01	Varchar(300),
	[Sequence]			Bigint,
	AccountId			Int)

	INSERT INTO @tblGLData
	SELECT	*
	FROM	(
			SELECT	*
			FROM	(
					SELECT	GL20.BACHNUMB,
							GL20.JRNENTRY AS JOURNAL,
							GPCustom.dbo.FindProNumber(GL20.REFRENCE) AS ProNumber,
							RTRIM(GL20.REFRENCE) AS REFERENCE,
							CAST(GL20.TRXDATE AS Date) AS [DATE],
							GL20.PERIODID AS [MONTH],
							RTRIM(GL05.ACTNUMST) AS ACCOUNT,
							RTRIM(GL1.ACTDESCR) AS ACCT_Description,
							CAST(GL01.DEBITAMT AS Numeric(10,2)) AS DEBIT,
							CAST(GL01.CRDTAMNT AS Numeric(10,2)) AS CREDIT,
							'Work' AS DatSource,
							RTRIM(GL01.ORDOCNUM) AS DocumentNumber,
							GL20.User_Defined_Text01,
							GL01.SQNCLINE,
							GL01.ACTINDX 
					FROM	GL10000 GL20
							LEFT JOIN GL10001 GL01 ON GL20.BACHNUMB = GL01.BACHNUMB AND GL20.JRNENTRY = GL01.JRNENTRY
							LEFT JOIN GL00105 GL05 ON GL01.ACTINDX = GL05.ACTINDX
							LEFT JOIN GL00100 GL1 on GL1.ACTINDX = GL05.ACTINDX
					WHERE	(@BatchId IS Null OR (@BatchId IS NOT Null AND GL20.BACHNUMB = @BatchId))
							AND (@Journal IS Null OR (@Journal IS NOT Null AND GL20.JRNENTRY = @Journal))
							AND (@GLAcct IS Null OR (@GLAcct IS NOT Null AND GL05.ACTNUMST = @GLAcct))
							--GL20.TRXDATE BETWEEN '01/01/2020' AND '05/31/2022'
					) DATA
			UNION
			SELECT	*
			FROM	(
					SELECT	GL20.ORGNTSRC AS BACHNUMB,
							GL20.JRNENTRY AS JOURNAL,
							GPCustom.dbo.FindProNumber(GL20.REFRENCE) AS ProNumber,
							RTRIM(GL20.REFRENCE) AS REFERENCE,
							CAST(GL20.TRXDATE AS Date) AS [DATE],
							GL20.PERIODID AS [MONTH],
							RTRIM(GL05.ACTNUMST) AS ACCOUNT,
							RTRIM(GL1.ACTDESCR) AS ACCT_Description,
							CAST(GL20.DEBITAMT AS Numeric(10,2)) AS DEBIT,
							CAST(GL20.CRDTAMNT AS Numeric(10,2)) AS CREDIT,
							'Open' AS DatSource,
							RTRIM(GL20.ORDOCNUM) AS DocumentNumber,
							GL20.User_Defined_Text01,
							GL20.SEQNUMBR,
							GL1.ACTINDX 
					FROM	GL20000 GL20
							LEFT JOIN GL00105 GL05 ON GL20.ACTINDX = GL05.ACTINDX
							LEFT JOIN GL00100 GL1 on GL1.ACTINDX = GL05.ACTINDX
					WHERE	(@BatchId IS Null OR (@BatchId IS NOT Null AND GL20.ORGNTSRC = @BatchId))
							AND (@Journal IS Null OR (@Journal IS NOT Null AND GL20.JRNENTRY = @Journal))
							AND (@GLAcct IS Null OR (@GLAcct IS NOT Null AND GL05.ACTNUMST = @GLAcct))
							--GL20.TRXDATE BETWEEN '01/01/2020' AND '07/30/2022'
					) DATA
			--UNION
			--SELECT	*
			--FROM	(
			--		SELECT	GL20.ORGNTSRC AS BACHNUMB,
			--				GL20.JRNENTRY AS JOURNAL,
			--				'' AS PRONUMBER, --GPCustom.dbo.FindProNumber(GL20.REFRENCE) AS ProNumber,
			--				RTRIM(GL20.REFRENCE) AS REFERENCE,
			--				CAST(GL20.TRXDATE AS Date) AS [DATE],
			--				GL20.PERIODID AS [MONTH],
			--				RTRIM(GL05.ACTNUMST) AS ACCOUNT,
			--				RTRIM(GL1.ACTDESCR) AS ACCT_Description,
			--				CAST(GL20.DEBITAMT AS Numeric(10,2)) AS DEBIT,
			--				CAST(GL20.CRDTAMNT AS Numeric(10,2)) AS CREDIT,
			--				'History' AS DatSource,
			--				RTRIM(GL20.ORDOCNUM) AS DocumentNumber,
			--				GL20.User_Defined_Text01
			--		FROM	GL30000 GL20
			--				LEFT JOIN GL00105 GL05 ON GL20.ACTINDX = GL05.ACTINDX
			--				LEFT JOIN GL00100 GL1 on GL1.ACTINDX = GL05.ACTINDX
			--		WHERE	GL20.TRXDATE BETWEEN '01/01/2020' AND '05/31/2022'
			--				AND ((@BatchId IS NOT Null AND GL20.ORGNTSRC = @BatchId)
			--				OR (@Journal IS NOT Null AND GL20.JRNENTRY = @Journal))
			--				OR (@GLAcct IS Null OR  GL05.ACTNUMST = @GLAcct)
			--		) DATA
			) GP_DATA

	SELECT	*
	FROM	@tblGLData
	ORDER BY ProNumber, JOURNAL, Sequence

END
ELSE
BEGIN
	-- BY GL ACCOUNT NUMBER
	SELECT	'GL' AS DataType, Account, Acct_Description, SUM(DEBIT) AS Debit, SUM(CREDIT) AS Credit, SUM(DEBIT + (CREDIT * -1)) AS Amount
	FROM	(
			SELECT	GL20.BACHNUMB,
					GL20.JRNENTRY AS JOURNAL,
					GPCustom.dbo.FindProNumber(GL20.REFRENCE) AS ProNumber,
					RTRIM(GL20.REFRENCE) AS REFERENCE,
					RTRIM(GL01.DSCRIPTN) AS [TRX_DESCRIPTION],
					CAST(GL20.TRXDATE AS Date) AS [DATE],
					GL20.PERIODID AS [MONTH],
					RTRIM(GL05.ACTNUMST) AS ACCOUNT,
					RTRIM(GL1.ACTDESCR) AS ACCT_Description,
					CAST(GL01.DEBITAMT AS Numeric(10,2)) AS DEBIT,
					CAST(GL01.CRDTAMNT AS Numeric(10,2)) AS CREDIT,
					GL20.User_Defined_Text01
			FROM	GL10000 GL20
					LEFT JOIN GL10001 GL01 ON GL20.BACHNUMB = GL01.BACHNUMB AND GL20.JRNENTRY = GL01.JRNENTRY
					LEFT JOIN GL00105 GL05 ON GL01.ACTINDX = GL05.ACTINDX
					LEFT JOIN GL00100 GL1 on GL1.ACTINDX = GL05.ACTINDX
			WHERE	(@BatchId IS Null OR (@BatchId IS NOT Null AND GL20.BACHNUMB = @BatchId))
					AND (@Journal IS Null OR (@Journal IS NOT Null AND GL20.JRNENTRY = @Journal))
					AND (@GLAcct IS Null OR (@GLAcct IS NOT Null AND GL05.ACTNUMST = @GLAcct))
					--AND GL20.TRXDATE BETWEEN '01/01/2020' AND '05/31/2022'
			) DATA1
	GROUP BY ACCOUNT, ACCT_Description
	UNION
	SELECT	'GL' AS DataType, Account, Acct_Description, SUM(DEBIT) AS Debit, SUM(CREDIT) AS Credit, SUM(DEBIT + (CREDIT * -1)) AS Amount
	FROM	(
			SELECT	GL20.ORGNTSRC AS BACHNUMB,
					GL20.JRNENTRY AS JOURNAL,
					GPCustom.dbo.FindProNumber(GL20.REFRENCE) AS ProNumber,
					RTRIM(GL20.REFRENCE) AS REFERENCE,
					RTRIM(GL20.DSCRIPTN) AS [TRX_DESCRIPTION],
					CAST(GL20.TRXDATE AS Date) AS [DATE],
					GL20.PERIODID AS [MONTH],
					RTRIM(GL05.ACTNUMST) AS ACCOUNT,
					RTRIM(GL1.ACTDESCR) AS ACCT_Description,
					CAST(GL20.DEBITAMT AS Numeric(10,2)) AS DEBIT,
					CAST(GL20.CRDTAMNT AS Numeric(10,2)) AS CREDIT,
					GL20.User_Defined_Text01
			FROM	GL20000 GL20
					LEFT JOIN GL00105 GL05 ON GL20.ACTINDX = GL05.ACTINDX
					LEFT JOIN GL00100 GL1 on GL1.ACTINDX = GL05.ACTINDX
			WHERE	(@BatchId IS Null OR (@BatchId IS NOT Null AND GL20.ORGNTSRC = @BatchId))
					AND (@Journal IS Null OR (@Journal IS NOT Null AND GL20.JRNENTRY = @Journal))
					AND (@GLAcct IS Null OR (@GLAcct IS NOT Null AND GL05.ACTNUMST = @GLAcct))
					--AND GL20.TRXDATE BETWEEN '01/01/2020' AND '05/31/2022'
			) DATA2
	GROUP BY ACCOUNT, ACCT_Description
	UNION 
	SELECT	'AP' AS DataType, GL5.ACTNUMST, RTRIM(GL1.ACTDESCR) AS ACCT_Description, SUM(DET.DEBITAMT) AS Debit, SUM(DET.CRDTAMNT) AS Credit, SUM(DET.CRDTAMNT - DET.DEBITAMT) AS Amount
	FROM	PM10000 HDR
			INNER JOIN PM10100 DET ON HDR.VENDORID = DET.VENDORID AND HDR.VCHRNMBR = DET.VCHRNMBR
			INNER JOIN GL00105 GL5 ON DET.DSTINDX = GL5.ACTINDX
			LEFT JOIN GL00100 GL1 on GL1.ACTINDX = GL5.ACTINDX
	WHERE	HDR.BACHNUMB = @BatchId
	GROUP BY GL5.ACTNUMST,GL1.ACTDESCR
	UNION 
	SELECT	'AP' AS DataType, GL5.ACTNUMST, RTRIM(GL1.ACTDESCR) AS ACCT_Description, SUM(DET.DEBITAMT) AS Debit, SUM(DET.CRDTAMNT) AS Credit, SUM(DET.CRDTAMNT - DET.DEBITAMT) AS Amount
	FROM	PM20000 HDR
			INNER JOIN PM10100 DET ON HDR.VENDORID = DET.VENDORID AND HDR.VCHRNMBR = DET.VCHRNMBR
			INNER JOIN GL00105 GL5 ON DET.DSTINDX = GL5.ACTINDX
			LEFT JOIN GL00100 GL1 on GL1.ACTINDX = GL5.ACTINDX
	WHERE	HDR.BACHNUMB = @BatchId
	GROUP BY GL5.ACTNUMST,GL1.ACTDESCR
	ORDER BY 2, 1
END

-- 1546751 1541882
