DECLARE	@ProNumber	Varchar(15) = '96-100981',
		@Company1	Varchar(10),
		@Company2	Varchar(10)

SELECT	@Company1 = VarC
FROM	GPCustom.dbo.Parameters
WHERE	ParameterCode = 'PREPAY_COMPANY'
		AND Company = 'PTS'

SELECT	@Company2 = VarC
FROM	GPCustom.dbo.Parameters
WHERE	ParameterCode = 'PREPAY_COMPANY'
		AND Company = 'GLSO'

SELECT	GL1.BACHNUMB,
		GL1.REFRENCE,
		GL1.JRNENTRY,
		GL0.ACTINDX,
		GL5.ACTNUMST,
		GL0.DEBITAMT,
		GL0.CRDTAMNT,
		'PTS' AS Company,
		@Company1 AS AccCompany
FROM	GL10000 GL1
		INNER JOIN GL10001 GL0 ON GL1.JRNENTRY = GL0.JRNENTRY
		INNER JOIN GL00105 GL5 ON GL0.ACTINDX = GL5.ACTINDX
WHERE	REFRENCE LIKE '%' + @ProNumber + '%'

SELECT	GL1.BACHNUMB,
		GL1.REFRENCE,
		GL1.JRNENTRY,
		GL0.ACTINDX,
		GL5.ACTNUMST,
		GL0.DEBITAMT,
		GL0.CRDTAMNT,
		'IMCNA' AS Company,
		@Company2 AS AccCompany
FROM	GLSO.dbo.GL10000 GL1
		INNER JOIN GLSO.dbo.GL10001 GL0 ON GL1.JRNENTRY = GL0.JRNENTRY
		INNER JOIN GLSO.dbo.GL00105 GL5 ON GL0.ACTINDX = GL5.ACTINDX
WHERE	REFRENCE LIKE '%' + @ProNumber + '%'
