DECLARE @RunDate	Date = DATEADD(DD, -3, CAST(GETDATE() AS Date))

SELECT	* 
FROM	PM20000
WHERE	DEX_ROW_TS >= @RunDate
		OR MODIFDT >= @RunDate

SELECT	DET.*
FROM	PM10100 DET
		INNER JOIN PM20000 HDR ON DET.VCHRNMBR = HDR.VCHRNMBR AND DET.VENDORID = HDR.VENDORID
WHERE	HDR.DEX_ROW_TS >= @RunDate
		OR HDR.MODIFDT >= @RunDate

SELECT	* 
FROM	PM30200
WHERE	DEX_ROW_TS >= @RunDate
		OR MODIFDT >= @RunDate

SELECT	DET.*
FROM	PM30600 DET
		INNER JOIN PM30200 HDR ON DET.VCHRNMBR = HDR.VCHRNMBR AND DET.VENDORID = HDR.VENDORID
WHERE	HDR.DEX_ROW_TS >= @RunDate
		OR HDR.MODIFDT >= @RunDate

SELECT	*
FROM	RM20101
WHERE	DEX_ROW_TS >= @RunDate
		OR VOIDDATE >= @RunDate

SELECT	DET.*
FROM	RM10101 DET
		INNER JOIN RM20101 HDR ON DET.CUSTNMBR = HDR.CUSTNMBR AND DET.DOCNUMBR = HDR.DOCNUMBR
WHERE	HDR.DEX_ROW_TS >= @RunDate
		OR HDR.VOIDDATE >= @RunDate

SELECT	TOP 100 *
FROM	RM30101
WHERE	DEX_ROW_TS >= @RunDate
		OR VOIDDATE >= @RunDate

SELECT	DET.*
FROM	RM30301 DET
		INNER JOIN RM30101 HDR ON DET.CUSTNMBR = HDR.CUSTNMBR AND DET.DOCNUMBR = HDR.DOCNUMBR
WHERE	HDR.DEX_ROW_TS >= @RunDate
		OR HDR.VOIDDATE >= @RunDate