SELECT	HDR.VENDORID,
		VND.VENDNAME,
		HDR.DOCNUMBR,
		HDR.DOCDATE,
		HDR.DUEDATE,
		HDR.POSTEDDT,
		HDR.DOCAMNT AS Amount,
		HDR.CURTRXAM AS Balance,
		HDR.TRXDSCRN,
		DET.DistRef,
		DET.DSTINDX,
		ACT.ACTNUMST,
		DET.DEBITAMT AS Debit,
		DET.CRDTAMNT AS Credit,
		'OPEN' AS SourceData
FROM	PM20000 HDR
		INNER JOIN PM10100 DET ON HDR.VENDORID = DET.VENDORID AND HDR.VCHRNMBR = DET.VCHRNMBR
		INNER JOIN PM00200 VND ON HDR.VENDORID = VND.VENDORID
		INNER JOIN GL00105 ACT ON DET.DSTINDX = ACT.ACTINDX

		SELECT * FROM PM10100