SELECT	HDR.CUSTNMBR,
		CUS.CUSTNAME,
		HDR.DOCNUMBR,
		HDR.DOCDATE,
		HDR.DUEDATE,
		HDR.POSTDATE,
		HDR.ORTRXAMT AS AMOUNT,
		HDR.CURTRXAM AS BALANCE,
		HDR.TRXDSCRN,
		DET.DistRef,
		DET.DSTINDX AS AccountIndex,
		ACT.ACTNUMST,
		DET.DEBITAMT AS Debit,
		DET.CRDTAMNT AS Credit,
		'OPEN' AS DataSource
FROM	RM20101 HDR
		INNER JOIN RM10101 DET ON HDR.CUSTNMBR = DET.CUSTNMBR AND HDR.DOCNUMBR = DET.DOCNUMBR
		INNER JOIN RM00101 CUS ON HDR.CUSTNMBR = CUS.CUSTNMBR
		INNER JOIN GL00105 ACT ON DET.DSTINDX = ACT.ACTINDX

