-- ManagementReporterDM
--SELECT * FROM DYNAMICS..View_AllCompanies
-- DELETE DYNAMICS..ACTIVITY  WHERE LOGINDAT < '04/02/2014'

SELECT	ACT.UserId,
		USR.UserName,
		CASE WHEN USR.UserType = '1' THEN 'Full' ELSE 'Limited' END AS LicenseType,
		ACT.CmpnyNam, 
		CAST(ACT.LOGINDAT AS Date) AS LoginDate, 
		RIGHT(CONVERT(Varchar, ACT.LoginTim, 100), 7) AS LogTime 
FROM	DYNAMICS.dbo.ACTIVITY ACT
		INNER JOIN DYNAMICS.dbo.SY01400 USR ON ACT.UserId = USR.UserId
ORDER BY ACT.UserId, ACT.LOGINDAT, ACT.LoginTim

SELECT * FROM DYNAMICS..ACTIVITY ORDER BY UserId --LoginDat, LoginTim, UserId
SELECT * FROM DYNAMICS..SY00800
SELECT * FROM DYNAMICS..SY00801
SELECT * FROM TEMPDB..DEX_LOCK
SELECT * FROM TEMPDB..DEX_SESSION ORDER BY sqlsvr_spid

/*
DELETE DYNAMICS..ACTIVITY WHERE LoginDat < '05/14/2021'

SELECT * FROM TEMPDB..DEX_LOCK WHERE session_id NOT IN (SELECT SQLSESID FROM DYNAMICS..ACTIVITY)
DELETE TEMPDB..DEX_LOCK --WHERE session_id NOT IN (SELECT SQLSESID FROM DYNAMICS..ACTIVITY)
DELETE DYNAMICS..ACTIVITY WHERE UserId IN ('mmoss')
DELETE DYNAMICS..SY00800 WHERE UserId IN ('mmoss')
DELETE IMC.dbo.SY00500 WHERE BACHNUMB = ''
select * from DYNAMICS..ACTIVITY where cmpnynam = 'Intermodal Cartage Co.'
--SELECT * FROM Dynamics.dbo.SY00800
SELECT * FROM TEMPDB..DEX_SESSION --AND Cmpnynam = 'Intermodal Cartage Company'

DELETE DYNAMICS..SYUPDATE -- FIX: your login has been removed from the users activity file
*/