SELECT	AP.VENDORID, AP.PYMNTPRI, CAST(DATEADD(dd, ISNULL(EFTPMPrenoteGracePeriod,1), SY.EFTPrenoteDate) AS Date) AS PreNoteDatePluseGD
FROM	GLSO.dbo.PM00200 AP
		INNER JOIN GLSO.dbo.CM00101 CH ON AP.CHEKBKID = CH.CHEKBKID
		INNER JOIN GLSO.dbo.SY06000 SY ON AP.VENDORID = SY.VENDORID AND AP.VADCDTRO = SY.ADRSCODE AND SY.INACTIVE = 0 AND DATEADD(dd, ISNULL(EFTPMPrenoteGracePeriod,1), SY.EFTPrenoteDate) < GETDATE()
WHERE	AP.PYMNTPRI <> 'EFT'
		AND AP.VENDSTTS = 1

--SELECT * FROM SY06000
--SELECT top 100 * FROM PM00200