DECLARE @DateIni	Date,
		@DateEnd	Date

SELECT	@DateIni = StartDate
FROM	DYNAMICS.dbo.View_FiscalPeriod
WHERE	Year1 = 2016
		AND PeriodId = 1

SELECT	@DateEnd = EndDate
FROM	DYNAMICS.dbo.View_FiscalPeriod
WHERE	Year1 = 2016
		AND PeriodId = 12

SELECT	VENDORID,
		CAST(DOCDATE AS Date) AS DOCDATE,
		DOCNUMBR,
		DOCAMNT * CASE WHEN DOCTYPE = 5 THEN -1 ELSE 1 END AS DOCAMNT,
		DOCTYPE,
		VCHRNMBR,
		POSTEDDT
FROM	PM20000
WHERE	VendorId = 'G0700'
		AND Voided = 0
		AND POSTEDDT BETWEEN @DateIni AND @DateEnd
UNION
SELECT	VENDORID,
		CAST(DOCDATE AS Date) AS DOCDATE,
		DOCNUMBR,
		DOCAMNT * CASE WHEN DOCTYPE = 5 THEN -1 ELSE 1 END AS DOCAMNT,
		DOCTYPE,
		VCHRNMBR,
		POSTEDDT
FROM	PM30200
WHERE	VendorId = 'G0700'
		AND Voided = 0
		AND POSTEDDT BETWEEN @DateIni AND @DateEnd
ORDER BY DOCDATE

