DECLARE	@EFT_Code	Varchar(10) = (SELECT VarC FROM GPCustom.dbo.Parameters WHERE ParameterCode = 'PAYCARDCODE')

SELECT	DB_NAME() AS Company
		,VND.VENDORID
		,VND.VENDNAME
		,VND.VNDCHKNM
		,VND.ADDRESS1
		,VND.ADDRESS2
		,VND.ADDRESS3
		,VND.CITY
		,VND.STATE
		,VND.ZIPCODE
		,VND.PHNUMBR1
		,VND.PHNUMBR2
		,CASE WHEN EFT.BANKNAME LIKE '%EFS%' THEN 'EFS'
			  WHEN EFT.EFTBankAcct IS Null THEN 'CHECK' 
			  ELSE 'DIRECT DEPOSIT' END AS PayType
		,ISNULL(EFT.BankName, '') AS BankName
		,ISNULL(EFT.EFTBankAcct, '') AS BankAccount
		,ISNULL(EFT.EFTTransitRoutingNo, '') AS RoutingNumber
		,CASE WHEN VND.VENDSTTS = 1 THEN 1 ELSE 0 END AS ACTIVE
FROM	PM00200 VND
		LEFT JOIN SY06000 EFT ON VND.VENDORID = EFT.VENDORID AND EFT.INACTIVE = 0
WHERE	VND.VNDCLSID = 'DRV'

-- SELECT * FROM SY06000 where vendname  like 'MIGUEL %'