SELECT	AR.CUSTNMBR AS CustomerId,
		AR.DOCNUMBR AS Invoice,
		AR.DOCDATE AS InvDate, 
		AR.ORTRXAMT AS InvAmount,
		AR.TRXDSCRN AS Description,
		AR.BACHNUMB AS BatchId,
		AR.GLPOSTDT AS PostingDate,
		COALESCE((SELECT SUM(DOCAMNT) FROM PM20000 AP WHERE AP.BACHNUMB LIKE 'IA%' AND (AP.DOCNUMBR = AR.DOCNUMBR OR AP.DOCNUMBR LIKE ('%' + RTRIM(AR.TRXDSCRN) + '%'))), (SELECT SUM(DOCAMNT) FROM PM30200 AP WHERE AP.BACHNUMB LIKE 'IA%' AND (AP.DOCNUMBR = AR.DOCNUMBR OR AP.DOCNUMBR LIKE ('%' + RTRIM(AR.TRXDSCRN) + '%'))), 0) AS Cost
FROM	RM20101 AR
WHERE	AR.BACHNUMB LIKE 'IA%'
		AND AR.VOIDSTTS = 0
		AND AR.DOCDATE BETWEEN '02/01/2018' AND '02/28/2018'
ORDER BY 
		AR.CUSTNMBR,
		AR.DOCDATE,
		AR.DOCNUMBR

--SELECT * FROM PM20000 WHERE BACHNUMB LIKE 'IA%'