--CREATE PROCEDURE SP_HistoricalAP 

DECLARE	@CutoffDate Datetime

SET @CutoffDate = '03/01/2022'

SELECT	* 
FROM	(
		SELECT	TRX.VCHRNMBR,
				RTRIM(TRX.VENDORID) AS VENDORID,
				TRX.DOCTYPE,
				CAST(TRX.DOCDATE AS Date) AS DOCDATE, 
				CAST(TRX.POSTEDDT AS Date) AS POSTEDDT, 
				RTRIM(TRX.DOCNUMBR) AS DOCNUMBR,
				ABS(TRX.DOCAMNT) AS DOCAMNT,
				CASE WHEN TRX.DOCTYPE < 5  THEN ABS(TRX.DOCAMNT) - ABS(ISNULL(APT.APPLDAMT, 0)) 
						WHEN TRX.DOCTYPE > 4  THEN ABS(TRX.DOCAMNT) - ABS(ISNULL(APF.APPLDAMT, 0))
					END AS CURRAMT,
				CAST(TRX.DUEDATE AS Date) AS DUEDATE, 
				TRX.PYMTRMID, 
				TRX.VOIDED,
				ISNULL(APT.APPLDAMT,0) AS APPLDAMT,
				DATASOURCE,
				DATEDIFF(dd, TRX.DUEDATE, @CutoffDate) AS DaysDue
		FROM	(
				SELECT	VCHRNMBR,
						VENDORID,
						DOCTYPE,
						DOCDATE, 
						POSTEDDT, 
						DOCNUMBR,
						DOCAMNT,
						DEX_ROW_ID,
						DISCAMNT, 
						DUEDATE, 
						PYMTRMID, 
						VOIDED,
						'HISTORY' AS DATASOURCE
				FROM	PM30200
				WHERE	DOCDATE <= @CutoffDate AND VOIDED = 0
				UNION
				SELECT	VCHRNMBR,
						VENDORID,
						DOCTYPE,
						DOCDATE, 
						POSTEDDT, 
						DOCNUMBR,
						DOCAMNT,
						DEX_ROW_ID,
						DISCAMNT, 
						DUEDATE, 
						PYMTRMID, 
						VOIDED,
						'OPEN' AS DATASOURCE
				FROM	PM20000
				WHERE	POSTEDDT <= @CutoffDate AND VOIDED = 0 
				) TRX
				LEFT JOIN (
							SELECT	VENDORID,
									APTODCNM,
									SUM(APPLDAMT) AS APPLDAMT, 
									MAX(GLPOSTDT) AS ApplyToGLPostDate, 
									MAX(DEX_ROW_ID) AS DEX_ROW_ID 
							FROM	PM30300 
							WHERE	GLPOSTDT <= @CutoffDate
							GROUP BY VENDORID, APTODCNM
							UNION
							SELECT	VENDORID,
									APTODCNM, 
									SUM(APPLDAMT) AS APPLDAMT, 
									MAX(ApplyToGLPostDate) AS ApplyToGLPostDate, 
									MAX(DEX_ROW_ID) AS DEX_ROW_ID 
							FROM	PM20100 
							WHERE	ApplyToGLPostDate <= @CutoffDate
							GROUP BY VENDORID, APTODCNM
							) APT ON TRX.VENDORID = APT.VENDORID AND TRX.DOCNUMBR = APT.APTODCNM 
				LEFT JOIN (
							SELECT	VENDORID,
									APFRDCNM,
									SUM(APPLDAMT) AS APPLDAMT, 
									MAX(GLPOSTDT) AS ApplyToGLPostDate, 
									MAX(DEX_ROW_ID) AS DEX_ROW_ID 
							FROM	PM30300 
							WHERE	GLPOSTDT <= @CutoffDate
							GROUP BY VENDORID, APFRDCNM
							UNION
							SELECT	VENDORID,
									APFRDCNM, 
									SUM(APPLDAMT) AS APPLDAMT, 
									MAX(ApplyToGLPostDate) AS ApplyToGLPostDate, 
									MAX(DEX_ROW_ID) AS DEX_ROW_ID 
							FROM	PM20100 
							WHERE	ApplyToGLPostDate <= @CutoffDate
							GROUP BY VENDORID, APFRDCNM
							) APF ON TRX.VENDORID = APF.VENDORID AND TRX.DOCNUMBR = APF.APFRDCNM 
	) AP
	WHERE	CURRAMT <> 0
			AND DOCTYPE < 6
ORDER BY DOCDATE, DOCNUMBR
		