/*
********************************************
**** INSERT GL ACCOUNT INTO GREAT PLAINS ***
********************************************
*/

DECLARE	@ActIndx	Int
SET		@ActIndx	= (SELECT MAX(ActIndx) + 1 FROM GL00100)

INSERT INTO GL00100 (ActIndx, ACTNUMBR_1, ACTNUMBR_2, ACTNUMBR_3, ACTDESCR, ACTALIAS, PSTNGTYP, UserDef1, UsrDefs1)
SELECT	@ActIndx + ROW_NUMBER() OVER (ORDER BY ACCT.AccountNumber) AS ActIndx
		,LEFT(ACCT.AccountNumber, 2) AS ACTNUMBR_1
		,SUBSTRING(ACCT.AccountNumber, 3, 2) AS  ACTNUMBR_2
		,SUBSTRING(ACCT.AccountNumber, 5, 4) AS  ACTNUMBR_3
		,LEFT(ACCT.AcctDescription, 51) AS ACTDESCR
		,LEFT(ACCT.AcctDescription, 21) AS ACTALIAS
		,CASE WHEN ACCT.PostingType = 'Balance Sheet' THEN 0 ELSE 1 END AS PSTNGTYP
		,LEFT(ISNULL(ACCT.AccountCategory, ''), 21) AS UserDef1
		,LEFT(ISNULL(ACCT.UserDef1, ''), 31) AS UsrDefs1
FROM	GPCustom.dbo.FI_Accounts ACCT
		LEFT JOIN GL00100 GLAC ON LEFT(ACCT.AccountNumber, 2) = GLAC.ACTNUMBR_1 AND SUBSTRING(ACCT.AccountNumber, 3, 2) = GLAC.ACTNUMBR_2 AND SUBSTRING(ACCT.AccountNumber, 5, 4) = GLAC.ACTNUMBR_3
WHERE	GLAC.ACTNUMBR_1 IS Null
ORDER BY 1, 2, 3

UPDATE	GL00100
SET		GL00100.ACCATNUM = DATA.ACCATNUM,
		GL00100.ACTIVE = 1,
		GL00100.ACCTTYPE = 1,
		GL00100.ACCTENTR = 1,
		GL00100.PostSlsIn = 1,
		GL00100.PostIvIn = 1,
		GL00100.PostPurchIn = 1,
		GL00100.PostPRIn = 1
FROM	(
		SELECT	GL2.ACTINDX
				,LEFT(AccountNumber, 2) AS ACTNUMBR_1
				,SUBSTRING(AccountNumber, 3, 2) AS  ACTNUMBR_2
				,SUBSTRING(AccountNumber, 5, 4) AS  ACTNUMBR_3
				,GL2.ACCATNUM
		FROM	GPCustom.dbo.FI_Accounts FI
				LEFT JOIN GL00102 GL1 ON FI.AccountCategory = GL1.ACCATDSC
				LEFT JOIN GL00100 GL2 ON LEFT(FI.AccountNumber, 2) = GL2.ACTNUMBR_1 AND SUBSTRING(AccountNumber, 3, 2) = GL2.ACTNUMBR_2 AND SUBSTRING(AccountNumber, 5, 4) = GL2.ACTNUMBR_3
		) DATA
WHERE	GL00100.ACTINDX = DATA.ACTINDX
