USE [IMCCS]

BEGIN TRANSACTION

TRUNCATE TABLE [IMCCS].[dbo].ASILOC90
TRUNCATE TABLE [IMCCS].[dbo].CM00100 
TRUNCATE TABLE [IMCCS].[dbo].CM40100 
TRUNCATE TABLE [IMCCS].[dbo].CM40101 
TRUNCATE TABLE [IMCCS].[dbo].GL00102 
TRUNCATE TABLE [IMCCS].[dbo].GL00105 
TRUNCATE TABLE [IMCCS].[dbo].GL40000 
TRUNCATE TABLE [IMCCS].[dbo].GL40200 
TRUNCATE TABLE [IMCCS].[dbo].IVC40100
TRUNCATE TABLE [IMCCS].[dbo].IVC40101
TRUNCATE TABLE [IMCCS].[dbo].MC40000 
TRUNCATE TABLE [IMCCS].[dbo].MC40100 
TRUNCATE TABLE [IMCCS].[dbo].PM00100 
TRUNCATE TABLE [IMCCS].[dbo].PM40100 
TRUNCATE TABLE [IMCCS].[dbo].PM40101 
TRUNCATE TABLE [IMCCS].[dbo].PM40102 
TRUNCATE TABLE [IMCCS].[dbo].RM00201 
TRUNCATE TABLE [IMCCS].[dbo].RM00301 
TRUNCATE TABLE [IMCCS].[dbo].RM00303 
TRUNCATE TABLE [IMCCS].[dbo].RM40101 
TRUNCATE TABLE [IMCCS].[dbo].RM40201 
TRUNCATE TABLE [IMCCS].[dbo].RM40401 
TRUNCATE TABLE [IMCCS].[dbo].SOP40100
TRUNCATE TABLE [IMCCS].[dbo].SOP40200
TRUNCATE TABLE [IMCCS].[dbo].SY00300 
TRUNCATE TABLE [IMCCS].[dbo].SY01100 
TRUNCATE TABLE [IMCCS].[dbo].SY02200 
TRUNCATE TABLE [IMCCS].[dbo].SY02300 
TRUNCATE TABLE [IMCCS].[dbo].SY03000 
TRUNCATE TABLE [IMCCS].[dbo].SY03300 
TRUNCATE TABLE [IMCCS].[dbo].SY04100 
TRUNCATE TABLE [IMCCS].[dbo].SY40100 
TRUNCATE TABLE [IMCCS].[dbo].SY40101 

INSERT INTO [IMCCS].[dbo].[ASILOC90]
		([SETUPKEY]
		,[ASI_Show_Inactive]
		,[ASI_QL_Key_Label_1]
		,[ASI_QL_Key_Label_2]
		,[ASI_QL_Key_Label_3]
		,[ASI_QL_Key_Label_4]
		,[ASI_QL_Key_Field_ID_1]
		,[ASI_QL_Key_Field_ID_2]
		,[ASI_QL_Key_Field_ID_3]
		,[ASI_QL_Key_Field_ID_4])
SELECT	[SETUPKEY]
		,[ASI_Show_Inactive]
		,[ASI_QL_Key_Label_1]
		,[ASI_QL_Key_Label_2]
		,[ASI_QL_Key_Label_3]
		,[ASI_QL_Key_Label_4]
		,[ASI_QL_Key_Field_ID_1]
		,[ASI_QL_Key_Field_ID_2]
		,[ASI_QL_Key_Field_ID_3]
		,[ASI_QL_Key_Field_ID_4]
FROM	[AIS].[dbo].[ASILOC90]

INSERT INTO [IMCCS].[dbo].[CM00100]
		([CHEKBKID]
		,[DSCRIPTN]
		,[BANKID]
		,[CURNCYID]
		,[ACTINDX]
		,[BNKACTNM]
		,[NXTCHNUM]
		,[Next_Deposit_Number]
		,[INACTIVE]
		,[DYDEPCLR]
		,[XCDMCHPW]
		,[MXCHDLR]
		,[DUPCHNUM]
		,[OVCHNUM1]
		,[LOCATNID]
		,[NOTEINDX]
		,[CMUSRDF1]
		,[CMUSRDF2]
		,[Last_Reconciled_Date]
		,[Last_Reconciled_Balance]
		,[CURRBLNC]
		,[CREATDDT]
		,[MODIFDT]
		,[Recond]
		,[Reconcile_In_Progress]
		,[Deposit_In_Progress]
		,[CHBKPSWD]
		,[CURNCYPD]
		,[CRNCYRCD]
		,[ADPVADLR]
		,[ADPVAPWD]
		,[DYCHTCLR]
		,[CMPANYID]
		,[CHKBKTYP]
		,[DDACTNUM]
		,[DDINDNAM]
		,[DDTRANS]
		,[PaymentRateTypeID]
		,[DepositRateTypeID]
		,[CashInTransAcctIdx])
SELECT	[CHEKBKID]
		,[DSCRIPTN]
		,[BANKID]
		,[CURNCYID]
		,[ACTINDX]
		,[BNKACTNM]
		,[NXTCHNUM]
		,[Next_Deposit_Number]
		,[INACTIVE]
		,[DYDEPCLR]
		,[XCDMCHPW]
		,[MXCHDLR]
		,[DUPCHNUM]
		,[OVCHNUM1]
		,[LOCATNID]
		,[NOTEINDX]
		,[CMUSRDF1]
		,[CMUSRDF2]
		,[Last_Reconciled_Date]
		,[Last_Reconciled_Balance]
		,[CURRBLNC]
		,[CREATDDT]
		,[MODIFDT]
		,[Recond]
		,[Reconcile_In_Progress]
		,[Deposit_In_Progress]
		,[CHBKPSWD]
		,[CURNCYPD]
		,[CRNCYRCD]
		,[ADPVADLR]
		,[ADPVAPWD]
		,[DYCHTCLR]
		,[CMPANYID]
		,[CHKBKTYP]
		,[DDACTNUM]
		,[DDINDNAM]
		,[DDTRANS]
		,[PaymentRateTypeID]
		,[DepositRateTypeID]
		,[CashInTransAcctIdx]
FROM	[AIS].[dbo].[CM00100]

INSERT INTO [IMCCS].[dbo].[CM40100]
		([CMRECNUM]
		,[NXTNUM]
		,[CMHISTORY]
		,[USRDFPR1]
		,[USRDRPR2]
		,[CHEKBKID])
SELECT	[CMRECNUM]
		,[NXTNUM]
		,[CMHISTORY]
		,[USRDFPR1]
		,[USRDRPR2]
		,[CHEKBKID]
FROM	[AIS].[dbo].[CM40100]

INSERT INTO [IMCCS].[dbo].[CM40101]
		([CMSortType]
		,[CMTrxType]
		,[DOCTYNAM]
		,[DOCABREV])
SELECT	[CMSortType]
		,[CMTrxType]
		,[DOCTYNAM]
		,[DOCABREV]
FROM	[AIS].[dbo].[CM40101]

INSERT INTO [IMCCS].[dbo].[GL00102]
		([ACCATNUM]
		,[ACCATDSC]
		,[DEX_ROW_TS])
SELECT	[ACCATNUM]
		,[ACCATDSC]
		,[DEX_ROW_TS]
FROM	[AIS].[dbo].[GL00102]

INSERT INTO [IMCCS].[dbo].[GL00105]
           ([ACTINDX]
           ,[ACTNUMBR_1]
           ,[ACTNUMBR_2]
           ,[ACTNUMBR_3]
           ,[ACTNUMST])
SELECT	[ACTINDX]
		,[ACTNUMBR_1]
		,[ACTNUMBR_2]
		,[ACTNUMBR_3]
		,[ACTNUMST]
FROM	[AIS].[dbo].[GL00105]

INSERT INTO [IMCCS].[dbo].[GL40000]
           ([UNIQKEY]
           ,[NJRNLENT]
           ,[RERINDX]
           ,[LSTCLSDT]
           ,[TRERCLSG]
           ,[DIVACTSG]
           ,[BLNCDSPL]
           ,[KPGACHST]
           ,[KPGTRXHS]
           ,[AHSTPSTG]
           ,[USRDFPR1]
           ,[USRDRPR2]
           ,[USRDRPR3]
           ,[USRDRPR4]
           ,[UPDTACCEL]
           ,[Posting_Number_Type]
           ,[Delete_Saved_Trx]
           ,[Void_Sub_Trx]
           ,[Correct_IC_Trx]
           ,[Allow_Reporting_Ledgers]
           ,[UseLedgersForAcctBalance]
           ,[NXTBUDJRLENT]
           ,[KPBUDTRXHIST]
           ,[NextReconciliationNumber]
           ,[DEX_ROW_TS])
SELECT	[UNIQKEY]
           ,[NJRNLENT]
           ,[RERINDX]
           ,[LSTCLSDT]
           ,[TRERCLSG]
           ,[DIVACTSG]
           ,[BLNCDSPL]
           ,[KPGACHST]
           ,[KPGTRXHS]
           ,[AHSTPSTG]
           ,[USRDFPR1]
           ,[USRDRPR2]
           ,[USRDRPR3]
           ,[USRDRPR4]
           ,[UPDTACCEL]
           ,[Posting_Number_Type]
           ,[Delete_Saved_Trx]
           ,[Void_Sub_Trx]
           ,[Correct_IC_Trx]
           ,[Allow_Reporting_Ledgers]
           ,[UseLedgersForAcctBalance]
           ,[NXTBUDJRLENT]
           ,[KPBUDTRXHIST]
           ,[NextReconciliationNumber]
           ,[DEX_ROW_TS]
FROM	[AIS].[dbo].[GL40000]

INSERT INTO [IMCCS].[dbo].[GL40200]
           ([SGMTNUMB]
           ,[SGMNTID]
           ,[DSCRIPTN]
           ,[SEGCOUNT]
           ,[NOTEINDX]
           ,[DEX_ROW_TS])
SELECT	[SGMTNUMB]
           ,[SGMNTID]
           ,[DSCRIPTN]
           ,[SEGCOUNT]
           ,[NOTEINDX]
           ,[DEX_ROW_TS]
FROM	[AIS].[dbo].[GL40200]

INSERT INTO [IMCCS].[dbo].[IVC40100]
           ([SETUPKEY]
           ,[DPYITMCS]
           ,[ACDSTRBN]
           ,[TRKVDTRX]
           ,[TRXDTL]
           ,[LOCNCODE]
           ,[CHEKBKID]
           ,[INVCFRMT]
           ,[RETNFRMT]
           ,[PKSLPFMT]
           ,[DECPLQTY]
           ,[DECPLCUR]
           ,[USEADVTX]
           ,[NONIVSCH]
           ,[FRTSCHID]
           ,[MSCSCHID]
           ,[TAXSCHID]
           ,[NONIVTXB]
           ,[FRGTTXBL]
           ,[MISCTXBL]
           ,[USRDFPR1]
           ,[USRDRPR2]
           ,[USEACFRM]
           ,[RTNUSIVC]
           ,[PKSLPIVC]
           ,[COMMNTID]
           ,[IVCALLOW_1]
           ,[IVCALLOW_2]
           ,[IVCALLOW_3]
           ,[IVCALLOW_4]
           ,[IVCALLOW_5]
           ,[IVCALLOW_6]
           ,[IVCALLOW_7]
           ,[IVCALLOW_8]
           ,[IVCALLOW_9]
           ,[IVCALLOW_10]
           ,[IVCALLOW_11]
           ,[IVCPSSWD_1]
           ,[IVCPSSWD_2]
           ,[IVCPSSWD_3]
           ,[IVCPSSWD_4]
           ,[IVCPSSWD_5]
           ,[IVCPSSWD_6]
           ,[IVCPSSWD_7]
           ,[IVCPSSWD_8]
           ,[IVCPSSWD_9]
           ,[IVCPSSWD_10]
           ,[IVCPSSWD_11]
           ,[IVCSEQNC_1]
           ,[IVCSEQNC_2]
           ,[IVCSEQNC_3]
           ,[IVCSEQNC_4]
           ,[IVCSEQNC_5]
           ,[IVCSEQNC_6]
           ,[IVCSEQNC_7]
           ,[IVCSEQNC_8]
           ,[IVCSEQNC_9]
           ,[IVCSEQNC_10]
           ,[IVCSEQNC_11]
           ,[IVCDSTCK]
           ,[NUMOFTRX])
SELECT	[SETUPKEY]
           ,[DPYITMCS]
           ,[ACDSTRBN]
           ,[TRKVDTRX]
           ,[TRXDTL]
           ,[LOCNCODE]
           ,[CHEKBKID]
           ,[INVCFRMT]
           ,[RETNFRMT]
           ,[PKSLPFMT]
           ,[DECPLQTY]
           ,[DECPLCUR]
           ,[USEADVTX]
           ,[NONIVSCH]
           ,[FRTSCHID]
           ,[MSCSCHID]
           ,[TAXSCHID]
           ,[NONIVTXB]
           ,[FRGTTXBL]
           ,[MISCTXBL]
           ,[USRDFPR1]
           ,[USRDRPR2]
           ,[USEACFRM]
           ,[RTNUSIVC]
           ,[PKSLPIVC]
           ,[COMMNTID]
           ,[IVCALLOW_1]
           ,[IVCALLOW_2]
           ,[IVCALLOW_3]
           ,[IVCALLOW_4]
           ,[IVCALLOW_5]
           ,[IVCALLOW_6]
           ,[IVCALLOW_7]
           ,[IVCALLOW_8]
           ,[IVCALLOW_9]
           ,[IVCALLOW_10]
           ,[IVCALLOW_11]
           ,[IVCPSSWD_1]
           ,[IVCPSSWD_2]
           ,[IVCPSSWD_3]
           ,[IVCPSSWD_4]
           ,[IVCPSSWD_5]
           ,[IVCPSSWD_6]
           ,[IVCPSSWD_7]
           ,[IVCPSSWD_8]
           ,[IVCPSSWD_9]
           ,[IVCPSSWD_10]
           ,[IVCPSSWD_11]
           ,[IVCSEQNC_1]
           ,[IVCSEQNC_2]
           ,[IVCSEQNC_3]
           ,[IVCSEQNC_4]
           ,[IVCSEQNC_5]
           ,[IVCSEQNC_6]
           ,[IVCSEQNC_7]
           ,[IVCSEQNC_8]
           ,[IVCSEQNC_9]
           ,[IVCSEQNC_10]
           ,[IVCSEQNC_11]
           ,[IVCDSTCK]
           ,[NUMOFTRX]
FROM	[AIS].[dbo].[IVC40100]

INSERT INTO [IMCCS].[dbo].[IVC40101]
           ([DOCTYPE]
           ,[DOCTYABR]
           ,[DOCTYNAM]
           ,[INVCNMBR]
           ,[SETUPKEY])
SELECT	[DOCTYPE]
           ,[DOCTYABR]
           ,[DOCTYNAM]
           ,[INVCNMBR]
           ,[SETUPKEY]
FROM	[AIS].[dbo].[IVC40101]

INSERT INTO [IMCCS].[dbo].[MC40000]
           ([FUNLCURR]
           ,[FUNCRIDX]
           ,[RPTGCURR]
           ,[RPTCRIDX]
           ,[RPTXRATE]
           ,[RPRTCLMD]
           ,[ALOWNWRT]
           ,[ANWRTPWD]
           ,[ALWMODRT]
           ,[MODRTPWD]
           ,[ALOVEXRT]
           ,[OVXRTPWD]
           ,[AOVRTVAR]
           ,[OVRTVPWD]
           ,[AOVRPTRT]
           ,[OVRPRPWD]
           ,[AVGEXRAT]
           ,[DEFFINTP]
           ,[DEFSLSTP]
           ,[DEFPURTP]
           ,[MNSUMHST]
           ,[LSTREVAL]
           ,[LSTPRVAL]
           ,[LSTSRVAL]
           ,[LSTTRXRV]
           ,[LSTSUMRV]
           ,[AVGCLMD]
           ,[DEX_ROW_TS])
SELECT	[FUNLCURR]
           ,[FUNCRIDX]
           ,[RPTGCURR]
           ,[RPTCRIDX]
           ,[RPTXRATE]
           ,[RPRTCLMD]
           ,[ALOWNWRT]
           ,[ANWRTPWD]
           ,[ALWMODRT]
           ,[MODRTPWD]
           ,[ALOVEXRT]
           ,[OVXRTPWD]
           ,[AOVRTVAR]
           ,[OVRTVPWD]
           ,[AOVRPTRT]
           ,[OVRPRPWD]
           ,[AVGEXRAT]
           ,[DEFFINTP]
           ,[DEFSLSTP]
           ,[DEFPURTP]
           ,[MNSUMHST]
           ,[LSTREVAL]
           ,[LSTPRVAL]
           ,[LSTSRVAL]
           ,[LSTTRXRV]
           ,[LSTSUMRV]
           ,[AVGCLMD]
           ,[DEX_ROW_TS]
FROM	[AIS].[dbo].[MC40000]

INSERT INTO [IMCCS].[dbo].[MC40100]
           ([RATETPID])
SELECT	[RATETPID]
FROM	[AIS].[dbo].[MC40100]

INSERT INTO [IMCCS].[dbo].[PM00100]
           ([VNDCLSID]
           ,[VNDCLDSC]
           ,[DEFLTCLS]
           ,[MXIAFVND]
           ,[MXINVAMT]
           ,[WRITEOFF]
           ,[CREDTLMT]
           ,[TEN99TYPE]
           ,[PTCSHACF]
           ,[MXWOFAMT]
           ,[MINORDER]
           ,[CRLMTDLR]
           ,[PYMNTPRI]
           ,[SHIPMTHD]
           ,[PYMTRMID]
           ,[MINPYTYP]
           ,[MINPYDLR]
           ,[MINPYPCT]
           ,[CURNCYID]
           ,[TAXSCHID]
           ,[KPCALHST]
           ,[KGLDSTHS]
           ,[KPERHIST]
           ,[KPTRXHST]
           ,[TRDDISCT]
           ,[USERDEF1]
           ,[USERDEF2]
           ,[PMAPINDX]
           ,[PMCSHIDX]
           ,[PMDAVIDX]
           ,[PMDTKIDX]
           ,[PMFINIDX]
           ,[PMMSCHIX]
           ,[PMFRTIDX]
           ,[PMTAXIDX]
           ,[PMWRTIDX]
           ,[PMPRCHIX]
           ,[PMRTNGIX]
           ,[PMTDSCIX]
           ,[ACPURIDX]
           ,[PURPVIDX]
           ,[CHEKBKID]
           ,[MODIFDT]
           ,[CREATDDT]
           ,[RATETPID]
           ,[Revalue_Vendor]
           ,[Post_Results_To]
           ,[FREEONBOARD]
           ,[DISGRPER]
           ,[DUEGRPER]
           ,[TaxInvRecvd]
           ,[CBVAT])
SELECT	[VNDCLSID]
           ,[VNDCLDSC]
           ,[DEFLTCLS]
           ,[MXIAFVND]
           ,[MXINVAMT]
           ,[WRITEOFF]
           ,[CREDTLMT]
           ,[TEN99TYPE]
           ,[PTCSHACF]
           ,[MXWOFAMT]
           ,[MINORDER]
           ,[CRLMTDLR]
           ,[PYMNTPRI]
           ,[SHIPMTHD]
           ,[PYMTRMID]
           ,[MINPYTYP]
           ,[MINPYDLR]
           ,[MINPYPCT]
           ,[CURNCYID]
           ,[TAXSCHID]
           ,[KPCALHST]
           ,[KGLDSTHS]
           ,[KPERHIST]
           ,[KPTRXHST]
           ,[TRDDISCT]
           ,[USERDEF1]
           ,[USERDEF2]
           ,[PMAPINDX]
           ,[PMCSHIDX]
           ,[PMDAVIDX]
           ,[PMDTKIDX]
           ,[PMFINIDX]
           ,[PMMSCHIX]
           ,[PMFRTIDX]
           ,[PMTAXIDX]
           ,[PMWRTIDX]
           ,[PMPRCHIX]
           ,[PMRTNGIX]
           ,[PMTDSCIX]
           ,[ACPURIDX]
           ,[PURPVIDX]
           ,[CHEKBKID]
           ,[MODIFDT]
           ,[CREATDDT]
           ,[RATETPID]
           ,[Revalue_Vendor]
           ,[Post_Results_To]
           ,[FREEONBOARD]
           ,[DISGRPER]
           ,[DUEGRPER]
           ,[TaxInvRecvd]
           ,[CBVAT]
FROM	[AIS].[dbo].[PM00100]

INSERT INTO [IMCCS].[dbo].[PM40100]
           ([UNIQKEY]
           ,[ADUPINNM]
           ,[OVVCHNUM]
           ,[TRKDISAV]
           ,[PRTHATRB]
           ,[AGEBY]
           ,[APPLYBY]
           ,[RMVNDHPW]
           ,[RMVTRHPW]
           ,[XCDMINPW]
           ,[WROFPSWD]
           ,[NTVCHNUM]
           ,[PMNPYNBR]
           ,[NXTVNDID]
           ,[USRDFPR1]
           ,[USRDRPR2]
           ,[PMTRXDSC_1]
           ,[PMTRXDSC_2]
           ,[PMTRXDSC_3]
           ,[PMTRXDSC_4]
           ,[PMTRXDSC_5]
           ,[PMTRXDSC_6]
           ,[PMTRXDSC_7]
           ,[PMTRXDSC_8]
           ,[PMTRXABR_1]
           ,[PMTRXABR_2]
           ,[PMTRXABR_3]
           ,[PMTRXABR_4]
           ,[PMTRXABR_5]
           ,[PMTRXABR_6]
           ,[PMTRXABR_7]
           ,[PMTRXABR_8]
           ,[CHEKBKID]
           ,[PCHSCHID]
           ,[FRTSCHID]
           ,[MSCSCHID]
           ,[LSTYECAL]
           ,[LSTYEFSC]
           ,[Check_Format_Default]
           ,[Check_Stub_Default]
           ,[PRNTPRVSLYAPPLDDCS]
           ,[DelUPDoc]
           ,[PrntTaxDetDoc]
           ,[DateSensitivitySumView]
           ,[PRNTDCUR]
           ,[AGEUNAPPLDCR]
           ,[PMNXTSCHDNBR]
           ,[ExcludeExprdDiscntsPymnt]
           ,[PMDefaultCheckSort]
           ,[WarnIfVenHasExistingPO])
SELECT	[UNIQKEY]
           ,[ADUPINNM]
           ,[OVVCHNUM]
           ,[TRKDISAV]
           ,[PRTHATRB]
           ,[AGEBY]
           ,[APPLYBY]
           ,[RMVNDHPW]
           ,[RMVTRHPW]
           ,[XCDMINPW]
           ,[WROFPSWD]
           ,[NTVCHNUM]
           ,[PMNPYNBR]
           ,[NXTVNDID]
           ,[USRDFPR1]
           ,[USRDRPR2]
           ,[PMTRXDSC_1]
           ,[PMTRXDSC_2]
           ,[PMTRXDSC_3]
           ,[PMTRXDSC_4]
           ,[PMTRXDSC_5]
           ,[PMTRXDSC_6]
           ,[PMTRXDSC_7]
           ,[PMTRXDSC_8]
           ,[PMTRXABR_1]
           ,[PMTRXABR_2]
           ,[PMTRXABR_3]
           ,[PMTRXABR_4]
           ,[PMTRXABR_5]
           ,[PMTRXABR_6]
           ,[PMTRXABR_7]
           ,[PMTRXABR_8]
           ,[CHEKBKID]
           ,[PCHSCHID]
           ,[FRTSCHID]
           ,[MSCSCHID]
           ,[LSTYECAL]
           ,[LSTYEFSC]
           ,[Check_Format_Default]
           ,[Check_Stub_Default]
           ,[PRNTPRVSLYAPPLDDCS]
           ,[DelUPDoc]
           ,[PrntTaxDetDoc]
           ,[DateSensitivitySumView]
           ,[PRNTDCUR]
           ,[AGEUNAPPLDCR]
           ,[PMNXTSCHDNBR]
           ,[ExcludeExprdDiscntsPymnt]
           ,[PMDefaultCheckSort]
           ,[WarnIfVenHasExistingPO]
FROM	[AIS].[dbo].[PM40100]

INSERT INTO [IMCCS].[dbo].[PM40101]
           ([UNIQKEY]
           ,[INDEX1]
           ,[DSCRIPTN]
           ,[ENDGPDYS])
SELECT	[UNIQKEY]
           ,[INDEX1]
           ,[DSCRIPTN]
           ,[ENDGPDYS]
FROM	[AIS].[dbo].[PM40101]

INSERT INTO [IMCCS].[dbo].[PM40102]
           ([DOCTYPE]
           ,[DOCABREV]
           ,[DOCTYNAM])
SELECT	[DOCTYPE]
           ,[DOCABREV]
           ,[DOCTYNAM]
FROM	[AIS].[dbo].[PM40102]

INSERT INTO [IMCCS].[dbo].[RM00201]
           ([CLASSID]
           ,[CLASDSCR]
           ,[CRLMTTYP]
           ,[CRLMTAMT]
           ,[CRLMTPER]
           ,[CRLMTPAM]
           ,[DEFLTCLS]
           ,[BALNCTYP]
           ,[CHEKBKID]
           ,[BANKNAME]
           ,[TAXSCHID]
           ,[SHIPMTHD]
           ,[PYMTRMID]
           ,[CUSTDISC]
           ,[CSTPRLVL]
           ,[MINPYTYP]
           ,[MINPYDLR]
           ,[MINPYPCT]
           ,[MXWOFTYP]
           ,[MXWROFAM]
           ,[FINCHARG]
           ,[FNCHATYP]
           ,[FINCHDLR]
           ,[FNCHPCNT]
           ,[PRCLEVEL]
           ,[CURNCYID]
           ,[RATETPID]
           ,[DEFCACTY]
           ,[RMCSHACC]
           ,[RMARACC]
           ,[RMCOSACC]
           ,[RMIVACC]
           ,[RMSLSACC]
           ,[RMAVACC]
           ,[RMTAKACC]
           ,[RMFCGACC]
           ,[RMWRACC]
           ,[RMSORACC]
           ,[SALSTERR]
           ,[SLPRSNID]
           ,[STMTCYCL]
           ,[SNDSTMNT]
           ,[INACTIVE]
           ,[KPCALHST]
           ,[KPDSTHST]
           ,[KPERHIST]
           ,[KPTRXHST]
           ,[NOTEINDX]
           ,[MODIFDT]
           ,[CREATDDT]
           ,[Revalue_Customer]
           ,[Post_Results_To]
           ,[DISGRPER]
           ,[DUEGRPER]
           ,[ORDERFULFILLDEFAULT]
           ,[CUSTPRIORITY]
           ,[RMOvrpymtWrtoffAcctIdx]
           ,[CBVAT]
           ,[INCLUDEINDP])
SELECT	[CLASSID]
           ,[CLASDSCR]
           ,[CRLMTTYP]
           ,[CRLMTAMT]
           ,[CRLMTPER]
           ,[CRLMTPAM]
           ,[DEFLTCLS]
           ,[BALNCTYP]
           ,[CHEKBKID]
           ,[BANKNAME]
           ,[TAXSCHID]
           ,[SHIPMTHD]
           ,[PYMTRMID]
           ,[CUSTDISC]
           ,[CSTPRLVL]
           ,[MINPYTYP]
           ,[MINPYDLR]
           ,[MINPYPCT]
           ,[MXWOFTYP]
           ,[MXWROFAM]
           ,[FINCHARG]
           ,[FNCHATYP]
           ,[FINCHDLR]
           ,[FNCHPCNT]
           ,[PRCLEVEL]
           ,[CURNCYID]
           ,[RATETPID]
           ,[DEFCACTY]
           ,[RMCSHACC]
           ,[RMARACC]
           ,[RMCOSACC]
           ,[RMIVACC]
           ,[RMSLSACC]
           ,[RMAVACC]
           ,[RMTAKACC]
           ,[RMFCGACC]
           ,[RMWRACC]
           ,[RMSORACC]
           ,[SALSTERR]
           ,[SLPRSNID]
           ,[STMTCYCL]
           ,[SNDSTMNT]
           ,[INACTIVE]
           ,[KPCALHST]
           ,[KPDSTHST]
           ,[KPERHIST]
           ,[KPTRXHST]
           ,[NOTEINDX]
           ,[MODIFDT]
           ,[CREATDDT]
           ,[Revalue_Customer]
           ,[Post_Results_To]
           ,[DISGRPER]
           ,[DUEGRPER]
           ,[ORDERFULFILLDEFAULT]
           ,[CUSTPRIORITY]
           ,[RMOvrpymtWrtoffAcctIdx]
           ,[CBVAT]
           ,[INCLUDEINDP]
FROM	[AIS].[dbo].[RM00201]

INSERT INTO [IMCCS].[dbo].[RM00301]
           ([SLPRSNID]
           ,[EMPLOYID]
           ,[VENDORID]
           ,[SLPRSNFN]
           ,[SPRSNSMN]
           ,[SPRSNSLN]
           ,[ADDRESS1]
           ,[ADDRESS2]
           ,[ADDRESS3]
           ,[CITY]
           ,[STATE]
           ,[ZIP]
           ,[COUNTRY]
           ,[PHONE1]
           ,[PHONE2]
           ,[PHONE3]
           ,[FAX]
           ,[INACTIVE]
           ,[SALSTERR]
           ,[COMMCODE]
           ,[COMPRCNT]
           ,[STDCPRCT]
           ,[COMAPPTO]
           ,[COSTTODT]
           ,[CSTLSTYR]
           ,[TTLCOMTD]
           ,[TTLCOMLY]
           ,[COMSLTDT]
           ,[COMSLLYR]
           ,[NCOMSLTD]
           ,[NCOMSLYR]
           ,[KPCALHST]
           ,[KPERHIST]
           ,[NOTEINDX]
           ,[MODIFDT]
           ,[CREATDDT]
           ,[COMMDEST]
           ,[DEX_ROW_TS])
SELECT	[SLPRSNID]
           ,[EMPLOYID]
           ,[VENDORID]
           ,[SLPRSNFN]
           ,[SPRSNSMN]
           ,[SPRSNSLN]
           ,[ADDRESS1]
           ,[ADDRESS2]
           ,[ADDRESS3]
           ,[CITY]
           ,[STATE]
           ,[ZIP]
           ,[COUNTRY]
           ,[PHONE1]
           ,[PHONE2]
           ,[PHONE3]
           ,[FAX]
           ,[INACTIVE]
           ,[SALSTERR]
           ,[COMMCODE]
           ,[COMPRCNT]
           ,[STDCPRCT]
           ,[COMAPPTO]
           ,[COSTTODT]
           ,[CSTLSTYR]
           ,[TTLCOMTD]
           ,[TTLCOMLY]
           ,[COMSLTDT]
           ,[COMSLLYR]
           ,[NCOMSLTD]
           ,[NCOMSLYR]
           ,[KPCALHST]
           ,[KPERHIST]
           ,[NOTEINDX]
           ,[MODIFDT]
           ,[CREATDDT]
           ,[COMMDEST]
           ,[DEX_ROW_TS]
FROM	[AIS].[dbo].[RM00301]

INSERT INTO [IMCCS].[dbo].[RM00303]
           ([SALSTERR]
           ,[SLTERDSC]
           ,[INACTIVE]
           ,[SLPRSNID]
           ,[STMGRFNM]
           ,[STMGRMNM]
           ,[STMGRLNM]
           ,[COUNTRY]
           ,[COSTTODT]
           ,[TTLCOMTD]
           ,[TTLCOMLY]
           ,[NCOMSLYR]
           ,[COMSLLYR]
           ,[CSTLSTYR]
           ,[COMSLTDT]
           ,[NCOMSLTD]
           ,[KPCALHST]
           ,[KPERHIST]
           ,[NOTEINDX]
           ,[MODIFDT]
           ,[CREATDDT]
           ,[DEX_ROW_TS])
SELECT	[SALSTERR]
           ,[SLTERDSC]
           ,[INACTIVE]
           ,[SLPRSNID]
           ,[STMGRFNM]
           ,[STMGRMNM]
           ,[STMGRLNM]
           ,[COUNTRY]
           ,[COSTTODT]
           ,[TTLCOMTD]
           ,[TTLCOMLY]
           ,[NCOMSLYR]
           ,[COMSLLYR]
           ,[CSTLSTYR]
           ,[COMSLTDT]
           ,[NCOMSLTD]
           ,[KPCALHST]
           ,[KPERHIST]
           ,[NOTEINDX]
           ,[MODIFDT]
           ,[CREATDDT]
           ,[DEX_ROW_TS]
FROM	[AIS].[dbo].[RM00303]

INSERT INTO [IMCCS].[dbo].[RM40101]
           ([SETUPKEY]
           ,[AGEBY]
           ,[AGPEREND_1]
           ,[AGPEREND_2]
           ,[AGPEREND_3]
           ,[AGPEREND_4]
           ,[AGPEREND_5]
           ,[AGPEREND_6]
           ,[AGPEREND_7]
           ,[AGPERUSD]
           ,[CRLMPSWD]
           ,[CUSTHPWD]
           ,[WRTFPSWD]
           ,[WVFCHPWD]
           ,[PRTHATRB]
           ,[CPDFINCH]
           ,[RMTRKDAV]
           ,[RMPCAIPD]
           ,[NSFCHDEF]
           ,[APLBYDEF]
           ,[LDFNCHGD]
           ,[LDSTPRTD]
           ,[LDBLFAGD]
           ,[LDOITAGD]
           ,[LDPTRRMV]
           ,[LSTYECAL]
           ,[LSTYEFSC]
           ,[USRDFPR1]
           ,[USRDRPR2]
           ,[FRTSCHID]
           ,[SLSCHDID]
           ,[MSCSCHID]
           ,[CHEKBKID]
           ,[SALESCB]
           ,[DISCNTCB]
           ,[FREIGHT]
           ,[MISC]
           ,[TAX]
           ,[RMVDSTTY_1]
           ,[RMVDSTTY_2]
           ,[RMVDSTTY_3]
           ,[RMVDSTTY_4]
           ,[RMVDSTTY_5]
           ,[RMVDSTTY_6]
           ,[RMVDSTTY_7]
           ,[RMVDSTTY_8]
           ,[RMVDSTTY_9]
           ,[LDCMTRNS]
           ,[PRCLEVEL]
           ,[RMDFTyp]
           ,[DelUPDoc]
           ,[PrntTaxDetDoc]
           ,[RPRNTSTTMNTS]
           ,[ATAPPLFNNCCHRGSFRST]
           ,[EmailStmtStatusRecipient]
           ,[DateSensitivitySumView]
           ,[PRNTDCUR]
           ,[AGEUNAPPLDCR]
           ,[WriteoffCreditMemoNumber]
           ,[WriteoffDebitMemoNumber]
           ,[USRDRPR3]
           ,[USRDRPR4]
           ,[DisplayOverCreditIcon]
           ,[DisplayOverCreditWarning])
SELECT	[SETUPKEY]
           ,[AGEBY]
           ,[AGPEREND_1]
           ,[AGPEREND_2]
           ,[AGPEREND_3]
           ,[AGPEREND_4]
           ,[AGPEREND_5]
           ,[AGPEREND_6]
           ,[AGPEREND_7]
           ,[AGPERUSD]
           ,[CRLMPSWD]
           ,[CUSTHPWD]
           ,[WRTFPSWD]
           ,[WVFCHPWD]
           ,[PRTHATRB]
           ,[CPDFINCH]
           ,[RMTRKDAV]
           ,[RMPCAIPD]
           ,[NSFCHDEF]
           ,[APLBYDEF]
           ,[LDFNCHGD]
           ,[LDSTPRTD]
           ,[LDBLFAGD]
           ,[LDOITAGD]
           ,[LDPTRRMV]
           ,[LSTYECAL]
           ,[LSTYEFSC]
           ,[USRDFPR1]
           ,[USRDRPR2]
           ,[FRTSCHID]
           ,[SLSCHDID]
           ,[MSCSCHID]
           ,[CHEKBKID]
           ,[SALESCB]
           ,[DISCNTCB]
           ,[FREIGHT]
           ,[MISC]
           ,[TAX]
           ,[RMVDSTTY_1]
           ,[RMVDSTTY_2]
           ,[RMVDSTTY_3]
           ,[RMVDSTTY_4]
           ,[RMVDSTTY_5]
           ,[RMVDSTTY_6]
           ,[RMVDSTTY_7]
           ,[RMVDSTTY_8]
           ,[RMVDSTTY_9]
           ,[LDCMTRNS]
           ,[PRCLEVEL]
           ,[RMDFTyp]
           ,[DelUPDoc]
           ,[PrntTaxDetDoc]
           ,[RPRNTSTTMNTS]
           ,[ATAPPLFNNCCHRGSFRST]
           ,[EmailStmtStatusRecipient]
           ,[DateSensitivitySumView]
           ,[PRNTDCUR]
           ,[AGEUNAPPLDCR]
           ,[WriteoffCreditMemoNumber]
           ,[WriteoffDebitMemoNumber]
           ,[USRDRPR3]
           ,[USRDRPR4]
           ,[DisplayOverCreditIcon]
           ,[DisplayOverCreditWarning]
FROM	[AIS].[dbo].[RM40101]

INSERT INTO [IMCCS].[dbo].[RM40201]
           ([INDEX1]
           ,[RMPERDSC]
           ,[RMPEREND])
SELECT	[INDEX1]
           ,[RMPERDSC]
           ,[RMPEREND]
FROM	[AIS].[dbo].[RM40201]

INSERT INTO [IMCCS].[dbo].[RM40401]
           ([RMDTYPAL]
           ,[DOCDESCR]
           ,[DOCABREV]
           ,[DOCNUMBR]
           ,[SETUPKEY])
SELECT	[RMDTYPAL]
           ,[DOCDESCR]
           ,[DOCABREV]
           ,[DOCNUMBR]
           ,[SETUPKEY]
FROM	[AIS].[dbo].[RM40401]

INSERT INTO [IMCCS].[dbo].[SOP40100]
           ([COMMNTID]
           ,[SETUPKEY]
           ,[DPYITMCS]
           ,[DQTYSWAR]
           ,[TRKVDTRX]
           ,[CALCKITC]
           ,[NEWRATES]
           ,[TRMSTNUM]
           ,[NXTMSTNO]
           ,[QUOTE]
           ,[PRDER]
           ,[INVORETU]
           ,[ACDSTRBN]
           ,[LOCNCODE]
           ,[CHEKBKID]
           ,[DFQTYSOP]
           ,[QUODOCID]
           ,[ORDDOCID]
           ,[BACDOCID]
           ,[INVDOCID]
           ,[RETDOCID]
           ,[DECPLQTY]
           ,[DECPLCUR]
           ,[USEACFRM]
           ,[USEADVTX]
           ,[TAXSCHID]
           ,[NONIVTXB]
           ,[NONIVSCH]
           ,[FRGTTXBL]
           ,[FRTSCHID]
           ,[MISCTXBL]
           ,[MSCSCHID]
           ,[MPACKSLP]
           ,[MPICKTIC]
           ,[PriceLevelWarning]
           ,[SOPALLOW_1]
           ,[SOPALLOW_2]
           ,[SOPALLOW_3]
           ,[SOPALLOW_4]
           ,[SOPALLOW_5]
           ,[SOPALLOW_6]
           ,[SOPALLOW_7]
           ,[SOPALLOW_8]
           ,[SOPALLOW_9]
           ,[SOPALLOW_10]
           ,[SOPPSSWD_1]
           ,[SOPPSSWD_2]
           ,[SOPPSSWD_3]
           ,[SOPPSSWD_4]
           ,[SOPPSSWD_5]
           ,[SOPPSSWD_6]
           ,[SOPPSSWD_7]
           ,[SOPPSSWD_8]
           ,[SOPPSSWD_9]
           ,[SOPPSSWD_10]
           ,[IVCDSTCK]
           ,[NUMOFTRX]
           ,[USRDFPR1]
           ,[USRDRPR2]
           ,[USRDRPR3]
           ,[USRDRPR4]
           ,[USRDRPR5]
           ,[USRDRPR6]
           ,[USRDRPR7]
           ,[USRDRPR8]
           ,[USRDRPR9]
           ,[USRDRP10]
           ,[USRDRP11]
           ,[USRDRP12]
           ,[USRDFPR13]
           ,[USRDFPR14]
           ,[USRDFPR15]
           ,[USRDFPR16]
           ,[USRDFPR17]
           ,[CREATDDT]
           ,[MODIFDT]
           ,[REQSHIP]
           ,[REQDAYS]
           ,[SITEPREF]
           ,[PREFSITE]
           ,[REQDATEPO]
           ,[Required_Days]
           ,[UMDEFAULT]
           ,[COMBONPO]
           ,[TXBASECS]
           ,[USEORGUC]
           ,[Prices_Not_Required_In_Pr]
           ,[PasswordUpper]
           ,[Convert_Functional_Price]
           ,[INDVPICKTICKETSORT]
           ,[PRINTAVAILABLEBINS]
           ,[FODOCID]
           ,[CombineDropshipSOLines]
           ,[CombineDropshipSODocs])
SELECT	[COMMNTID]
           ,[SETUPKEY]
           ,[DPYITMCS]
           ,[DQTYSWAR]
           ,[TRKVDTRX]
           ,[CALCKITC]
           ,[NEWRATES]
           ,[TRMSTNUM]
           ,[NXTMSTNO]
           ,[QUOTE]
           ,[PRDER]
           ,[INVORETU]
           ,[ACDSTRBN]
           ,[LOCNCODE]
           ,[CHEKBKID]
           ,[DFQTYSOP]
           ,[QUODOCID]
           ,[ORDDOCID]
           ,[BACDOCID]
           ,[INVDOCID]
           ,[RETDOCID]
           ,[DECPLQTY]
           ,[DECPLCUR]
           ,[USEACFRM]
           ,[USEADVTX]
           ,[TAXSCHID]
           ,[NONIVTXB]
           ,[NONIVSCH]
           ,[FRGTTXBL]
           ,[FRTSCHID]
           ,[MISCTXBL]
           ,[MSCSCHID]
           ,[MPACKSLP]
           ,[MPICKTIC]
           ,[PriceLevelWarning]
           ,[SOPALLOW_1]
           ,[SOPALLOW_2]
           ,[SOPALLOW_3]
           ,[SOPALLOW_4]
           ,[SOPALLOW_5]
           ,[SOPALLOW_6]
           ,[SOPALLOW_7]
           ,[SOPALLOW_8]
           ,[SOPALLOW_9]
           ,[SOPALLOW_10]
           ,[SOPPSSWD_1]
           ,[SOPPSSWD_2]
           ,[SOPPSSWD_3]
           ,[SOPPSSWD_4]
           ,[SOPPSSWD_5]
           ,[SOPPSSWD_6]
           ,[SOPPSSWD_7]
           ,[SOPPSSWD_8]
           ,[SOPPSSWD_9]
           ,[SOPPSSWD_10]
           ,[IVCDSTCK]
           ,[NUMOFTRX]
           ,[USRDFPR1]
           ,[USRDRPR2]
           ,[USRDRPR3]
           ,[USRDRPR4]
           ,[USRDRPR5]
           ,[USRDRPR6]
           ,[USRDRPR7]
           ,[USRDRPR8]
           ,[USRDRPR9]
           ,[USRDRP10]
           ,[USRDRP11]
           ,[USRDRP12]
           ,[USRDFPR13]
           ,[USRDFPR14]
           ,[USRDFPR15]
           ,[USRDFPR16]
           ,[USRDFPR17]
           ,[CREATDDT]
           ,[MODIFDT]
           ,[REQSHIP]
           ,[REQDAYS]
           ,[SITEPREF]
           ,[PREFSITE]
           ,[REQDATEPO]
           ,[Required_Days]
           ,[UMDEFAULT]
           ,[COMBONPO]
           ,[TXBASECS]
           ,[USEORGUC]
           ,[Prices_Not_Required_In_Pr]
           ,[PasswordUpper]
           ,[Convert_Functional_Price]
           ,[INDVPICKTICKETSORT]
           ,[PRINTAVAILABLEBINS]
           ,[FODOCID]
           ,[CombineDropshipSOLines]
           ,[CombineDropshipSODocs]
FROM	[AIS].[dbo].[SOP40100]

INSERT INTO [IMCCS].[dbo].[SOP40200]
           ([DOCID]
           ,[NOTEINDX]
           ,[SOPTYPE]
           ,[SETUPKEY]
           ,[DOCTYABR]
           ,[SOPNUMBE]
           ,[COMMNTID]
           ,[DOCUFORM]
           ,[DAYTOEXP]
           ,[ALLREPEA]
           ,[ALLOCABY]
           ,[USEPROSP]
           ,[USNXTINV]
           ,[USPFULPR]
           ,[QUOTOINV]
           ,[QUOTOORD]
           ,[INVTOBAC]
           ,[BACTOINV]
           ,[BACTOORD]
           ,[ORDTOBAC]
           ,[ORDTOORD]
           ,[USDOCID1]
           ,[USDOCID2]
           ,[QTYDEFAU]
           ,[SOPALLOW_1]
           ,[SOPALLOW_2]
           ,[SOPALLOW_3]
           ,[SOPALLOW_4]
           ,[SOPALLOW_5]
           ,[SOPALLOW_6]
           ,[SOPALLOW_7]
           ,[SOPALLOW_8]
           ,[SOPALLOW_9]
           ,[SOPALLOW_10]
           ,[SOPPSSWD_1]
           ,[SOPPSSWD_2]
           ,[SOPPSSWD_3]
           ,[SOPPSSWD_4]
           ,[SOPPSSWD_5]
           ,[SOPPSSWD_6]
           ,[SOPPSSWD_7]
           ,[SOPPSSWD_8]
           ,[SOPPSSWD_9]
           ,[SOPPSSWD_10]
           ,[SOPSEQNC_1]
           ,[SOPSEQNC_2]
           ,[SOPSEQNC_3]
           ,[SOPSEQNC_4]
           ,[SOPSEQNC_5]
           ,[SOPSEQNC_6]
           ,[SOPSEQNC_7]
           ,[SOPSEQNC_8]
           ,[USER2ENT]
           ,[CREATDDT]
           ,[MODIFDT]
           ,[SHPPGDOC]
           ,[CORRCTN]
           ,[SIMPLIFD]
           ,[ALLBACKODPRT]
           ,[XORDINVC]
           ,[USDOCID3]
           ,[WORKFLOWENABLED]
           ,[UPDTONPRINT]
           ,[CREDITLIMITHOLDID]
           ,[UPDTACTUALSHPDT]
           ,[WORKFLOWHOLDID]
           ,[OVERRIDEIVCBILLQTY]
           ,[ENABLEBACKORDER]
           ,[ENABLECANCELED]
           ,[SOPSTATUSACTIVE_1]
           ,[SOPSTATUSACTIVE_2]
           ,[SOPSTATUSACTIVE_3]
           ,[SOPSTATUSACTIVE_4]
           ,[SOPSTATUSACTIVE_5]
           ,[SOPSTATUSACTIVE_6]
           ,[SOPSTATUSACTIVE_7]
           ,[SOPSTATUSACTIVE_8]
           ,[SOPSTATUSACTIVE_9])
SELECT	[DOCID]
           ,[NOTEINDX]
           ,[SOPTYPE]
           ,[SETUPKEY]
           ,[DOCTYABR]
           ,[SOPNUMBE]
           ,[COMMNTID]
           ,[DOCUFORM]
           ,[DAYTOEXP]
           ,[ALLREPEA]
           ,[ALLOCABY]
           ,[USEPROSP]
           ,[USNXTINV]
           ,[USPFULPR]
           ,[QUOTOINV]
           ,[QUOTOORD]
           ,[INVTOBAC]
           ,[BACTOINV]
           ,[BACTOORD]
           ,[ORDTOBAC]
           ,[ORDTOORD]
           ,[USDOCID1]
           ,[USDOCID2]
           ,[QTYDEFAU]
           ,[SOPALLOW_1]
           ,[SOPALLOW_2]
           ,[SOPALLOW_3]
           ,[SOPALLOW_4]
           ,[SOPALLOW_5]
           ,[SOPALLOW_6]
           ,[SOPALLOW_7]
           ,[SOPALLOW_8]
           ,[SOPALLOW_9]
           ,[SOPALLOW_10]
           ,[SOPPSSWD_1]
           ,[SOPPSSWD_2]
           ,[SOPPSSWD_3]
           ,[SOPPSSWD_4]
           ,[SOPPSSWD_5]
           ,[SOPPSSWD_6]
           ,[SOPPSSWD_7]
           ,[SOPPSSWD_8]
           ,[SOPPSSWD_9]
           ,[SOPPSSWD_10]
           ,[SOPSEQNC_1]
           ,[SOPSEQNC_2]
           ,[SOPSEQNC_3]
           ,[SOPSEQNC_4]
           ,[SOPSEQNC_5]
           ,[SOPSEQNC_6]
           ,[SOPSEQNC_7]
           ,[SOPSEQNC_8]
           ,[USER2ENT]
           ,[CREATDDT]
           ,[MODIFDT]
           ,[SHPPGDOC]
           ,[CORRCTN]
           ,[SIMPLIFD]
           ,[ALLBACKODPRT]
           ,[XORDINVC]
           ,[USDOCID3]
           ,[WORKFLOWENABLED]
           ,[UPDTONPRINT]
           ,[CREDITLIMITHOLDID]
           ,[UPDTACTUALSHPDT]
           ,[WORKFLOWHOLDID]
           ,[OVERRIDEIVCBILLQTY]
           ,[ENABLEBACKORDER]
           ,[ENABLECANCELED]
           ,[SOPSTATUSACTIVE_1]
           ,[SOPSTATUSACTIVE_2]
           ,[SOPSTATUSACTIVE_3]
           ,[SOPSTATUSACTIVE_4]
           ,[SOPSTATUSACTIVE_5]
           ,[SOPSTATUSACTIVE_6]
           ,[SOPSTATUSACTIVE_7]
           ,[SOPSTATUSACTIVE_8]
           ,[SOPSTATUSACTIVE_9]
FROM	[AIS].[dbo].[SOP40200]

INSERT INTO [IMCCS].[dbo].[SY00300]
           ([SGMTNUMB]
           ,[SGMTNAME]
           ,[LOFSGMNT]
           ,[MXLENSEG]
           ,[USDFSGKY]
           ,[MNSEGIND]
           ,[SegmentWidth]
           ,[DEX_ROW_TS])
SELECT	[SGMTNUMB]
           ,[SGMTNAME]
           ,[LOFSGMNT]
           ,[MXLENSEG]
           ,[USDFSGKY]
           ,[MNSEGIND]
           ,[SegmentWidth]
           ,[DEX_ROW_TS]
FROM	[AIS].[dbo].[SY00300]

INSERT INTO [IMCCS].[dbo].[SY01100]
           ([SERIES]
           ,[SEQNUMBR]
           ,[ACTINDX]
           ,[PTGACDSC])
SELECT	[SERIES]
           ,[SEQNUMBR]
           ,[ACTINDX]
           ,[PTGACDSC]
FROM	[AIS].[dbo].[SY01100]

INSERT INTO [IMCCS].[dbo].[SY02200]
           ([FILEXPNM]
           ,[PRNTJRNL]
           ,[SERIES]
           ,[TRXSOURC]
           ,[PTGRPTNM]
           ,[ASECTMNT]
           ,[PRTOPRNT]
           ,[PRTOSCNT]
           ,[PRTOFLNT]
           ,[EXPTTYPE]
           ,[APNDRPLC])
SELECT	[FILEXPNM]
           ,[PRNTJRNL]
           ,[SERIES]
           ,[TRXSOURC]
           ,[PTGRPTNM]
           ,[ASECTMNT]
           ,[PRTOPRNT]
           ,[PRTOSCNT]
           ,[PRTOFLNT]
           ,[EXPTTYPE]
           ,[APNDRPLC]
FROM	[AIS].[dbo].[SY02200]

INSERT INTO [IMCCS].[dbo].[SY02300]
           ([UPSTDTFR]
           ,[BCHEXIST]
           ,[PTGENLED]
           ,[SERIES]
           ,[TRXSOURC]
           ,[PSTOGLHW]
           ,[ALTRXPST]
           ,[AUTPSTGL]
           ,[VERBATOT]
           ,[VERTRX]
           ,[REQBAPRV]
           ,[PASSWORD]
           ,[INCMCINF]
           ,[Use_Account_Settings]
           ,[POSTINDETAIL])
SELECT	[UPSTDTFR]
           ,[BCHEXIST]
           ,[PTGENLED]
           ,[SERIES]
           ,[TRXSOURC]
           ,[PSTOGLHW]
           ,[ALTRXPST]
           ,[AUTPSTGL]
           ,[VERBATOT]
           ,[VERTRX]
           ,[REQBAPRV]
           ,[PASSWORD]
           ,[INCMCINF]
           ,[Use_Account_Settings]
           ,[POSTINDETAIL]
FROM	[AIS].[dbo].[SY02300]

INSERT INTO [IMCCS].[dbo].[SY03000]
           ([SHIPMTHD]
           ,[SHMTHDSC]
           ,[PHONNAME]
           ,[CONTACT]
           ,[CARRACCT]
           ,[CARRIER]
           ,[SHIPTYPE]
           ,[NOTEINDX]
           ,[LSTUSRED]
           ,[CREATDDT]
           ,[MODIFDT])
SELECT	[SHIPMTHD]
           ,[SHMTHDSC]
           ,[PHONNAME]
           ,[CONTACT]
           ,[CARRACCT]
           ,[CARRIER]
           ,[SHIPTYPE]
           ,[NOTEINDX]
           ,[LSTUSRED]
           ,[CREATDDT]
           ,[MODIFDT]
FROM	[AIS].[dbo].[SY03000]

INSERT INTO [IMCCS].[dbo].[SY03300]
           ([PYMTRMID]
           ,[DUETYPE]
           ,[DUEDTDS]
           ,[DISCTYPE]
           ,[DISCDTDS]
           ,[DSCLCTYP]
           ,[DSCDLRAM]
           ,[DSCPCTAM]
           ,[SALPURCH]
           ,[DISCNTCB]
           ,[FREIGHT]
           ,[MISC]
           ,[TAX]
           ,[NOTEINDX]
           ,[CBUVATMD]
           ,[LSTUSRED]
           ,[MODIFDT]
           ,[CREATDDT]
           ,[USEGRPER]
           ,[CalculateDateFrom]
           ,[CalculateDateFromDays]
           ,[DueMonth]
           ,[DiscountMonth])
SELECT	[PYMTRMID]
           ,[DUETYPE]
           ,[DUEDTDS]
           ,[DISCTYPE]
           ,[DISCDTDS]
           ,[DSCLCTYP]
           ,[DSCDLRAM]
           ,[DSCPCTAM]
           ,[SALPURCH]
           ,[DISCNTCB]
           ,[FREIGHT]
           ,[MISC]
           ,[TAX]
           ,[NOTEINDX]
           ,[CBUVATMD]
           ,[LSTUSRED]
           ,[MODIFDT]
           ,[CREATDDT]
           ,[USEGRPER]
           ,[CalculateDateFrom]
           ,[CalculateDateFromDays]
           ,[DueMonth]
           ,[DiscountMonth]
FROM	[AIS].[dbo].[SY03300]

INSERT INTO [IMCCS].[dbo].[SY04100]
           ([BANKID]
           ,[BANKNAME]
           ,[ADDRESS1]
           ,[ADDRESS2]
           ,[ADDRESS3]
           ,[CITY]
           ,[STATE]
           ,[ZIPCODE]
           ,[COUNTRY]
           ,[PHNUMBR1]
           ,[PHNUMBR2]
           ,[PHONE3]
           ,[FAXNUMBR]
           ,[TRNSTNBR]
           ,[BNKBRNCH]
           ,[NOTEINDX]
           ,[DDTRANUM])
SELECT	[BANKID]
           ,[BANKNAME]
           ,[ADDRESS1]
           ,[ADDRESS2]
           ,[ADDRESS3]
           ,[CITY]
           ,[STATE]
           ,[ZIPCODE]
           ,[COUNTRY]
           ,[PHNUMBR1]
           ,[PHNUMBR2]
           ,[PHONE3]
           ,[FAXNUMBR]
           ,[TRNSTNBR]
           ,[BNKBRNCH]
           ,[NOTEINDX]
           ,[DDTRANUM]
FROM	[AIS].[dbo].[SY04100]

INSERT INTO [IMCCS].[dbo].[SY40100]
           ([CLOSED]
           ,[SERIES]
           ,[ODESCTN]
           ,[FORIGIN]
           ,[PERIODID]
           ,[PERIODDT]
           ,[PERNAME]
           ,[PSERIES_1]
           ,[PSERIES_2]
           ,[PSERIES_3]
           ,[PSERIES_4]
           ,[PSERIES_5]
           ,[PSERIES_6]
           ,[YEAR1]
           ,[PERDENDT]
           ,[DEX_ROW_TS])
SELECT	[CLOSED]
           ,[SERIES]
           ,[ODESCTN]
           ,[FORIGIN]
           ,[PERIODID]
           ,[PERIODDT]
           ,[PERNAME]
           ,[PSERIES_1]
           ,[PSERIES_2]
           ,[PSERIES_3]
           ,[PSERIES_4]
           ,[PSERIES_5]
           ,[PSERIES_6]
           ,[YEAR1]
           ,[PERDENDT]
           ,[DEX_ROW_TS]
FROM	[AIS].[dbo].[SY40100]

INSERT INTO [IMCCS].[dbo].[SY40101]
           ([YEAR1]
           ,[FSTFSCDY]
           ,[LSTFSCDY]
           ,[NUMOFPER]
           ,[HISTORYR]
           ,[DEX_ROW_TS])
SELECT	[YEAR1]
           ,[FSTFSCDY]
           ,[LSTFSCDY]
           ,[NUMOFPER]
           ,[HISTORYR]
           ,[DEX_ROW_TS]
FROM	[AIS].[dbo].[SY40101]

IF @@ERROR = 0
	COMMIT TRANSACTION
ELSE
	ROLLBACK TRANSACTION