DECLARE @tblData Table (Company Varchar(5), Deduction varchar(15))

INSERT INTO @tblData (Company, Deduction) VALUES ('AIS','4Q10')
INSERT INTO @tblData (Company, Deduction) VALUES ('AIS','ACC')
INSERT INTO @tblData (Company, Deduction) VALUES ('AIS','ADV2')
INSERT INTO @tblData (Company, Deduction) VALUES ('AIS','ESA3')
INSERT INTO @tblData (Company, Deduction) VALUES ('AIS','ESA4')
INSERT INTO @tblData (Company, Deduction) VALUES ('AIS','ESCA')
INSERT INTO @tblData (Company, Deduction) VALUES ('AIS','HLT2')
INSERT INTO @tblData (Company, Deduction) VALUES ('AIS','HUT')
INSERT INTO @tblData (Company, Deduction) VALUES ('AIS','IRP')
INSERT INTO @tblData (Company, Deduction) VALUES ('AIS','IRP8')
INSERT INTO @tblData (Company, Deduction) VALUES ('AIS','LTO2 ')
INSERT INTO @tblData (Company, Deduction) VALUES ('AIS','MAN2')
INSERT INTO @tblData (Company, Deduction) VALUES ('AIS','MT09')
INSERT INTO @tblData (Company, Deduction) VALUES ('AIS','MT10')
INSERT INTO @tblData (Company, Deduction) VALUES ('AIS','MT11')
INSERT INTO @tblData (Company, Deduction) VALUES ('AIS','OAC2')
INSERT INTO @tblData (Company, Deduction) VALUES ('AIS','OAC8')
INSERT INTO @tblData (Company, Deduction) VALUES ('AIS','SL05')
INSERT INTO @tblData (Company, Deduction) VALUES ('AIS','SL06')
INSERT INTO @tblData (Company, Deduction) VALUES ('AIS','SL12')
INSERT INTO @tblData (Company, Deduction) VALUES ('AIS','SL16')
INSERT INTO @tblData (Company, Deduction) VALUES ('AIS','SLMR')
INSERT INTO @tblData (Company, Deduction) VALUES ('AIS','TIN2')
INSERT INTO @tblData (Company, Deduction) VALUES ('AIS','TNMR')
INSERT INTO @tblData (Company, Deduction) VALUES ('AIS','TR05')
INSERT INTO @tblData (Company, Deduction) VALUES ('AIS','TRKM')
INSERT INTO @tblData (Company, Deduction) VALUES ('AIS','TRSL')
INSERT INTO @tblData (Company, Deduction) VALUES ('OIS','BN55')
INSERT INTO @tblData (Company, Deduction) VALUES ('PTS','DEDD')
INSERT INTO @tblData (Company, Deduction) VALUES ('PTS','PDTR')
INSERT INTO @tblData (Company, Deduction) VALUES ('PTS','RFID')
INSERT INTO @tblData (Company, Deduction) VALUES ('PTS','TIRE')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','DEDD')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','ESC1')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','ESC2')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','ESCA')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','FUEL')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','HLT2')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','HUT')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','IRP')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','IRP2')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','M&R2')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','MSC')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','MT09')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','MT10')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','MT11')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','MT12')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','MT2')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','NOMT')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','NOTR')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','OAC2')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','PK03 ')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','PK07')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','PK09 ')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','PK10')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','PK19')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','PK22')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','PPL')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','RCCL')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','REIM')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','TAG')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','TAG1')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','TAG8')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','TAG9')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','TIN2')
INSERT INTO @tblData (Company, Deduction) VALUES ('IMC','TRKM')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','DEDD')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','ESC1')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','ESC2')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','ESCA')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','GIS')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','GIS2')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','GIS3')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','GTAP')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','HLT2')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','HUT')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','IRP')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','IRP2')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','M&R2')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','M&R3')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','MSC')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','MT09')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','MT10')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','MT11')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','NOMT')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','NOTR')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','OAC2')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','SECD')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','TAG0')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','TAG1')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','TAG8')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','TAG9')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','TG12')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','TG13')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','TIN2')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','TRKM')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','YARD')
INSERT INTO @tblData (Company, Deduction) VALUES ('GIS','YD37')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','AMT')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','BN28')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','DEDD')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','DTRK')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','ESC1')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','ESC2')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','ESCA')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','FTAX')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','GTAP')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','HLT2')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','IRP')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','IRP2')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','LEGL')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','MAN2')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','MSC')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','MT09')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','MT10')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','MT12')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','MTN')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','NOMT')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','NOTR')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','OAC2')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','TAG0')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','TAG8')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','TAG9')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','TG12')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','TIN2')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','TRK2')
INSERT INTO @tblData (Company, Deduction) VALUES ('DNJ','TRKM')

UPDATE	OOS_DeductionTypes
SET		Inactive = 1
FROM	(
SELECT	DAT.Company,
		DAT.Deduction
FROM	OOS_DeductionTypes OOS
		INNER JOIN @tblData DAT ON OOS.Company = DAT.Company AND OOS.DeductionCode = DAT.Deduction
		) DATA
WHERE	OOS_DeductionTypes.Company = DATA.Company
		AND OOS_DeductionTypes.DeductionCode = DATA.Deduction