INSERT INTO [GPCustom].[dbo].[EscrowTransactions]
           ([Source]
           ,[VoucherNumber]
           ,[ItemNumber]
           ,[CompanyId]
           ,[Fk_EscrowModuleId]
           ,[AccountNumber]
           ,[AccountType]
           ,[VendorId]
           ,[DriverId]
           ,[Division]
           ,[Amount]
           ,[ClaimNumber]
           ,[DriverClass]
           ,[AccidentType]
           ,[Status]
           ,[DMSubmitted]
           ,[DeductionPlan]
           ,[Comments]
           ,[ProNumber]
           ,[TransactionDate]
           ,[PostingDate]
           ,[EnteredBy]
           ,[EnteredOn]
           ,[ChangedBy]
           ,[ChangedOn]
           ,[Void]
           ,[InvoiceNumber]
           ,[OtherStatus]
           ,[DeletedBy]
           ,[DeletedOn]
           ,[BatchId])
SELECT	[Source]
           ,[VoucherNumber]
           ,[ItemNumber]
           ,[CompanyId]
           ,[Fk_EscrowModuleId]
           ,[AccountNumber]
           ,[AccountType]
           ,[VendorId]
           ,[DriverId]
           ,[Division]
           ,[Amount] * -1
           ,[ClaimNumber]
           ,[DriverClass]
           ,[AccidentType]
           ,[Status]
           ,[DMSubmitted]
           ,[DeductionPlan]
           ,[Comments]
           ,[ProNumber]
           ,[TransactionDate]
           ,'10/31/2011' as [PostingDate]
           ,[EnteredBy]
           ,[EnteredOn]
           ,[ChangedBy]
           ,[ChangedOn]
           ,[Void]
           ,[InvoiceNumber]
           ,[OtherStatus]
           ,[DeletedBy]
           ,[DeletedOn]
           ,[BatchId]
FROM	EscrowTransactions
WHERE	CompanyId = 'GIS'
		AND VendorId = 'G0154'
		AND VoucherNumber IN ('00000000000024751', '00000000000024753', '00000000000024754')