insert into Integrations_Cash
SELECT	'LCKBX' AS Integration,
		'PTS' AS Company,
		BACHNUMB,
		CUSTNMBR,
		DOCNUMBR,
		DOCDATE,
		ORTRXAMT,
		GLPOSTDT,
		CSHRCTYP,
		CHEKBKID,
		CHEKNMBR,
		CRCARDID,
		TRXDSCRN,
		0 AS Processed
FROM	PRISQL01P.PTS.dbo.RM10201
WHERE	BACHNUMB LIKE '%LOCKBOX%'