INSERT INTO [IMC].[dbo].[RM20201]
           ([CUSTNMBR]
           ,[CPRCSTNM]
           ,[TRXSORCE]
           ,[DATE1]
           ,[TIME1]
           ,[GLPOSTDT]
           ,[POSTED]
           ,[TAXDTLID]
           ,[APTODCNM]
           ,[APTODCTY]
           ,[APTODCDT]
           ,[ApplyToGLPostDate]
           ,[CURNCYID]
           ,[CURRNIDX]
           ,[APPTOAMT]
           ,[DISTKNAM]
           ,[DISAVTKN]
           ,[WROFAMNT]
           ,[ORAPTOAM]
           ,[ORDISTKN]
           ,[ORDATKN]
           ,[ORWROFAM]
           ,[APTOEXRATE]
           ,[APTODENRATE]
           ,[APTORTCLCMETH]
           ,[APTOMCTRXSTT]
           ,[APFRDCNM]
           ,[APFRDCTY]
           ,[APFRDCDT]
           ,[ApplyFromGLPostDate]
           ,[FROMCURR]
           ,[APFRMAPLYAMT]
           ,[APFRMDISCTAKEN]
           ,[APFRMDISCAVAIL]
           ,[APFRMWROFAMT]
           ,[ActualApplyToAmount]
           ,[ActualDiscTakenAmount]
           ,[ActualDiscAvailTaken]
           ,[ActualWriteOffAmount]
           ,[APFRMEXRATE]
           ,[APFRMDENRATE]
           ,[APFRMRTCLCMETH]
           ,[APFRMMCTRXSTT]
           ,[APYFRMRNDAMT]
           ,[APYTORNDAMT]
           ,[APYTORNDDISC]
           ,[OAPYFRMRNDAMT]
           ,[OAPYTORNDAMT]
           ,[OAPYTORNDDISC]
           ,[GSTDSAMT]
           ,[PPSAMDED]
           ,[RLGANLOS]
           ,[Settled_Gain_CreditCurrT]
           ,[Settled_Loss_CreditCurrT]
           ,[Settled_Gain_DebitCurrTr]
           ,[Settled_Loss_DebitCurrTr]
           ,[Settled_Gain_DebitDiscAv]
           ,[Settled_Loss_DebitDiscAv]
           ,[Revaluation_Status])
SELECT	R1.CUSTNMBR
           ,R1.CPRCSTNM
           ,R1.TRXSORCE
           ,R1.DATE1
           ,R1.TIME1
           ,R1.GLPOSTDT
           ,R1.POSTED
           ,R1.TAXDTLID
           ,R1.APTODCNM
           ,R1.APTODCTY
           ,R1.APTODCDT
           ,R1.ApplyToGLPostDate
           ,R1.CURNCYID
           ,R1.CURRNIDX
           ,R1.APPTOAMT
           ,R1.DISTKNAM
           ,R1.DISAVTKN
           ,R1.WROFAMNT
           ,R1.ORAPTOAM
           ,R1.ORDISTKN
           ,R1.ORDATKN
           ,R1.ORWROFAM
           ,R1.APTOEXRATE
           ,R1.APTODENRATE
           ,R1.APTORTCLCMETH
           ,R1.APTOMCTRXSTT
           ,R1.APFRDCNM
           ,R1.APFRDCTY
           ,R1.APFRDCDT
           ,R1.ApplyFromGLPostDate
           ,R1.FROMCURR
           ,R1.APFRMAPLYAMT
           ,R1.APFRMDISCTAKEN
           ,R1.APFRMDISCAVAIL
           ,R1.APFRMWROFAMT
           ,R1.ActualApplyToAmount
           ,R1.ActualDiscTakenAmount
           ,R1.ActualDiscAvailTaken
           ,R1.ActualWriteOffAmount
           ,R1.APFRMEXRATE
           ,R1.APFRMDENRATE
           ,R1.APFRMRTCLCMETH
           ,R1.APFRMMCTRXSTT
           ,R1.APYFRMRNDAMT
           ,R1.APYTORNDAMT
           ,R1.APYTORNDDISC
           ,R1.OAPYFRMRNDAMT
           ,R1.OAPYTORNDAMT
           ,R1.OAPYTORNDDISC
           ,R1.GSTDSAMT
           ,R1.PPSAMDED
           ,R1.RLGANLOS
           ,R1.Settled_Gain_CreditCurrT
           ,R1.Settled_Loss_CreditCurrT
           ,R1.Settled_Gain_DebitCurrTr
           ,R1.Settled_Loss_DebitCurrTr
           ,R1.Settled_Gain_DebitDiscAv
           ,R1.Settled_Loss_DebitDiscAv
           ,R1.Revaluation_Status
FROM	RM20201 R1
		LEFT JOIN IMC.dbo.RM20201 R2 ON R1.CUSTNMBR = R2.CUSTNMBR AND R1.APFRDCNM = R2.APFRDCNM
WHERE	R2.APFRDCNM IS NULL