INSERT INTO SY03300
	   (PymTrmId,
		Duedtds)
SELECT	DISTINCT PymTrmId,
		CASE WHEN PATINDEX('NET%', PymTrmId) > 0 THEN CAST(RTRIM(SUBSTRING(PymTrmId, 5, 2)) AS Int)
		ELSE 999 END AS Days
FROM	PM00200 
WHERE	PymTrmId <> '' AND
		PymTrmId NOT IN (SELECT PymTrmId FROM SY03300)
ORDER BY 
		2

--UPDATE PM00200 SET PymTrmId = UPPER(RTRIM(PymTrmId))
UPDATE SY03300 SET DueType = 1, DiscType = 1, DsclcTyp = 1, LstUsrEd = 'cflores'
SELECT * FROM SY03300