USE [ManagementReporter]
GO

INSERT INTO [Reporting].[SecurityUser]
           ([UserID]
           ,[UserName]
           ,[RoleType]
           ,[AlgorithmName]
           ,[PasswordSalt]
           ,[PasswordHash]
           ,[WindowsSecurityIdentifier]
           ,[EmailAddress]
           ,[InvalidLoginAttempts]
           ,[LastLoginAttempt]
           ,[PasswordExpires]
           ,[AccountDisabled]
           ,[ForcePasswordChange]
           ,[CanAdministerSecurity]
           ,[CanAdministerReportServer]
           ,[CanAdministerRepositorySecurity]
           ,[CanExportReport]
           ,[CanViewReportBook]
           ,[CanGenerateAndDistributeReports]
           ,[CanEditReportDesigns]
           ,[CanEditAllCompanies]
           ,[CanEditCompanyAndSpecSet]
           ,[CanEditAccountSets]
           ,[CanEditForeignCurrency]
           ,[CanEditDesignerOptions]
           ,[CanUndoBuildingBlockCheckout]
           ,[CanUnprotectBuildingBlock]
           ,[CanUseRepository]
           ,[CanViewAlerts]
           ,[CanViewCharts]
           ,[CanViewComments]
           ,[CanViewIndicators]
           ,[CanEditAlerts]
           ,[CanEditCharts]
           ,[CanEditComments]
           ,[CanEditIndicators]
           ,[CanModifyAndSubmitXbrlData]
           ,[AuthenticationType]
           ,[CanActOnBehalfOf]
           ,[ExternalId])
     VALUES
           ('776adc75-6f28-4904-b8ba-8ddb160261f4'
           ,'eConnectService'
           ,5
           ,''
           ,CAST('' AS varbinary(64))
           ,CAST('' AS varbinary(64))
           ,'S-1-5-21-3677505629-1728297437-125762653-12246'
           ,''
           ,0
           ,GETDATE()
           ,'9999-12-31 23:59'
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,null)