SELECT	*
FROM	PARAMETERS
WHERE	PARAMETERCODE = 'PREPAY_COMPANY'

UPDATE	PARAMETERS
SET		VarC = '3'
WHERE	PARAMETERCODE = 'PREPAY_COMPANY'
		AND COMPANY = 'PTS'

INSERT Parameters (Company, ParameterCode, Description, VarType, VarC)
VALUES
('AIS','PREPAY_COMPANY','MAPPING COMPANY CODE FOR PRE-PAY','C','4')

INSERT Parameters (Company, ParameterCode, Description, VarType, VarC)
VALUES
('DNJ','PREPAY_COMPANY','MAPPING COMPANY CODE FOR PRE-PAY','C','7')