INSERT INTO [GPCustom].[dbo].[EscrowTransactionsHistory]
           ([Source]
           ,[VoucherNumber]
           ,[ItemNumber]
           ,[CompanyId]
           ,[Fk_EscrowModuleId]
           ,[AccountNumber]
           ,[AccountType]
           ,[VendorId]
           ,[DriverId]
           ,[Division]
           ,[Amount]
           ,[ClaimNumber]
           ,[DriverClass]
           ,[AccidentType]
           ,[Status]
           ,[DMSubmitted]
           ,[DeductionPlan]
           ,[Comments]
           ,[ProNumber]
           ,[TransactionDate]
           ,[PostingDate]
           ,[EnteredBy]
           ,[EnteredOn]
           ,[ChangedBy]
           ,[ChangedOn]
           ,[Void]
           ,[InvoiceNumber]
           ,[OtherStatus]
           ,[DeletedBy]
           ,[DeletedOn]
           ,[BatchId]
           ,[SOPDocumentNumber]
           ,[UnitNumber]
           ,[RepairDate]) 
SELECT		[Source]
           ,[VoucherNumber]
           ,[ItemNumber]
           ,[CompanyId]
           ,[Fk_EscrowModuleId]
           ,[AccountNumber]
           ,[AccountType]
           ,[VendorId]
           ,[DriverId]
           ,[Division]
           ,[Amount]
           ,[ClaimNumber]
           ,[DriverClass]
           ,[AccidentType]
           ,[Status]
           ,[DMSubmitted]
           ,[DeductionPlan]
           ,[Comments]
           ,[ProNumber]
           ,[TransactionDate]
           ,[PostingDate]
           ,[EnteredBy]
           ,[EnteredOn]
           ,[ChangedBy]
           ,[ChangedOn]
           ,[Void]
           ,[InvoiceNumber]
           ,[OtherStatus]
           ,[DeletedBy]
           ,[DeletedOn]
           ,[BatchId]
           ,[SOPDocumentNumber]
           ,[UnitNumber]
           ,[RepairDate]
FROM	EscrowTransactions 
WHERE	PostingDate < '1/1/2014'
		AND PostingDate IS NOT Null

-- DELETE EscrowTransactions WHERE PostingDate < '1/1/2014' AND PostingDate IS NOT Null