INSERT INTO [PM30600]
           ([DOCTYPE]
		   ,[VCHRNMBR]
           ,[DSTSQNUM]
           ,[CNTRLTYP]
           ,[CRDTAMNT]
           ,[DEBITAMT]
           ,[DSTINDX]
           ,[DISTTYPE]
           ,[USERID]
           ,[VENDORID]
           ,[TRXSORCE]
           ,[PSTGDATE]
           ,[ORCRDAMT]
           ,[ORDBTAMT]
           ,[DistRef])
SELECT	AP.DOCTYPE
		,AP.[VCHRNMBR]
		,OrigSeqNum AS [DSTSQNUM]
		,1 AS [CNTRLTYP]
		,GL.[CRDTAMNT]
		,GL.[DEBITAMT]
		,GL.ACTINDX
		,IIF(GL.ACTINDX = 2, 1, 2) AS [DISTTYPE]
		,'RESTORED'
		,AP.[VENDORID]
		,AP.[TRXSORCE]
		,[PSTGDATE]
		,[ORCRDAMT]
		,[ORDBTAMT]
		,GL.REFRENCE AS [DistRef]
FROM	GL20000 GL
		INNER JOIN PM30200 AP ON GL.ORCTRNUM = AP.VCHRNMBR AND GL.ORMSTRID = AP.VENDORID
WHERE	RTRIM(AP.VENDORID) + '-' + RTRIM(AP.DOCNUMBR) IN (SELECT	RTRIM(PM.VENDORID) + '-' + RTRIM(PM.DOCNUMBR)
FROM	PM30200 PM
		INNER JOIN (
					SELECT	PH.VENDORID,
							PA.APTODCNM,
							PA.APTVCHNM
					FROM	PM30200 PH
							LEFT JOIN PM30300 PA ON PH.VENDORID = PA.VENDORID AND PH.DOCNUMBR = PA.APFRDCNM
					WHERE	PH.VENDORID = '1316'
							AND PH.DOCNUMBR = '8708'
					) DA ON PM.VENDORID = DA.VENDORID AND PM.VCHRNMBR = DA.APTVCHNM)
--WHERE	GL.JRNENTRY = 515093