SELECT	distinct 'INSERT INTO @tblAcctAlias VALUES (''' + Company + ''',''' + Company + ''')'
FROM	IntercompanyReport_Accounts
WHERE	Company = 'IMCC' -- AND Intercompany = 'GLSO'

INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('AIS','0 - 10 - 2100','Intercompany Payable - IILS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('AIS','0 - 70 - 2100','Intercompany Payable - RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('AIS','0 - 10 - 1100','Intercompany Receivable-IILS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('AIS','0 - 70 - 1100','Intercompany Receivable - RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('AIS','0 - 20 - 1100','Intercompany Receivable - GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('AIS','0 - 07 - 1100','Intercompany Receivable - DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('AIS','0 - 07 - 2100','Intercompany Payable - DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('AIS','0 - 20 - 2100','Intercompany Payable - GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('AIS','0 - 90 - 1100','Intercompany Receivable - IGS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('AIS','0 - 33 - 1100','Intercompany Rec from PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('AIS','0 - 33 - 2100','Intercompany Pay to PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('AIS','0 - 15 - 1100','Intercompany Receivable - OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('AIS','0 - 40 - 1100','Intercompany Receivable - IMC')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('AIS','0 - 15 - 2100','Intercompany Payable - OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('AIS','0 - 31 - 1100','Intercompany Rec from PTS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('AIS','0 - 31 - 2100','Intercompany Pay to PTS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('AIS','0 - 90 - 2100','Interco Payable to IGS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('AIS','0 - 45 - 2100','Intercompany Payable - HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('AIS','0 - 45 - 1100','Intercompany Receivable - HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('AIS','0 - 40 - 2100','Intercompany Payable - IMC')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('AIS','0 - 80 - 2100','Intercompany Payable - IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('AIS','0 - 80 - 1100','Intercompany Receivable - IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('DNJ','0 - 10 - 1100','Intercompany Receivable - IILS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('DNJ','0 - 10 - 2100','Intercompany Payable - IILS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('DNJ','0 - 07 - 1100','Intercompany Receivable - IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('DNJ','0 - 07 - 2100','Intercompany Payable - IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('DNJ','0 - 70 - 1100','Intercompany Receivable - RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('DNJ','0 - 70 - 2100','Intercompany Payable - RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('DNJ','0 - 80 - 1100','Intercompany Receivable - IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('DNJ','0 - 80 - 2100','Intercompany Payable - IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('DNJ','0 - 40 - 2100','Intercompany Payable - AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('DNJ','0 - 90 - 2100','Intercompany Payable - IGS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('DNJ','0 - 45 - 1100','Intercompany Receivable - H&M Intermodal')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('DNJ','0 - 45 - 2100','Intercompany Payable - H&M Intermodal')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('DNJ','0 - 31 - 1100','Intercompany Receivable - PTS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('DNJ','0 - 31 - 2100','Intercompany Payable - PTS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('DNJ','0 - 20 - 1100','Intercompany Receivable - GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('DNJ','0 - 20 - 2100','Intercompany Payable - GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('DNJ','0 - 90 - 1100','Intercompany Receivable - IGS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('DNJ','0 - 15 - 1100',' Intercompany Receivable - OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('DNJ','0 - 15 - 2100',' Intercompany Payable - OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('DNJ','0 - 40 - 1100','Intercompany Receivable - AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('DNJ','0 - 33 - 1100','Intercompany Receivable - PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('DNJ','0 - 33 - 2100','Intercompany Payable - PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GIS','0 - 33 - 2100','Intercompany Pay to PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GIS','0 - 33 - 1100','Intercompany Rec from PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GIS','0 - 10 - 1100','Intercompany Receivable - IILS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GIS','0 - 40 - 1100','Intercompany Receivable - AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GIS','0 - 70 - 1100','Intercompany Receivable - RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GIS','0 - 10 - 2100','Intercompany Payable - IILS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GIS','0 - 40 - 2100','Intercompany Payable - AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GIS','0 - 70 - 2100','Intercompany Payable - RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GIS','0 - 80 - 1100','Intercompany Receivable - IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GIS','0 - 80 - 2100','Intercompany Payable - IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GIS','0 - 20 - 1100','Intercompany Receivable - IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GIS','0 - 20 - 2100','Intercompany Payable - IMC')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GIS','0 - 07 - 2100','Intercompany Payable - DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GIS','0 - 07 - 1100','Intercompany Receivable - DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GIS','0 - 90 - 1100','Intercompany Receivable - IGS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GIS','0 - 90 - 2100','Intercompany Payable - IGS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GIS','0 - 15 - 1100','Intercompany Rec from OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GIS','0 - 15 - 2100','Intercompany Pay to OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GIS','0 - 31 - 1100','Intercompany Rec from PTS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GIS','0 - 31 - 2100','Intercompany Pay to PTS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GIS','0 - 45 - 1100','Intercompany Receivable - HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GIS','0 - 45 - 2100','Intercompany Payable - HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GLSO','0 - 33 - 1100','Intercompany Receivable - PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GLSO','0 - 33 - 2100','Intercompany Payable - PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GLSO','0 - 70 - 2100','Intercompany Pyable - RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GLSO','0 - 70 - 1100','Intercompany Receivable - RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GLSO','0 - 80 - 2100','Intercompany Payable - IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GLSO','0 - 80 - 1100','Intercompany Receivable - IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GLSO','0 - 07 - 1100','Intercompany Receivable - DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GLSO','0 - 07 - 2100','Intercompany Payable - DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GLSO','0 - 10 - 1100','Intercompany Receivable - IILS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GLSO','0 - 10 - 2100','Intercompany Payable - IILS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GLSO','0 - 20 - 1100','Intercompany Receivable - GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GLSO','0 - 20 - 2100','Intercompany Payable - GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GLSO','0 - 40 - 1100','Intercompany Receivable - AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GLSO','0 - 40 - 2100','Intercompany Payable - AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GLSO','0 - 90 - 1100','Intercompany Receivable - IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GLSO','0 - 90 - 2100','Intercompany Payable - IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GLSO','0 - 15 - 1100','Intercompany Receivable - OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GLSO','0 - 15 - 2100','Intercompany Payable - OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GLSO','0 - 31 - 1100','Intercompany Receivable - PTS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GLSO','0 - 31 - 2100','Intercompany Payable - PTS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GLSO','0 - 45 - 1100',' Intercompany Receivable - H&M Intermodal Services')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GLSO','0 - 45 - 2100','Intercompany Payable - H&M Intermodal Services')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GSA','0 - 07 - 1100','Intercompany Receivable - DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GSA','0 - 07 - 2100','Intercompany Payable - DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GSA','0 - 10 - 1100','Intercompany Receivable - IILS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GSA','0 - 10 - 2100','Intercompany Payable - IILS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GSA','0 - 20 - 1100','Intercompany Receivable - GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GSA','0 - 20 - 2100','Intercompany Payable - GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GSA','0 - 40 - 1100','Intercompany Receivable - AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GSA','0 - 40 - 2100','Intercompany Payable - AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GSA','0 - 80 - 1100','Intercompany Receivable - IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GSA','0 - 80 - 2100','Intercompany Payable - IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GSA','0 - 31 - 1100','Intercompany Receivable - PTS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GSA','0 - 31 - 2100','Intercompany Payable - PTS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GSA','0 - 33 - 1100','Intercompany Receivable - PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GSA','0 - 33 - 1200','Intercompany Payable - PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GSA','0 - 70 - 1100','Intercompany Receivable - RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GSA','0 - 70 - 1200','Intercompany Payable - RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GSA','0 - 90 - 1100','Intercompany Receivable - IGS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GSA','0 - 90 - 2100','Intercompany Payable - IGS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GSA','0 - 45 - 1100','Intercompany Receivable - H&M')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GSA','0 - 45 - 2100','Intercompany Payable - H&M')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GSA','0 - 15 - 1100','Intercompany Receivable - OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('GSA','0 - 15 - 2100','Intercompany Payable - OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('HMIS','0 - 45 - 1100','Intercompany Receivable - IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('HMIS','0 - 45 - 2100','Intercomapny Payable - IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('HMIS','0 - 07 - 1100','Intercompany Receivable - DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('HMIS','0 - 10 - 1100','Intercompany Receivable-IILS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('HMIS','0 - 15 - 1100','Intercompany Receivable - OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('HMIS','0 - 20 - 1100','Intercompany Receivable - GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('HMIS','0 - 31 - 1100','Intercompany Rec from PTS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('HMIS','0 - 40 - 1100','Intercompany Receivable - AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('HMIS','0 - 70 - 1100','Intercompany Receivable - RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('HMIS','0 - 80 - 1100','Intercompany Receivable - IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('HMIS','0 - 90 - 1100','Intercompany Receivable - IGS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('HMIS','0 - 07 - 2100','Intercompany Payable - DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('HMIS','0 - 10 - 2100','Intercompany Payable - IILS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('HMIS','0 - 15 - 2100','Intercompany Payable - OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('HMIS','0 - 20 - 2100','Intercompany Payable - GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('HMIS','0 - 31 - 2100','Intercompany Pay to PTS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('HMIS','0 - 40 - 2100','Intercompany Payable - AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('HMIS','0 - 70 - 2100','Intercompany Payable - RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('HMIS','0 - 80 - 2100','Intercompany Payable - IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('HMIS','0 - 90 - 2100','Intercompany Payable to IGS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('HMIS','0 - 33 - 2100','Intercompany Payable - PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('HMIS','0 - 33 - 1100','Intercompany Receivable - PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCC','0 - 20 - 1100','Receivable from ABS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCC','0 - 20 - 2100','Payable to ABS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCC','0 - 70 - 2100','Payable to RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCC','0 - 80 - 1100','Receivable from IMC Company')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCC','0 - 07 - 1100','Receivable from DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCC','0 - 80 - 2100','Payable to IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCC','0 - 40 - 1100','Receivable from AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCC','0 - 70 - 1100','Receivable from RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCC','0 - 10 - 1100','Receivable from IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCC','0 - 40 - 2100','Payables to AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCC','0 - 10 - 2100','Payable to IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCC','0 - 90 - 1100','Receivable from IMC Global Solutions')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCC','0 - 45 - 1100','Receivable from H&M')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCC','0 - 45 - 2100','Payable to H&M')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCC','0 - 90 - 2100','Intercompany Payable to IGS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCC','0 - 15 - 1100','Receivable from OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCC','0 - 15 - 2100','Payable to OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCC','0 - 31 - 1100','Receivable from PTS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCC','0 - 31 - 2100','Payable to PTS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCC','0 - 07 - 2100','Payable to DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCC','0 - 33 - 1100','Receivable from PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCC','0 - 33 - 2100','Payable to PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMC','0 - 07 - 1100','Intercompany Receivable - DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMC','0 - 07 - 2100','Intercompany Payable - DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMC','0 - 10 - 1100','Intercompany Receivable - IILS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMC','0 - 10 - 2100','Intercompany Payable - IILS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMC','0 - 15 - 1100','Intercompany Receivable - OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMC','0 - 15 - 2100','Intercompany Payable - OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMC','0 - 20 - 1100','Intercompany Receivable - GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMC','0 - 20 - 2100','Intercompany Payable - GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMC','0 - 31 - 1100','Intercompany Receivable - PTS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMC','0 - 31 - 2100','Intercompany Payable - PTS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMC','0 - 33 - 1100','Intercompany Receivable - PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMC','0 - 33 - 2100','Intercompany Payable - PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMC','0 - 40 - 1100','Intercompany Receivable - AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMC','0 - 40 - 2100','Intercompany Payable - AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMC','0 - 45 - 1100','Intercompany Receivable - H&M Intermodal')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMC','0 - 45 - 2100','Intercompany Payables - H&M Intermodal')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMC','0 - 70 - 1100','Intercompany Receivable - RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMC','0 - 70 - 2100','Intercompany Payable - RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMC','0 - 80 - 1100','Intercompany Receivable - IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMC','0 - 80 - 2100','Intercompany Payable-IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMC','0 - 90 - 1100','Intercompany Receivable - IMCGlobal')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMC','0 - 90 - 2100','Intercompany Payable - IMC Global')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCH','0 - 80 - 1100','Intercompany Receivable - IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCH','0 - 80 - 2100','Intercompany Payable - IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCH','0 - 40 - 2100','Intercompany Payable - AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCH','0 - 40 - 1100','Intercompany Receivable - AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCH','0 - 20 - 1100','Intercompany Receivable - GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCH','0 - 20 - 2100','Intercompany Payable - GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCH','0 - 07 - 1100','Intercompany Receivable - DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCH','0 - 07 - 2100','Intercompany Payable - DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCH','0 - 90 - 2100','Intercompany Payable - IGS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCH','0 - 15 - 2100','Intercompany Payable - OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCH','0 - 15 - 1100','Intercompany Receivable - OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCH','0 - 31 - 1100','Intercompany Receivable - PTS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCH','0 - 31 - 2100','Intercompany Payable - PTS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCH','0 - 45 - 1100','Intercompany Receivable - H&M')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCH','0 - 45 - 2100','Intercompany Payable - H&M')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCH','0 - 10 - 1100','Intercompany Receivable - ILS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCH','0 - 70 - 1100','Intercompany Receivable - RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCH','0 - 70 - 2100','Intercompany Payable - RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCH','0 - 10 - 2100','Intercompany Payable - IILS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCH','0 - 90 - 1100','Intercompany Receivable - IGS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCH','0 - 33 - 1100','Intercompany Receivable - PDS, LLC')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('IMCH','0 - 33 - 2100','Intercompany Payable - PDS, LLC')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('OIS','0 - 07 - 1100','Intercompany Receivable - DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('OIS','0 - 07 - 2100','Intercompany Payable - DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('OIS','0 - 10 - 1100','Intercompany Receivable - IILS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('OIS','0 - 10 - 2100','Intercompany Payable - IILS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('OIS','0 - 20 - 1100','Intercompany Receivable - GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('OIS','0 - 20 - 2100','Intercompany Payable - GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('OIS','0 - 40 - 1100','Intercompany Receivable - AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('OIS','0 - 40 - 2100','Intercompany Payable - AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('OIS','0 - 70 - 1100','Intercompany Receivable - RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('OIS','0 - 70 - 2100','Intercompany Payable - RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('OIS','0 - 80 - 1100','Intercompany Receivable - IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('OIS','0 - 80 - 2100','Intercompany Payable - IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('OIS','0 - 90 - 1100','Intercompany Receivable - IGS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('OIS','0 - 90 - 2100','Intercompany Payable - IGS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('OIS','0 - 15 - 1100','Intercompany Receivable - IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('OIS','0 - 15 - 2100','Intercompany Payable - IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('OIS','0 - 45 - 1100','Intercompany Receivable - HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('OIS','0 - 45 - 2100','Intercompany Payable - HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('OIS','0 - 31 - 1100','Intercompany Receivable - PTS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('OIS','0 - 31 - 2100','Intercompany Payable - PTS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('OIS','0 - 33 - 1100','Intercompany Receivable - PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('OIS','0 - 33 - 2100','Intercompany Payable - PDS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('PDS','0 - 07 - 1100','Intercompany Receivable - DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('PDS','0 - 10 - 1100','Intercompany Receivable - IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('PDS','0 - 15 - 1100','Intercompany Rec from OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('PDS','0 - 20 - 1100','Intercompany Receivable - GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('PDS','0 - 31 - 1100','Intercompany Receivable - PTS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('PDS','0 - 40 - 1100','Intercompany Receivable - AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('PDS','0 - 45 - 1100','Intercompany Receivable - HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('PDS','0 - 70 - 1100','Intercompany Receivable - RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('PDS','0 - 80 - 1100','Intercompany Receivable - IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('PDS','0 - 90 - 1100','Intercompany Receivable - IGS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('PDS','0 - 07 - 2100','Intercompany Payable - DNJ')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('PDS','0 - 10 - 2100','Intercompany Payable - IMCC')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('PDS','0 - 15 - 2100','Intercompany Pay to OIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('PDS','0 - 20 - 2100','Intercompany Payable - GIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('PDS','0 - 31 - 2100','Intercompany Payable - PTS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('PDS','0 - 40 - 2100','Intercompany Payable - AIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('PDS','0 - 45 - 2100','Intercompany Payable - HMIS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('PDS','0 - 70 - 2100','Intercompany Payable - RCCL')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('PDS','0 - 80 - 2100','Intercompany Payable - IMCH')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('PDS','0 - 90 - 2100','Intercompany Payable - IGS')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('PDS','0 - 33 - 1100','Intercompany Receivable - IMCG')
INSERT INTO IntercompanyReport_Accounts (Company, Account, Description) VALUES ('PDS','0 - 33 - 2100','Intercompany Payable - IMCG')

 ---- TRUNCATE TABLE IntercompanyReport_Accounts