SELECT	HDR.CSHRCTYP,
		HDR.CUSTNMBR,
		HDR.CPRCSTNM,
		HDR.BACHNUMB,
		HDR.DOCNUMBR,
		CAST(HDR.DOCDATE AS Date) AS DOCDATE,
		CAST(HDR.POSTDATE AS Date) AS POSTDATE,
		HDR.PSTUSRID,
		CAST(HDR.ORTRXAMT AS Numeric(10,2)) AS ORTRXAMT,
		HDR.TRXDSCRN,
		HDR.FRTSCHID,
		HDR.MSCSCHID,
		HDR.NOTEINDX,
		DET.DISTTYPE,
		DET.SEQNUMBR,
		GLA.ACTNUMST,
		CAST(DET.DEBITAMT AS Numeric(10,2)) AS DEBITAMT,
		CAST(DET.CRDTAMNT AS Numeric(10,2)) AS CRDTAMNT,
		DET.DistRef,
		APL.APPTOAMT,
		APL.APTODCNM,
		APL.ApplyToGLPostDate,
		ISNULL(TRN.TXTFIELD,'') AS Note
FROM	RM30101 HDR
		INNER JOIN RM30301 DET ON HDR.DOCNUMBR = DET.DOCNUMBR AND HDR.TRXSORCE = DET.TRXSORCE
		INNER JOIN GL00105 GLA ON DET.DSTINDX = GLA.ACTINDX
		LEFT JOIN RM30201 APL ON HDR.CUSTNMBR = APL.CUSTNMBR AND HDR.DOCNUMBR = APL.APFRDCNM
		LEFT JOIN SY03900 TRN ON HDR.NOTEINDX = TRN.NOTEINDX
WHERE	HDR.BACHNUMB = '010719LOCKBOX1'
ORDER BY
		HDR.DOCNUMBR,
		DET.SEQNUMBR

-- SELECT * FROM RM30101 WHERE DOCDATE > '01/01/2019' ORDER BY BACHNUMB