--INSERT INTO IV00101 (ITEMNMBR, ITEMDESC, ITMCLSCD, DECPLQTY)
--SELECT	DISTINCT FIPartNo,
--		Description,
--		'INVENTORY',
--		0
--FROM	GPCustom.dbo.Martec
--WHERE	FIPartNo NOT IN (SELECT ITEMNMBR FROM IV00101)

INSERT INTO IV00103 (ITEMNMBR, VENDORID, VNDITNUM)
SELECT	RTRIM(FIPartNo),
		'206',
		RTRIM(VendorPartNo)
FROM	GPCustom.dbo.Martec
WHERE	FIPartNo IN (SELECT ITEMNMBR FROM IV00101)
		AND FIPartNo NOT IN (SELECT ITEMNMBR FROM IV00103)

UPDATE	IV00101
SET		DECPLQTY = 1,
		DECPLCUR = 2,
		ITMGEDSC = '',
		ITMTRKOP = 1,
		ITEMTYPE = 1,
		TAXOPTNS = 3,
		IVIVINDX = 112,
		UOMSCHDL = 'EACH',
		USCATVLS_1 = '',
		PRCLEVEL = 'RETAIL',
		PRICEGROUP = '',
		VCTNMTHD = 1,
		MSTRCDTY = 1,
		ABCCODE = 1,
		Revalue_Inventory = 1,
		Purchase_Tax_Options = 1,
		ITMPLNNNGTYP = 1
WHERE	ITMCLSCD = 'INVENTORY'
		AND DECPLQTY = 1
