SELECT	CND.*,
		ISNULL(PMH.DOCNUMBR,PM2.DOCNUMBR) AS DOCNUMBR,
		ISNULL(PMH.DOCDATE,PM2.DOCDATE) AS DOCDATE,
		CAST(ISNULL(PMH.POSTEDDT,PM2.POSTEDDT) AS Date) AS POSTEDDT,
		DEBIT_ACCT = ISNULL((SELECT ACTNUMST FROM GL00105 WHERE ACTINDX = (SELECT TOP 1 DSTINDX FROM PM30600 PM6 WHERE PM6.VENDORID = PM2.VENDORID AND PM6.VCHRNMBR = PM2.VCHRNMBR AND PM6.DEBITAMT > 0)), (SELECT ACTNUMST FROM GL00105 WHERE ACTINDX = (SELECT TOP 1 DSTINDX FROM PM30600 PM6 WHERE PM6.VENDORID = PMH.VENDORID AND PM6.VCHRNMBR = PMH.VCHRNMBR AND PM6.DEBITAMT > 0))),
		CREDIT_ACCT = ISNULL((SELECT ACTNUMST FROM GL00105 WHERE ACTINDX = (SELECT TOP 1 DSTINDX FROM PM30600 PM6 WHERE PM6.VENDORID = PM2.VENDORID AND PM6.VCHRNMBR = PM2.VCHRNMBR AND PM6.DEBITAMT = 0)), (SELECT ACTNUMST FROM GL00105 WHERE ACTINDX = (SELECT TOP 1 DSTINDX FROM PM30600 PM6 WHERE PM6.VENDORID = PMH.VENDORID AND PM6.VCHRNMBR = PMH.VCHRNMBR AND PM6.DEBITAMT = 0))),
		FIP.GP_Period
FROM	GPCustom.dbo.tmpMary_CNDs CND
		LEFT JOIN PM20000 PMH ON CND.Vendor_Code = PMH.VendorId AND CND.Reference = PMH.DOCNUMBR --OR PMH.DOCNUMBR LIKE (LEFT(CND.Reference, LEN(RTRIM(CND.Reference)) - IIF(LEN(RTRIM(CND.Reference)) > 15, 3, 0)) + '%'))
		LEFT JOIN PM30200 PM2 ON CND.Vendor_Code = PM2.VendorId AND CND.Reference = PM2.DOCNUMBR --OR PM2.DOCNUMBR LIKE (LEFT(CND.Reference, LEN(RTRIM(CND.Reference)) - IIF(LEN(RTRIM(CND.Reference)) > 15, 3, 0)) + '%'))
		LEFT JOIN DYNAMICS.dbo.View_FiscalPeriod FIP ON ISNULL(PMH.POSTEDDT,PM2.POSTEDDT) BETWEEN FIP.StartDate AND FIP.EndDate
WHERE	CND.IntegrationType = 'FSIP' 
UNION
SELECT	CND.*,
		ISNULL(GLO.REFRENCE,GLH.REFRENCE) AS DOCNUMBR,
		CAST(ISNULL(GLO.TRXDATE,GLH.TRXDATE) AS Date) AS TRXDATE,
		CAST(ISNULL(GLO.TRXDATE,GLH.TRXDATE) AS Date) AS POSTEDDT,
		DEBIT_ACCT = ISNULL((SELECT ACTNUMST FROM GL00105 WHERE ACTINDX = (SELECT TOP 1 ACTINDX FROM GL20000 GL2 WHERE GL2.SEQNUMBR IN (1000, 16384) AND (GL2.DEBITAMT + GL2.CRDTAMNT) = CND.Amount AND (CND.Reference = GL2.Refrence OR GL2.Refrence LIKE ('PN:' + RTRIM(CND.DivPro) + '%')))), (SELECT ACTNUMST FROM GL00105 WHERE ACTINDX = (SELECT TOP 1 ACTINDX FROM GL30000 GL2 WHERE GL2.SEQNUMBR IN (1000, 16384) AND (GL2.DEBITAMT + GL2.CRDTAMNT) = CND.Amount AND (CND.Reference = GL2.Refrence OR GL2.Refrence LIKE ('PN:' + RTRIM(CND.DivPro) + '%'))))),
		CREDIT_ACCT = ISNULL((SELECT ACTNUMST FROM GL00105 WHERE ACTINDX = (SELECT TOP 1 ACTINDX FROM GL20000 GL2 WHERE GL2.SEQNUMBR IN (2000, 32768) AND (GL2.DEBITAMT + GL2.CRDTAMNT) = CND.Amount AND (CND.Reference = GL2.Refrence OR GL2.Refrence LIKE ('PN:' + RTRIM(CND.DivPro) + '%')))), (SELECT ACTNUMST FROM GL00105 WHERE ACTINDX = (SELECT TOP 1 ACTINDX FROM GL30000 GL2 WHERE GL2.SEQNUMBR IN (2000, 32768) AND (GL2.DEBITAMT + GL2.CRDTAMNT) = CND.Amount AND (CND.Reference = GL2.Refrence OR GL2.Refrence LIKE ('PN:' + RTRIM(CND.DivPro) + '%'))))),
		GP_Period = (SELECT GP_Period FROM DYNAMICS.dbo.View_FiscalPeriod FIP WHERE ISNULL(GLO.TRXDATE,GLH.TRXDATE) BETWEEN FIP.StartDate AND FIP.EndDate)
FROM	GPCustom.dbo.tmpMary_CNDs CND
		LEFT JOIN GL20000 GLO ON GLO.SEQNUMBR IN (1000, 16384) AND (GLO.DEBITAMT + GLO.CRDTAMNT) = CND.Amount AND (CND.Reference = GLO.Refrence OR GLO.Refrence LIKE ('PN:' + RTRIM(CND.DivPro) + '%'))
		LEFT JOIN GL30000 GLH ON GLH.SEQNUMBR IN (1000, 16384) AND (GLH.DEBITAMT + GLH.CRDTAMNT) = CND.Amount AND (CND.Reference = GLH.Refrence OR GLH.Refrence LIKE ('PN:' + RTRIM(CND.DivPro) + '%'))
WHERE	CND.IntegrationType = 'FSIG' 

/*
SELECT	TOP 100 *
FROM	PM30600
WHERE	DOCNUMBR LIKE 'DFSU6639693/96124%'

SELECT	*
FROM	DYNAMICS.dbo.View_FiscalPeriod
*/

--SELECT ACTNUMST FROM GL00105 WHERE ACTINDX = 