/*
DROP TABLE tmpGL30000
DROP TABLE tmpGL20000

SELECT	DEBITAMT, CRDTAMNT, Refrence, TRXDATE, SEQNUMBR, GL3.ACTINDX, GP_Period, RTRIM(ACTNUMST) AS ACTNUMST, JRNENTRY
INTO	tmpGL30000
FROM	GL30000 GL3
		LEFT JOIN DYNAMICS.dbo.View_FiscalPeriod FIP ON TRXDATE BETWEEN FIP.StartDate AND FIP.EndDate
		LEFT JOIN GL00105 GL5 ON GL3.ACTINDX = GL5.ACTINDX
WHERE	TRXDATE >= '01/01/2020' 
		AND SOURCDOC = 'GJ'
		AND VOIDED = 0

SELECT	DEBITAMT, CRDTAMNT, Refrence, TRXDATE, SEQNUMBR, GL3.ACTINDX, GP_Period, RTRIM(ACTNUMST) AS ACTNUMST, JRNENTRY
INTO	tmpGL20000
FROM	GL20000 GL3
		LEFT JOIN DYNAMICS.dbo.View_FiscalPeriod FIP ON TRXDATE BETWEEN FIP.StartDate AND FIP.EndDate
		LEFT JOIN GL00105 GL5 ON GL3.ACTINDX = GL5.ACTINDX
WHERE	SOURCDOC = 'GJ'
		AND VOIDED = 0

CREATE INDEX IX_tmpGL20000_Refrence ON tmpGL20000 (Refrence)
CREATE INDEX IX_tmpGL30000_Refrence ON tmpGL30000 (Refrence)

CREATE INDEX IX_tmpGL20000_SEQNUMBR ON tmpGL20000 (SEQNUMBR)
CREATE INDEX IX_tmpGL30000_SEQNUMBR ON tmpGL30000 (SEQNUMBR)

CREATE INDEX IX_tmpGL20000_DEBITAMT ON tmpGL20000 (DEBITAMT)
CREATE INDEX IX_tmpGL30000_DEBITAMT ON tmpGL30000 (DEBITAMT)

CREATE INDEX IX_tmpGL20000_CRDTAMNT ON tmpGL20000 (CRDTAMNT)
CREATE INDEX IX_tmpGL30000_CRDTAMNT ON tmpGL30000 (CRDTAMNT)
*/

SELECT	DISTINCT CND.*,
		ISNULL(GLO.REFRENCE,GLH.REFRENCE) AS DOCNUMBR,
		CAST(ISNULL(GLO.TRXDATE,GLH.TRXDATE) AS Date) AS TRXDATE,
		CAST(ISNULL(GLO.TRXDATE,GLH.TRXDATE) AS Date) AS POSTEDDT,
		DEBIT_ACCT = ISNULL(GLO.ACTNUMST, GLH.ACTNUMST),
		CREDIT_ACCT = ISNULL((SELECT TOP 1 GL2.ACTNUMST FROM tmpGL20000 GL2 WHERE GL2.CRDTAMNT = ABS(CND.Amount) AND CND.Reference = GL2.Refrence), (SELECT TOP 1 ACTNUMST FROM tmpGL30000 GL2 WHERE GL2.CRDTAMNT = ABS(CND.Amount) AND CND.Reference = GL2.Refrence)),
		ISNULL(GLO.GP_Period,GLH.GP_Period) AS GP_Period,
		ISNULL(GLO.JRNENTRY, GLH.JRNENTRY) AS JRNENTRY
FROM	GPCustom.dbo.tmpMary_CNDs CND
		LEFT JOIN tmpGL20000 GLO ON GLO.DEBITAMT = ABS(CND.Amount) AND CND.Reference = GLO.Refrence --OR GLO.Refrence LIKE ('PN:' + RTRIM(CND.DivPro) + '%'))
		LEFT JOIN tmpGL30000 GLH ON GLH.DEBITAMT = ABS(CND.Amount) AND CND.Reference = GLH.Refrence --OR GLH.Refrence LIKE ('PN:' + RTRIM(CND.DivPro) + '%'))
WHERE	CND.[Previous] = 0
		AND CND.IntegrationType = 'FSIG' 
		--AND REFERENCE = 'D96-105972|TEMU540784'

--DROP TABLE tmpGL20000
--DROP TABLE tmpGL30000