SELECT * FROM (

SELECT HDR.DOCNUMBR AS InvoiceNumber,
       HDR.CUSTNMBR AS bill_to_id,
       HDR.CUSTNMBR AS customer_id,
       HDR.CUSTNMBR AS shipper_id,
       HDR.DOCDATE  AS invoice_date,
       HDR.ORTRXAMT AS InvoiceAmount,
       HDR.CURTRXAM AS Balance,
       HDR.TRXDSCRN AS Description,
       HDR.BACHNUMB AS BatchId,
       ACT.ACTNUMST,
		ACT.ACTNUMBR_3,
		DET.DEBITAMT,
        DET.CRDTAMNT,
		DET.DistRef,
		'OPEN' AS SourceTable
FROM   RM20101 HDR
		INNER JOIN RM10101 DET ON HDR.DOCNUMBR = DET.DOCNUMBR
		INNER JOIN GL00105 ACT ON DET.DSTINDX = ACT.ACTINDX
WHERE  ACT.ACTNUMBR_3 BETWEEN '4010' AND '4033' AND 
       HDR.DOCDATE BETWEEN '04/29/2018'  AND '06/02/2018' AND 
          HDR.VOIDSTTS = 0 
UNION
SELECT  HDR.DOCNUMBR AS InvoiceNumber,
       HDR.CUSTNMBR AS bill_to_id,
       HDR.CUSTNMBR AS customer_id,
       HDR.CUSTNMBR AS shipper_id,
       HDR.DOCDATE  AS invoice_date,
       HDR.ORTRXAMT AS InvoiceAmount,
       HDR.CURTRXAM AS Balance,
       HDR.TRXDSCRN AS Description,
       HDR.BACHNUMB AS BatchId,
       ACT.ACTNUMST,
          ACT.ACTNUMBR_3, 
       DET.DEBITAMT,
          DET.CRDTAMNT,
       DET.DistRef,
      'HISTORY' AS SourceTable
FROM   RM30101 HDR
              INNER JOIN RM30301 DET ON HDR.DOCNUMBR = DET.DOCNUMBR
              INNER JOIN GL00105 ACT ON DET.DSTINDX = ACT.ACTINDX
WHERE  ACT.ACTNUMBR_3 BETWEEN '4010' AND '4033'
              AND HDR.DOCDATE BETWEEN '04/29/2018'  AND '06/02/2018'
        AND HDR.VOIDSTTS = 0      
) AS DATA
WHERE DISTREF LIKE '0011683-1%'
or DISTREF LIKE '0011689-4%'

--SELECT	*
--FROM	GL20000
--WHERE	JRNENTRY = 154780

--SELECT	*
--FROM	GL00105
--WHERE	ACTINDX = 455