SELECT	HDR.DOCNUMBR AS InvoiceNumber,
		HDR.CUSTNMBR AS CustomerNumber,
		HDR.DOCDATE AS InvoiceDate,
		HDR.ORTRXAMT AS InvoiceAmount,
		HDR.CURTRXAM AS Balance,
		HDR.TRXDSCRN AS Description,
		HDR.BACHNUMB AS BatchId,
		ACT.ACTNUMST AS GLAccount,
		DET.DEBITAMT AS Debit,
		DET.CRDTAMNT AS Credit,
		DET.DistRef AS Reference,
		'OPEN' AS SourceTable
FROM	RM20101 HDR
		INNER JOIN RM10101 DET ON HDR.DOCNUMBR = DET.DOCNUMBR
		INNER JOIN GL00105 ACT ON DET.DSTINDX = ACT.ACTINDX
WHERE	ACT.ACTNUMBR_3 BETWEEN '4010' AND '4033'
		AND HDR.DOCDATE BETWEEN '04/29/2018'  AND '06/02/2018'
        AND HDR.VOIDSTTS = 0
UNION
SELECT	HDR.DOCNUMBR AS InvoiceNumber,
		HDR.CUSTNMBR AS CustomerNumber,
		HDR.DOCDATE AS InvoiceDate,
		HDR.ORTRXAMT AS InvoiceAmount,
		HDR.CURTRXAM AS Balance,
		HDR.TRXDSCRN AS Description,
		HDR.BACHNUMB AS BatchId,
		ACT.ACTNUMST AS GLAccount,
		DET.DEBITAMT AS Debit,
		DET.CRDTAMNT AS Credit,
		DET.DistRef AS Reference,
		'HISTORY' AS SourceTable
FROM	RM30101 HDR
		INNER JOIN RM10101 DET ON HDR.DOCNUMBR = DET.DOCNUMBR
		INNER JOIN GL00105 ACT ON DET.DSTINDX = ACT.ACTINDX
WHERE	ACT.ACTNUMBR_3 BETWEEN '4010' AND '4033'
		AND HDR.DOCDATE BETWEEN '04/29/2018'  AND '06/02/2018'
        AND HDR.VOIDSTTS = 0
ORDER BY HDR.DOCNUMBR

SELECT	TOP 100 *
FROM	RM10101

SELECT	*
FROM	GL20000
WHERE	JRNENTRY = 156933

SELECT * FROM GL00105 WHERE ACTINDX = 456

SELECT AR.CUSTNMBR,
        AR.DOCNUMBR AS Invoice,
        AR.DOCDATE  AS Invoice_Date, 
        AR.ORTRXAMT,
        AR.TRXDSCRN AS Description,
        AR.BACHNUMB
FROM   RM20101 AR
WHERE  AR.DOCDATE BETWEEN '04/29/2018'  AND '06/02/2018' AND 
        AR.VOIDSTTS = 0 AND
LEFT(AR.BACHNUMB, 2) = 'IA'
UNION
SELECT AR.CUSTNMBR,
        AR.DOCNUMBR AS Invoice,
        AR.DOCDATE  AS Invoice_Date, 
        AR.ORTRXAMT,
        AR.TRXDSCRN AS Description,
        AR.BACHNUMB
FROM   RM30101 AR
WHERE  AR.DOCDATE BETWEEN '04/29/2018' AND '06/02/2018' AND
        AR.VOIDSTTS = 0 AND
LEFT(AR.BACHNUMB, 2) = 'IA'
ORDER BY Invoice
