DECLARE	@DateIni	Date = '05/05/2018',
		@DateEnd	Date = '06/02/2018'

-- SUMMARY
--SELECT	ACTNUMST,
--		ACTDESCR,
--		DEBITAMT - CRDTAMNT AS AMOUNT
--FROM	(
--		SELECT	G5.ACTNUMST,
--				G1.ACTDESCR,
--				SUM(DEBITAMT) AS DEBITAMT,
--				SUM(CRDTAMNT) AS CRDTAMNT
--		FROM	GL20000 GL
--				INNER JOIN GL00100 G1 ON GL.ACTINDX = G1.ACTINDX AND G1.ACTNUMBR_3 BETWEEN '5010' AND '5019' AND G1.ACTNUMBR_2 IN ('08','11','13')
--				INNER JOIN GL00105 G5 ON GL.ACTINDX = G5.ACTINDX
--		WHERE	GL.VOIDED = 0
--				AND GL.TRXDATE BETWEEN @DateIni AND @DateEnd
--				AND LEFT(IIF(GL.ORTRXSRC = '', GL.TRXSORCE, GL.ORTRXSRC), 2) <> 'PM'
--		GROUP BY G5.ACTNUMST, G1.ACTDESCR
--		) DATA
--ORDER BY ACTNUMST

-- DETAILS
SELECT	G5.ACTNUMST,
		G1.ACTDESCR,
		CAST(GL.TRXDATE AS Date) AS TRXDATE,
		GL.REFRENCE,
		Manifest_Description = ISNULL((SELECT TOP 1 AP1.ReferenceNumber FROM LENSASQL002.Manifest.dbo.TransactionsAP AP1 INNER JOIN LENSASQL002.Manifest.dbo.TransactionsDetailsAP AP2 ON AP1.TransactionAPId = AP2.fk_TransactionAPId WHERE AP2.DocumentNumber = GL.ORDOCNUM AND AP2.ChargeAmount = GL.DEBITAMT),''),
		GL.ORMSTRID,
		GL.ORDOCNUM,
		GL.DEBITAMT,
		GL.CRDTAMNT,
		IIF(GL.ORTRXSRC = '', GL.TRXSORCE, GL.ORTRXSRC) AS ORTRXSRC,
		CASE WHEN LEFT(GL.ORTRXSRC,2) = 'PM' THEN 'AP' ELSE 'GL' END AS [Source]
FROM	GL20000 GL
		INNER JOIN GL00100 G1 ON GL.ACTINDX = G1.ACTINDX AND G1.ACTNUMBR_3 BETWEEN '5010' AND '5019' AND G1.ACTNUMBR_2 IN ('08','11','13')
		INNER JOIN GL00105 G5 ON GL.ACTINDX = G5.ACTINDX
WHERE	GL.VOIDED = 0
		AND GL.TRXDATE BETWEEN @DateIni AND @DateEnd
ORDER BY G5.ACTNUMST, GL.TRXDATE

-- select top 100 * from GL20000 where ORTRXSRC = 'PMTRX00006734'
-- SELECT TOP 100 * FROM PM20000