DECLARE	@DOCNUMBR	Varchar(30) = 'DRYU293461CRM'

BEGIN TRANSACTION

INSERT INTO [PM20000]
           ([VCHRNMBR]
           ,[VENDORID]
           ,[DOCTYPE]
           ,[DOCDATE]
           ,[DOCNUMBR]
           ,[DOCAMNT]
           ,[CURTRXAM]
           ,[DISTKNAM]
           ,[DISCAMNT]
           ,[DSCDLRAM]
           ,[BACHNUMB]
           ,[TRXSORCE]
           ,[BCHSOURC]
           ,[DISCDATE]
           ,[DUEDATE]
           ,[PORDNMBR]
           ,[TEN99AMNT]
           ,[WROFAMNT]
           ,[DISAMTAV]
           ,[TRXDSCRN]
           ,[UN1099AM]
           ,[BKTPURAM]
           ,[BKTFRTAM]
           ,[BKTMSCAM]
           ,[VOIDED]
           ,[HOLD]
           ,[CHEKBKID]
           ,[DINVPDOF]
           ,[PPSAMDED]
           ,[PPSTAXRT]
           ,[PGRAMSBJ]
           ,[GSTDSAMT]
           ,[POSTEDDT]
           ,[PTDUSRID]
           ,[MODIFDT]
           ,[MDFUSRID]
           ,[PYENTTYP]
           ,[CARDNAME]
           ,[PRCHAMNT]
           ,[TRDISAMT]
           ,[MSCCHAMT]
           ,[FRTAMNT]
           ,[TAXAMNT]
           ,[TTLPYMTS]
           ,[CURNCYID]
           ,[PYMTRMID]
           ,[SHIPMTHD]
           ,[TAXSCHID]
           ,[PCHSCHID]
           ,[FRTSCHID]
           ,[MSCSCHID]
           ,[PSTGDATE]
           ,[DISAVTKN]
           ,[CNTRLTYP]
           ,[NOTEINDX]
           ,[PRCTDISC]
           ,[RETNAGAM]
           ,[ICTRX]
           ,[Tax_Date]
           ,[PRCHDATE]
           ,[CORRCTN]
           ,[SIMPLIFD]
           ,[APLYWITH]
           ,[Electronic]
           ,[ECTRX]
           ,[DocPrinted]
           ,[TaxInvReqd]
           ,[VNDCHKNM]
           ,[BackoutTradeDisc]
           ,[CBVAT]
           ,[VADCDTRO])
SELECT	[VCHRNMBR]
		,[VENDORID]
		,[DOCTYPE]
		,[DOCDATE]
		,[DOCNUMBR]
		,[DOCAMNT]
		,[CURTRXAM]
		,[DISTKNAM]
		,[DISCAMNT]
		,[DSCDLRAM]
		,[BACHNUMB]
		,[TRXSORCE]
		,[BCHSOURC]
		,[DISCDATE]
		,[DUEDATE]
		,[PORDNMBR]
		,[TEN99AMNT]
		,[WROFAMNT]
		,[DISAMTAV]
		,[TRXDSCRN]
		,[UN1099AM]
		,[BKTPURAM]
		,[BKTFRTAM]
		,[BKTMSCAM]
		,[VOIDED]
		,[HOLD]
		,[CHEKBKID]
		,[DINVPDOF]
		,[PPSAMDED]
		,[PPSTAXRT]
		,[PGRAMSBJ]
		,[GSTDSAMT]
		,[POSTEDDT]
		,[PTDUSRID]
		,[MODIFDT]
		,'manual ' + REPLACE(CONVERT(Char(10), GETDATE(), 101), '/', '')
		,[PYENTTYP]
		,[CARDNAME]
		,[PRCHAMNT]
		,[TRDISAMT]
		,[MSCCHAMT]
		,[FRTAMNT]
		,[TAXAMNT]
		,[TTLPYMTS]
		,[CURNCYID]
		,[PYMTRMID]
		,[SHIPMTHD]
		,[TAXSCHID]
		,[PCHSCHID]
		,[FRTSCHID]
		,[MSCSCHID]
		,[PSTGDATE]
		,[DISAVTKN]
		,[CNTRLTYP]
		,[NOTEINDX]
		,[PRCTDISC]
		,[RETNAGAM]
		,[ICTRX]
		,[Tax_Date]
		,[PRCHDATE]
		,[CORRCTN]
		,[SIMPLIFD]
		,[APLYWITH]
		,[Electronic]
		,[ECTRX]
		,[DocPrinted]
		,[TaxInvReqd]
		,[VNDCHKNM]
		,[BackoutTradeDisc]
		,[CBVAT]
		,[VADCDTRO]
FROM	[PM30200]
WHERE	DOCNUMBR = @DOCNUMBR

INSERT INTO [PM10100]
           ([VCHRNMBR]
           ,[DSTSQNUM]
           ,[CNTRLTYP]
           ,[CRDTAMNT]
           ,[DEBITAMT]
           ,[DSTINDX]
           ,[DISTTYPE]
           ,[CHANGED]
           ,[USERID]
           ,[PSTGSTUS]
           ,[VENDORID]
           ,[TRXSORCE]
           ,[PSTGDATE]
           ,[INTERID]
           ,[CURNCYID]
           ,[CURRNIDX]
           ,[ORCRDAMT]
           ,[ORDBTAMT]
           ,[APTVCHNM]
           ,[APTODCTY]
           ,[SPCLDIST]
           ,[DistRef]
           ,[XCHGRATE]
           ,[EXCHDATE]
           ,[TIME1]
           ,[RTCLCMTD]
           ,[DECPLACS]
           ,[EXPNDATE]
           ,[ICCURRID]
           ,[ICCURRIX])
SELECT	[VCHRNMBR]
		,[DSTSQNUM]
		,[CNTRLTYP]
		,[CRDTAMNT]
		,[DEBITAMT]
		,[DSTINDX]
		,[DISTTYPE]
		,[CHANGED]
		,'manual ' + REPLACE(CONVERT(Char(10), GETDATE(), 101), '/', '')
		,[PSTGSTUS]
		,[VENDORID]
		,[TRXSORCE]
		,[PSTGDATE]
		,DB_NAME()
		,[CURNCYID]
		,[CURRNIDX]
		,[ORCRDAMT]
		,[ORDBTAMT]
		,[APTVCHNM]
		,[APTODCTY]
		,[SPCLDIST]
		,[DistRef],
		1,
		'01/01/1900',
		'01/01/1900',
		0,
		2,
		'01/01/1900',
		'USD2',
		1001
FROM	[PM30600]
WHERE	VCHRNMBR IN (SELECT VCHRNMBR FROM PM30200 WHERE	DOCNUMBR = @DOCNUMBR)

DELETE	[PM30600]
WHERE	VCHRNMBR IN (SELECT VCHRNMBR FROM PM30200 WHERE	DOCNUMBR = @DOCNUMBR)

DELETE	PM30200 
WHERE	DOCNUMBR = @DOCNUMBR

IF @@ERROR = 0
BEGIN
	COMMIT TRANSACTION
END
ELSE
BEGIN
	ROLLBACK TRANSACTION
END