USE ONESUPPORT_DBV2
GO 

SELECT	WKO.WORKORDERID AS TicketNo
		,CASE WHEN WST.STATUSID = 1 THEN 'OPEN' WHEN WST.STATUSID = 3 THEN 'CLOSED' ELSE 'RESOLVED' END AS [STATUS]
		,USR.FIRST_NAME
		,dbo.UnixDateTime(WKO.CREATEDTIME) AS CREATED_TIME
		,dbo.UnixDateTime(WST.ASSIGNEDTIME) AS ASSIGNED_TIME
		,WKO.Title
FROM	WorkOrder WKO 
		INNER JOIN WorkOrderStates WST ON WKO.WORKORDERID = WST.WORKORDERID
		INNER JOIN AaaUser USR ON WST.OWNERID = USR.USER_ID
WHERE	WST.OWNERID IN (715,29702,32150,75324, 146105)
		AND WST.STATUSID IN (1,3,4)
		AND dbo.UnixDateTime(ASSIGNEDTIME) > '12/01/2022'
		--WKO.WORKORDERID IN (471562)
ORDER BY 3,4

SELECT	USR.FIRST_NAME
		,CASE WHEN WST.STATUSID = 1 THEN 'OPEN' WHEN WST.STATUSID = 3 THEN 'CLOSED' ELSE 'RESOLVED' END AS [STATUS]
		,COUNT(*) AS Count
FROM	WorkOrder WKO
		INNER JOIN WorkOrderStates WST ON WKO.WORKORDERID = WST.WORKORDERID
		INNER JOIN AaaUser USR ON WST.OWNERID = USR.USER_ID
WHERE	WST.OWNERID IN (715,29702,32150,75324, 146105)
		AND WST.STATUSID IN (1,3,4)
		AND dbo.UnixDateTime(ASSIGNEDTIME) > '12/01/2022'
GROUP BY USR.FIRST_NAME, WST.STATUSID
ORDER BY USR.FIRST_NAME, WST.STATUSID

/*
SELECT	* 
FROM	AaaUser  
WHERE	FIRST_NAME = 'David Ulloa'

SELECT	*
FROM	WorkOrderStates 
WHERE	WORKORDERID IN (446892,446841,446833,446762)

UPDATE	ONESUPPORT_DBV2.dbo.WorkOrderStates
SET		STATUSID = 3,
		CLOSE_COMMENTS = 'The problem has been resolved.'
WHERE	OWNERID IN (715,29702,32150,75324)
		AND STATUSID = 1
		AND WORKORDERID NOT IN (473559)

*/
