SELECT	JRNENTRY,
		REFRENCE,
		TRXDATE,
		GL20.ORGNTSRC,
		(CRDTAMNT + DEBITAMT) * IIF(CRDTAMNT <> 0, -1, 1) AS Amount
INTO	#tmpData
FROM	GL20000 GL20
		INNER JOIN GL00105 GL05 ON GL20.ACTINDX = GL05.ACTINDX 
WHERE	GL05.ACTNUMST = '0-88-1866'

SELECT	REFRENCE,
		SUM(Amount) AS Amount
INTO	#tmpResult
FROM	#tmpData DATA
GROUP BY REFRENCE
HAVING	SUM(Amount) <> 0
ORDER BY REFRENCE

SELECT	GL20.JRNENTRY,
		TMP.REFRENCE AS [DESCRIPTION],
		GPCustom.dbo.FindProNumber(GL20.REFRENCE) AS ProNumber,
		CAST(TRXDATE AS Date) AS TrxDate,
		TMP.Amount,
		IIF(LEFT(GL20.ORGNTSRC, 4) = 'PMTR', 'AP', GL20.ORGNTSRC) AS TRXSOURCE
FROM	#tmpResult TMP
		INNER JOIN #tmpData GL20 ON TMP.REFRENCE = GL20.REFRENCE
ORDER BY 4,3
		--SELECT TOP 100 * FROM GL20000

DROP TABLE #tmpData
DROP TABLE #tmpResult