SELECT	*
FROM	(
		SELECT	RTRIM(APH.VENDORID) AS VENDORID,
				RTRIM(APH.DOCNUMBR) AS DOCNUMBR,
				APH.DOCTYPE,
				CAST(APH.DOCDATE AS date) AS DOCDATE,
				CAST(APH.PSTGDATE AS date) AS PSTGDATE,
				CAST(APH.DOCAMNT AS Numeric(10,2)) AS DOCAMNT,
				RTRIM(ACD.ACTNUMST) AS ACTNUMST,
				CAST(APD.DEBITAMT AS Numeric(10,2)) AS DEBITAMT,
				CAST(APD.CRDTAMNT AS Numeric(10,2)) AS CRDTAMNT,
				RTRIM(IIF(RTRIM(APD.DistRef) = '', APH.TRXDSCRN, APD.DistRef)) AS TRXDSCRN
		FROM	PM20000 APH
				INNER JOIN PM10100 APD ON APH.VENDORID = APD.VENDORID AND APH.VCHRNMBR = APD.VCHRNMBR
				INNER JOIN GL00105 ACD ON APD.DSTINDX = ACD.ACTINDX
		WHERE	APH.VENDORID IN (SELECT VendorId FROM GPCustom.dbo.VendorMaster WHERE Company = 'PTS')
				AND APH.VOIDED = 0
		UNION
		SELECT	RTRIM(APH.VENDORID) AS VENDORID,
				RTRIM(APH.DOCNUMBR) AS DOCNUMBR,
				APH.DOCTYPE,
				CAST(APH.DOCDATE AS date) AS DOCDATE,
				CAST(APH.PSTGDATE AS date) AS PSTGDATE,
				CAST(APH.DOCAMNT AS Numeric(10,2)) AS DOCAMNT,
				RTRIM(ACD.ACTNUMST) AS ACTNUMST,
				CAST(APD.DEBITAMT AS Numeric(10,2)) AS DEBITAMT,
				CAST(APD.CRDTAMNT AS Numeric(10,2)) AS CRDTAMNT,
				RTRIM(IIF(RTRIM(APD.DistRef) = '', APH.TRXDSCRN, APD.DistRef)) AS TRXDSCRN
		FROM	PM30200 APH
				INNER JOIN PM30600 APD ON APH.VENDORID = APD.VENDORID AND APH.VCHRNMBR = APD.VCHRNMBR
				INNER JOIN GL00105 ACD ON APD.DSTINDX = ACD.ACTINDX
		WHERE	APH.VENDORID IN (SELECT VendorId FROM GPCustom.dbo.VendorMaster WHERE Company = 'PTS')
				AND APH.VOIDED = 0
		) DATA
ORDER BY
		VENDORID,
		DOCDATE,
		DOCNUMBR