SELECT	ParameterCode AS Parameter,
		VarC AS ParValue
INTO	##tmpParameters
FROM	GPCustom.dbo.Parameters
WHERE	ParameterCode LIKE 'RAISTONE_%'

SELECT	SYT.*
FROM	AIS.dbo.SY06000 SYT
		INNER JOIN AIS.dbo.PM00200 VND ON SYT.VENDORID = VND.VENDORID AND SYT.ADRSCODE = VND.VADCDTRO
WHERE	SYT.VENDORID LIKE '1%' and ADRSCODE like 'REM%'
ORDER BY SYT.VENDORID
--UPDATE	AIS.dbo.SY06000
--SET		SY06000.BANKNAME			= DATA.BANK_NAME,
--		SY06000.EFTBankAcct			= DATA.BANKACCT,
--		SY06000.EFTTransitRoutingNo	= DATA.BANKROUTING,
--		SY06000.EFTPrenoteDate		= '01/01/1900'
--FROM	(
--		SELECT	SYT.VENDORID,
--				SYT.ADRSCODE,
--				BANK_NAME = (SELECT ParValue FROM ##tmpParameters WHERE Parameter = 'RAISTONE_BANK'),
--				BANKACCT = (SELECT ParValue FROM ##tmpParameters WHERE Parameter = 'RAISTONE_BNK_ACCOUNT'),
--				BANKROUTING = (SELECT ParValue FROM ##tmpParameters WHERE Parameter = 'RAISTONE_ACH_ACCOUNT')
--		FROM	AIS.dbo.SY06000 SYT
--				INNER JOIN AIS.dbo.PM00200 VND ON SYT.VENDORID = VND.VENDORID AND SYT.ADRSCODE = VND.VADCDTRO
--		WHERE	SYT.VENDORID = 'A0156'
--		) DATA
--WHERE	SY06000.VENDORID = DATA.VENDORID
--		AND SY06000.ADRSCODE = DATA.ADRSCODE

DROP TABLE ##tmpParameters

/*
SELECT	ParameterCode AS Parameter,
		VarC AS ParValue
FROM	GPCustom.dbo.Parameters
WHERE	ParameterCode LIKE 'RAISTONE_%'
*/