SELECT	RTRIM(HDR.VENDORID) AS VENDORID,
		RTRIM(HDR.DOCNUMBR) AS DOCNUMBR,
		CAST(HDR.DOCDATE AS Date) AS DOCDATE,
		HDR.DOCAMNT,
		RTRIM(DET.DistRef) AS DESCRIPTION
FROM	PM30600 DET
		INNER JOIN PM30200 HDR ON DET.VENDORID = HDR.VENDORID AND DET.VCHRNMBR = HDR.VCHRNMBR
WHERE	DET.DSTINDX IN (SELECT ACTINDX FROM GL00105 WHERE ACTNUMST = '5-08-5007')