IF DB_NAME() <> 'GPCustom'
BEGIN
	ALTER INDEX ALL ON PM20000 REBUILD WITH (FILLFACTOR = 90, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON)

	ALTER INDEX ALL ON PM30200 REBUILD WITH (FILLFACTOR = 90, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON)

	ALTER INDEX ALL ON PM00200 REBUILD WITH (FILLFACTOR = 90, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON) 

	ALTER INDEX ALL ON SY06000 REBUILD WITH (FILLFACTOR = 90, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON)
END 
 
USE [GPCustom] 
GO 

--ALTER INDEX ALL ON Agents REBUILD WITH (FILLFACTOR = 90, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON)
--GO

ALTER INDEX ALL ON Companies REBUILD WITH (FILLFACTOR = 90, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON)
GO

ALTER INDEX ALL ON Companies_Parameters REBUILD WITH (FILLFACTOR = 90, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON)
GO

ALTER INDEX ALL ON Divisions REBUILD WITH (FILLFACTOR = 90, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON)
GO

ALTER INDEX ALL ON DriverDocuments REBUILD WITH (FILLFACTOR = 90, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON)
GO

ALTER INDEX ALL ON EscrowInterest REBUILD WITH (FILLFACTOR = 90, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON)
GO

ALTER INDEX ALL ON EscrowAccounts REBUILD WITH (FILLFACTOR = 90, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON)
GO

ALTER INDEX ALL ON EscrowTransactions REBUILD WITH (FILLFACTOR = 90, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON)
GO

ALTER INDEX ALL ON EscrowTransactionsHistory REBUILD WITH (FILLFACTOR = 90, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON)
GO

ALTER INDEX ALL ON OOS_Transactions REBUILD WITH (FILLFACTOR = 90, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON)
GO 

ALTER INDEX ALL ON SafetyBonus REBUILD WITH (FILLFACTOR = 90, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON)
GO

ALTER INDEX ALL ON Parameters REBUILD WITH (FILLFACTOR = 90, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON)
GO 

ALTER INDEX ALL ON PM10201 REBUILD WITH (FILLFACTOR = 90, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON)
GO

ALTER INDEX ALL ON PM10300 REBUILD WITH (FILLFACTOR = 90, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON)
GO

ALTER INDEX ALL ON VendorMaster REBUILD WITH (FILLFACTOR = 90, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON)
GO

ALTER INDEX ALL ON ILS_Datawarehouse.dbo.DocumentBatches REBUILD WITH (FILLFACTOR = 90, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON)
GO

ALTER INDEX ALL ON ILS_Datawarehouse.dbo.DrvReps_RemittanceAdvise REBUILD WITH (FILLFACTOR = 90, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON)
GO