SELECT	*
FROM	DYNAMICS..ACTIVITY 

SELECT	*
FROM	DYNAMICS..SY00800 

SELECT	*
FROM	DYNAMICS..SY00801

SELECT	*
FROM	TEMPDB..DEX_LOCK

DELETE	TEMPDB..DEX_LOCK
WHERE	session_id = 134

SELECT	*
delete TEMPDB..DEX_SESSION
WHERE	session_id = 134
--WHERE	sqlsvr_spid NOT IN (SELECT SQLSESID FROM DYNAMICS..ACTIVITY)