UPDATE	PM20000
SET		HOLD = 0
FROM	(
		SELECT	FSI.VendorId,
				FSI.InvoiceNumber
		FROM	GPCustom.dbo.AP_FSI_InvoiceImage FSI
				INNER JOIN PM20000 PMO ON FSI.VENDORID = PMO.VENDORID AND FSI.InvoiceNumber = PMO.DOCNUMBR
		WHERE	COMPANY = DB_NAME()
				AND InHold = 1
		) FSI
WHERE	PM20000.VENDORID = FSI.VendorId
		AND PM20000.DOCNUMBR = FSI.InvoiceNumber