SET NOCOUNT ON

SELECT	COUNT(*) AS RowsCount_Det
FROM	GPCustom.dbo.PM10201
WHERE	DOCDATE < DATEADD(DD, -365, GETDATE())

SELECT	COUNT(*) AS RowsCount_Hdr
FROM	GPCustom.dbo.PM10300 
WHERE	DOCDATE < DATEADD(DD, -365, GETDATE())

SELECT	COUNT(*) AS RowsCount_DataWH
FROM	GPCustom.dbo.ILS_Datawarehouse.dbo.DrvReps_RemittanceAdvise
WHERE	WeekendDate < DATEADD(DD, -365, GETDATE())
GO

DELETE	GPCustom.dbo.PM10201
WHERE	DOCDATE < DATEADD(DD, -365, GETDATE())

DELETE	GPCustom.dbo.PM10300 
WHERE	DOCDATE < DATEADD(DD, -365, GETDATE())

DELETE	ILS_Datawarehouse.dbo.DrvReps_RemittanceAdvise
WHERE	WeekendDate < DATEADD(DD, -365, GETDATE())

DELETE	ILS_Datawarehouse.dbo.DocumentBatches
WHERE	WeekendDate < DATEADD(DD, -365, GETDATE())
GO

USE [GPCustom]
GO

ALTER INDEX ALL ON PM10201 REBUILD WITH (FILLFACTOR = 90, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON)
ALTER INDEX ALL ON PM10300 REBUILD WITH (FILLFACTOR = 90, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON)
GO

USE [ILS_Datawarehouse]
GO

ALTER INDEX ALL ON DrvReps_RemittanceAdvise REBUILD WITH (FILLFACTOR = 90, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON)
ALTER INDEX ALL ON DocumentBatches REBUILD WITH (FILLFACTOR = 90, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON)
GO