SELECT	PROD.CUSTNMBR,
		PROD.CUSTNAME,
		PROD.CRLMTTYP AS Prod_CreditLimit,
		CASE PROD.CRLMTTYP WHEN 0 THEN 'No Credit' WHEN 1 THEN 'Unlimited' ELSE 'Amount' END AS ProdCreditLimitDescription, 
		TST.CRLMTTYP AS Test_CreditLimit,
		CASE TST.CRLMTTYP WHEN 0 THEN 'No Credit' WHEN 1 THEN 'Unlimited' ELSE 'Amount' END AS ProdCreditLimitDescription, 
		PROD.MODIFDT
FROM	RM00101 PROD
		INNER JOIN LENSASQL001T.IMC.dbo.RM00101 TST ON PROD.CUSTNMBR = TST.CUSTNMBR
ORDER BY PROD.MODIFDT DESC

UPDATE	RM00101
SET		RM00101.CRLMTTYP = DATA.CRLMTTYP,
		RM00101.CRLMTAMT = DATA.CRLMTAMT
FROM	(
			SELECT	CUSTNMBR,
					CRLMTTYP,
					CRLMTAMT
			FROM	LENSASQL001T.IMC.dbo.RM00101
		) DATA
WHERE	RM00101.CUSTNMBR = DATA.CUSTNMBR