DECLARE	@Document	Varchar(20) = '42-124278',
		@DocAmount	Numeric(10,2),
		@DocBalance	Numeric(10,2)

SELECT	@DocAmount = ORTRXAMT
FROM	RM20101
WHERE	DOCNUMBR = @Document

SET		@DocBalance = (SELECT SUM(APPTOAMT) FROM (SELECT APPTOAMT FROM RM20201 WHERE APTODCNM = @Document UNION SELECT APPTOAMT FROM RM30201 WHERE APTODCNM = @Document) DATA)
PRINT	@DocAmount - ISNULL(@DocBalance, 0)

UPDATE	RM20101
SET		CURTRXAM = (@DocAmount - ISNULL(@DocBalance, 0))
WHERE	DOCNUMBR = @Document

SELECT	CUSTNMBR,
		DOCNUMBR,
		DOCDATE,
		ORTRXAMT,
		CURTRXAM
FROM	RM20101
WHERE	DOCNUMBR = @Document