RESTORE DATABASE [ABS] 
FROM DISK = N'C:\Temp\ABS_backup_200809111900.bak'
WITH FILE = 1, NOUNLOAD, STATS = 10, RECOVERY, REPLACE,
MOVE N'GPSABSDat.mdf' TO N'C:\SqlServer\GPSABSDat.mdf', 
MOVE N'GPSABSLog.ldf' TO N'C:\SqlServer\GPSABSLog.ldf'