SELECT	*
FROM	(
		SELECT	DISTINCT ACTNUMBR_3 AS Code
				,ACTDESCR
		FROM	GL00100
		WHERE	ACTIVE = 1
		UNION
		SELECT	DISTINCT ACTNUMBR_1 AS Code
				,'' AS ACTDESCR
		FROM	GL00100
		WHERE	ACTIVE = 1
		UNION
		SELECT	DISTINCT ACTNUMBR_2 AS Code
				,'' AS ACTDESCR
		FROM	GL00100
		WHERE	ACTIVE = 1
		) DATA
ORDER BY LEN(RTRIM(Code)), Code

/*
SELECT	*
FROM	GL00100


SELECT	*
FROM	GL00100
where	PATINDEX('%	Members'' Draw%', ACTDESCR) >0
*/