ALTER PROCEDURE Load401K 
	@StartDate 	VARCHAR(25), 
	@EndDate 	VARCHAR(25),
	@StartDednCode 	VARCHAR(7),
	@EndDednCode 	VARCHAR(7),
	@StartBeneCode 	VARCHAR(7),
	@EndBeneCode 	VARCHAR(7),
	@LoanCode 	VARCHAR(7),
	@EmpOptions 	SMALLINT,
	@UserID 	VARCHAR(30)  
AS
DECLARE @EMPLOYID 	VARCHAR(15), 
	@LASTNAME 	VARCHAR(21),
	@FIRSTNAME 	VARCHAR(30),
	@MIDLNAME 	VARCHAR(30),
	@FNAMEMI 	VARCHAR(30),
	@SOCSCNUM 	VARCHAR(15),
	@HIREDATE 	DATETIME,
	@EARNINGS 	NUMERIC(19,5),
	@DEDNCODE 	VARCHAR(7),
	@DEDNAMNT 	NUMERIC(19,5),
	@DEDNPERC 	NUMERIC(19,5),
	@BENECODE 	VARCHAR(7),
	@BENEAMNT 	NUMERIC(19,5),
	@BENEPERC 	NUMERIC(19,5),
	@StartLoanCode 	VARCHAR(7),
	@EndLoanCode 	VARCHAR(7),
	@LOANAMNT 	NUMERIC(19,5),
	@LOANPERC 	NUMERIC(19,5),
	@DEPRTMNT 	VARCHAR(7),
	@YTDHOURS 	NUMERIC(19,5),
	@YTD_DAYS 	INTEGER,
	@YTD_START_DATE VARCHAR(30),
	@EMPLOYERMATCH 	NUMERIC(19,5),
	@TERM_DATE 	DATETIME

	SET @StartLoanCode 	= @LoanCode 
	SET @EndLoanCode 	= @LoanCode 

	DELETE IMC_401KREP WHERE USERID = @USERID
	
	IF @EmpOptions = 0 
	    BEGIN
		DECLARE EMPLOYEES CURSOR LOCAL KEYSET OPTIMISTIC 
		FOR SELECT EMPLOYID, DEPRTMNT, LASTNAME, FRSTNAME, MIDLNAME, SOCSCNUM, STRTDATE 
		FROM UPR00100 WHERE INACTIVE = 0 
	    END
	    
	IF @EmpOptions = 1 
	    BEGIN
		DECLARE EMPLOYEES CURSOR LOCAL KEYSET OPTIMISTIC 
		FOR SELECT EMPLOYID, DEPRTMNT, LASTNAME, FRSTNAME, MIDLNAME, SOCSCNUM, STRTDATE 
		FROM UPR00100 WHERE INACTIVE = 1 
	    END

	IF @EmpOptions = 2
	    BEGIN
		DECLARE EMPLOYEES CURSOR LOCAL KEYSET OPTIMISTIC 
		FOR SELECT EMPLOYID, DEPRTMNT, LASTNAME, FRSTNAME, MIDLNAME, SOCSCNUM, STRTDATE 
		FROM UPR00100  
	    END

	IF @EmpOptions = 3
	    BEGIN
		DECLARE EMPLOYEES CURSOR LOCAL KEYSET OPTIMISTIC 
		FOR SELECT EMPLOYID, DEPRTMNT, LASTNAME, FRSTNAME, MIDLNAME, SOCSCNUM, STRTDATE 
		FROM 	UPR00100 
			LEFT JOIN TE024230 ON UPR00100.EMPLOYID = TE024230.EMPID_I
		WHERE	INACTIVE = 0 OR 
			(INACTIVE = 1 AND 
			TE024230.TERMINATIONDATE_I > UPR00100.STRTDATE AND
			YEAR(TE024230.TERMINATIONDATE_I) < YEAR(CAST(@StartDate AS DateTime)))
	    END 
OPEN EMPLOYEES 

FETCH FROM EMPLOYEES 
INTO 
	@EMPLOYID, 
	@DEPRTMNT, 
	@LASTNAME, 
	@FIRSTNAME, 
	@MIDLNAME, 
	@SOCSCNUM, 
	@HIREDATE  

WHILE @@FETCH_STATUS = 0 
BEGIN
	SELECT 	@EARNINGS = sum(uprtrxam) 
	FROM	UPR30300 
	WHERE	chekdate BETWEEN @STARTDATE AND @ENDDATE AND 
		PYRLRTYP = 1 AND 
		EMPLOYID = @EMPLOYID 
	
	SET @EARNINGS 		= ISNULL(@EARNINGS, 0)
	SET @FNAMEMI 		= RTRIM(ISNULL(@FIRSTNAME,'')) + ' ' + RTRIM(ISNULL(@MIDLNAME,''))
	SET @FNAMEMI 		= ISNULL(@FNAMEMI, '')
	SET @YTDHOURS 		= 0  
	SET @YTD_START_DATE 	= '1-JAN-' + ltrim(str(YEAR(@EndDate)))
	
	IF @YTD_START_DATE < @HIREDATE 
  		SET @YTD_START_DATE = @HIREDATE

	--	print @HIREDATE 
	--	print @YTD_START_DATE


	SET @YTD_DAYS = DATEDIFF(d, @YTD_START_DATE, @EndDate)

--	print @YTD_DAYS
	
	SET @YTD_DAYS = @YTD_DAYS / 7
	SET @YTDHOURS = @YTD_DAYS * 40
	SET @YTDHOURS = ISNULL(@YTDHOURS,0)

--	print @YTD_DAYS
--	print @YTDHOURS


	SELECT	@TERM_DATE = MAX(TERMINATIONDATE_I) 
	FROM 	TE024230 
	WHERE 	EMPID_I = @EMPLOYID 

	SET @TERM_DATE = ISNULL(@TERM_DATE, '1/1/1900')	

	INSERT INTO IMC_401KREP (
		EMPLOYID, 
		DEPRTMNT, 
		LASTNAME, 
		FNAMEMI, 
		SOCSCNUM, 
		HIREDATE, 
		EARNINGS, 
		DEDNCODE, 
		DEDNAMNT,
		DEDNPERC, 
		BENECODE, 
		BENEAMNT, 
		BENEPERC, 
		LOANCODE, 
		LOANAMNT, 
		LOANPERC, 
		STARTDATE, 
		ENDDATE, 
		USERID, 
		YTDHOURS, 
		EMPLOYERMATCH,
		TERMDATE) 
	VALUES (@EMPLOYID, 
		@DEPRTMNT, 
		@LASTNAME, 
		@FNAMEMI, 
		@SOCSCNUM, 
		@HIREDATE, 
		@EARNINGS,
		'' , 
		0,
		0, 
		'', 
		0, 
		0, 
		'', 
		0, 
		0, 
		@STARTDATE, 
		@ENDDATE, 
		@USERID, 
		@YTDHOURS, 
		0, 
		@TERM_DATE)

	
	DECLARE DEDUCTIONS CURSOR 
		LOCAL KEYSET OPTIMISTIC 
	FOR 	SELECT 	SUM(UPRTRXAM), PAYROLCD 
		FROM 	UPR30300 
		WHERE 	CHEKDATE BETWEEN @STARTDATE AND @ENDDATE AND 
			PYRLRTYP = 2 AND 
			PAYROLCD BETWEEN @StartDednCode AND @EndDednCode AND 
			EMPLOYID = @EMPLOYID 
		GROUP BY PAYROLCD 
		
	OPEN DEDUCTIONS
	
	FETCH FROM DEDUCTIONS 
	INTO 	@DEDNAMNT, 
		@DEDNCODE
	
	WHILE @@FETCH_STATUS = 0 
	    BEGIN
		SELECT	@DEDNPERC = DEDNPRCT_1 
	 	FROM	UPR00500 
	 	WHERE	EMPLOYID = @EMPLOYID AND 
		 	DEDUCTON = @DEDNCODE 
	 
		SET @DEDNPERC = ISNULL(@DEDNPERC, 0) 

		SET @EMPLOYERMATCH = 0.0

		IF @DEDNPERC > 6 
		     BEGIN
			SET @EMPLOYERMATCH = (@DEDNAMNT/@DEDNPERC)*6*0.5  
		     END
		ELSE
		     BEGIN
			SET @EMPLOYERMATCH = @DEDNAMNT*0.5	   
		     END

		SET @EMPLOYERMATCH = ISNULL(@EMPLOYERMATCH,0) 

		IF EXISTS(SELECT * FROM IMC_401KREP WHERE EMPLOYID = @EMPLOYID AND USERID = @USERID AND (LEN(DEDNCODE) = 0 OR DEDNCODE = @DEDNCODE))
		     BEGIN

			UPDATE 
				IMC_401KREP 
			SET 
				DEDNCODE = @DEDNCODE, 
				DEDNAMNT = @DEDNAMNT, 
				DEDNPERC = @DEDNPERC, 
				EMPLOYERMATCH = @EMPLOYERMATCH 
			WHERE 
				EMPLOYID = @EMPLOYID AND 
				USERID = @USERID 

		     END 
		 ELSE
		     BEGIN

			INSERT INTO IMC_401KREP (
				EMPLOYID, 
				DEPRTMNT, 
				LASTNAME, 
				FNAMEMI, 
				SOCSCNUM, 
				HIREDATE, 
				EARNINGS, 
				DEDNCODE, 
				DEDNAMNT,
				DEDNPERC, 
				EMPLOYERMATCH, 
				BENECODE, 
				BENEAMNT, 
				BENEPERC, 
				LOANCODE, 
				LOANAMNT, 
				LOANPERC, 
				STARTDATE, 
				ENDDATE, 
				USERID, 
				YTDHOURS,
				TERMDATE) 
			VALUES (
				@EMPLOYID, 
				@DEPRTMNT, 
				@LASTNAME, 
				@FNAMEMI, 
				@SOCSCNUM, 
				@HIREDATE, 
				0, 
				@DEDNCODE, 
				@DEDNAMNT, 
				@DEDNPERC,
				@EMPLOYERMATCH, 
				'', 
				0, 
				0, 
				'', 
				0, 
				0, 
				@STARTDATE, 
				@ENDDATE, 
				@USERID, 
				@YTDHOURS,
				@TERM_DATE)	    
		     END
	 
	 	FETCH NEXT 
	 	FROM DEDUCTIONS 
	 	INTO 
	 		@DEDNAMNT, 
	 		@DEDNCODE
	    END
	
	CLOSE DEDUCTIONS 
	
	DEALLOCATE DEDUCTIONS

	DECLARE BENEFITS CURSOR 
		LOCAL KEYSET OPTIMISTIC 
	FOR SELECT SUM(UPRTRXAM), PAYROLCD 
		FROM 
			UPR30300 
		WHERE 
			CHEKDATE BETWEEN @STARTDATE and @ENDDATE AND 
			PYRLRTYP = 3 and 
			PAYROLCD between @StartBeneCode and @EndBeneCode AND 
			EMPLOYID = @EMPLOYID 
		GROUP BY PAYROLCD 
	
	
	OPEN BENEFITS
	
	FETCH FROM 
	BENEFITS INTO 
		@BENEAMNT, 
		@BENECODE
	
	WHILE @@FETCH_STATUS = 0 
	    BEGIN

	    	SELECT 
	    		@BENEPERC = BNFPRCNT_1 
	    	FROM 
	    		UPR00600 
	    	WHERE 
	    		EMPLOYID = @EMPLOYID AND 
	    		BENEFIT = @BENECODE  
	    		
	    	SET @BENEPERC = ISNULL(@BENEPERC, 0) 



	 	IF EXISTS(SELECT * FROM IMC_401KREP WHERE EMPLOYID = @EMPLOYID AND USERID = @USERID AND (LEN(BENECODE) = 0 OR BENECODE = @BENECODE))
	  	    BEGIN
	   		
	   		UPDATE 
	   			IMC_401KREP 
	   		SET 
	   			BENECODE = @BENECODE, 
	   			BENEAMNT = @BENEAMNT, 
	   			BENEPERC = @BENEPERC 
	   		WHERE 
	   			EMPLOYID = @EMPLOYID AND 
	   			USERID = @USERID 
	  	    END
	  	ELSE
	  	    BEGIN
	   
	   
	   		INSERT INTO IMC_401KREP (
	   			EMPLOYID, 
	   			DEPRTMNT, 
	   			LASTNAME, 
	   			FNAMEMI, 
	   			SOCSCNUM, 
	   			HIREDATE, 
	   			EARNINGS, 
	   			DEDNCODE, 
	   			DEDNAMNT,
	   			DEDNPERC, 
	   			BENECODE, 
	   			BENEAMNT, 
	   			BENEPERC, 
	   			LOANCODE, 
	   			LOANAMNT, 
	   			LOANPERC, 
	   			STARTDATE, 
	   			ENDDATE, 
	   			USERID, 
	   			YTDHOURS, 
	   			EMPLOYERMATCH,
				TERMDATE) 
	   		VALUES (
	   			@EMPLOYID, 
	   			@DEPRTMNT, 
	   			@LASTNAME, 
	   			@FNAMEMI, 
	   			@SOCSCNUM, 
	   			@HIREDATE, 
	   			0, 
	   			'', 
	   			0, 
	   			0, 
	   			@BENECODE, 
	   			@BENEAMNT, 
	   			@BENEPERC, 
	   			'', 
	   			0, 
	   			0, 
	   			@STARTDATE, 
	   			@ENDDATE, 
	   			@USERID, 
	   			@YTDHOURS, 
	   			0,
				@TERM_DATE)	    

	  	    END
	  	    
	 	FETCH NEXT FROM BENEFITS 
	 	INTO 
	 		@BENEAMNT, 
	 		@BENECODE
	 		
	
	    END
	
	CLOSE BENEFITS 
	
	DEALLOCATE BENEFITS

	DECLARE LOANS CURSOR 
		LOCAL KEYSET OPTIMISTIC 
	FOR SELECT 
		SUM(UPRTRXAM), 
		PAYROLCD 
	FROM 
		UPR30300 
	WHERE 
		CHEKDATE BETWEEN @STARTDATE and @ENDDATE AND 
		PYRLRTYP = 2 and 
		PAYROLCD between @StartLoanCode and @EndLoanCode AND 
		EMPLOYID = @EMPLOYID GROUP BY PAYROLCD 
	
	OPEN LOANS
	
	FETCH FROM LOANS 
	INTO 
		@LOANAMNT, 
		@LOANCODE
		
	WHILE @@FETCH_STATUS = 0 
	    BEGIN

		SELECT 
			@LOANPERC = DEDNPRCT_1 
		FROM 
			UPR00500 
		WHERE 
			EMPLOYID = @EMPLOYID AND 
			DEDUCTON = @LOANCODE 
			
		 SET @LOANPERC = ISNULL(@DEDNPERC, 0) 

		 IF EXISTS(SELECT * FROM IMC_401KREP WHERE EMPLOYID = @EMPLOYID AND USERID = @USERID AND (LEN(LOANCODE) = 0 OR LOANCODE = @LOANCODE))
		     BEGIN

			UPDATE 
				IMC_401KREP 
			SET 
				LOANCODE = @LOANCODE, 
				LOANAMNT = @LOANAMNT, 
				LOANPERC = @LOANPERC 
			WHERE 
				EMPLOYID = @EMPLOYID AND 
				USERID = @USERID 

		     END 
		 ELSE
		     BEGIN

			INSERT INTO IMC_401KREP (
				EMPLOYID, 
				DEPRTMNT, 
				LASTNAME, 
				FNAMEMI, 
				SOCSCNUM, 
				HIREDATE, 
				EARNINGS, 
				DEDNCODE, 
				DEDNAMNT,
				DEDNPERC, 
				BENECODE, 
				BENEAMNT, 
				BENEPERC, 
				LOANCODE, 
				LOANAMNT, 
				LOANPERC, 
				STARTDATE, 
				ENDDATE, 
				USERID, 
				YTDHOURS, 
				EMPLOYERMATCH,
				TERMDATE) 
			VALUES (
				@EMPLOYID, 
				@DEPRTMNT, 
				@LASTNAME, 
				@FNAMEMI, 
				@SOCSCNUM, 
				@HIREDATE, 
				0, 
				'', 
				0, 
				0, 
				'', 
				0, 
				0, 
				@LOANCODE, 
				@LOANAMNT, 
				@LOANPERC, 
				@STARTDATE, 
				@ENDDATE, 
				@USERID, 
				@YTDHOURS, 
				0,
				@TERM_DATE)	    
		     END

		FETCH NEXT FROM LOANS INTO @LOANAMNT, @LOANCODE
            END

	CLOSE LOANS
	DEALLOCATE LOANS

	FETCH NEXT FROM EMPLOYEES 
	INTO	@EMPLOYID, 
		@DEPRTMNT, 
		@LASTNAME, 
		@FIRSTNAME, 
		@MIDLNAME, 
		@SOCSCNUM, 
		@HIREDATE  
		
		
END

CLOSE EMPLOYEES
DEALLOCATE EMPLOYEES

SELECT	EMPLOYID, 
	DEPRTMNT, 
	LASTNAME, 
	FNAMEMI, 
	SOCSCNUM, 
	HIREDATE, 
	YTDHOURS, 
	EARNINGS, 
	DEDNCODE, 
	DEDNAMNT, 
	DEDNPERC,
	EMPLOYERMATCH, 
	BENECODE, 
	BENEAMNT, 
	BENEPERC, 
	LOANCODE, 
	LOANAMNT, 
	LOANPERC, 
	STARTDATE, 
	ENDDATE,
	TERMDATE 
FROM	IMC_401KREP 
WHERE	USERID = @USERID

GO