DECLARE @VENDORID VARCHAR(15) = '7903'

--UPDATE	GLSO.dbo.PM00200
--SET		VADDCDPR = 'MAIN'
--WHERE	VENDORID = @VENDORID

SELECT	*
FROM	GLSO.dbo.PM00200
WHERE	VENDORID = @VENDORID

SELECT	*
FROM	GLSO.dbo.PM00300
WHERE	VENDORID = @VENDORID

SELECT	*
FROM	RapidPay_VendorAch
WHERE	VENDORID = @VENDORID

SELECT	*
FROM	RapidPay_VendorAddress
WHERE	VENDORID = @VENDORID

SELECT	*
FROM	GPVendorMaster
WHERE	Company = 'GLSO'
		AND VENDORID = @VENDORID

/*
UPDATE	GPVendorMaster 
SET		RP_Active = 1, 
		RapidPay = 1,
		RP_EffectiveDate = GETDATE()
WHERE	Company = 'GLSO'
		AND VendorId = '1151'
*/

/*
DELETE	RapidPay_VendorAch
WHERE	VENDORID = @VENDORID
		AND RecordId <> 35

DELETE	RapidPay_VendorAddress
WHERE	VENDORID = '1151'
		AND RecordId <> 25
*/