DECLARE	@RunDate		Date = GETDATE(),
		@JustSummary	Bit = 0,
		@CustomerId		Varchar(25) = Null
		 
IF @JustSummary = 1
BEGIN
	SELECT	DB_NAME() AS Company,
			CM.CUSTNMBR AS Customer_ID, 
			CM.CUSTNAME AS Customer_Name,
			CM.PYMTRMID AS Customer_Terms, 
			CM.CUSTCLAS AS Customer_Class,
			SUM(CASE WHEN RM.RMDTYPAL < 7 THEN RM.CURTRXAM ELSE RM.CURTRXAM * -1 END) AS Total_Due,
			SUM(CASE WHEN DATEDIFF(d, RM.DUEDATE, @RunDate) < 31 AND RM.RMDTYPAL < 7 THEN RM.CURTRXAM WHEN DATEDIFF(d, RM.DOCDATE, @RunDate) < 31 AND RM.RMDTYPAL > 6 THEN RM.CURTRXAM *-1 ELSE 0 END) AS [Current],
			SUM(CASE WHEN DATEDIFF(d, RM.DUEDATE, @RunDate) BETWEEN 31 AND 60 AND RM.RMDTYPAL < 7 THEN RM.CURTRXAM WHEN DATEDIFF(d, RM.DOCDATE, @RunDate) BETWEEN 31 AND 60 AND RM.RMDTYPAL > 6 THEN RM.CURTRXAM * -1 ELSE 0 END) AS [31_to_60_Days],
			SUM(CASE WHEN DATEDIFF(d, RM.DUEDATE, @RunDate) BETWEEN 61 AND 90 AND RM.RMDTYPAL < 7 THEN RM.CURTRXAM WHEN DATEDIFF(d, RM.DOCDATE, @RunDate) BETWEEN 61 AND 90 AND RM.RMDTYPAL > 6 THEN RM.CURTRXAM * -1 ELSE 0 END) AS [61_to_90_Days],
			SUM(CASE WHEN DATEDIFF(d, RM.DUEDATE, @RunDate) BETWEEN 91 AND 180 AND RM.RMDTYPAL < 7 THEN RM.CURTRXAM WHEN DATEDIFF(d, RM.DOCDATE, @RunDate) BETWEEN 61 AND 90 AND RM.RMDTYPAL > 6 THEN RM.CURTRXAM * -1 ELSE 0 END) AS [91_to_180_Days],
			SUM(CASE WHEN DATEDIFF(d, RM.DUEDATE, @RunDate) > 180 AND RM.RMDTYPAL < 7 THEN RM.CURTRXAM WHEN DATEDIFF(d, RM.DOCDATE, @RunDate) > 90 AND RM.RMDTYPAL > 6 THEN RM.CURTRXAM *-1 ELSE 0 END) AS [Over_180],
			CAST(CS.LASTPYDT AS Date) AS Last_Payment_Date,
			CAST(CS.LPYMTAMT AS Numeric(12,2)) AS Last_Payment_Amount 
	FROM	RM20101 RM 
			INNER JOIN RM00101 CM ON RM.CUSTNMBR = CM.CUSTNMBR
			INNER JOIN RM00103 CS ON RM.CUSTNMBR = CS.CUSTNMBR
	WHERE	RM.VOIDSTTS = 0 
			AND RM.CURTRXAM <> 0
			AND (@CustomerId IS Null OR (@CustomerId IS NOT Null AND RM.CUSTNMBR = @CustomerId))
	GROUP BY 
			CM.CUSTNMBR, 
			CM.CUSTNAME, 
			CM.PYMTRMID, 
			CM.CUSTCLAS, 
			CM.PRCLEVEL, 
			CS.LASTPYDT,
			CS.LPYMTAMT
END
ELSE
BEGIN
	SELECT	CM.CUSTNMBR AS Customer_ID,
			CM.CUSTNAME AS Customer_Name,
			CM.PYMTRMID AS Customer_Terms,
			CM.CUSTCLAS AS Customer_Class,
			CASE RM.RMDTYPAL
				  WHEN 1 THEN 'Sale / Invoice'
				  WHEN 3 THEN 'Debit Memo'
				  WHEN 4 THEN 'Finance Charge'
				  WHEN 5 THEN 'Service Repair'
				  WHEN 6 THEN 'Warranty'
				  WHEN 7 THEN 'Credit Memo'
				  WHEN 8 THEN 'Return'
				  WHEN 9 THEN 'Payment'
				  ELSE 'Other'
			END AS Document_Type,
			RM.DOCNUMBR AS Document_Number,
			CAST(RM.DOCDATE AS Date) AS Document_Date,
			CAST(RM.DUEDATE AS Date) AS Due_Date,
			CAST(S.LASTPYDT AS Date) AS Last_Payment_Date,
			CASE WHEN RM.RMDTYPAL < 7 THEN RM.ORTRXAMT ELSE RM.ORTRXAMT * -1 END AS Document_Amount,
			CASE WHEN RM.RMDTYPAL < 7 THEN RM.CURTRXAM ELSE RM.CURTRXAM * -1 END AS Unapplied_Amount,
			CASE WHEN DATEDIFF(d, RM.DUEDATE, @RunDate) <= 0 AND RM.RMDTYPAL < 7 THEN RM.CURTRXAM WHEN DATEDIFF(d, RM.DOCDATE, @RunDate) <= 0 AND RM.RMDTYPAL > 6 THEN RM.CURTRXAM *-1 ELSE 0 END AS [Current],
			CASE WHEN DATEDIFF(d, RM.DUEDATE, @RunDate) between 1 AND 30 AND RM.RMDTYPAL < 7 THEN RM.CURTRXAM WHEN DATEDIFF(d, RM.DOCDATE, @RunDate) between 1 AND 30 AND RM.RMDTYPAL > 6 THEN RM.CURTRXAM * -1 ELSE 0 END AS [0_to_30_Days],
			CASE WHEN DATEDIFF(d, RM.DUEDATE, @RunDate) between 31 AND 60 AND RM.RMDTYPAL < 7 THEN RM.CURTRXAM WHEN DATEDIFF(d, RM.DOCDATE, @RunDate) between 31 AND 60 AND RM.RMDTYPAL > 6 THEN RM.CURTRXAM * -1 ELSE 0 END AS [31_to_60_Days],
			CASE WHEN DATEDIFF(d, RM.DUEDATE, @RunDate) between 61 AND 90 AND RM.RMDTYPAL < 7 THEN RM.CURTRXAM WHEN DATEDIFF(d, RM.DOCDATE, @RunDate) between 61 AND 90 AND RM.RMDTYPAL > 6 THEN RM.CURTRXAM * -1 ELSE 0 END AS [61_to_90_Days],
			CASE WHEN DATEDIFF(d, RM.DUEDATE, @RunDate) between 61 AND 90 AND RM.RMDTYPAL < 7 THEN RM.CURTRXAM WHEN DATEDIFF(d, RM.DOCDATE, @RunDate) between 91 AND 180 AND RM.RMDTYPAL > 6 THEN RM.CURTRXAM * -1 ELSE 0 END AS [91_to_180_Days],
			CASE WHEN DATEDIFF(d, RM.DUEDATE, @RunDate) > 90 AND RM.RMDTYPAL < 7 THEN RM.CURTRXAM WHEN DATEDIFF(d, RM.DOCDATE, @RunDate) > 180 AND RM.RMDTYPAL > 6 THEN RM.CURTRXAM *-1 ELSE 0 END AS [Over_180] 
	FROM	RM20101 RM
			INNER JOIN RM00101 CM ON RM.CUSTNMBR = CM.CUSTNMBR
			INNER JOIN RM00103 S ON RM.CUSTNMBR = S.CUSTNMBR
	WHERE	RM.VOIDSTTS = 0 
			AND RM.CURTRXAM <> 0
			AND (@CustomerId IS Null OR (@CustomerId IS NOT Null AND RM.CUSTNMBR = @CustomerId))

END