UPDATE	SY10550
SET		SECMODALTID = 'TRUCKING'
FROM	(
Select r.userid, r.SECMODALTID AS PROFILE, c.INTERID, R.DEX_ROW_ID AS RECORDID
from SY10550 R 
Join SY01500 C on C.CMPANYID=r.CMPANYID
where R.SECMODALTID <>'TRUCKING'
AND c.INTERID NOT IN ('MHGC','RCCL','FI','RCMR','ABS','COIMC','ATEST','IMCC','MHG','PTSC ','MIT','MCCP','RCCON','IGSC','MHGH','IMCGH','ITEST','IMCPH','IMMRC','TISO ','HIS01','HIS04','SUNST','SUCON','HIS07','HIS02','HIS02','ARC01','ARC04')
) DATA
WHERE	SY10550.DEX_ROW_ID = DATA.RECORDID
