UPDATE	GL00100
SET		ACTDESCR = LTRIM(RTRIM(DATA.DESCRIPTION))
FROM	(
		SELECT	G5.ACTINDX,
				GL.DESCRIPTION
		FROM	GL00105 G5
				INNER JOIN GPCustom.dbo.GLDescriptions GL ON G5.ACTNUMST = GL.ACCOUNT
		) DATA
WHERE	GL00100.ACTINDX = DATA.ACTINDX

SELECT	*
FROM	GL00100