DECLARE @BACHNUMB	Varchar(25), 
		@CUSTNMBR	Varchar(15), 
		@DOCNUMBR	Varchar(30),
		@Agent		Char(2)

DECLARE curInvoices CURSOR LOCAL KEYSET OPTIMISTIC FOR
SELECT	RTRIM(BACHNUMB) AS BACHNUMB,
		RTRIM(CUSTNMBR) AS CUSTNMBR,
		RTRIM(DOCNUMBR) AS DOCNUMBR
FROM	RM20101
WHERE	GPCustom.dbo.AT('_', DOCNUMBR, 1) = 0
		AND RMDTYPAL < 7
		AND SLSTERCD = '' 

OPEN curInvoices 
FETCH FROM curInvoices INTO @BACHNUMB, @CUSTNMBR, @DOCNUMBR

WHILE @@FETCH_STATUS = 0 
BEGIN
	PRINT @BACHNUMB + ' - ' + @DOCNUMBR

	SET @Agent = Null

	IF LEFT(@BACHNUMB, 2) = 'PD'
		SELECT	@Agent = LEFT(DivisionNum, 2)
		FROM	LENSASQL002.Accounting.dbo.InvoiceDetail
		WHERE	CustInvNum  = REPLACE(REPLACE(@DOCNUMBR, 'A', ''), '.', '')
	ELSE
		IF LEFT(@BACHNUMB, 5) = 'DMSAR'
			SELECT	@Agent = Cmpy_No
			FROM	IntegrationsDB.Integrations.dbo.DMS_ReceivedTransactions
			WHERE	Invoice_No = @DOCNUMBR

	IF @Agent IS NOT Null
		UPDATE	NDS.dbo.RM20101
		SET		SLSTERCD = @Agent
		WHERE	BACHNUMB = @BACHNUMB
				AND CUSTNMBR = @CUSTNMBR
				AND DOCNUMBR = @DOCNUMBR

	FETCH FROM curInvoices INTO @BACHNUMB, @CUSTNMBR, @DOCNUMBR
END

CLOSE curInvoices
DEALLOCATE curInvoices