SELECT	*
FROM	Parameters
WHERE	VARC LIKE '\\%'

UPDATE	Parameters
SET		VarC = '\\PRIAPINT01P\INTEGRATIONS\FTP\EFSMANUALCHECKS\'
WHERE	ParameterCode = 'EFSMCFILESPATH'

UPDATE	Parameters
SET		VarC = '\\PRIAPINT01P\INTEGRATIONS\FTP\PTS\'
WHERE	ParameterCode = 'PTSPAYROLLFILESPATH'

UPDATE	Parameters
SET		VarC = '\\PRIAPINT01P\FTP\DRIVERFUELTAX\'
WHERE	ParameterCode = 'FUELTAXFILESPATH'

UPDATE	Parameters
SET		VarC = '\\PRIAPINT01P\FTP\HMIS_PAYROLL\'
WHERE	ParameterCode = 'HMISPAYFILES'

UPDATE	Parameters
SET		VarC = '\\PRIAPINT01P\FTP\HEALTHINSURANCE\'
WHERE	ParameterCode = 'HLTHINSFILEPATH'

UPDATE	Parameters
SET		VarC = '\\PRIAPINT01P\FTP\SAFEPAY\'
WHERE	ParameterCode = 'SAFEPAYFILESFOLDER'

-- PRIAPINT01P