SELECT	*
FROM	Parameters
WHERE	ParameterCode IN ('INTEGRATIONSFILES','MU_FTP_FOLDER','PROCESSEDINTEGRATIONS')

UPDATE	Parameters
SET		VarC = upper(REPLACE(REPLACE(VarC, 'ILSINT01', 'PRIAPINT01P'), 'ILSINT02', 'PRIAPINT01P'))
WHERE	ParameterCode IN ('INTEGRATIONSFILES','MU_FTP_FOLDER','PROCESSEDINTEGRATIONS')