USE GLSO
GO

DECLARE	@DateIni	Date = '01/01/2022',
		@DateEnd	Date = '12/31/2022',
		@ApplyFix	Bit = 1

SELECT	*
INTO	##tmpData
FROM (
		SELECT	TRA.VENDORID,
				TRA.VCHRNMBR,
				TRA.DOCNUMBR,
				CAST(TRA.DOCDATE AS Date) AS DOCDATE,
				CAST(TRA.DOCAMNT AS Numeric(10,2)) AS DOCAMNT,
				CAST(TRA.TEN99AMNT AS Numeric(10,2)) AS TEN99AMNT,
				CAST(TRA.DOCAMNT AS Numeric(10,2)) AS FIX1099,
				VND.TEN99TYPE,
				IIF(VND.TEN99TYPE = 4, 'MISC', 'NEC') AS TEN99TYPE_TEXT,
				TRA.DEX_ROW_ID AS RecordId,
				'OPEN' AS DATASOURCE
		FROM	PM20000 TRA
				INNER JOIN PM00200 VND ON TRA.VENDORID = VND.VENDORID AND VND.TEN99TYPE > 1 AND VND.VNDCLSID <> 'DRV'
		WHERE	TRA.DOCDATE BETWEEN @DateIni AND @DateEnd
				AND TRA.DOCTYPE IN (1,5)
				AND (TRA.TEN99AMNT = 0
				OR TRA.TEN99TYPE <> VND.TEN99TYPE
				OR TRA.TEN99BOXNUMBER = 0)
				--AND TRA.VENDORID = '1034'
		UNION
		SELECT	TRA.VENDORID,
				TRA.VCHRNMBR,
				TRA.DOCNUMBR,
				CAST(TRA.DOCDATE AS Date) AS DOCDATE,
				CAST(TRA.DOCAMNT AS Numeric(10,2)) AS DOCAMNT,
				CAST(TRA.TEN99AMNT AS Numeric(10,2)) AS TEN99AMNT,
				CAST(TRA.DOCAMNT AS Numeric(10,2)) AS FIX1099,
				VND.TEN99TYPE,
				IIF(VND.TEN99TYPE = 4, 'MISC', 'NEC') AS TEN99TYPE_TEXT,
				TRA.DEX_ROW_ID AS RecordId,
				'HISTORICAL' AS DATASOURCE
		FROM	PM30200 TRA
				INNER JOIN PM00200 VND ON TRA.VENDORID = VND.VENDORID AND VND.TEN99TYPE > 1 AND VND.VNDCLSID <> 'DRV'
		WHERE	TRA.DOCDATE BETWEEN @DateIni AND @DateEnd
				AND TRA.DOCTYPE IN (1,5)
				AND (TRA.TEN99AMNT = 0
				OR TRA.TEN99TYPE <> VND.TEN99TYPE
				OR TRA.TEN99BOXNUMBER = 0)
				--AND TRA.VENDORID = '1034'
		) data

IF @ApplyFix = 0
BEGIN
	SELECT	CPY.CompanyAlias,
			TMP.*
	FROM	##tmpData TMP
			INNER JOIN GPCustom.dbo.View_CompaniesAndAgents CPY ON CPY.CompanyId = DB_NAME()
	ORDER BY 1, 4, 3
END
ELSE
BEGIN
	UPDATE	PM20000
	SET		PM20000.TEN99AMNT		= DATA.FIX1099,
			PM20000.TEN99TYPE		= DATA.TEN99TYPE,
			PM20000.TEN99BOXNUMBER	= 1
	FROM	##tmpData DATA
	WHERE	PM20000.DEX_ROW_ID = DATA.RecordId
			AND DATA.DATASOURCE = 'OPEN'

	UPDATE	PM30200
	SET		PM30200.TEN99AMNT		= DATA.FIX1099,
			PM30200.TEN99TYPE		= DATA.TEN99TYPE,
			PM30200.TEN99BOXNUMBER	= 1
	FROM	##tmpData DATA
	WHERE	PM30200.DEX_ROW_ID = DATA.RecordId
			AND DATA.DATASOURCE = 'HISTORICAL'
END

DROP TABLE ##tmpData

