CREATE PROCEDURE USP_HistoricalAP (@CutoffDate Datetime)
AS 
SELECT	a.VCHRNMBR,
	a.VENDORID,
	a.DOCTYPE,
	a.DOCDATE,
	a.POSTEDDT,
	a.DOCNUMBR,
	a.DOCAMNT,
	CASE WHEN b.APTVCHNM is null THEN a.DOCAMNT ELSE (a.DOCAMNT-b.APPLDAMT) END AS CURRAMT,
	a.DEX_ROW_ID AS DEX_ROW_ID1,
	b.DEX_ROW_ID AS DEX_ROW_ID2,
	a.DISCAMNT,
	a.DUEDATE,
	a.PYMTRMID,
	a.VOIDED
FROM	--PM30200 
	(SELECT	VCHRNMBR,
		VENDORID,
		DOCTYPE,
		DOCDATE,
		POSTEDDT,
		DOCNUMBR,
		DOCAMNT,
		DEX_ROW_ID,
		DISCAMNT,
		DUEDATE,
		PYMTRMID,
		VOIDED
	FROM	PM30200
	UNION
	SELECT	VCHRNMBR,
		VENDORID,
		DOCTYPE,
		DOCDATE,
		POSTEDDT,
		DOCNUMBR,
		DOCAMNT,
		DEX_ROW_ID,
		DISCAMNT,
		DUEDATE,
		PYMTRMID,
		VOIDED
	FROM	PM20000) a
	--PM30300
LEFT JOIN (	SELECT	APTODCTY, 
			APTVCHNM, 
			SUM(APPLDAMT) AS APPLDAMT, 
			MAX(ApplyToGLPostDate) AS ApplyToGLPostDate, 
			MAX(DEX_ROW_ID) AS DEX_ROW_ID 
		FROM	PM30300 
		GROUP BY 
			APTODCTY, 
			APTVCHNM
		UNION
		SELECT	APTODCTY, 
			APTVCHNM, 
			SUM(APPLDAMT) AS APPLDAMT, 
			MAX(ApplyToGLPostDate) AS ApplyToGLPostDate, 
			MAX(DEX_ROW_ID) AS DEX_ROW_ID 
		FROM	PM20100 
		GROUP BY
			APTODCTY, 
			APTVCHNM) b ON a.VCHRNMBR = b.APTVCHNM AND a.DOCTYPE = b.APTODCTY AND a.DOCTYPE <= 4 AND a.VOIDED = 0
WHERE	a.DOCDATE <= @CutoffDate AND
	b.ApplyToGLPostDate <= @CutoffDate
UNION
SELECT	a.VCHRNMBR,
	a.VENDORID,
	a.DOCTYPE,
	a.DOCDATE,
	a.POSTEDDT,
	a.DOCNUMBR,
	-a.DOCAMNT,
	CASE WHEN b.VCHRNMBR IS NULL THEN a.DOCAMNT ELSE a.DOCAMNT-b.APPLDAMT END AS CURRAMT,
	a.DEX_ROW_ID AS DEX_ROW_ID1,
	b.DEX_ROW_ID AS DEX_ROW_ID2,
	a.DISCAMNT,
	a.DUEDATE,
	a.PYMTRMID,
	a.VOIDED
FROM	--PM30200
	(SELECT	VCHRNMBR,
		VENDORID,
		DOCTYPE,
		DOCDATE,
		POSTEDDT,
		DOCNUMBR,
		DOCAMNT,
		DEX_ROW_ID,
		DISCAMNT,
		DUEDATE,
		PYMTRMID,
		VOIDED
	FROM	PM30200
	UNION
	SELECT	VCHRNMBR,
		VENDORID,
		DOCTYPE,
		DOCDATE,
		POSTEDDT,
		DOCNUMBR,
		DOCAMNT,
		DEX_ROW_ID,
		DISCAMNT,
		DUEDATE,
		PYMTRMID,
		VOIDED
	FROM	PM20000) a
--PM30300
LEFT JOIN (	SELECT	DOCTYPE, 
			VCHRNMBR, 
			SUM(APPLDAMT) AS APPLDAMT, 
			MAX(ApplyToGLPostDate) AS ApplyToGLPostDate, 
			MAX(DEX_ROW_ID) AS DEX_ROW_ID 
		FROM	PM30300 
		GROUP BY
			DOCTYPE, 
			VCHRNMBR
		UNION
		SELECT	DOCTYPE, 
			VCHRNMBR, 
			SUM(APPLDAMT) AS APPLDAMT, 
			MAX(ApplyToGLPostDate) AS ApplyToGLPostDate, 
			MAX(DEX_ROW_ID) AS DEX_ROW_ID 
		FROM	PM20100 
		GROUP BY
			DOCTYPE, 
			VCHRNMBR) b ON a.VCHRNMBR = b.VCHRNMBR AND a.DOCTYPE = b.DOCTYPE AND a.DOCTYPE > 4 AND a.VOIDED = 0
WHERE	a.DOCDATE <= @CutoffDate AND 
	b.ApplyToGLPostDate <= @CutoffDate