/*
EXECUTE USP_FindCurrentFiscalPeriod '12/9/2011'
*/
ALTER PROCEDURE USP_FindCurrentFiscalPeriod (@Date Datetime)
AS
SELECT	MIN(DATESTART) AS DATESTART
FROM	(
		SELECT	DATESTART
		FROM	View_FiscalPeriods 
		WHERE	@Date BETWEEN DATESTART AND DATEEND
		UNION	
		SELECT	DATESTART
		FROM	View_FiscalPeriods 
		WHERE	@Date - 25 BETWEEN DATESTART AND DATEEND
				AND CLOSED = 0
		) RECS
WHERE	DATESTART IS NOT NULL