/*
EXECUTE USP_ImportAccounts
*/
ALTER PROCEDURE USP_ImportAccounts
AS
SELECT * INTO ##tmpCustomers FROM OPENQUERY([FIDepot_SyBase], 'SELECT * FROM Accounts')

UPDATE	Accounts
SET		Accounts.acct_name	= DATA.acct_name
		,Accounts.address	= DATA.address
		,Accounts.address1	= DATA.address1
		,Accounts.city		= DATA.city
		,Accounts.state		= DATA.state
		,Accounts.zip		= DATA.zip
		,Accounts.area_code	= DATA.area_code
		,Accounts.phone_no	= DATA.phone_no
FROM	##tmpCustomers DATA
WHERE	Accounts.Acct_No = DATA.Acct_No

INSERT INTO dbo.Accounts
           (acct_no
           ,acct_name
           ,address
           ,address1
           ,city
           ,state
           ,zip
           ,area_code
           ,phone_no
           ,baddress
           ,baddress1
           ,bcity
           ,bstate
           ,bzip
           ,bcontact
           ,mr_fax_no
           ,terms
           ,max_credit
           ,cur_bal
           ,contact
           ,afxcontact
           ,fax_no
           ,afaxcont2
           ,fax_no2
           ,bfxcontact
           ,bfax_no
           ,remarks
           ,total_sale
           ,last_sale
           ,acct_typ
           ,vencode
           ,price_levl
           ,yard_code
           ,mark_up_pt
           ,mark_up_tp
           ,mark_dn_pt
           ,gllink
           ,glstor
           ,edi_active
           ,edi_provid
           ,edi_phnumb
           ,edi_usrid
           ,edi_usrpas
           ,ftp_addres
           ,senders_id
           ,recevrs_id
           ,edi_templa
           ,trans_no
           ,unique_no
           ,send_auto
           ,time_zone
           ,cedx_activ
           ,cdx_provid
           ,cdx_usrid
           ,cdx_usrpas
           ,cdx_ftp
           ,cedx_squal
           ,cedx_senid
           ,cedx_rqual
           ,cedx_recid
           ,cedx_trans
           ,cedx_labor
           ,cedx_depot
           ,cedx_email
           ,cedx_scac
           ,cedx_owner
           ,cedx_refcd
           ,e996_activ
           ,e996_sendi
           ,e996_recev
           ,e996_shopc
           ,actvemail1
           ,actvemail2
           ,activi_rpt
           ,activi_eml
           ,yard_check
           ,yard_eml
           ,cust_rpt
           ,activi_sub
           ,yard_sub
           ,chass_pool
           ,tir_in
           ,tir_out
           ,send_qual
           ,recev_qual
           ,prnt_no_ac
           ,is_leas_co
           ,lease_pool
           ,lease_acct
           ,lease_scac
           ,send_pdf
           ,bnum_forma
           ,cnum_forma
           ,prefix_chk
           ,inv_fax1
           ,inv_fax2
           ,invemail1
           ,invemail2
           ,inv_rpt
           ,est_rpt
           ,prnt_yard
           ,prnt_yard2
           ,prnt_actv
           ,prnt_last
           ,prnt_repr
           ,prnt_mr
           ,prnt_statu
           ,prnt_est
           ,use_driver
           ,use_contro
           ,auto_tir
           ,use_tires
           ,est_code
           ,inv_code
           ,wrk_code
           ,mr_a_appro
           ,depot_loc
           ,addid
           ,ground_box
           ,prnt_actv2
           ,actvemail3
           ,actvemail4
           ,actvemailc
           ,cdx_pickup
           ,e996pickup
           ,e322pickup
           ,e204_usrid
           ,e204_usrpa
           ,e204_provi
           ,e204_ftp
           ,e204_sende
           ,e204_recei
           ,e204_squal
           ,e204_rqual
           ,e204_trans
           ,e204_scac
           ,e204_activ
           ,e204_code1
           ,e204_code2
           ,checkdig
           ,wrk_rpt
           ,bat_rpt
           ,yardst_rpt
           ,boxleaseco
           ,chsleaseco
           ,mustdelvno
           ,use_fhwa
           ,email_edi
           ,print_edi
           ,mr_status
           ,tir_copies
           ,chas_type2
           ,chas_type4
           ,ias_gate
           ,ias_hsac
           ,use_tire_3
           ,cedx_orig
           ,cedx_compr
           ,cedx_damag
           ,use_inspec
           ,loaded
           ,tpp_oocl
           ,tir_cr
           ,tir_incr
           ,tir_outcr
           ,new_bookin
           ,def_status
           ,use_time
           ,sbt_acctno
           ,notaxest
           ,e301nyk
           ,e301csav
           ,e301oocl
           ,ptaxrate
           ,ltaxrate
           ,e301usr
           ,e301pas
           ,oocl_site
           ,oocl_tech
           ,auto_otir
           ,is_cpship
           ,is_csav
           ,iscustbond
           ,isfrtreles
           ,nochassis
           ,editcondit
           ,sbtstoract
           ,oocl_login
           ,oocl_pass
           ,nogenset
           ,autocedex
           ,e996_prov
           ,e996_usrid
           ,e996_usrpa
           ,chrgdemur
           ,ground_gen
           ,no_mr
           ,no_lic
           ,no_trailer
           ,no_ground
           ,no_load
           ,no_mrstat
           ,use_loc
           ,useseal
           ,usevessel
           ,e810_usrid
           ,e810_usrpa
           ,use_stack
           ,use_remark
           ,iscod
           ,cedx_stat
           ,cedx_party
           ,cedx_flexi
           ,cedx_job
           ,use_none
           ,chg_agate
           ,use_drvdb
           ,use_isig
           ,use_osig
           ,last_rept
           ,use_condes
           ,cdxlabch
           ,cdxlabrf
           ,bkformat1
           ,bkformat2
           ,qbtaxcode
           ,cedx_chs
           ,newport
           ,newclid
           ,newvnid
           ,newdpid
           ,tir_cout
           ,bkg_email
           ,qbtaxname
           ,notaxcus
           ,chg_bgate
           ,use_inv
           ,inv_remark
           ,no_bl
           ,sep_inout
           ,edi_email
           ,maerskedi
           ,autotarif
           ,gidnondep
           ,use_mech
           ,force_av
           ,edi_type
           ,use_euser
           ,cedxretid
           ,shipper
           ,ecurrency
           ,e322_name
           ,tarfacct
           ,e301apl)
SELECT	acct_no
		,acct_name
		,address
		,address1
		,city
		,state
		,zip
		,area_code
		,phone_no
		,baddress
		,baddress1
		,bcity
		,bstate
		,bzip
		,bcontact
		,mr_fax_no
		,terms
		,max_credit
		,cur_bal
		,contact
		,afxcontact
		,fax_no
		,afaxcont2
		,fax_no2
		,bfxcontact
		,bfax_no
		,remarks
		,total_sale
		,last_sale
		,acct_typ
		,vencode
		,price_levl
		,yard_code
		,mark_up_pt
		,mark_up_tp
		,mark_dn_pt
		,gllink
		,glstor
		,edi_active
		,edi_provid
		,edi_phnumb
		,edi_usrid
		,edi_usrpas
		,ftp_addres
		,senders_id
		,recevrs_id
		,edi_templa
		,trans_no
		,unique_no
		,send_auto
		,time_zone
		,cedx_activ
		,cdx_provid
		,cdx_usrid
		,cdx_usrpas
		,cdx_ftp
		,cedx_squal
		,cedx_senid
		,cedx_rqual
		,cedx_recid
		,cedx_trans
		,cedx_labor
		,cedx_depot
		,cedx_email
		,cedx_scac
		,cedx_owner
		,cedx_refcd
		,e996_activ
		,e996_sendi
		,e996_recev
		,e996_shopc
		,actvemail1
		,actvemail2
		,activi_rpt
		,activi_eml
		,yard_check
		,yard_eml
		,cust_rpt
		,activi_sub
		,yard_sub
		,chass_pool
		,tir_in
		,tir_out
		,send_qual
		,recev_qual
		,prnt_no_ac
		,is_leas_co
		,lease_pool
		,lease_acct
		,lease_scac
		,send_pdf
		,bnum_forma
		,cnum_forma
		,prefix_chk
		,inv_fax1
		,inv_fax2
		,invemail1
		,invemail2
		,inv_rpt
		,est_rpt
		,prnt_yard
		,prnt_yard2
		,prnt_actv
		,prnt_last
		,prnt_repr
		,prnt_mr
		,prnt_statu
		,prnt_est
		,use_driver
		,use_contro
		,auto_tir
		,use_tires
		,est_code
		,inv_code
		,wrk_code
		,mr_a_appro
		,depot_loc
		,addid
		,ground_box
		,prnt_actv2
		,actvemail3
		,actvemail4
		,actvemailc
		,cdx_pickup
		,e996pickup
		,e322pickup
		,e204_usrid
		,e204_usrpa
		,e204_provi
		,e204_ftp
		,e204_sende
		,e204_recei
		,e204_squal
		,e204_rqual
		,e204_trans
		,e204_scac
		,e204_activ
		,e204_code1
		,e204_code2
		,checkdig
		,wrk_rpt
		,bat_rpt
		,yardst_rpt
		,boxleaseco
		,chsleaseco
		,mustdelvno
		,use_fhwa
		,email_edi
		,print_edi
		,mr_status
		,tir_copies
		,chas_type2
		,chas_type4
		,ias_gate
		,ias_hsac
		,use_tire_3
		,cedx_orig
		,cedx_compr
		,cedx_damag
		,use_inspec
		,loaded
		,tpp_oocl
		,tir_cr
		,tir_incr
		,tir_outcr
		,new_bookin
		,def_status
		,use_time
		,sbt_acctno
		,notaxest
		,e301nyk
		,e301csav
		,e301oocl
		,ptaxrate
		,ltaxrate
		,e301usr
		,e301pas
		,oocl_site
		,oocl_tech
		,auto_otir
		,is_cpship
		,is_csav
		,iscustbond
		,isfrtreles
		,nochassis
		,editcondit
		,sbtstoract
		,oocl_login
		,oocl_pass
		,nogenset
		,autocedex
		,e996_prov
		,e996_usrid
		,e996_usrpa
		,chrgdemur
		,ground_gen
		,no_mr
		,no_lic
		,no_trailer
		,no_ground
		,no_load
		,no_mrstat
		,use_loc
		,useseal
		,usevessel
		,e810_usrid
		,e810_usrpa
		,use_stack
		,use_remark
		,iscod
		,cedx_stat
		,cedx_party
		,cedx_flexi
		,cedx_job
		,use_none
		,chg_agate
		,use_drvdb
		,use_isig
		,use_osig
		,last_rept
		,use_condes
		,cdxlabch
		,cdxlabrf
		,bkformat1
		,bkformat2
		,qbtaxcode
		,cedx_chs
		,newport
		,newclid
		,newvnid
		,newdpid
		,tir_cout
		,bkg_email
		,qbtaxname
		,notaxcus
		,chg_bgate
		,use_inv
		,inv_remark
		,no_bl
		,sep_inout
		,edi_email
		,maerskedi
		,autotarif
		,gidnondep
		,use_mech
		,force_av
		,edi_type
		,use_euser
		,cedxretid
		,shipper
		,ecurrency
		,e322_name
		,tarfacct
		,e301apl
FROM	##tmpCustomers
WHERE	Acct_No NOT IN (SELECT Acct_No FROM Accounts)

DROP TABLE ##tmpCustomers