-- CREATE PROCEDURE USP_EscrowTransactions_ClaimsUpdate
DECLARE	@BatchId	Varchar(20),
		@GLAccount	Varchar(20)

SELECT	GLT.JRNENTRY,
		GLT.SQNCLINE
FROM	GL10001 GLT
		INNER JOIN GL00105 GLA ON GLT.ACTINDX = GLA.ACTINDX
WHERE	GLT.DEBITAMT + GLT.CRDTAMNT <> 0
		AND GLT.BACHNUMB = @BatchId
		AND GLA.ACTNUMST = @GLAccount