/*
EXECUTE USP_FindSaleItems 'CFLORES', '10/02/2011', '10/29/2011', 'HOUSTON', NULL, 'FI10N'

SELECT * FROM Sale WHERE Date BETWEEN '10/02/2011' AND '10/05/2011' AND DEPOT_LOC = 'HOUSTON'
SELECT * FROM Invoices WHERE Inv_Date BETWEEN '10/02/2011' AND '10/05/2011' AND DEPOT_LOC = 'HOUSTON'
*/
ALTER PROCEDURE USP_FindSaleItems
		@UserId		Varchar(25),
		@Date1		Date,
		@Date2		Date,
		@Location	Varchar(20) = NULL,
		@Type		Char(1) = NULL,
		@Bin		Varchar(20) = Null,
		@PartNo		Varchar(25) = NULL
AS
SELECT 	INV.INV_NO
		,INV.INV_EST
		,INV.DEPOT_LOC AS DEPOT_LOC_
		,SAL.PART_NO
		,SAL.DESCRIPT
		,QTY_SHIPED
		,UNIT_PRICE
		,PART_TOTAL
		,SAL.DATE
		,SAL.CDEX_REPAI
		,SAL.RLABOR
		,SAL.RLABOR_QTY
		,SAL.LAB_PRICE
		,ESTATUS
		,ACCT_NO
		,SAL.DEPOT_LOC AS DEPOT_LOC2
		,CONTAINER
		,CHASSIS
		,GENSET_NO
		,GEN_HOURS
		,INV_TYPE
		,WORKORDER
		,SAL.CDEX_DAMAG
		,SAL.CDEX_LOCAT
		,NEWDOTON
		,NEWDOTOFF
		,INV.INV_DATE
		,INV.EST_DATE
		,INV.REP_DATE
		,SAL.Bin
		,@UserId AS UserId 
FROM 	Invoices INV
		INNER JOIN Sale SAL ON INV.Inv_No = SAL.Inv_No
		LEFT JOIN DeaParts PAR ON SAL.PART_NO = PAR.PART_NO
WHERE	SAL.Date BETWEEN @Date1 AND @Date2
		AND ((@Location IS NOT NULL AND INV.DEPOT_LOC = @Location) OR @Location IS NULL) 
		AND ((@Type IS NOT NULL AND INV.INV_EST = @Type) OR @Type IS NULL) 
		AND ((@Bin IS NOT NULL AND SAL.BIN = @Bin) OR @Bin IS NULL) 
		AND ((@PartNo IS NOT NULL AND SAL.Part_No = @PartNo) OR @PartNo IS NULL) 
ORDER BY SAL.Date, INV.INV_NO 