USE GPCustom
GO

/*
EXECUTE USP_AR_Trial_Balance 'GLSO', Null, 0, '25500'
EXECUTE USP_AR_Trial_Balance 'AIS', Null, 1
*/
ALTER PROCEDURE dbo.USP_AR_Trial_Balance
		@Company	Varchar(5),
		@Customer	Varchar(15) = Null,
		@Summary	Bit = 0,
		@Parent		Varchar(15) = Null
AS
SET NOCOUNT ON

DECLARE @Query		Varchar(MAX)

IF @Customer = ''
	SET @Customer = Null

IF @Parent = ''
	SET @Parent = Null

IF @Summary = 1
BEGIN
	SET @Query = N'SELECT CM.CUSTNMBR Customer_ID, 
			UPPER(RTRIM(CM.CUSTNAME)) Customer_Name,
			UPPER(RTRIM(CM.CPRCSTNM)) Customer_Group,
			ISNULL(UPPER(RTRIM(NA.CUSTNAME)), '''') Customer_Group_Name,
			UPPER(RTRIM(CM.PYMTRMID)) Customer_Terms,
			CM.CUSTCLAS Customer_Class,
			CAST(SUM(CASE WHEN DATEDIFF(d, RM.DUEDATE, GETDATE()) < 31 AND RM.RMDTYPAL < 7 THEN RM.CURTRXAM
					 WHEN DATEDIFF(d, RM.DOCDATE, GETDATE()) < 31 AND RM.RMDTYPAL > 6 THEN RM.CURTRXAM * -1
					 ELSE 0 END) AS Numeric(12,2)) [Current],
			CAST(SUM(CASE WHEN DATEDIFF(d, RM.DUEDATE, GETDATE()) BETWEEN 31 AND 60 AND RM.RMDTYPAL < 7 THEN RM.CURTRXAM
					 WHEN DATEDIFF(d, RM.DOCDATE, GETDATE()) BETWEEN 31 AND 60 AND RM.RMDTYPAL > 6 THEN RM.CURTRXAM * -1
					 ELSE 0 END) AS Numeric(12,2)) [31-60],
			CAST(SUM(CASE WHEN DATEDIFF(d, RM.DUEDATE, GETDATE()) BETWEEN 61 AND 90 AND RM.RMDTYPAL < 7 THEN RM.CURTRXAM
					 WHEN DATEDIFF(d, RM.DOCDATE, GETDATE()) BETWEEN 61 AND 90 AND RM.RMDTYPAL > 6 THEN RM.CURTRXAM * -1
					 ELSE 0 END) AS Numeric(12,2)) [61-90],
			CAST(SUM(CASE WHEN DATEDIFF(d, RM.DUEDATE, GETDATE()) BETWEEN 91 AND 180 AND RM.RMDTYPAL < 7 THEN RM.CURTRXAM
					 WHEN DATEDIFF(d, RM.DOCDATE, GETDATE()) BETWEEN 91 AND 180 AND RM.RMDTYPAL > 6 THEN RM.CURTRXAM * -1
					 ELSE 0 END) AS Numeric(12,2)) [91-180],
			CAST(SUM(CASE WHEN DATEDIFF(d, RM.DUEDATE, GETDATE()) > 180 AND RM.RMDTYPAL < 7 THEN RM.CURTRXAM 
					 WHEN DATEDIFF(d, RM.DOCDATE, GETDATE()) > 180 AND RM.RMDTYPAL > 6 THEN RM.CURTRXAM * -1
					 ELSE 0 END) AS Numeric(12,2)) [181-More],
			CAST(SUM(CASE WHEN RM.RMDTYPAL < 7 THEN RM.CURTRXAM ELSE RM.CURTRXAM * -1 END) AS Numeric(12,2)) Total_Due,
			CAST(CS.LPYMTAMT AS Numeric(12,2)) Last_Payment_Amount,
			CAST(CS.LASTPYDT AS Date) Last_Payment_Date
	FROM	' + @Company + '.dbo.RM20101 RM WITH (NOLOCK)
			INNER JOIN ' + @Company + '.dbo.RM00101 CM WITH (NOLOCK) ON RM.CUSTNMBR = CM.CUSTNMBR
			INNER JOIN ' + @Company + '.dbo.RM00103 CS WITH (NOLOCK) ON RM.CUSTNMBR = CS.CUSTNMBR
			LEFT JOIN ' + @Company + '.dbo.RM00101 NA WITH (NOLOCK) ON RM.CPRCSTNM = NA.CUSTNMBR
	WHERE	RM.VOIDSTTS = 0 AND RM.CURTRXAM <> 0 '

	IF @Customer IS NOT Null
		SET @Query = @Query + 'AND RM.CUSTNMBR = ''' + RTRIM(@Customer) + ''' '

	IF @Parent IS NOT Null
		SET @Query = @Query + 'AND RM.CPRCSTNM = ''' + RTRIM(@Parent) + ''' '

	SET @Query = @Query + 'GROUP BY CM.CUSTNMBR, CM.CUSTNAME, CM.PYMTRMID, CM.CUSTCLAS, 
			 CM.PRCLEVEL, CS.LASTPYDT, CS.LPYMTAMT, CM.CPRCSTNM, NA.CUSTNAME '

	SET @Query = @Query + 'ORDER BY CM.CUSTNAME'
END
ELSE
BEGIN
	SET @Query = N'SELECT CM.CUSTNMBR Customer_ID, 
			UPPER(RTRIM(CM.CUSTNAME)) Customer_Name,
			UPPER(RTRIM(CM.CPRCSTNM)) Customer_Group,
			ISNULL(UPPER(RTRIM(NA.CUSTNAME)), '''') Customer_Group_Name,
			UPPER(RTRIM(CM.PYMTRMID)) Customer_Terms, 
			CM.CUSTCLAS Customer_Class,			
			RTRIM(RM.DOCNUMBR) AS Document,
			RMDTYPAL AS DocType,
			CAST(DOCDATE AS Date) AS TrxDate,
			CAST(CASE WHEN DATEDIFF(d, RM.DUEDATE, GETDATE()) < 31 AND RM.RMDTYPAL < 7 THEN RM.CURTRXAM
					 WHEN DATEDIFF(d, RM.DOCDATE, GETDATE()) < 31 AND RM.RMDTYPAL > 6 THEN RM.CURTRXAM * -1
					 ELSE 0 END AS Numeric(12,2)) [Current],
			CAST(CASE WHEN DATEDIFF(d, RM.DUEDATE, GETDATE()) BETWEEN 31 AND 60 AND RM.RMDTYPAL < 7 THEN RM.CURTRXAM
					 WHEN DATEDIFF(d, RM.DOCDATE, GETDATE()) BETWEEN 31 AND 60 AND RM.RMDTYPAL > 6 THEN RM.CURTRXAM * -1
					 ELSE 0 END AS Numeric(12,2)) [31-60],
			CAST(CASE WHEN DATEDIFF(d, RM.DUEDATE, GETDATE()) BETWEEN 61 AND 90 AND RM.RMDTYPAL < 7 THEN RM.CURTRXAM
					 WHEN DATEDIFF(d, RM.DOCDATE, GETDATE()) BETWEEN 61 AND 90 AND RM.RMDTYPAL > 6 THEN RM.CURTRXAM * -1
					 ELSE 0 END AS Numeric(12,2)) [61-90],
			CAST(CASE WHEN DATEDIFF(d, RM.DUEDATE, GETDATE()) BETWEEN 91 AND 180 AND RM.RMDTYPAL < 7 THEN RM.CURTRXAM
					 WHEN DATEDIFF(d, RM.DOCDATE, GETDATE()) BETWEEN 91 AND 180 AND RM.RMDTYPAL > 6 THEN RM.CURTRXAM * -1
					 ELSE 0 END AS Numeric(12,2)) [91-180],
			CAST(CASE WHEN DATEDIFF(d, RM.DUEDATE, GETDATE()) > 180 AND RM.RMDTYPAL < 7 THEN RM.CURTRXAM 
					 WHEN DATEDIFF(d, RM.DOCDATE, GETDATE()) > 180 AND RM.RMDTYPAL > 6 THEN RM.CURTRXAM * -1
					 ELSE 0 END AS Numeric(12,2)) [181-More],
			CAST(CASE WHEN RM.RMDTYPAL < 7 THEN RM.CURTRXAM ELSE RM.CURTRXAM * -1 END AS Numeric(12,2)) Total_Due
	FROM	' + @Company + '.dbo.RM20101 RM WITH (NOLOCK)
			INNER JOIN ' + @Company + '.dbo.RM00101 CM WITH (NOLOCK) ON RM.CUSTNMBR = CM.CUSTNMBR
			INNER JOIN ' + @Company + '.dbo.RM00103 CS WITH (NOLOCK) ON RM.CUSTNMBR = CS.CUSTNMBR
			LEFT JOIN ' + @Company + '.dbo.RM00101 NA WITH (NOLOCK) ON RM.CPRCSTNM = NA.CUSTNMBR
	WHERE	RM.VOIDSTTS = 0 AND RM.CURTRXAM <> 0 '

	IF @Customer IS NOT Null
		SET @Query = @Query + 'AND RM.CUSTNMBR = ''' + RTRIM(@Customer) + ''' '

	IF @Parent IS NOT Null
		SET @Query = @Query + 'AND RM.CPRCSTNM = ''' + RTRIM(@Parent) + ''' '

	SET @Query = @Query + 'ORDER BY CM.CUSTNAME, RM.DOCNUMBR'
END

EXECUTE(@Query)