UPDATE	PM00200
SET		VENDSTTS = 2
FROM	(
		SELECT	RTRIM(VENDORID) AS VendorId
				,REPLACE(REPLACE(RTRIM(VENDNAME), '"', ''), '''', '') AS VendorName
				,RTRIM(VNDCNTCT) AS Contact
				,RTRIM(REPLACE(ADDRESS1, '"', ' ')) AS Address
				,RTRIM(CITY) AS City
				,RTRIM(STATE) AS State
				,RTRIM(ZIPCODE) AS ZipCode
				,RTRIM(GPCustom.dbo.FORMATPHONENUMBER(PHNUMBR1)) AS PhoneNum
				,VndClsId
				,'No Transactions Ever in Great Plains' AS Status
		FROM	PM00200
		WHERE	VENDSTTS = 1
				AND VENDORID NOT IN (SELECT VENDORID FROM PM10100)
				AND VENDORID NOT IN (SELECT VENDORID FROM PM20000)
				AND VENDORID NOT IN (SELECT VENDORID FROM PM30200)
				AND VndClsId <> 'MSCPD'
		UNION
		SELECT	RTRIM(PM00200.VENDORID) AS VendorId
				,REPLACE(REPLACE(RTRIM(VENDNAME), '"', ''), '''', '') AS VendorName
				,RTRIM(VNDCNTCT) AS Contact
				,RTRIM(REPLACE(ADDRESS1, '"', ' ')) AS Address
				,RTRIM(CITY) AS City
				,RTRIM(STATE) AS State
				,RTRIM(ZIPCODE) AS ZipCode
				,RTRIM(GPCustom.dbo.FORMATPHONENUMBER(PHNUMBR1)) AS PhoneNum
				,VndClsId
				,'No Transactions Since ' + CONVERT(Char(10), LastDate, 101) AS Status
		FROM	PM00200
				INNER JOIN (
							SELECT Vendorid, MAX(PSTGDATE) AS LastDate FROM PM20000 GROUP BY Vendorid HAVING MAX(PSTGDATE) < '12/31/2009'
							UNION
							SELECT Vendorid, MAX(PSTGDATE) AS LastDate FROM PM30200 GROUP BY Vendorid HAVING MAX(PSTGDATE) < '12/31/2009'
							) RECS ON PM00200.VendorId = RECS.VendorId
		WHERE	VENDSTTS = 1
				AND VndClsId <> 'MSCPD'
		) RECS
WHERE	PM00200.VendorId = RECS.VendorId

/*
SELECT * FROM PM00200 WHERE VENDSTTS = 1

SELECT	RTRIM(PM00200.VENDORID) AS VendorId
		,REPLACE(REPLACE(RTRIM(VENDNAME), '"', ''), '''', '') AS VendorName
		,RTRIM(VNDCNTCT) AS Contact
		,RTRIM(REPLACE(ADDRESS1, '"', ' ')) AS Address
		,RTRIM(CITY) AS City
		,RTRIM(STATE) AS State
		,RTRIM(ZIPCODE) AS ZipCode
		,RTRIM(GPCustom.dbo.FORMATPHONENUMBER(PHNUMBR1)) AS PhoneNum
		,'No Transactions Since ' + CONVERT(Char(10), LastDate, 101) AS Status
FROM	PM00200
		INNER JOIN (
					SELECT Vendorid, MIN(PSTGDATE) AS LastDate FROM PM20000 GROUP BY Vendorid HAVING DATEDIFF(dd, MIN(PSTGDATE), GETDATE()) > 365
					UNION
					SELECT Vendorid, MIN(PSTGDATE) AS LastDate FROM PM30200 GROUP BY Vendorid HAVING DATEDIFF(dd, MIN(PSTGDATE), GETDATE()) > 365
					) RECS ON PM00200.VendorId = RECS.VendorId
WHERE	VENDSTTS = 1
*/