SELECT	PAY.EMPLOYID
		,EMP.LastName
		,EMP.FrstName
		,PAY.PAYROLCD AS PayCode
		,PAY.PAYRATE
		,CAST(PAY.UNTSTOPY AS Numeric(10,2)) AS Hours
		--,PAY.UPRTRXAM
--SELECT	PAY.*
FROM	FI.dbo.UPR30300 PAY
		INNER JOIN FI.dbo.UPR00100 EMP ON PAY.EMPLOYID = EMP.EMPLOYID
		INNER JOIN FI.dbo.UPR00400 COD ON PAY.EMPLOYID = COD.EMPLOYID AND PAY.PAYROLCD = COD.PAYRCORD -- AND COD.INACTIVE = 0
WHERE	PAY.EMPLOYID IN (SELECT EMPLOYID FROM FI.dbo.UPR00100 WHERE DEPRTMNT = '529' AND (DEMPINAC < '01/01/1980' OR DEMPINAC > DATEADD(dd, -7, '02/22/2014')))
		AND PAY.CHEKDATE = GPCustom.dbo.DayFwdBack('02/22/2014', 'P', 'Thursday')
		AND PAY.PYRLRTYP = 1
		AND ((PAY.PAYROLCD LIKE '%OT%' AND PAY.PAYRATE <> 0) OR PAY.PAYROLCD NOT LIKE '%OT%')
		AND PAY.PAYRATE <> 0
		--AND PAY.EMPLOYID = '573'
ORDER BY
		PAY.EMPLOYID
		,PAY.PAYROLCD

		--SELECT * FROM FI.DBO.UPR00400