SELECT	VCHNUMWK,
		SUM(DEBITAMT) AS DEBITAMT,
		SUM(CRDTAMNT) AS CRDTAMNT
INTO	#tmp1
FROM	Integrations_AP
WHERE	Integration = 'MYT'
GROUP BY VCHNUMWK

SELECT	DISTINCT VCHNUMWK,
		DOCNUMBR,
		DOCAMNT
INTO	#tmp2
FROM	Integrations_AP
WHERE	Integration = 'MYT'

SELECT	AP1.VCHNUMWK,
		AP1.DOCNUMBR,
		AP1.DOCAMNT,
		AP2.DEBITAMT,
		AP2.CRDTAMNT
FROM	#tmp2 AP1
		INNER JOIN #tmp1 AP2 ON AP1.VCHNUMWK = AP2.VCHNUMWK
WHERE	AP1.DOCAMNT <> AP2.DEBITAMT

DROP TABLE #tmp1
DROP TABLE #tmp2

/*
SELECT	*
FROM	Integrations_AP
WHERE	VCHNUMWK = 'MYT0000530'
*/