ALTER VIEW View_Employees
AS
SELECT 	EMPMST.EMPLOYID, 
	LASTNAME, 
	RTRIM(FRSTNAME) + ' ' + LEFT(MIDLNAME, 1) AS FullName, 
	LEFT(SOCSCNUM, 3) + '-' + SUBSTRING(SOCSCNUM, 4, 2) + '-' + SUBSTRING(SOCSCNUM, 6, 4) AS SOCSCNUM, 
	CASE WHEN GENDER = 1 THEN 'MALE' ELSE 'FEMALE' END AS GENDER,
	EMPCLASS.DSCRIPTN AS EmployeeClass,
	RTRIM(EMPADDRMST.Address1) + ' ' + RTRIM(Address2) AS Address,
	CITY, 
	STATE,
	ZIPCODE,
	RTRIM(RTRIM(EMPADDRMST.Address1) + ' ' + RTRIM(Address2)) + ', ' + RTRIM(CITY) + ', ' + RTRIM(STATE) + ' ' + ZIPCODE AS FullAddress,
	STRTDATE, 
	CASE WHEN CONVERT(Char(10), DEMPINAC, 101) = '01/01/1900' THEN NULL ELSE DEMPINAC END AS LASTDAYWORKED_I, 
	BRTHDATE, 
	CASE WHEN MARITALSTATUS = 1 THEN 'MARRIED' ELSE 'SINGLE' END AS MARITALSTATUS, 
	INACTIVE, 
	EMPLOYMENTTYPE, 
	EMPMST.WRKRCOMP, 
	JOBTTLMST.DSCRIPTN AS JOBTITLE, 
	DEPTMST.DSCRIPTN AS DEPT, 
	FLSASTATUS, 
	EMPMST.DEPRTMNT, 
	CASE ISNUMERIC(EMPMST.USERDEF2) WHEN 1 THEN EMPMST.USERDEF2 ELSE 0 END AS UserDefined
FROM 	UPR00100 EMPMST 
	INNER JOIN UPR00102 EMPADDRMST ON EMPMST.EMPLOYID = EMPADDRMST.EMPLOYID AND EMPMST.ADRSCODE = EMPADDRMST.ADRSCODE 
    	INNER JOIN UPR40301 JOBTTLMST ON JOBTTLMST.JOBTITLE = EMPMST.JOBTITLE 
    	INNER JOIN UPR40300 DEPTMST ON DEPTMST.DEPRTMNT = EMPMST.DEPRTMNT
	LEFT JOIN UPR41200 EMPCLASS ON EMPMST.EMPLCLAS = EMPCLASS.EMPLCLAS

--PRINT CONVERT(Char(10), GETDATE(), 101)

select * from UPR00100
select * from UPR41200