CREATE VIEW View_Employee_User
AS
SELECT	EMP.EMPLOYID
		,LOWER(DOM.UserId) AS UserId
		,EMP.LASTNAME
		,EMP.FRSTNAME
		,EMP.MIDLNAME
		,EMP.STRTDATE
		,EMP.LOCATNID
		,POS.DSCRIPTN AS JOBTITLE
		,SUP.SUPERVISOR
FROM	UPR00100 EMP
		LEFT JOIN UPR40301 POS ON EMP.JOBTITLE = POS.JOBTITLE
		LEFT JOIN UPR41700 SUP ON EMP.SUPERVISORCODE_I = SUP.SUPERVISORCODE_I
		LEFT JOIN GPCustom.dbo.DomainUsers DOM ON (EMP.LASTNAME = DOM.SN AND EMP.FRSTNAME = DOM.GivenName) OR LEFT(EMP.FRSTNAME, 1) + RTRIM(EMP.LASTNAME) = DOM.UserId OR LEFT(EMP.MIDLNAME, 1) + RTRIM(EMP.LASTNAME) = DOM.UserId AND DOM.Company = CASE WHEN DB_NAME() = 'IILS' THEN 'ILS' WHEN DB_NAME() = 'IMC' THEN 'IMCG' ELSE DB_NAME() END
WHERE	EMP.INACTIVE = 0	
		AND DOM.UserId IS NOT NULL
		
/*
SELECT	*
FROM	UPR41700

SELECT	*
FROM	GPCustom.dbo.DomainUsers
WHERE	Company = 'ILS'
ORDER BY SN, GivenName
*/