/*
SELECT	*
FROM	PTS.dbo.View_PierPass_Transactions
WHERE	Container = 'CAIU310306'
		AND ProNumber = '57-139606'
*/
ALTER VIEW View_PierPass_Transactions
AS
SELECT	GLW.JRNENTRY,
		GLW.DSCRIPTN,
		CAST(GLW.CRDTAMNT AS Numeric(10,2)) AS CRDTAMNT,
		CAST(GLW.DEBITAMT AS Numeric(10,2)) AS DEBITAMT,
		CAST(GLH.TRXDATE AS Date) AS TRXDATE,
		CASE WHEN GLW.DSCRIPTN LIKE '%|%' THEN LEFT(GLW.DSCRIPTN, GPCustom.dbo.AT('|', GLW.DSCRIPTN, 1) - 1) ELSE '' END AS Container,
		CASE WHEN GLW.DSCRIPTN LIKE '%|%' THEN SUBSTRING(GLW.DSCRIPTN, GPCustom.dbo.AT('|', GLW.DSCRIPTN, 1) + 1, 10) ELSE '' END AS ProNumber,
		'W' AS TBLSOURCE
FROM	GL10001 GLW
		INNER JOIN GL00105 GLA ON GLW.ACTINDX = GLA.ACTINDX
		INNER JOIN GL10000 GLH ON GLW.JRNENTRY = GLH.JRNENTRY
WHERE	GLA.ACTNUMST = '0-00-1866'
		AND GLW.DSCRIPTN LIKE '%|%'
UNION
SELECT	GLO.JRNENTRY,
		GLO.DSCRIPTN,
		CAST(GLO.CRDTAMNT AS Numeric(10,2)) AS CRDTAMNT,
		CAST(GLO.DEBITAMT AS Numeric(10,2)) AS DEBITAMT,
		CAST(GLO.TRXDATE AS Date) AS TRXDATE,
		CASE WHEN GLO.DSCRIPTN LIKE '%|%' THEN LEFT(GLO.DSCRIPTN, GPCustom.dbo.AT('|', GLO.DSCRIPTN, 1) - 1) ELSE '' END AS Container,
		CASE WHEN GLO.DSCRIPTN LIKE '%|%' THEN SUBSTRING(GLO.DSCRIPTN, GPCustom.dbo.AT('|', GLO.DSCRIPTN, 1) + 1, 10) ELSE '' END AS ProNumber,
		'O' AS TBLSOURCE
FROM	GL20000 GLO
		INNER JOIN GL00105 GLA ON GLO.ACTINDX = GLA.ACTINDX
WHERE	GLA.ACTNUMST = '0-00-1866'
		AND GLO.SOURCDOC = 'GJ'
		AND GLO.DSCRIPTN LIKE '%|%'


--SELECT TOP 100 * FROM GL20000
