CREATE VIEW View_FiscalPeriods
AS 
SELECT	YEAR1
		,CLOSED
		,PERIODID
		,PERNAME
		,PERIODDT AS DATESTART
		,PERDENDT AS DATEEND
		,CAST(Year1 AS Char(5)) + LEFT(PerName, 5) + CONVERT(Char(10), PERIODDT, 101) + ' - ' + CONVERT(Char(10), PERDENDT, 101) AS TextPeriod
		,CAST(Year1 AS Char(4)) + '-' + CAST(PERIODID AS Char(2)) AS Period
FROM	SY40100
WHERE	SERIES = 2
		AND ODESCTN = 'General Entry'
		AND PERIODID > 0