--select	*
--from	GP_XCB_Prepaid
--where	journalno = 690132 ---NOT in (SELECT JRNENTRY FROM GLSO..GL20000 WHERE ACTINDX = 650 UNION SELECT JRNENTRY FROM GLSO..GL30000 WHERE ACTINDX = 650)
--		--GLACCOUNT = '0-88-1866'
--		--AND pronumber in ('96-140386')

--SELECT * FROM GLSO..GL00105  WHERE ACTNUMST = '0-88-1866'

UPDATE	GP_XCB_Prepaid
SET		Voided = 1
WHERE	JournalNo IN (
						SELECT	XCB.JournalNo
						FROM	GP_XCB_Prepaid XCB
								INNER JOIN GLSO.dbo.GL00105 GLA ON XCB.GLAccount = GLA.ACTNUMST
								INNER JOIN GLSO.dbo.PM30200 PMH ON XCB.AUDIT_TRIAL = PMH.TRXSORCE AND XCB.DocumentNo = PMH.DOCNUMBR AND PMH.VOIDED = 1
						WHERE	XCB.AUDIT_TRIAL LIKE 'PM%'
						)

UPDATE	GP_XCB_Prepaid
SET		Voided = 1
WHERE	AUDIT_TRIAL LIKE 'PMVVR%'

/*
SELECT	XCB.JournalNo, XCB.AUDIT_TRIAL, XCB.DocumentNo, XCB.Amount, XCB.GLAccount, PMH.VCHRNMBR, PMH.DOCNUMBR, PMH.DOCAMNT
FROM	GP_XCB_Prepaid XCB
		INNER JOIN GLSO.dbo.GL00105 GLA ON XCB.GLAccount = GLA.ACTNUMST
		INNER JOIN GLSO.dbo.PM30200 PMH ON XCB.AUDIT_TRIAL = PMH.TRXSORCE AND XCB.DocumentNo = PMH.DOCNUMBR AND PMH.VOIDED = 1
WHERE	XCB.AUDIT_TRIAL LIKE 'PM%'
ORDER BY XCB.GLAccount, XCB.DocumentNo, XCB.JournalNo

SELECT	*
FROM	GP_XCB_Prepaid
WHERE	AUDIT_TRIAL LIKE 'PMVVR%'
ORDER BY GLAccount, DocumentNo, JournalNo
*/

INSERT INTO GP_XCB_Prepaid_Matched (RecordId)
SELECT	RecordId
FROM	GP_XCB_Prepaid XCB
WHERE	Matched = 1