SELECT	DISTINCT GL.JRNENTRY, IIF(GL.CRDTAMNT > 0, CRDTAMNT * -1, DEBITAMT) AS Amount, GPPERIOD
FROM	GL30000 GL
		INNER JOIN DYNAMICS.dbo.View_Fiscalperiod FP ON FP.GP_Period = '11-2020' AND GL.HSTYEAR = FP.YEAR1 AND GL.PERIODID = FP.PERIODID
		FULL JOIN GPCustom.dbo.GP_XCB_Prepaid XC ON GL.JRNENTRY = XC.JournalNo
WHERE	LEFT(GL.SOURCDOC, 2) NOT IN ('AP','CR','SJ','RM')
		AND GL.ACTINDX = 650
		AND FP_StartDate <= '10/30/2022'
--		and GL.JRNENTRY not in (
--SELECT	JournalNo
--FROM	GPCustom.dbo.GP_XCB_Prepaid
--WHERE	gpperiod = 'NOV-20')
ORDER BY 1

/*
SELECT	SUM(IIF(GL.CRDTAMNT > 0, CRDTAMNT * -1, DEBITAMT)) AS Amount, COUNT(*) AS Counter
FROM	GL30000 GL
		INNER JOIN DYNAMICS.dbo.View_Fiscalperiod FP ON FP.GP_Period = '11-2020' AND GL.HSTYEAR = FP.YEAR1 AND GL.PERIODID = FP.PERIODID
WHERE	LEFT(GL.SOURCDOC, 2) NOT IN ('AP','CR','SJ','RM')
		AND GL.ACTINDX = 650

SELECT	count(*), sum(amount)
FROM	GP_XCB_Prepaid
WHERE	gpperiod = 'nov-20'

UPDATE	GPCustom.dbo.GP_XCB_Prepaid
SET		GPPeriod = 'Nov-20'
WHERE	JournalNo IN (640136, 639612)
*/